REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'ID01', 'Name', 'adam_6066', 'ADAM', '1_1', 'ADAM', 'ADAM6066', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'ADAM6066', 'adam_6066_param', 'adam_6066_groups');




REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'comm_port', 'ADAM', '3', '', '', ''),
(NOW(), 'mb_tcp_servers', 'ADAM', '1;192.168.10.40;502;1000;2;500', '', 'ID;IPadr;IPport;ConnTout;ConnRetries;RequestTout', ''),
(NOW(), 'idle_event_rate', 'ADAM', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'ADAM', '2000', 'msec.', '', ''),
(NOW(), 'value_quality_check_limit', 'ADAM', '0', '', '0 = disabled', ''),
(NOW(), 'packet_timeout', 'ADAM', '0', 'sec.', '', ''),
(NOW(), 'max_outstanding_packets', 'ADAM', '-1', '', '', ''),
(NOW(), 'max_error_count', 'ADAM', '2', '', '', ''),
(NOW(), 'max_group_count', 'ADAM', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'ADAM', '2', 'hours', '', ''),
(NOW(), 'speed_index_norm', 'ADAM', '1', '', '', ''),
(NOW(), 'speed_index_slow', 'ADAM', '1', '', '', ''),
(NOW(), 'speed_index_offline', 'ADAM', '10', '', '', ''),
(NOW(), 'speed_index_block', 'ADAM', '10', '', '', ''),
(NOW(), 'show_queue_info', 'ADAM', '0', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'ADAM', '10', 'min.', '', ''),
(NOW(), 'mb_request_retries', 'ADAM', '0', '', '', ''),
(NOW(), 'mb_request_timeout', 'ADAM', '500', 'ms', '', ''),
(NOW(), 'mb_mode', 'ADAM', '0', '', '0=RTU|1=ASCII|2=TCP', ''),
(NOW(), 'mux_settle_time', 'ADAM', '1500', 'ms', 'Time for the muxed input to settle. The value shuld be a multiple off 100.', ''),
(NOW(), 'startup_delay', 'ADAM', '15', 'Sec.', '', ''),
(NOW(), 'comm_baudrate', 'ADAM', '9600', '', '', ''),
(NOW(), 'comm_stop_bits', 'ADAM', '1', '', '', ''),
(NOW(), 'comm_data_bits', 'ADAM', '8', '', '', ''),
(NOW(), 'comm_parity', 'ADAM', '0', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'check_rate', 'ADAM', '1', 'ms', '', ''),
(NOW(), 'handshake', 'ADAM', '0', '', '0|1|2', ''),
(NOW(), 'force_word_not_byte', 'ADAM', '0', '', '0|1', ''),
(NOW(), 'alarm_handler', 'ADAM', '', '', '', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_mb.exe', 'ADAM', '', '');

CREATE TABLE IF NOT EXISTS `iw_par_adam_6066_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_adam_6066_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'unit_status', 'Unit Status'),
(NOW(), 'group', 1, 'unit_status', 'di0'),
(NOW(), 'group', 2, 'unit_status', 'di1'),
(NOW(), 'group', 3, 'unit_status', 'di2'),
(NOW(), 'group', 4, 'unit_status', 'di3'),
(NOW(), 'group', 5, 'unit_status', 'di4'),
(NOW(), 'group', 6, 'unit_status', 'di5'),
(NOW(), 'group', 7, 'unit_status', 'do0'),
(NOW(), 'group', 8, 'unit_status', 'do1'),
(NOW(), 'group', 9, 'unit_status', 'do2'),
(NOW(), 'group', 10, 'unit_status', 'do3'),
(NOW(), 'group', 11, 'unit_status', 'do4'),
(NOW(), 'group', 12, 'unit_status', 'do5'),
(NOW(), 'group', 13, 'unit_status', 'counter_start_stop_ch_0'),
(NOW(), 'group', 14, 'unit_status', 'clear_counter_ch_0'),
(NOW(), 'group', 15, 'unit_status', 'clear_overflow_ch_0'),
(NOW(), 'group', 16, 'unit_status', 'latch_status_clear_status_ch_0'),
(NOW(), 'group', 17, 'unit_status', 'counter_start_stop_ch_1'),
(NOW(), 'group', 18, 'unit_status', 'clear_counter_ch_1'),
(NOW(), 'group', 19, 'unit_status', 'clear_overflow_ch_1'),
(NOW(), 'group', 20, 'unit_status', 'latch_status_clear_status_ch_1'),
(NOW(), 'group', 21, 'unit_status', 'counter_start_stop_ch_2'),
(NOW(), 'group', 22, 'unit_status', 'clear_counter_ch_2'),
(NOW(), 'group', 23, 'unit_status', 'clear_overflow_ch_2'),
(NOW(), 'group', 24, 'unit_status', 'latch_status_clear_status_ch_2'),
(NOW(), 'group', 25, 'unit_status', 'counter_start_stop_ch_3'),
(NOW(), 'group', 26, 'unit_status', 'clear_counter_ch_3'),
(NOW(), 'group', 27, 'unit_status', 'clear_overflow_ch_3'),
(NOW(), 'group', 28, 'unit_status', 'latch_status_clear_status_ch_3'),
(NOW(), 'group', 29, 'unit_status', 'counter_start_stop_ch_4'),
(NOW(), 'group', 30, 'unit_status', 'clear_counter_ch_4'),
(NOW(), 'group', 31, 'unit_status', 'clear_overflow_ch_4'),
(NOW(), 'group', 32, 'unit_status', 'latch_status_clear_status_ch_4'),
(NOW(), 'group', 33, 'unit_status', 'counter_start_stop_ch_5'),
(NOW(), 'group', 34, 'unit_status', 'clear_counter_ch_5'),
(NOW(), 'group', 35, 'unit_status', 'clear_overflow_ch_5'),
(NOW(), 'group', 36, 'unit_status', 'latch_status_clear_status_ch_5'),
(NOW(), 'group', 37, 'unit_status', 'counter_0'),
(NOW(), 'group', 38, 'unit_status', 'counter_1'),
(NOW(), 'group', 39, 'unit_status', 'counter_2'),
(NOW(), 'group', 40, 'unit_status', 'counter_3'),
(NOW(), 'group', 41, 'unit_status', 'counter_4'),
(NOW(), 'group', 42, 'unit_status', 'counter_5'),
(NOW(), 'group', 43, 'unit_status', 'pulse_output_low_level_0'),
(NOW(), 'group', 44, 'unit_status', 'pulse_output_low_level_1'),
(NOW(), 'group', 45, 'unit_status', 'pulse_output_low_level_2'),
(NOW(), 'group', 46, 'unit_status', 'pulse_output_low_level_3'),
(NOW(), 'group', 47, 'unit_status', 'pulse_output_low_level_4'),
(NOW(), 'group', 48, 'unit_status', 'pulse_output_low_level_5'),
(NOW(), 'group', 49, 'unit_status', 'pulse_output_high_level_0'),
(NOW(), 'group', 50, 'unit_status', 'pulse_output_high_level_1'),
(NOW(), 'group', 51, 'unit_status', 'pulse_output_high_level_2'),
(NOW(), 'group', 52, 'unit_status', 'pulse_output_high_level_3'),
(NOW(), 'group', 53, 'unit_status', 'pulse_output_high_level_4'),
(NOW(), 'group', 54, 'unit_status', 'pulse_output_high_level_5'),
(NOW(), 'group', 55, 'unit_status', 'set_absolute_pulse_0'),
(NOW(), 'group', 56, 'unit_status', 'set_absolute_pulse_1'),
(NOW(), 'group', 57, 'unit_status', 'set_absolute_pulse_2'),
(NOW(), 'group', 58, 'unit_status', 'set_absolute_pulse_3'),
(NOW(), 'group', 59, 'unit_status', 'set_absolute_pulse_4'),
(NOW(), 'group', 60, 'unit_status', 'set_absolute_pulse_5'),
(NOW(), 'group', 61, 'unit_status', 'set_incremental_pulse_0'),
(NOW(), 'group', 62, 'unit_status', 'set_incremental_pulse_1'),
(NOW(), 'group', 63, 'unit_status', 'set_incremental_pulse_2'),
(NOW(), 'group', 64, 'unit_status', 'set_incremental_pulse_3'),
(NOW(), 'group', 65, 'unit_status', 'set_incremental_pulse_4'),
(NOW(), 'group', 66, 'unit_status', 'set_incremental_pulse_5');

CREATE TABLE IF NOT EXISTS `iw_par_adam_6066_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(50) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_adam_6066_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`) VALUES
(NOW(), 'di0', '0_1_0', 'DI 0', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_0_X_N_-_-_-_-'),
(NOW(), 'di1', '0_1_1', 'DI 1', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_1_X_N_-_-_-_-'),
(NOW(), 'di2', '0_1_2', 'DI 2', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_2_X_N_-_-_-_-'),
(NOW(), 'di3', '0_1_3', 'DI 3', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_3_X_N_-_-_-_-'),
(NOW(), 'di4', '0_1_4', 'DI 4', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_4_X_N_-_-_-_-'),
(NOW(), 'di5', '0_1_5', 'DI 5', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_5_X_N_-_-_-_-'),
(NOW(), 'do0', '0_1_16', 'DO 0', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_16_X_N_5_16_X_N'),
(NOW(), 'do1', '0_1_17', 'DO 1', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_17_X_N_5_17_X_N'),
(NOW(), 'do2', '0_1_18', 'DO 2', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_18_X_N_5_18_X_N'),
(NOW(), 'do3', '0_1_19', 'DO 3', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_19_X_N_5_19_X_N'),
(NOW(), 'do4', '0_1_20', 'DO 4', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_20_X_N_5_20_X_N'),
(NOW(), 'do5', '0_1_21', 'DO 5', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_21_X_N_5_21_X_N'),
(NOW(), 'counter_start_stop_ch_0', '0_1_32', 'Counter Start(1)/Stop(0) Ch 0', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_32_X_N_5_32_X_N'),
(NOW(), 'clear_counter_ch_0', '0_1_33', 'Clear Counter(1) Ch 0', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_33_X_N_5_33_X_N'),
(NOW(), 'clear_overflow_ch_0', '0_1_34', 'Clear Overflow Ch 0', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_34_X_N_5_34_X_N'),
(NOW(), 'latch_status_clear_status_ch_0', '0_1_35', 'Latch Status/Clear Status Ch 0', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_35_X_N_5_35_X_N'),
(NOW(), 'counter_start_stop_ch_1', '0_1_36', 'Counter Start(1)/Stop(0) Ch 1', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_36_X_N_5_36_X_N'),
(NOW(), 'clear_counter_ch_1', '0_1_37', 'Clear Counter(1) Ch 1', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_37_X_N_5_37_X_N'),
(NOW(), 'clear_overflow_ch_1', '0_1_38', 'Clear Overflow Ch 1', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_38_X_N_5_38_X_N'),
(NOW(), 'latch_status_clear_status_ch_1', '0_1_39', 'Latch Status/Clear Status Ch 1', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_39_X_N_5_39_X_N'),
(NOW(), 'counter_start_stop_ch_2', '0_1_40', 'Counter Start(1)/Stop(0) Ch 2', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_40_X_N_5_40_X_N'),
(NOW(), 'clear_counter_ch_2', '0_1_41', 'Clear Counter(1) Ch 2', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_41_X_N_5_41_X_N'),
(NOW(), 'clear_overflow_ch_2', '0_1_42', 'Clear Overflow Ch 2', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_42_X_N_5_42_X_N'),
(NOW(), 'latch_status_clear_status_ch_2', '0_1_43', 'Latch Status/Clear Status Ch 2', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_43_X_N_5_43_X_N'),
(NOW(), 'counter_start_stop_ch_3', '0_1_44', 'Counter Start(1)/Stop(0) Ch 3', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_44_X_N_5_44_X_N'),
(NOW(), 'clear_counter_ch_3', '0_1_45', 'Clear Counter(1) Ch 3', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_45_X_N_5_45_X_N'),
(NOW(), 'clear_overflow_ch_3', '0_1_46', 'Clear Overflow Ch 3', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_46_X_N_5_46_X_N'),
(NOW(), 'latch_status_clear_status_ch_3', '0_1_477', 'Latch Status/Clear Status Ch 3', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_47_X_N_5_47_X_N'),
(NOW(), 'counter_start_stop_ch_4', '0_1_48', 'Counter Start(1)/Stop(0) Ch 4', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_48_X_N_5_48_X_N'),
(NOW(), 'clear_counter_ch_4', '0_1_49', 'Clear Counter(1) Ch 4', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_49_X_N_5_49_X_N'),
(NOW(), 'clear_overflow_ch_4', '0_1_50', 'Clear Overflow Ch 4', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_50_X_N_5_50_X_N'),
(NOW(), 'latch_status_clear_status_ch_4', '0_1_51', 'Latch Status/Clear Status Ch 4', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_51_X_N_5_51_X_N'),
(NOW(), 'counter_start_stop_ch_5', '0_1_52', 'Counter Start(1)/Stop(0) Ch 5', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_52_X_N_5_52_X_N'),
(NOW(), 'clear_counter_ch_5', '0_1_53', 'Clear Counter(1) Ch 5', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_53_X_N_5_53_X_N'),
(NOW(), 'clear_overflow_ch_5', '0_1_54', 'Clear Overflow Ch 5', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_54_X_N_5_54_X_N'),
(NOW(), 'latch_status_clear_status_ch_5', '0_1_55', 'Latch Status/Clear Status Ch 5', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_55_X_N_5_55_X_N'),
(NOW(), 'counter_0', '0_4_0', 'Counter Ch 0', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_0_I32_N_-_-_-_-'),
(NOW(), 'counter_1', '0_4_2', 'Counter Ch 1', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_2_I32_N_-_-_-_-'),
(NOW(), 'counter_2', '0_4_4', 'Counter Ch 2', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_4_I32_N_-_-_-_-'),
(NOW(), 'counter_3', '0_4_6', 'Counter Ch 3', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_6_I32_N_-_-_-_-'),
(NOW(), 'counter_4', '0_4_8', 'Counter Ch 4', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_8_I32_N_-_-_-_-'),
(NOW(), 'counter_5', '0_4_10', 'Counter Ch 5', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_10_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_low_level_0', '0_4_12', 'Pulse Output Low Level Ch 0', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_12_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_low_level_1', '0_4_14', 'Pulse Output Low Level Ch 1', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_14_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_low_level_2', '0_4_16', 'Pulse Output Low Level Ch 2', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_16_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_low_level_3', '0_4_18', 'Pulse Output Low Level Ch 3', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_18_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_low_level_4', '0_4_20', 'Pulse Output Low Level Ch 4', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_20_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_low_level_5', '0_4_22', 'Pulse Output Low Level Ch 5', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_22_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_high_level_0', '0_4_24', 'Pulse Output High Level Ch 0', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_24_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_high_level_1', '0_4_26', 'Pulse Output High Level Ch 1', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_26_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_high_level_2', '0_4_28', 'Pulse Output High Level Ch 2', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_28_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_high_level_3', '0_4_30', 'Pulse Output High Level Ch 3', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_30_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_high_level_4', '0_4_32', 'Pulse Output High Level Ch 4', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_32_I32_N_-_-_-_-'),
(NOW(), 'pulse_output_high_level_5', '0_4_34', 'Pulse Output High Level Ch 5', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '', '', '', '', '', '4_34_I32_N_-_-_-_-'),
(NOW(), 'set_absolute_pulse_0', '0_4_36', 'Set Absolute Pulse Ch 0', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_36_I32_N_6_36_I32_N'),
(NOW(), 'set_absolute_pulse_1', '0_4_38', 'Set Absolute Pulse Ch 1', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_38_I32_N_6_38_I32_N'),
(NOW(), 'set_absolute_pulse_2', '0_4_40', 'Set Absolute Pulse Ch 2', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_40_I32_N_6_40_I32_N'),
(NOW(), 'set_absolute_pulse_3', '0_4_42', 'Set Absolute Pulse Ch 3', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_42_I32_N_6_42_I32_N'),
(NOW(), 'set_absolute_pulse_4', '0_4_44', 'Set Absolute Pulse Ch 4', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_44_I32_N_6_44_I32_N'),
(NOW(), 'set_absolute_pulse_5', '0_4_46', 'Set Absolute Pulse Ch 5', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_46_I32_N_6_46_I32_N'),
(NOW(), 'set_incremental_pulse_0', '0_4_48', 'Set Incremental Pulse Ch 0', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_48_I32_N_6_48_I32_N'),
(NOW(), 'set_incremental_pulse_1', '0_4_50', 'Set Incremental Pulse Ch 1', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_50_I32_N_6_50_I32_N'),
(NOW(), 'set_incremental_pulse_2', '0_4_52', 'Set Incremental Pulse Ch 2', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_52_I32_N_6_52_I32_N'),
(NOW(), 'set_incremental_pulse_3', '0_4_54', 'Set Incremental Pulse Ch 3', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_54_I32_N_6_54_I32_N'),
(NOW(), 'set_incremental_pulse_4', '0_4_56', 'Set Incremental Pulse Ch 4', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_56_I32_N_6_56_I32_N'),
(NOW(), 'set_incremental_pulse_5', '0_4_58', 'Set Incremental Pulse Ch 5', '', 'Integral values', 'integer', '', '', 'rw', '', '%.0f', '', '', '', '', '', '', '', '4_58_I32_N_6_58_I32_N');

CREATE TABLE IF NOT EXISTS `iw_set_adam_6066` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` enum('0','1','2') NOT NULL DEFAULT '0',
  `save_freq` set('','fast','norm','slow') NOT NULL DEFAULT 'norm',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.4';

REPLACE INTO `iw_set_adam_6066` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'di0', '1', '1', 'norm', '2', 'norm', 'N', '', 0),
(NOW(), 'di1', '1', '1', 'norm', '2', 'norm', 'N', '', 0),
(NOW(), 'di2', '1', '0', 'norm', '2', 'norm', 'N', '', 0),
(NOW(), 'di3', '1', '0', 'norm', '2', 'norm', 'N', '', 0),
(NOW(), 'di4', '1', '0', 'norm', '2', 'norm', 'N', '', 0),
(NOW(), 'di5', '1', '0', 'norm', '2', 'norm', 'N', '', 0),
(NOW(), 'do0', '1', '0', 'norm', '2', 'norm', '', '', 0),
(NOW(), 'do1', '1', '0', 'norm', '2', 'norm', '', '', 0),
(NOW(), 'do2', '1', '0', 'norm', '2', 'norm', '', '', 0),
(NOW(), 'do3', '1', '0', 'norm', '2', 'norm', '', '', 0),
(NOW(), 'do4', '1', '0', 'norm', '2', 'norm', '', '', 0),
(NOW(), 'do5', '1', '0', 'norm', '2', 'norm', '', '', 0),
(NOW(), 'counter_start_stop_ch_0', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_counter_ch_0', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_overflow_ch_0', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'latch_status_clear_status_ch_0', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'counter_start_stop_ch_1', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_counter_ch_1', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_overflow_ch_1', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'latch_status_clear_status_ch_1', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'counter_start_stop_ch_2', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_counter_ch_2', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_overflow_ch_2', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'latch_status_clear_status_ch_2', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'counter_start_stop_ch_3', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_counter_ch_3', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_overflow_ch_3', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'latch_status_clear_status_ch_3', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'counter_start_stop_ch_4', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_counter_ch_4', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_overflow_ch_4', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'latch_status_clear_status_ch_4', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'counter_start_stop_ch_5', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_counter_ch_5', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'clear_overflow_ch_5', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'latch_status_clear_status_ch_5', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'counter_0', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'counter_1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'counter_2', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'counter_3', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'counter_4', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'counter_5', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'pulse_output_low_level_0', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_low_level_1', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_low_level_2', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_low_level_3', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_low_level_4', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_low_level_5', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_high_level_0', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_high_level_1', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_high_level_2', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_high_level_3', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_high_level_4', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pulse_output_high_level_5', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_absolute_pulse_0', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_absolute_pulse_1', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_absolute_pulse_2', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_absolute_pulse_3', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_absolute_pulse_4', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_absolute_pulse_5', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_incremental_pulse_0', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_incremental_pulse_1', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_incremental_pulse_2', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_incremental_pulse_3', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_incremental_pulse_4', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'set_incremental_pulse_5', '1', '0', 'slow', '2', 'norm', '', '', 0);




-- Changelog
--
-- v1 Orginal
--
--