DROP TABLE IF EXISTS `iw_par_adamgcl_groups`;
CREATE TABLE IF NOT EXISTS `iw_par_adamgcl_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_adamgcl_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 2, 'status', 'Status'),
(NOW(), 'group_alias', 1, 'ai', 'Analog Innganger'),
(NOW(), 'group', 1, 'ai', '0_AI_0'),
(NOW(), 'group', 2, 'ai', '0_AI_1'),
(NOW(), 'group', 3, 'ai', '0_AI_2'),
(NOW(), 'group', 4, 'ai', '0_AI_3'),
(NOW(), 'group', 5, 'ai', '0_AI_4'),
(NOW(), 'group', 6, 'ai', '0_AI_5'),
(NOW(), 'group', 7, 'ai', '0_AI_6'),
(NOW(), 'group', 8, 'ai', '0_AI_7'),
(NOW(), 'group', 42, 'ai', 'lalm_3'),
(NOW(), 'group', 41, 'ai', 'halm_3'),
(NOW(), 'group', 44, 'ai', 'llimit_3'),
(NOW(), 'group', 45, 'ai', 'hlimit_3'),
(NOW(), 'group', 46, 'ai', 'delay_3'),
(NOW(), 'group', 32, 'ai', 'lalm_2'),
(NOW(), 'group', 31, 'ai', 'halm_2'),
(NOW(), 'group', 34, 'ai', 'llimit_2'),
(NOW(), 'group', 35, 'ai', 'hlimit_2'),
(NOW(), 'group', 36, 'ai', 'delay_2'),
(NOW(), 'group', 22, 'ai', 'lalm_1'),
(NOW(), 'group', 21, 'ai', 'halm_1'),
(NOW(), 'group', 24, 'ai', 'llimit_1'),
(NOW(), 'group', 25, 'ai', 'hlimit_1'),
(NOW(), 'group', 26, 'ai', 'delay_1'),
(NOW(), 'group', 52, 'ai', 'lalm_4'),
(NOW(), 'group', 51, 'ai', 'halm_4'),
(NOW(), 'group', 54, 'ai', 'llimit_4'),
(NOW(), 'group', 55, 'ai', 'hlimit_4'),
(NOW(), 'group', 56, 'ai', 'delay_4'),
(NOW(), 'group', 62, 'ai', 'lalm_5'),
(NOW(), 'group', 61, 'ai', 'halm_5'),
(NOW(), 'group', 64, 'ai', 'llimit_5'),
(NOW(), 'group', 65, 'ai', 'hlimit_5'),
(NOW(), 'group', 66, 'ai', 'delay_5'),
(NOW(), 'group', 72, 'ai', 'lalm_6'),
(NOW(), 'group', 71, 'ai', 'halm_6'),
(NOW(), 'group', 74, 'ai', 'llimit_6'),
(NOW(), 'group', 75, 'ai', 'hlimit_6'),
(NOW(), 'group', 76, 'ai', 'delay_6'),
(NOW(), 'group', 12, 'ai', 'lalm_0'),
(NOW(), 'group', 11, 'ai', 'halm_0'),
(NOW(), 'group', 14, 'ai', 'llimit_0'),
(NOW(), 'group', 15, 'ai', 'hlimit_0'),
(NOW(), 'group', 16, 'ai', 'delay_0'),
(NOW(), 'group', 82, 'ai', 'lalm_7'),
(NOW(), 'group', 81, 'ai', 'halm_7'),
(NOW(), 'group', 84, 'ai', 'llimit_7'),
(NOW(), 'group', 85, 'ai', 'hlimit_7'),
(NOW(), 'group', 86, 'ai', 'delay_7'),
(NOW(), 'group', 0, 'status', '0_SN_0'),
(NOW(), 'group', 1, 'status', '0_SI_0'),
(NOW(), 'group', 2, 'status', '0_SP_0'),
(NOW(), 'group', 3, 'status', '0_LI_0'),
(NOW(), 'group', 4, 'status', '0_CV_0'),
(NOW(), 'group', 5, 'status', '0_MO_0'),
(NOW(), 'group', 6, 'status', '0_TIMEOUT_0');

DROP TABLE IF EXISTS `iw_par_adamgcl_param`;
CREATE TABLE IF NOT EXISTS `iw_par_adamgcl_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(50) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_adamgcl_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), '0_AI_0', '0_AI_0', 'Analog Inn 0', 'AI0', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '1', '0', '65536', '-40', '160', '', ''),
(NOW(), '0_AI_1', '0_AI_1', 'Analog Inn 1', 'AI1', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '1', '0', '65536', '-40', '160', '', ''),
(NOW(), '0_AI_2', '0_AI_2', 'Analog Inn 2', 'AI2', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '1', '0', '65536', '-40', '160', '', ''),
(NOW(), '0_AI_3', '0_AI_3', 'Analog Inn 3', 'AI3', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '1', '0', '65536', '-50', '150', '', ''),
(NOW(), '0_AI_4', '0_AI_4', 'Analog Inn 4', 'AI4', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '1', '0', '65536', '-50', '150', '', ''),
(NOW(), '0_AI_5', '0_AI_5', 'Analog Inn 5', 'AI5', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '1', '0', '65536', '-50', '150', '', ''),
(NOW(), '0_AI_6', '0_AI_6', 'Analog Inn 6', 'AI6', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '1', '0', '65536', '-50', '150', '', ''),
(NOW(), '0_AI_7', '0_AI_7', 'Analog Inn 7', 'AI7', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '1', '0', '65536', '-50', '150', '', ''),
(NOW(), '0_CO_0', '0_CO_0', 'COUNTER 0', '', 'Integral values', 'integer', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_CO_1', '0_CO_1', 'COUNTER 1', '', 'Integral values', 'integer', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_CO_2', '0_CO_2', 'COUNTER 2', '', 'Integral values', 'integer', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_CO_3', '0_CO_3', 'COUNTER 3', '', 'Integral values', 'integer', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_CO_4', '0_CO_4', 'COUNTER 4', '', 'Integral values', 'integer', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_CO_5', '0_CO_5', 'COUNTER 5', '', 'Integral values', 'integer', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DI_0', '0_DI_0', 'DIG I/P 0', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DI_1', '0_DI_1', 'DIG I/P 1', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DI_2', '0_DI_2', 'DIG I/P 2', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DI_3', '0_DI_3', 'DIG I/P 3', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DI_4', '0_DI_4', 'DIG I/P 4', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DI_5', '0_DI_5', 'DIG I/P 5', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DO_0', '0_DO_0', 'DIG O/P 0', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DO_1', '0_DO_1', 'DIG O/P 1', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DO_2', '0_DO_2', 'DIG O/P 2', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DO_3', '0_DO_3', 'DIG O/P 3', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DO_4', '0_DO_4', 'DIG O/P 4', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_DO_5', '0_DO_5', 'DIG O/P 5', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_SN_0', '0_SN_0', 'SEQ NO', '', 'Integral values', 'integer', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_SI_0', '0_SI_0', 'Source ip', '', 'String values', 'string', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_SP_0', '0_SP_0', 'Source port', '', 'Integral values', 'integer', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_LI_0', '0_LI_0', 'Local ip', '', 'String values', 'string', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_CV_0', '0_CV_0', 'Custom value', '', 'Integral values', 'integer', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_MO_0', '0_MO_0', 'Model', '', 'Integral values', 'integer', '', '1', 'r', '', '%X', '', '', '', '', '', '', '', '', ''),
(NOW(), '0_TIMEOUT_0', '0_TIMEOUT_0', 'Module Timeout', '', 'Digital IO', 'boolean', '', '1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'delay_0', 'DELAY_AI_0', 'Analog Inngang 0 Forsinkelse alarm', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_0', 'HLIMIT_AI_0', 'Analog Inngang 0 Grense for høy alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_0', 'LLIMIT_AI_0', 'Analog Inngang 0 Grense for lav alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'halm_0', 'HALM_AI_0', 'Analog Inngang 0 Alarm høy alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_0', 'LALM_AI_0', 'Analog Inngang 0 Alarm lav alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'delay_1', 'DELAY_AI_1', 'Analog Inngang 1 Forsinkelse alarm', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_1', 'HLIMIT_AI_1', 'Analog Inngang 1 Grense for høy alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_1', 'LLIMIT_AI_1', 'Analog Inngang 1 Grense for lav alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'halm_1', 'HALM_AI_1', 'Analog Inngang 1 Alarm høy alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_1', 'LALM_AI_1', 'Analog Inngang 1 Alarm lav alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'delay_2', 'DELAY_AI_2', 'Analog Inngang 2 Forsinkelse alarm', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_2', 'HLIMIT_AI_2', 'Analog Inngang 2 Grense for høy alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_2', 'LLIMIT_AI_2', 'Analog Inngang 2 Grense for lav alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'halm_2', 'HALM_AI_2', 'Analog Inngang 2 Alarm høy alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_2', 'LALM_AI_2', 'Analog Inngang 2 Alarm lav alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'delay_3', 'DELAY_AI_3', 'Analog Inngang 3 Forsinkelse alarm', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_3', 'HLIMIT_AI_3', 'Analog Inngang 3 Grense for høy alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_3', 'LLIMIT_AI_3', 'Analog Inngang 3 Grense for lav alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'halm_3', 'HALM_AI_3', 'Analog Inngang 3 Alarm høy alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_3', 'LALM_AI_3', 'Analog Inngang 3 Alarm lav alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'delay_4', 'DELAY_AI_4', 'Analog Inngang 4 Forsinkelse alarm', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_4', 'HLIMIT_AI_4', 'Analog Inngang 4 Grense for høy alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_4', 'LLIMIT_AI_4', 'Analog Inngang 4 Grense for lav alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'halm_4', 'HALM_AI_4', 'Analog Inngang 4 Alarm høy alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_4', 'LALM_AI_4', 'Analog Inngang 4 Alarm lav alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'delay_5', 'DELAY_AI_5', 'Analog Inngang 5 Forsinkelse alarm', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_5', 'HLIMIT_AI_5', 'Analog Inngang 5 Grense for høy alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_5', 'LLIMIT_AI_5', 'Analog Inngang 5 Grense for lav alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'halm_5', 'HALM_AI_5', 'Analog Inngang 5 Alarm høy alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_5', 'LALM_AI_5', 'Analog Inngang 5 Alarm lav alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'delay_6', 'DELAY_AI_6', 'Analog Inngang 6 Forsinkelse alarm', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_6', 'HLIMIT_AI_6', 'Analog Inngang 6 Grense for høy alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_6', 'LLIMIT_AI_6', 'Analog Inngang 6 Grense for lav alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'halm_6', 'HALM_AI_6', 'Analog Inngang 6 Alarm høy alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_6', 'LALM_AI_6', 'Analog Inngang 6 Alarm lav alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'delay_7', 'DELAY_AI_7', 'Analog Inngang 7 Forsinkelse alarm', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_7', 'HLIMIT_AI_7', 'Analog Inngang 7 Grense for høy alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_7', 'LLIMIT_AI_7', 'Analog Inngang 7 Grense for lav alarm', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'halm_7', 'HALM_AI_7', 'Analog Inngang 7 Alarm høy alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_7', 'LALM_AI_7', 'Analog Inngang 7 Alarm lav alarmeratur', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', '');

DROP TABLE IF EXISTS `iw_set_adamgcl`;
CREATE TABLE IF NOT EXISTS `iw_set_adamgcl` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_adamgcl` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), '0_AI_0', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_AI_1', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_AI_2', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_AI_3', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_AI_4', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_AI_5', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_AI_6', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_AI_7', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DI_0', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DI_1', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DI_2', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DI_3', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DI_4', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DI_5', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DO_0', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DO_1', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DO_2', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DO_3', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DO_4', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_DO_5', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_CO_0', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_CO_1', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_CO_2', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_CO_3', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_CO_4', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_CO_5', '0', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_SN_0', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_SI_0', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_SP_0', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_LI_0', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_CV_0', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_MO_0', '1', '1', 'never', 'sec', '15', '', '', 0),
(NOW(), '0_TIMEOUT_0', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'delay_1', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'hlimit_1', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'llimit_1', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'halm_1', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'lalm_1', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'delay_2', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'hlimit_2', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'llimit_2', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'halm_2', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'lalm_2', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'delay_3', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'hlimit_3', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'llimit_3', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'halm_3', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'lalm_3', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'hlimit_0', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'llimit_0', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'halm_0', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'lalm_0', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'delay_0', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'hlimit_4', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'llimit_4', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'halm_4', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'lalm_4', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'delay_4', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'hlimit_5', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'llimit_5', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'halm_5', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'lalm_5', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'delay_5', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'hlimit_6', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'llimit_6', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'halm_6', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'lalm_6', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'delay_6', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'hlimit_7', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'llimit_7', '1', '1', 'norm', 'sec', '15', '', '', 0),
(NOW(), 'halm_7', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'lalm_7', '1', '1', 'norm', 'sec', '15', 'A', '', 0),
(NOW(), 'delay_7', '1', '1', 'norm', 'sec', '15', '', '', 0);



-- Changelog
--
-- v1 Orginal
--
--