REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'U01', 'Aermec Fancoil', 'AERMEC_E1', 'AERMEC', '0_1', 'AERMEC', 'AERMEC', 0, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'comm_port', 'AERMEC', '2', '', '', ''),
(NOW(), 'mb_mode', 'AERMEC', '0', '', '0=RTU|1=ASCII|2=TCP', ''),
(NOW(), 'mb_tcp_servers', 'AERMEC', '1;192.168.10.100;502;1000;2;1000\r\n', '', 'ID;IPadr;IPport;ConnTout;ConnRetries;RequestTout', ''),
(NOW(), 'comm_baudrate', 'AERMEC', '19200', '', '', ''),
(NOW(), 'comm_stop_bits', 'AERMEC', '1', '', '', ''),
(NOW(), 'comm_data_bits', 'AERMEC', '8', '', '', ''),
(NOW(), 'comm_parity', 'AERMEC', '2', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'max_param_block_time', 'AERMEC', '2', 'hours', '', ''),
(NOW(), 'speed_index_slow', 'AERMEC', '1', '', '', ''),
(NOW(), 'speed_index_norm', 'AERMEC', '1', '', '', ''),
(NOW(), 'speed_index_offline', 'AERMEC', '10', '', '', ''),
(NOW(), 'speed_index_block', 'AERMEC', '10', '', '', ''),
(NOW(), 'show_queue_info', 'AERMEC', '0', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'AERMEC', '10', 'min.', '', ''),
(NOW(), 'max_error_count', 'AERMEC', '2', '', '', ''),
(NOW(), 'mb_request_timeout', 'AERMEC', '1000', 'ms', '', ''),
(NOW(), 'sql_queue_poll_time', 'AERMEC', '2000', 'msec.', '', ''),
(NOW(), 'idle_event_rate', 'AERMEC', '250', 'msec.', '', ''),
(NOW(), 'packet_timeout', 'AERMEC', '1', 'sec.', '', ''),
(NOW(), 'max_outstanding_packets', 'AERMEC', '-1', '', '', ''),
(NOW(), 'check_rate', 'AERMEC', '1', 'ms', '', ''),
(NOW(), 'handshake', 'AERMEC', '0', '', '0|1|2', ''),
(NOW(), 'force_word_not_byte', 'AERMEC', '0', '', '0|1', ''),
(NOW(), 'mb_request_retries', 'AERMEC', '2', '', '', ''),
(NOW(), 'max_group_count', 'AERMEC', '1', '', '', ''),
(NOW(), 'value_quality_check_limit', 'AERMEC', '0', '', '0 = disabled', ''),
(NOW(), 'mux_settle_time', 'AERMEC', '1500', 'ms', 'Time for the muxed input to settle. The value shuld be a multiple off 100.', ''),
(NOW(), 'startup_delay', 'AERMEC', '15', 'Sec.', '', ''),
(NOW(), 'alarm_handler', 'AERMEC', '', '', '', ''),
(NOW(), 'mb_tcp_connect_retries_default', 'AERMEC', '2', '', '', ''),
(NOW(), 'mb_tcp_connect_timeout_default', 'AERMEC', '1000', 'ms', '', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_mb.exe', 'AERMEC', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'AERMEC', 'AERMEC_E1_param', 'AERMEC_E1_groups');

CREATE TABLE IF NOT EXISTS `iw_par_aermec_e1_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_aermec_e1_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'main', 'Measurements'),
(NOW(), 'group_alias', 2, 'adv', 'Advanced'),
(NOW(), 'group', 1, 'adv', 'adv_0_3_10.5'),
(NOW(), 'group', 11, 'adv', 'adv_0_3_10.6'),
(NOW(), 'group', 21, 'adv', 'adv_0_3_10.7'),
(NOW(), 'group', 31, 'adv', 'adv_0_3_6.3'),
(NOW(), 'group', 41, 'adv', 'adv_0_3_6.4'),
(NOW(), 'group', 51, 'adv', 'adv_0_3_6.5'),
(NOW(), 'group', 61, 'adv', 'adv_0_3_6.6'),
(NOW(), 'group', 71, 'adv', 'adv_0_3_6.7'),
(NOW(), 'group', 81, 'adv', 'adv_0_3_13.1'),
(NOW(), 'group', 91, 'adv', 'adv_0_3_13.2'),
(NOW(), 'group', 101, 'adv', 'adv_0_3_13.3'),
(NOW(), 'group', 111, 'adv', 'adv_0_3_13.4'),
(NOW(), 'group', 121, 'adv', 'adv_0_3_13.5'),
(NOW(), 'group', 131, 'adv', 'adv_0_3_13.7'),
(NOW(), 'group', 1, 'main', 'main_0_3_0'),
(NOW(), 'group', 11, 'main', 'main_0_3_1'),
(NOW(), 'group', 21, 'main', 'main_0_3_2'),
(NOW(), 'group', 31, 'main', 'main_0_3_3'),
(NOW(), 'group', 41, 'main', 'main_0_3_4'),
(NOW(), 'group', 51, 'main', 'main_0_3_5'),
(NOW(), 'group', 61, 'main', 'main_0_3_7'),
(NOW(), 'group', 71, 'main', 'main_0_3_9'),
(NOW(), 'group', 81, 'main', 'main_0_3_11'),
(NOW(), 'group', 91, 'main', 'main_0_3_12'),
(NOW(), 'group', 101, 'main', 'main_0_3_14'),
(NOW(), 'group', 111, 'main', 'main_0_3_15'),
(NOW(), 'group', 121, 'main', 'main_0_3_16'),
(NOW(), 'group', 131, 'main', 'main_0_3_17'),
(NOW(), 'group', 141, 'main', 'main_0_3_18'),
(NOW(), 'group', 151, 'main', 'main_0_3_20'),
(NOW(), 'group', 161, 'main', 'main_0_3_10.8#8'),
(NOW(), 'group', 171, 'main', 'main_0_3_10.3'),
(NOW(), 'group', 181, 'main', 'main_0_3_10.4'),
(NOW(), 'group', 191, 'main', 'main_0_3_8.0'),
(NOW(), 'group', 201, 'main', 'main_0_3_8.1'),
(NOW(), 'group', 211, 'main', 'main_0_3_8.2'),
(NOW(), 'group', 221, 'main', 'main_0_3_8.3'),
(NOW(), 'group', 231, 'main', 'main_0_3_8.4'),
(NOW(), 'group', 241, 'main', 'main_0_3_8.5'),
(NOW(), 'group', 251, 'main', 'main_0_3_8.6'),
(NOW(), 'group', 261, 'main', 'main_0_3_8.7');

CREATE TABLE IF NOT EXISTS `iw_par_aermec_e1_param` (
  `row_date` datetime NOT NULL DEFAULT '2002-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_aermec_e1_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'main_0_3_0', '0_3_0', 'Room Probe', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_0_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_1', '0_3_1', 'Regulation Probe', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_1_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_2', '0_3_2', 'Water Probe', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_2_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_3', '0_3_3', 'Auxiliary Probe', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_3_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_4', '0_3_4', 'Regulation Set-point', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_4_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_5', '0_3_5', 'Mode Selector', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_5_I16_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Unknown state contact supplier"},"1":{"t":"OFF"},"2":{"t":"AUTO"},"3":{"t":"V1"},"4":{"t":"V2"},"5":{"t":"V3"},"6":{"t":"LOAD"}}}'),
(NOW(), 'main_0_3_6', '0_3_6', 'Fan-Valve State', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_6_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_7', '0_3_7', 'Requested Power', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_7_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_8', '0_3_8', 'Alarms', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_8_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_9', '0_3_9', 'Dip-Switch', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_9_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_10', '0_3_10', 'I/O', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_10_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_11', '0_3_11', 'Software Version', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_11_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_12', '0_3_12', 'Type of regulation probe', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_12_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_13', '0_3_13', 'Forcing Flag', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_13_I16_N_-_-_-_-', ''),
(NOW(), 'main_0_3_14', '0_3_14', 'Forced Mode', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_14_I16_N_16_14_I16_N', '{"rev":"1","type":"num","v":{"0":{"t":"xxxx"},"1":{"t":"OFF"},"2":{"t":"AUTO"},"3":{"t":"V1"},"4":{"t":"V2"},"5":{"t":"V3"},"6":{"t":"LOAD"}}}'),
(NOW(), 'main_0_3_15', '0_3_15', 'Overall set-point', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_15_I16_N_16_15_I16_N', ''),
(NOW(), 'main_0_3_16', '0_3_16', 'Valve Logic', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_16_I16_N_16_16_I16_N', '{"rev":"1","type":"num","v":{"0":{"t":"Optimised valve logic"},"1":{"t":"Normal valve logic"}}}'),
(NOW(), 'main_0_3_17', '0_3_17', '4-PIPE Water Probe', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_17_I16_N_16_17_I16_N', '{"rev":"1","type":"num","v":{"0":{"t":"Disabled probe"},"1":{"t":"Enabled maximum level control probe"}}}'),
(NOW(), 'main_0_3_18', '0_3_18', 'Inverter Power', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_18_I16_N_16_18_I16_N', ''),
(NOW(), 'main_0_3_20', '0_3_20', 'Serial Addressing Register', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_20_I16_N_16_20_I16_N', ''),
(NOW(), 'main_0_3_10.8#8', '0_3_10.8#8', 'Type of Interface', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_10_I16_N_', '{"rev":"1","type":"num","v":{"162":{"t":"E2"},"163":{"t":"E3"},"164":{"t":"E4"}}}'),
(NOW(), 'adv_0_3_10.0', '0_3_10.0', 'Reserved', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_10_I16_N_', ''),
(NOW(), 'adv_0_3_10.1', '0_3_10.1', 'Reserved', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_10_I16_N_', ''),
(NOW(), 'adv_0_3_10.2', '0_3_10.2', 'WIN', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_10_I16_N_', ''),
(NOW(), 'main_0_3_10.3', '0_3_10.3', 'Season Mode', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_10_I16_N_', '{"rev":"1","type":"num","v":{"0":{"t":"Cold season"},"1":{"t":"Hot season"}}}'),
(NOW(), 'main_0_3_10.4', '0_3_10.4', 'Thermostat request', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_10_I16_N_', '{"rev":"1","type":"num","v":{"0":{"t":"Thermostat reached"},"1":{"t":"Thermostat request"}}}'),
(NOW(), 'adv_0_3_10.5', '0_3_10.5', 'Thermostat Economy mode', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_10_I16_N_', '{"rev":"1","type":"num","v":{"0":{"t":"Disabled"},"1":{"t":"Enabled"}}}'),
(NOW(), 'adv_0_3_10.6', '0_3_10.6', 'External contact input state', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_10_I16_N_', '{"rev":"1","type":"num","v":{"0":{"t":"Closed input"},"1":{"t":"Open input"}}}'),
(NOW(), 'adv_0_3_10.7', '0_3_10.7', 'Micro switch input state', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_10_I16_N_', '{"rev":"1","type":"num","v":{"0":{"t":"Closed input"},"1":{"t":"Open input"}}}'),
(NOW(), 'main_0_3_8.0', '0_3_8.0', 'Fuse broken', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_8_I16_N_', ''),
(NOW(), 'main_0_3_8.1', '0_3_8.1', 'Condensate discharge', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_8_I16_N_', ''),
(NOW(), 'main_0_3_8.2', '0_3_8.2', 'Electric heater fault', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_8_I16_N_', ''),
(NOW(), 'main_0_3_8.3', '0_3_8.3', 'Inverter control alarm', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_8_I16_N_', ''),
(NOW(), 'main_0_3_8.4', '0_3_8.4', 'Disconnected user interface', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_8_I16_N_', ''),
(NOW(), 'main_0_3_8.5', '0_3_8.5', 'Water alarm not suitable for operation', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_8_I16_N_', ''),
(NOW(), 'main_0_3_8.6', '0_3_8.6', 'Fan coil in anti-freeze mode', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_8_I16_N_', ''),
(NOW(), 'main_0_3_8.7', '0_3_8.7', 'Room probe anomaly', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_8_I16_N_', ''),
(NOW(), 'adv_0_3_6.3', '0_3_6.3', 'Fan-Valve State Y2', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_6_I16_N_', ''),
(NOW(), 'adv_0_3_6.4', '0_3_6.4', 'Fan-Valve State Y1', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_6_I16_N_', ''),
(NOW(), 'adv_0_3_6.5', '0_3_6.5', 'Fan-Valve State V3', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_6_I16_N_', ''),
(NOW(), 'adv_0_3_6.6', '0_3_6.6', 'Fan-Valve State V2', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_6_I16_N_', ''),
(NOW(), 'adv_0_3_6.7', '0_3_6.7', 'Fan-Valve State V1', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_6_I16_N_', ''),
(NOW(), 'adv_0_3_13.0', '0_3_13.0', 'Reserved', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_13_I16_N_', ''),
(NOW(), 'adv_0_3_13.1', '0_3_13.1', 'Season mode forcing flag', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_13_I16_N_', ''),
(NOW(), 'adv_0_3_13.2', '0_3_13.2', 'Seasons flag', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_13_I16_N_', ''),
(NOW(), 'adv_0_3_13.3', '0_3_13.3', 'Self-addressing flag', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_13_I16_N_', ''),
(NOW(), 'adv_0_3_13.4', '0_3_13.4', 'Serial address display activation flag', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_13_I16_N_', ''),
(NOW(), 'adv_0_3_13.5', '0_3_13.5', 'Functioning set-point forcing flag', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_13_I16_N_', ''),
(NOW(), 'adv_0_3_13.6', '0_3_13.6', 'Reserved', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_13_I16_N_', ''),
(NOW(), 'adv_0_3_13.7', '0_3_13.7', 'Functioning mode forcing flag', '', 'Integral values', 'integer', '', '-1', 'vr', '', '', '', '', '', '', '', '', '', '3_13_I16_N_', '');

CREATE TABLE IF NOT EXISTS `iw_set_aermec_e1` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_aermec_e1` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'main_0_3_0', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'main_0_3_1', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'main_0_3_2', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'main_0_3_3', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'main_0_3_4', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'main_0_3_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_11', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_12', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_13', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_14', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_15', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_16', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_17', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_18', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_20', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_10.8#8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_10.0', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_10.1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_10.2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_10.3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_10.4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_10.5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_10.6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_10.7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'main_0_3_8.0', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'main_0_3_8.1', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'main_0_3_8.2', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'main_0_3_8.3', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'main_0_3_8.4', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'main_0_3_8.5', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'main_0_3_8.6', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'main_0_3_8.7', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'adv_0_3_6.3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_6.4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_6.5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_6.6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_6.7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_13.0', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_13.1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_13.2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_13.3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_13.4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_13.5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_13.6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'adv_0_3_13.7', '1', '0', 'slow', 'change', '', '', '', 0);




-- Changelog
--
--
-- v1 orginal
--
--
--