REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'EV01', 'Energi Mbus', 'anybus_mbus', 'ANYBUS', '1_0', 'ANYBUS', 'ANYBUS', 50, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'comm_port', 'ANYBUS', '7', '', '', ''),
(NOW(), 'force_word_not_byte', 'ANYBUS', '0', '', '0|1', ''),
(NOW(), 'handshake', 'ANYBUS', '0', '', '0|1|2', ''),
(NOW(), 'check_rate', 'ANYBUS', '1', 'ms', '', ''),
(NOW(), 'comm_parity', 'ANYBUS', '0', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'comm_data_bits', 'ANYBUS', '8', '', '', ''),
(NOW(), 'comm_stop_bits', 'ANYBUS', '1', '', '', ''),
(NOW(), 'comm_baudrate', 'ANYBUS', '19200', '', '', ''),
(NOW(), 'max_outstanding_packets', 'ANYBUS', '-1', '', '', ''),
(NOW(), 'packet_timeout', 'ANYBUS', '1', 'sec.', '', ''),
(NOW(), 'idle_event_rate', 'ANYBUS', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'ANYBUS', '2000', 'msec.', '', ''),
(NOW(), 'max_error_count', 'ANYBUS', '2', '', '', ''),
(NOW(), 'mb_mode', 'ANYBUS', '2', '', '0=RTU|1=ASCII|2=TCP', ''),
(NOW(), 'mb_request_timeout', 'ANYBUS', '1000', 'ms', '', ''),
(NOW(), 'mb_request_retries', 'ANYBUS', '2', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'ANYBUS', '10', 'min.', '', ''),
(NOW(), 'show_queue_info', 'ANYBUS', '0', '', '', ''),
(NOW(), 'speed_index_block', 'ANYBUS', '10', '', '', ''),
(NOW(), 'speed_index_offline', 'ANYBUS', '10', '', '', ''),
(NOW(), 'speed_index_slow', 'ANYBUS', '1', '', '', ''),
(NOW(), 'speed_index_norm', 'ANYBUS', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'ANYBUS', '2', 'hours', '', ''),
(NOW(), 'max_group_count', 'ANYBUS', '1', '', '', ''),
(NOW(), 'value_quality_check_limit', 'ANYBUS', '0', '', '0 = disabled', ''),
(NOW(), 'mux_settle_time', 'ANYBUS', '1500', 'ms', 'Time for the muxed input to settle. The value shuld be a multiple off 100.', ''),
(NOW(), 'startup_delay', 'ANYBUS', '15', 'Sec.', '', ''),
(NOW(), 'alarm_handler', 'ANYBUS', '', '', '', ''),
(NOW(), 'mb_tcp_servers', 'ANYBUS', '1;192.168.10.120;502;1000;2;500\r\n1;192.168.163.14;502;1000;2;500', '', 'ID;IPadr;IPport;ConnTout;ConnRetries;RequestTout', ''),
(NOW(), 'mb_tcp_connect_timeout_default', 'ANYBUS', '2000', 'ms', '', ''),
(NOW(), 'mb_tcp_connect_retries_default', 'ANYBUS', '2', '', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'ANYBUS', 'anybus_mbus_param', 'anybus_mbus_groups');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_mb.exe', 'ANYBUS', '', '');

CREATE TABLE IF NOT EXISTS `iw_par_anybus_mbus_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_anybus_mbus_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'meter1', 'Måler 1'),
(NOW(), 'group_alias', 2, 'meter2', 'Måler 2'),
(NOW(), 'group_alias', 3, 'meter3', 'Måler 3'),
(NOW(), 'group_alias', 4, 'meter4', 'Måler 4'),
(NOW(), 'group', 10, 'meter1', 'meter1_id'),
(NOW(), 'group', 11, 'meter1', 'meter1_energy'),
(NOW(), 'group', 12, 'meter1', 'meter1_volume'),
(NOW(), 'group', 13, 'meter1', 'meter1_power'),
(NOW(), 'group', 14, 'meter1', 'meter1_flow'),
(NOW(), 'group', 15, 'meter1', 'meter1_flow_temp'),
(NOW(), 'group', 16, 'meter1', 'meter1_return_temp'),
(NOW(), 'group', 17, 'meter1', 'meter1_diff_temp'),
(NOW(), 'group', 18, 'meter1', 'meter1_fabrication'),
(NOW(), 'group', 10, 'meter2', 'meter2_id'),
(NOW(), 'group', 11, 'meter2', 'meter2_energy'),
(NOW(), 'group', 12, 'meter2', 'meter2_volume'),
(NOW(), 'group', 13, 'meter2', 'meter2_power'),
(NOW(), 'group', 14, 'meter2', 'meter2_flow'),
(NOW(), 'group', 15, 'meter2', 'meter2_flow_temp'),
(NOW(), 'group', 16, 'meter2', 'meter2_return_temp'),
(NOW(), 'group', 17, 'meter2', 'meter2_diff_temp'),
(NOW(), 'group', 18, 'meter2', 'meter2_fabrication'),
(NOW(), 'group', 10, 'meter3', 'meter3_id'),
(NOW(), 'group', 11, 'meter3', 'meter3_energy'),
(NOW(), 'group', 12, 'meter3', 'meter3_volume'),
(NOW(), 'group', 13, 'meter3', 'meter3_power'),
(NOW(), 'group', 14, 'meter3', 'meter3_flow'),
(NOW(), 'group', 15, 'meter3', 'meter3_flow_temp'),
(NOW(), 'group', 16, 'meter3', 'meter3_return_temp'),
(NOW(), 'group', 17, 'meter3', 'meter3_diff_temp'),
(NOW(), 'group', 18, 'meter3', 'meter3_fabrication'),
(NOW(), 'group', 10, 'meter4', 'meter4_id'),
(NOW(), 'group', 11, 'meter4', 'meter4_energy'),
(NOW(), 'group', 12, 'meter4', 'meter4_volume'),
(NOW(), 'group', 13, 'meter4', 'meter4_power'),
(NOW(), 'group', 14, 'meter4', 'meter4_flow'),
(NOW(), 'group', 15, 'meter4', 'meter4_flow_temp'),
(NOW(), 'group', 16, 'meter4', 'meter4_return_temp'),
(NOW(), 'group', 17, 'meter4', 'meter4_diff_temp'),
(NOW(), 'group', 18, 'meter4', 'meter4_fabrication');

CREATE TABLE IF NOT EXISTS `iw_par_anybus_mbus_param` (
  `row_date` datetime NOT NULL DEFAULT '2002-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_anybus_mbus_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'meter1_id', '0_3_10', 'Måler 1-M-Bus meter', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_13_U32_W_-_-_-_-', ''),
(NOW(), 'meter1_energy', '0_3_40', 'Måler 1-Energy', '', 'Integral values', 'integer', '', '-1', 'r', 'kWh', '%.0f', '', '', '', '', '', '', '', '3_43_U16_N_-_-_-_-', ''),
(NOW(), 'meter1_volume', '0_3_50', 'Måler 1-Volume', '', 'Analog values', 'float', '', '-1', 'r', 'm3', '%.1f', '', '', '1', '0', '1000', '0', '10', '3_53_U16_N_-_-_-_-', ''),
(NOW(), 'meter1_power', '0_3_60', 'Måler 1-Power', '', 'Analog values', 'float', '', '-1', 'r', 'kW', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_63_U16_N_-_-_-_-', ''),
(NOW(), 'meter1_flow', '0_3_70', 'Måler 1-Volume flow', '', 'Analog values', 'float', '', '-1', 'r', 'm3/h', '%.1f', '', '', '1', '0', '1000', '0', '1', '3_73_U16_N_-_-_-_-', ''),
(NOW(), 'meter1_flow_temp', '0_3_80', 'Måler 1-Flow temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '', '', '', '', '', '3_83_F_N_-_-_-_-', ''),
(NOW(), 'meter1_return_temp', '0_3_90', 'Måler 1-Return temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '', '', '', '', '', '3_93_F_N_-_-_-_-', ''),
(NOW(), 'meter1_diff_temp', '0_3_100', 'Måler 1-Temperature difference', '', 'Analog values', 'float', '', '-1', 'r', '&deg;K', '%.1f', '', '', '', '', '', '', '', '3_103_F_N_-_-_-_-', ''),
(NOW(), 'meter1_fabrication', '0_3_130', 'Måler 1-Fabrication No', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_133_U32_W_-_-_-_-', ''),
(NOW(), 'meter2_id', '0_3_270', 'Måler 2-M-Bus meter', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_273_U32_W_-_-_-_-', ''),
(NOW(), 'meter2_energy', '0_3_290', 'Måler 2-Energy', '', 'Integral values', 'integer', '', '-1', 'r', 'kWh', '%.0f', '', '', '', '', '', '', '', '3_293_U16_N_-_-_-_-', ''),
(NOW(), 'meter2_volume', '0_3_300', 'Måler 2-Volume', '', 'Analog values', 'float', '', '-1', 'r', 'm3', '%.1f', '', '', '1', '0', '1000', '0', '10', '3_303_U16_N_-_-_-_-', ''),
(NOW(), 'meter2_power', '0_3_350', 'Måler 2-Power', '', 'Analog values', 'float', '', '-1', 'r', 'kW', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_353_U16_N_-_-_-_-', ''),
(NOW(), 'meter2_flow', '0_3_370', 'Måler 2-Volume flow', '', 'Analog values', 'float', '', '-1', 'r', 'm3/h', '%.1f', '', '', '1', '0', '1000', '0', '1', '3_373_U16_N_-_-_-_-', ''),
(NOW(), 'meter2_flow_temp', '0_3_320', 'Måler 2-Flow temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '', '', '', '', '', '3_323_F_N_-_-_-_-', ''),
(NOW(), 'meter2_return_temp', '0_3_330', 'Måler 2-Return temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '', '', '', '', '', '3_333_F_N_-_-_-_-', ''),
(NOW(), 'meter2_diff_temp', '0_3_340', 'Måler 2-Temperature difference', '', 'Analog values', 'float', '', '-1', 'r', '&deg;K', '%.1f', '', '', '', '', '', '', '', '3_343_F_N_-_-_-_-', ''),
(NOW(), 'meter2_fabrication', '0_3_280', 'Måler 2-Fabrication No', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_283_U32_W_-_-_-_-', ''),
(NOW(), 'meter3_id', '0_3_530', 'Måler 3-M-Bus meter', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_533_U32_W_-_-_-_-', ''),
(NOW(), 'meter3_energy', '0_3_550', 'Måler 3-Energy', '', 'Integral values', 'integer', '', '-1', 'r', 'kWh', '%.0f', '', '', '', '', '', '', '', '3_553_U16_N_-_-_-_-', ''),
(NOW(), 'meter3_volume', '0_3_560', 'Måler 3-Volume', '', 'Analog values', 'float', '', '-1', 'r', 'm3', '%.1f', '', '', '1', '0', '1000', '0', '10', '3_563_U16_N_-_-_-_-', ''),
(NOW(), 'meter3_power', '0_3_610', 'Måler 3-Power', '', 'Analog values', 'float', '', '-1', 'r', 'kW', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_613_U16_N_-_-_-_-', ''),
(NOW(), 'meter3_flow', '0_3_630', 'Måler 3-Volume flow', '', 'Analog values', 'float', '', '-1', 'r', 'm3/h', '%.1f', '', '', '1', '0', '1000', '0', '1', '3_633_U16_N_-_-_-_-', ''),
(NOW(), 'meter3_flow_temp', '0_3_580', 'Måler 3-Flow temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '', '', '', '', '', '3_583_F_N_-_-_-_-', ''),
(NOW(), 'meter3_return_temp', '0_3_590', 'Måler 3-Return temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '', '', '', '', '', '3_593_F_N_-_-_-_-', ''),
(NOW(), 'meter3_diff_temp', '0_3_600', 'Måler 3-Temperature difference', '', 'Analog values', 'float', '', '-1', 'r', '&deg;K', '%.1f', '', '', '', '', '', '', '', '3_603_F_N_-_-_-_-', ''),
(NOW(), 'meter3_fabrication', '0_3_540', 'Måler 3-Fabrication No', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_543_U32_W_-_-_-_-', ''),
(NOW(), 'meter4_id', '0_3_790', 'Måler 4-M-Bus meter', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_793_U32_W_-_-_-_-', ''),
(NOW(), 'meter4_energy', '0_3_810', 'Måler 4-Energy', '', 'Integral values', 'integer', '', '-1', 'r', 'kWh', '%.0f', '', '', '', '', '', '', '', '3_813_U16_N_-_-_-_-', ''),
(NOW(), 'meter4_volume', '0_3_820', 'Måler 4-Volume', '', 'Analog values', 'float', '', '-1', 'r', 'm3', '%.1f', '', '', '1', '0', '1000', '0', '10', '3_823_U16_N_-_-_-_-', ''),
(NOW(), 'meter4_power', '0_3_870', 'Måler 4-Power', '', 'Analog values', 'float', '', '-1', 'r', 'kW', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_873_U16_N_-_-_-_-', ''),
(NOW(), 'meter4_flow', '0_3_890', 'Måler 4-Volume flow', '', 'Analog values', 'float', '', '-1', 'r', 'm3/h', '%.1f', '', '', '1', '0', '1000', '0', '1', '3_893_U16_N_-_-_-_-', ''),
(NOW(), 'meter4_flow_temp', '0_3_840', 'Måler 4-Flow temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '', '', '', '', '', '3_843_F_N_-_-_-_-', ''),
(NOW(), 'meter4_return_temp', '0_3_850', 'Måler 4-Return temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '', '', '', '', '', '3_853_F_N_-_-_-_-', ''),
(NOW(), 'meter4_diff_temp', '0_3_860', 'Måler 4-Temperature difference', '', 'Analog values', 'float', '', '-1', 'r', '&deg;K', '%.1f', '', '', '', '', '', '', '', '3_863_F_N_-_-_-_-', ''),
(NOW(), 'meter4_fabrication', '0_3_800', 'Måler 4-Fabrication No', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_803_U32_W_-_-_-_-', '');

CREATE TABLE IF NOT EXISTS `iw_set_anybus_mbus` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_anybus_mbus` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'meter1_id', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter1_energy', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter1_volume', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter1_power', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter1_flow', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter1_flow_temp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter1_return_temp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter1_diff_temp', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter1_fabrication', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter2_id', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter2_energy', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter2_volume', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter2_power', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter2_flow', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter2_flow_temp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter2_return_temp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter2_diff_temp', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter2_fabrication', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter3_id', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter3_energy', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter3_volume', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter3_power', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter3_flow', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter3_flow_temp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter3_return_temp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter3_diff_temp', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter3_fabrication', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter4_id', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter4_energy', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter4_volume', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter4_power', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter4_flow', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'meter4_flow_temp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter4_return_temp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter4_diff_temp', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'meter4_fabrication', '0', '0', 'slow', 'change', '', '', '', 0);



-- Changelog
--
-- v1 Orginal
--
--