REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'ID01', 'navn', 'ca_powersplit', 'CAREL485', '0_1', 'POWERSPLIT', 'CA_POW', ''),
(NOW(), '1', '0', 'ID02', 'navn', 'ca_powersplit', 'CAREL485', '0_2', 'POWERSPLIT', 'CA_POW', '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'com_port', 'CAREL485', '3', '', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'CA_POW', 'ca_powersplit_param', 'ca_powersplit_groups');

CREATE TABLE IF NOT EXISTS `iw_par_ca_powersplit_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_ca_powersplit_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'man', 'Main Parameters'),
(NOW(), 'group_alias', 2, 'defrost', 'Defrost Parameters'),
(NOW(), 'group', 1, 'man', 'man_0_A_1'),
(NOW(), 'group', 2, 'man', 'man_0_A_2'),
(NOW(), 'group', 3, 'man', 'man_0_A_3'),
(NOW(), 'group', 4, 'man', 'man_0_A_4'),
(NOW(), 'group', 5, 'man', 'man_0_A_5'),
(NOW(), 'group', 6, 'man', 'man_0_A_6'),
(NOW(), 'group', 7, 'man', 'man_0_A_7'),
(NOW(), 'group', 8, 'man', 'man_0_A_8'),
(NOW(), 'group', 9, 'man', 'man_0_A_9'),
(NOW(), 'group', 10, 'man', 'man_0_A_10'),
(NOW(), 'group', 11, 'man', 'man_0_A_11'),
(NOW(), 'group', 12, 'man', 'man_0_A_12'),
(NOW(), 'group', 13, 'man', 'man_0_A_13'),
(NOW(), 'group', 14, 'man', 'man_0_A_14'),
(NOW(), 'group', 15, 'man', 'man_0_A_15'),
(NOW(), 'group', 16, 'man', 'man_0_A_26'),
(NOW(), 'group', 17, 'man', 'man_0_A_27'),
(NOW(), 'group', 18, 'man', 'man_0_A_28'),
(NOW(), 'group', 19, 'man', 'man_0_A_29'),
(NOW(), 'group', 20, 'man', 'man_0_A_30'),
(NOW(), 'group', 21, 'man', 'man_0_D_1'),
(NOW(), 'group', 22, 'man', 'man_0_D_2'),
(NOW(), 'group', 23, 'man', 'man_0_D_3'),
(NOW(), 'group', 24, 'man', 'man_0_D_4'),
(NOW(), 'group', 25, 'man', 'man_0_D_5'),
(NOW(), 'group', 26, 'man', 'man_0_D_6'),
(NOW(), 'group', 27, 'man', 'man_0_D_7'),
(NOW(), 'group', 28, 'man', 'man_0_D_8'),
(NOW(), 'group', 29, 'man', 'man_0_D_9'),
(NOW(), 'group', 30, 'man', 'man_0_D_10'),
(NOW(), 'group', 31, 'man', 'man_0_D_11'),
(NOW(), 'group', 32, 'man', 'man_0_D_12'),
(NOW(), 'group', 33, 'man', 'man_0_D_13'),
(NOW(), 'group', 34, 'man', 'man_0_D_14'),
(NOW(), 'group', 35, 'man', 'man_0_D_15'),
(NOW(), 'group', 36, 'man', 'man_0_D_16'),
(NOW(), 'group', 37, 'man', 'man_0_D_17'),
(NOW(), 'group', 38, 'man', 'man_0_D_18'),
(NOW(), 'group', 39, 'man', 'man_0_D_29'),
(NOW(), 'group', 40, 'man', 'man_0_D_30'),
(NOW(), 'group', 41, 'man', 'man_0_D_31'),
(NOW(), 'group', 42, 'man', 'man_0_D_32'),
(NOW(), 'group', 43, 'man', 'man_0_D_33'),
(NOW(), 'group', 44, 'man', 'man_0_D_34'),
(NOW(), 'group', 45, 'man', 'man_0_D_35'),
(NOW(), 'group', 46, 'man', 'man_0_D_36'),
(NOW(), 'group', 47, 'man', 'man_0_D_37'),
(NOW(), 'group', 48, 'man', 'man_0_D_38'),
(NOW(), 'group', 49, 'man', 'man_0_D_39'),
(NOW(), 'group', 50, 'man', 'man_0_D_40'),
(NOW(), 'group', 51, 'man', 'man_0_D_41'),
(NOW(), 'group', 52, 'man', 'man_0_D_42'),
(NOW(), 'group', 53, 'man', 'man_0_D_43'),
(NOW(), 'group', 54, 'man', 'man_0_D_44'),
(NOW(), 'group', 55, 'man', 'man_0_D_45'),
(NOW(), 'group', 56, 'man', 'man_0_D_46'),
(NOW(), 'group', 57, 'man', 'man_0_D_47'),
(NOW(), 'group', 58, 'man', 'man_0_D_48'),
(NOW(), 'group', 59, 'man', 'man_0_D_49'),
(NOW(), 'group', 60, 'man', 'man_0_D_50'),
(NOW(), 'group', 61, 'man', 'man_0_D_51'),
(NOW(), 'group', 62, 'man', 'man_0_D_52'),
(NOW(), 'group', 63, 'man', 'man_0_D_53'),
(NOW(), 'group', 64, 'man', 'man_0_D_54'),
(NOW(), 'group', 65, 'man', 'man_0_D_55'),
(NOW(), 'group', 66, 'man', 'man_0_D_56'),
(NOW(), 'group', 67, 'man', 'man_0_D_57'),
(NOW(), 'group', 68, 'man', 'man_0_I_1'),
(NOW(), 'group', 69, 'man', 'man_0_I_2'),
(NOW(), 'group', 70, 'man', 'man_0_I_3'),
(NOW(), 'group', 71, 'man', 'man_0_I_4'),
(NOW(), 'group', 72, 'man', 'man_0_I_5'),
(NOW(), 'group', 73, 'man', 'man_0_I_6'),
(NOW(), 'group', 74, 'man', 'man_0_I_7'),
(NOW(), 'group', 75, 'man', 'man_0_I_8'),
(NOW(), 'group', 76, 'man', 'man_0_I_9'),
(NOW(), 'group', 77, 'man', 'man_0_I_10'),
(NOW(), 'group', 78, 'man', 'man_0_I_11'),
(NOW(), 'group', 79, 'man', 'man_0_I_12'),
(NOW(), 'group', 80, 'man', 'man_0_I_13'),
(NOW(), 'group', 81, 'man', 'man_0_I_14'),
(NOW(), 'group', 82, 'man', 'man_0_I_15'),
(NOW(), 'group', 83, 'man', 'man_0_I_16'),
(NOW(), 'group', 84, 'man', 'man_0_I_17'),
(NOW(), 'group', 85, 'man', 'man_0_I_18'),
(NOW(), 'group', 86, 'man', 'man_0_I_19'),
(NOW(), 'group', 87, 'man', 'man_0_I_20'),
(NOW(), 'group', 88, 'man', 'man_0_I_21'),
(NOW(), 'group', 89, 'man', 'man_0_I_22'),
(NOW(), 'group', 90, 'man', 'man_0_I_23'),
(NOW(), 'group', 91, 'man', 'man_0_I_24'),
(NOW(), 'group', 92, 'man', 'man_0_I_25'),
(NOW(), 'group', 93, 'man', 'man_0_I_26'),
(NOW(), 'group', 94, 'man', 'man_0_I_27'),
(NOW(), 'group', 95, 'man', 'man_0_I_28'),
(NOW(), 'group', 96, 'man', 'man_0_I_29'),
(NOW(), 'group', 97, 'man', 'man_0_I_30'),
(NOW(), 'group', 98, 'man', 'man_0_I_31'),
(NOW(), 'group', 99, 'man', 'man_0_I_32'),
(NOW(), 'group', 100, 'man', 'man_0_I_33'),
(NOW(), 'group', 101, 'man', 'man_0_I_34'),
(NOW(), 'group', 102, 'man', 'man_0_I_35'),
(NOW(), 'group', 1, 'defrost', 'defrost_0_I_36'),
(NOW(), 'group', 2, 'defrost', 'defrost_0_I_37'),
(NOW(), 'group', 3, 'defrost', 'defrost_0_I_38'),
(NOW(), 'group', 4, 'defrost', 'defrost_0_I_39'),
(NOW(), 'group', 5, 'defrost', 'defrost_0_I_40'),
(NOW(), 'group', 6, 'defrost', 'defrost_0_I_41'),
(NOW(), 'group', 7, 'defrost', 'defrost_0_I_42'),
(NOW(), 'group', 8, 'defrost', 'defrost_0_I_43'),
(NOW(), 'group', 9, 'defrost', 'defrost_0_I_44'),
(NOW(), 'group', 10, 'defrost', 'defrost_0_I_45'),
(NOW(), 'group', 11, 'defrost', 'defrost_0_I_46'),
(NOW(), 'group', 12, 'defrost', 'defrost_0_I_47'),
(NOW(), 'group', 13, 'defrost', 'defrost_0_I_48'),
(NOW(), 'group', 14, 'defrost', 'defrost_0_I_49'),
(NOW(), 'group', 15, 'defrost', 'defrost_0_I_50'),
(NOW(), 'group', 16, 'defrost', 'defrost_0_I_51'),
(NOW(), 'group', 17, 'defrost', 'defrost_0_I_52'),
(NOW(), 'group', 18, 'defrost', 'defrost_0_I_53'),
(NOW(), 'group', 19, 'defrost', 'defrost_0_I_54'),
(NOW(), 'group', 20, 'defrost', 'defrost_0_I_55'),
(NOW(), 'group', 21, 'defrost', 'defrost_0_I_56'),
(NOW(), 'group', 22, 'defrost', 'defrost_0_I_67');

CREATE TABLE IF NOT EXISTS `iw_par_ca_powersplit_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(50) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_ca_powersplit_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'man_0_A_1', '0_A_1', 'Calibration  - Probe 3', '8', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_2', '0_A_2', 'Calibration room probe - Probe 1', 'C', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_3', '0_A_3', 'Calibration defrost probe - Probe 2', 'd', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_4', '0_A_4', 'Alarm and fan differential', 'A0', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_5', '0_A_5', 'High temperature alarm (delta)', 'AH', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_6', '0_A_6', 'Low temperature alarm (delta)', 'AL', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_7', '0_A_7', 'End defrost temperature', 'dt', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_8', '0_A_8', 'Fan ON temperature', 'F1', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_9', '0_A_9', 'Minimum Set allowed to user', 'r1', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_10', '0_A_10', 'Maximum Set allowed to user', 'r2', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_11', '0_A_11', 'Night-time Set Point', 'r4', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_12', '0_A_12', 'Control differential (hysteresis)', 'rd', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_13', '0_A_13', 'Max. temp. measured during <rt>', 'rH', 'Analog values', 'float', '', '-1', 'r', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_14', '0_A_14', 'Min. temp. measured during <rt>', 'rL', 'Analog values', 'float', '', '-1', 'r', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_15', '0_A_15', 'Temperature Set Point', 'St', 'Analog values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_26', '0_A_26', 'Probe 1', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_27', '0_A_27', 'Probe 2', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_28', '0_A_28', 'Probe 3', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_29', '0_A_29', 'Virtual probe', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C/&deg;F', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_A_30', '0_A_30', 'Power supply voltage', '', 'Analog values', 'float', '', '-1', 'r', 'V', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_D_1', '0_D_1', 'Centigrade/Fahrenheit selection', '5', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Centigrade"},"1":{"t":"Fahrenheit"}}}'),
(NOW(), 'man_0_D_2', '0_D_2', 'Scale', '6', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_D_3', '0_D_3', 'Defrost with probe S3', '9', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_D_4', '0_D_4', 'Type of defrost control', 'd2', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Start Only"},"1":{"t":"Start and Stop"}}}'),
(NOW(), 'man_0_D_5', '0_D_5', 'Defrost at power up', 'd4', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"No"},"1":{"t":"Yes"}}}'),
(NOW(), 'man_0_D_6', '0_D_6', 'Display during defrost. ', 'd6', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_D_7', '0_D_7', 'Defrost priority over compr. protection', 'd9', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"No"},"1":{"t":"Yes"}}}'),
(NOW(), 'man_0_D_8', '0_D_8', 'Fan management ', 'F0', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_D_9', '0_D_9', 'Fans OFF with compressor', 'F2', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"No"},"1":{"t":"Yes"}}}'),
(NOW(), 'man_0_D_10', '0_D_10', 'Fans OFF in defrost', 'F3', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"No"},"1":{"t":"Yes"}}}'),
(NOW(), 'man_0_D_11', '0_D_11', 'disable keypad', 'H3', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Enabled"},"1":{"t":"Disabled"}}}'),
(NOW(), 'man_0_D_12', '0_D_12', 'Enable local ON/OFF', 'Lo', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Enabled"},"1":{"t":"Disabled"}}}'),
(NOW(), 'man_0_D_13', '0_D_13', 'Enable network ON/OFF', 'LL', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Enabled"},"1":{"t":"Disabled"}}}'),
(NOW(), 'man_0_D_14', '0_D_14', 'Propagation of DIN 2 on LAN ', 'Ld', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_D_15', '0_D_15', 'Signal enabling Ed (defrost time-out) ', 'r3', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_D_16', '0_D_16', 'Enable min. max. temperature monitoring', 'r5', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"No"},"1":{"t":"Yes"}}}'),
(NOW(), 'man_0_D_17', '0_D_17', 'Night-time control with product probe', 'r6', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Enabled"},"1":{"t":"Disabled"}}}'),
(NOW(), 'man_0_D_18', '0_D_18', 'Reset HACCP alarms HA HF 0=HACCP alarm not present 1=HACCP alarm present', 'to', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_D_29', '0_D_29', 'Digital input 1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Closed"},"1":{"t":"Open"}}}'),
(NOW(), 'man_0_D_30', '0_D_30', 'Digital input 2', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Closed"},"1":{"t":"Open"}}}'),
(NOW(), 'man_0_D_31', '0_D_31', 'Photocell input 1 ', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_D_32', '0_D_32', 'Virtual digital input', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Closed"},"1":{"t":"Open"}}}'),
(NOW(), 'man_0_D_33', '0_D_33', 'Compressor relay status', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Inactive"},"1":{"t":"Active"}}}'),
(NOW(), 'man_0_D_34', '0_D_34', 'Fan relay status', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Inactive"},"1":{"t":"Active"}}}'),
(NOW(), 'man_0_D_35', '0_D_35', 'Defrost relay status', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Inactive"},"1":{"t":"Active"}}}'),
(NOW(), 'man_0_D_36', '0_D_36', 'AUX relay status', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Inactive"},"1":{"t":"Active"}}}'),
(NOW(), 'man_0_D_37', '0_D_37', 'Alarm relay status', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Inactive"},"1":{"t":"Active"}}}'),
(NOW(), 'man_0_D_38', '0_D_38', 'ON-OFF status', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Inactive"},"1":{"t":"Active"}}}'),
(NOW(), 'man_0_D_39', '0_D_39', 'Light relay status ', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_D_40', '0_D_40', 'Defrost request', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"No Request"},"1":{"t":"Defrost Request"}}}'),
(NOW(), 'man_0_D_41', '0_D_41', 'End defrost request', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"No Request"},"1":{"t":"End Defrost Request"}}}'),
(NOW(), 'man_0_D_42', '0_D_42', 'Continuous cycle starting request', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"No Request"},"1":{"t":"CC Request"}}}'),
(NOW(), 'man_0_D_43', '0_D_43', 'Continuous cycle stop request', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"No Request"},"1":{"t":"End CC Request"}}}'),
(NOW(), 'man_0_D_44', '0_D_44', 'Room probe 1 error E1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_45', '0_D_45', 'Defrost probe 2 error E2', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_46', '0_D_46', 'Product probe 3 error E3', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_47', '0_D_47', 'Immediate external alarm IA', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_48', '0_D_48', 'Delayed external alarm dA', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_49', '0_D_49', 'E2Prom alarm EA', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_50', '0_D_50', 'Regulation probe alarm rE', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_51', '0_D_51', 'Duty Setting from external contact Id', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_52', '0_D_52', 'High temperature alarm HI', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_53', '0_D_53', 'Low temperature alarm LO', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_54', '0_D_54', 'HACCP alarm HA', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_55', '0_D_55', 'HACCP alarm HF', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_56', '0_D_56', 'Defrost timeout alarm Ed', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_D_57', '0_D_57', 'Alarm in progress', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"ALARM"}}}'),
(NOW(), 'man_0_I_1', '0_I_1', 'Overall measurement stability', '2', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_2', '0_I_2', 'Virtual probe', '4', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_3', '0_I_3', 'Display probe', '7', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_4', '0_I_4', 'Terminal probe', 't', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_5', '0_I_5', 'Presence of defrost probe/product probe', 'A', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_6', '0_I_6', 'Configuration digital input 1', 'A4', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_7', '0_I_7', 'Configuration digital input 2', 'A5', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_8', '0_I_8', 'Delayed alarm input delay', 'A7', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_9', '0_I_9', 'Temperature alarm delay', 'Ad', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_10', '0_I_10', 'Compressor and fan start delay instrument ON', 'c0', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_11', '0_I_11', 'Minimum time between 2 compressor starts', 'c1', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_12', '0_I_12', 'Minimum compressor OFF time', 'c2', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_13', '0_I_13', 'Minimum compressor ON time', 'c3', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_14', '0_I_14', 'Safety function Duty Setting', 'c4', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_15', '0_I_15', 'Alarm bypass time after continuous cycle', 'c6', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_16', '0_I_16', 'Continuous cycle', 'cc', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_17', '0_I_17', 'Type of defrost', 'd0', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_18', '0_I_18', 'Defrost delay at ON or from digital input', 'd5', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_19', '0_I_19', 'Alarm bypass time after defrost or door open', 'd8', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_20', '0_I_20', 'Dripping time after defrost', 'dd', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_21', '0_I_21', 'Interval between defrosts', 'dI', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_22', '0_I_22', 'Max/effective defrost duration', 'dP', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_23', '0_I_23', 'Fans OFF in post-dripping', 'Fd', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_24', '0_I_24', 'AUX 1 function relay no. 4', 'H1', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_25', '0_I_25', 'AUX 2 function relay no. 5', 'H2', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_26', '0_I_26', 'Photocell sensitivity', 'L1', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_27', '0_I_27', 'Light on time from sensor', 'Lt', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_28', '0_I_28', 'Effective temperature measurement interval', 'rt', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_29', '0_I_29', 'Weekday HA event', 'tu', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_30', '0_I_30', 'Hours HA event', 'th', 'Integral values', 'integer', '', '-1', 'r', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_31', '0_I_31', 'Minutes HA event', 't', 'Integral values', 'integer', '', '-1', 'r', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_32', '0_I_32', 'Weekday HF event', 'tu', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_33', '0_I_33', 'Hours HF event', 'th', 'Integral values', 'integer', '', '-1', 'r', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_34', '0_I_34', 'Minutes HF event', 't', 'Integral values', 'integer', '', '-1', 'r', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'man_0_I_35', '0_I_35', 'HACCP alarm delay', 'tr', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_36', '0_I_36', 'Defrost event No.1st day', 'T1', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_37', '0_I_37', 'Defrost event No.1st hours', 'T1', 'Integral values', 'integer', '', '-1', 'rw', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_38', '0_I_38', 'Defrost event No.1st minutes', 'T1', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_39', '0_I_39', 'Defrost event No.2st day', 'T2', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_40', '0_I_40', 'Defrost event No.2st hours', 'T2', 'Integral values', 'integer', '', '-1', 'rw', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_41', '0_I_41', 'Defrost event No.2st minutes', 'T2', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_42', '0_I_42', 'Defrost event No.3st day', 'T3', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_43', '0_I_43', 'Defrost event No.3st hours', 'T3', 'Integral values', 'integer', '', '-1', 'rw', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_44', '0_I_44', 'Defrost event No.3st minutes', 'T3', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_45', '0_I_45', 'Defrost event No.4st day', 'T4', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_46', '0_I_46', 'Defrost event No.4st hours', 'T4', 'Integral values', 'integer', '', '-1', 'rw', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_47', '0_I_47', 'Defrost event No.4st minutes', 'T4', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_48', '0_I_48', 'Defrost event No.5st day', 'T5', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_49', '0_I_49', 'Defrost event No.5st hours', 'T5', 'Integral values', 'integer', '', '-1', 'rw', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_50', '0_I_50', 'Defrost event No.5st minutes', 'T5', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_51', '0_I_51', 'Defrost event No.6st day', 'T6', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_52', '0_I_52', 'Defrost event No.6st hours', 'T6', 'Integral values', 'integer', '', '-1', 'rw', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_53', '0_I_53', 'Defrost event No.6st minutes', 'T6', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_54', '0_I_54', 'Current minutes', 'tM', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_55', '0_I_55', 'Current hours', 'th', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_56', '0_I_56', 'Current weekday', 'td', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'defrost_0_I_67', '0_I_67', 'Logic state regulation alghorithm', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '');

CREATE TABLE IF NOT EXISTS `iw_set_ca_powersplit` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_ca_powersplit` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'man_0_A_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_11', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_12', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_13', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'man_0_A_14', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'man_0_A_15', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_A_26', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'man_0_A_27', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'man_0_A_28', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'man_0_A_29', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'man_0_A_30', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'man_0_D_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_11', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_12', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_13', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_14', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_15', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_16', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_17', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_18', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_29', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_30', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_31', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_32', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_33', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_34', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_35', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_36', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_37', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_38', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_39', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_40', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_41', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_42', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_43', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_D_44', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_45', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_46', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_47', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_48', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_49', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_50', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_51', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_52', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_53', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_54', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_55', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_56', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_D_57', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'man_0_I_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_11', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_12', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_13', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_14', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_15', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_16', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_17', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_18', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_19', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_20', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_21', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_22', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_23', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_24', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_25', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_26', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_27', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_28', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_29', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_30', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_31', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_32', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_33', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_34', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'man_0_I_35', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_36', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_37', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_38', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_39', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_40', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_41', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_42', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_43', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_44', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_45', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_46', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_47', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_48', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_49', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_50', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_51', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_52', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_53', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_54', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_55', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_56', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_0_I_67', '1', '0', 'slow', 'change', '', '', '', 0);
