REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'ID01', 'Pos 01', 'ca_rivacold', 'CAREL485', '0_1', 'Rivacold', 'rivacold', 0, ''),
(NOW(), '1', '0', 'ID02', 'Pos 02', 'ca_rivacold', 'CAREL485', '0_2', 'Rivacold', 'rivacold', 0, ''),
(NOW(), '1', '0', 'ID03', 'Pos 03', 'ca_rivacold', 'CAREL485', '0_3', 'Rivacold', 'rivacold', 0, ''),
(NOW(), '1', '0', 'ID04', 'Pos 04', 'ca_rivacold', 'CAREL485', '0_4', 'Rivacold', 'rivacold', 0, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'com_port', 'CAREL485', '1', '', '', ''),
(NOW(), 'baud_rate', 'CAREL485', '19200', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'CAREL485', '60', 'min.', '', ''),
(NOW(), 'gateway_type', 'CAREL485', '485N', '', '', ''),
(NOW(), 'idle_event_rate', 'CAREL485', '250', 'msec', '', ''),
(NOW(), 'max_error_count', 'CAREL485', '4', '', '', ''),
(NOW(), 'max_group_count', 'CAREL485', '1', '', '', ''),
(NOW(), 'max_outstanding_packets', 'CAREL485', '-1', '', '', ''),
(NOW(), 'max_param_block_time', 'CAREL485', '2', 'hours', '', ''),
(NOW(), 'packet_timeout', 'CAREL485', '0', 'sec', '', ''),
(NOW(), 'speed_index_block', 'CAREL485', '10', '', '', ''),
(NOW(), 'speed_index_norm', 'CAREL485', '1', '', '', ''),
(NOW(), 'speed_index_offline', 'CAREL485', '10', '', '', ''),
(NOW(), 'speed_index_slow', 'CAREL485', '1', '', '', ''),
(NOW(), 'sql_queue_poll_time', 'CAREL485', '1000', 'msec', '', ''),
(NOW(), 'unblock_timer', 'CAREL485', '2 min', 'Time string', '', ''),
(NOW(), 'show_queue_info', 'CAREL485', '0', '', '', ''),
(NOW(), 'startup_delay', 'CAREL485', '15', 'Sec.', '', ''),
(NOW(), 'alarm_handler', 'CAREL485', '', '', '', ''),
(NOW(), 'count_com_ports', 'CAREL485', '1', '', '', ''),
(NOW(), 'reopen_timer', 'CAREL485', 'never', '', 'never,x min,x hour', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_carel485.exe', 'CAREL485', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'rivacold', 'ca_rivacold_param', 'ca_rivacold_groups');

CREATE TABLE IF NOT EXISTS `iw_par_ca_rivacold_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_ca_rivacold_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'A', 'Analog'),
(NOW(), 'group_alias', 2, 'I', 'Integer'),
(NOW(), 'group_alias', 3, 'D', 'Digital'),
(NOW(), 'group', 10, 'A', 'A_0_A_1'),
(NOW(), 'group', 20, 'A', 'A_0_A_2'),
(NOW(), 'group', 30, 'A', 'A_0_A_3'),
(NOW(), 'group', 40, 'A', 'A_0_A_4'),
(NOW(), 'group', 50, 'A', 'A_0_A_5'),
(NOW(), 'group', 60, 'A', 'A_0_A_6'),
(NOW(), 'group', 70, 'A', 'A_0_A_7'),
(NOW(), 'group', 80, 'A', 'A_0_A_8'),
(NOW(), 'group', 90, 'A', 'A_0_A_9'),
(NOW(), 'group', 100, 'A', 'A_0_A_10'),
(NOW(), 'group', 110, 'A', 'A_0_A_11'),
(NOW(), 'group', 120, 'A', 'A_0_A_12'),
(NOW(), 'group', 130, 'A', 'A_0_A_13'),
(NOW(), 'group', 140, 'A', 'A_0_A_14'),
(NOW(), 'group', 150, 'A', 'A_0_A_15'),
(NOW(), 'group', 160, 'A', 'A_0_A_16'),
(NOW(), 'group', 170, 'A', 'A_0_A_17'),
(NOW(), 'group', 180, 'A', 'A_0_A_18'),
(NOW(), 'group', 190, 'A', 'A_0_A_19'),
(NOW(), 'group', 200, 'A', 'A_0_A_20'),
(NOW(), 'group', 210, 'A', 'A_0_A_52'),
(NOW(), 'group', 220, 'A', 'A_0_A_53'),
(NOW(), 'group', 230, 'A', 'A_0_A_54'),
(NOW(), 'group', 240, 'A', 'A_0_A_55'),
(NOW(), 'group', 250, 'A', 'A_0_A_56'),
(NOW(), 'group', 260, 'A', 'A_0_A_57'),
(NOW(), 'group', 270, 'A', 'A_0_A_58'),
(NOW(), 'group', 280, 'A', 'A_0_A_59'),
(NOW(), 'group', 290, 'A', 'A_0_A_60'),
(NOW(), 'group', 300, 'A', 'A_0_A_61'),
(NOW(), 'group', 310, 'I', 'I_0_I_1'),
(NOW(), 'group', 320, 'I', 'I_0_I_6'),
(NOW(), 'group', 330, 'I', 'I_0_I_7'),
(NOW(), 'group', 340, 'I', 'I_0_I_8'),
(NOW(), 'group', 350, 'I', 'I_0_I_9'),
(NOW(), 'group', 360, 'I', 'I_0_I_10'),
(NOW(), 'group', 370, 'I', 'I_0_I_11'),
(NOW(), 'group', 380, 'I', 'I_0_I_12'),
(NOW(), 'group', 390, 'I', 'I_0_I_13'),
(NOW(), 'group', 400, 'I', 'I_0_I_14'),
(NOW(), 'group', 410, 'I', 'I_0_I_15'),
(NOW(), 'group', 420, 'I', 'I_0_I_16'),
(NOW(), 'group', 430, 'I', 'I_0_I_17'),
(NOW(), 'group', 440, 'I', 'I_0_I_18'),
(NOW(), 'group', 450, 'I', 'I_0_I_19'),
(NOW(), 'group', 460, 'I', 'I_0_I_20'),
(NOW(), 'group', 470, 'I', 'I_0_I_21'),
(NOW(), 'group', 480, 'I', 'I_0_I_22'),
(NOW(), 'group', 490, 'I', 'I_0_I_23'),
(NOW(), 'group', 500, 'I', 'I_0_I_24'),
(NOW(), 'group', 510, 'I', 'I_0_I_25'),
(NOW(), 'group', 520, 'I', 'I_0_I_26'),
(NOW(), 'group', 530, 'I', 'I_0_I_27'),
(NOW(), 'group', 540, 'I', 'I_0_I_28'),
(NOW(), 'group', 550, 'I', 'I_0_I_29'),
(NOW(), 'group', 560, 'I', 'I_0_I_30'),
(NOW(), 'group', 570, 'I', 'I_0_I_31'),
(NOW(), 'group', 580, 'I', 'I_0_I_32'),
(NOW(), 'group', 590, 'I', 'I_0_I_33'),
(NOW(), 'group', 600, 'I', 'I_0_I_34'),
(NOW(), 'group', 610, 'I', 'I_0_I_35'),
(NOW(), 'group', 620, 'I', 'I_0_I_36'),
(NOW(), 'group', 630, 'I', 'I_0_I_37'),
(NOW(), 'group', 640, 'I', 'I_0_I_38'),
(NOW(), 'group', 650, 'I', 'I_0_I_39'),
(NOW(), 'group', 660, 'I', 'I_0_I_40'),
(NOW(), 'group', 670, 'I', 'I_0_I_41'),
(NOW(), 'group', 680, 'I', 'I_0_I_42'),
(NOW(), 'group', 690, 'I', 'I_0_I_43'),
(NOW(), 'group', 700, 'I', 'I_0_I_44'),
(NOW(), 'group', 710, 'I', 'I_0_I_45'),
(NOW(), 'group', 720, 'I', 'I_0_I_46'),
(NOW(), 'group', 730, 'I', 'I_0_I_47'),
(NOW(), 'group', 740, 'I', 'I_0_I_48'),
(NOW(), 'group', 750, 'I', 'I_0_I_49'),
(NOW(), 'group', 760, 'I', 'I_0_I_50'),
(NOW(), 'group', 770, 'I', 'I_0_I_52'),
(NOW(), 'group', 780, 'I', 'I_0_I_53'),
(NOW(), 'group', 790, 'I', 'I_0_I_54'),
(NOW(), 'group', 800, 'I', 'I_0_I_55'),
(NOW(), 'group', 810, 'I', 'I_0_I_56'),
(NOW(), 'group', 820, 'I', 'I_0_I_57'),
(NOW(), 'group', 830, 'I', 'I_0_I_58'),
(NOW(), 'group', 840, 'I', 'I_0_I_59'),
(NOW(), 'group', 850, 'I', 'I_0_I_60'),
(NOW(), 'group', 860, 'I', 'I_0_I_61'),
(NOW(), 'group', 870, 'I', 'I_0_I_62'),
(NOW(), 'group', 880, 'I', 'I_0_I_63'),
(NOW(), 'group', 890, 'I', 'I_0_I_64'),
(NOW(), 'group', 900, 'I', 'I_0_I_65'),
(NOW(), 'group', 910, 'I', 'I_0_I_66'),
(NOW(), 'group', 920, 'I', 'I_0_I_97'),
(NOW(), 'group', 930, 'I', 'I_0_I_98'),
(NOW(), 'group', 940, 'I', 'I_0_I_99'),
(NOW(), 'group', 950, 'I', 'I_0_I_100'),
(NOW(), 'group', 960, 'I', 'I_0_I_101'),
(NOW(), 'group', 970, 'D', 'D_0_D_1'),
(NOW(), 'group', 980, 'D', 'D_0_D_2'),
(NOW(), 'group', 990, 'D', 'D_0_D_3'),
(NOW(), 'group', 1000, 'D', 'D_0_D_4'),
(NOW(), 'group', 1010, 'D', 'D_0_D_5'),
(NOW(), 'group', 1020, 'D', 'D_0_D_6'),
(NOW(), 'group', 1030, 'D', 'D_0_D_7'),
(NOW(), 'group', 1040, 'D', 'D_0_D_8'),
(NOW(), 'group', 1050, 'D', 'D_0_D_9'),
(NOW(), 'group', 1060, 'D', 'D_0_D_10'),
(NOW(), 'group', 1070, 'D', 'D_0_D_11'),
(NOW(), 'group', 1080, 'D', 'D_0_D_12'),
(NOW(), 'group', 1090, 'D', 'D_0_D_58'),
(NOW(), 'group', 1100, 'D', 'D_0_D_59'),
(NOW(), 'group', 1110, 'D', 'D_0_D_60'),
(NOW(), 'group', 1120, 'D', 'D_0_D_61'),
(NOW(), 'group', 1130, 'D', 'D_0_D_62'),
(NOW(), 'group', 1140, 'D', 'D_0_D_63'),
(NOW(), 'group', 1150, 'D', 'D_0_D_64'),
(NOW(), 'group', 1160, 'D', 'D_0_D_65'),
(NOW(), 'group', 1170, 'D', 'D_0_D_66'),
(NOW(), 'group', 1180, 'D', 'D_0_D_67'),
(NOW(), 'group', 1190, 'D', 'D_0_D_88'),
(NOW(), 'group', 1200, 'D', 'D_0_D_90'),
(NOW(), 'group', 1210, 'D', 'D_0_D_91'),
(NOW(), 'group', 1220, 'D', 'D_0_D_92'),
(NOW(), 'group', 1230, 'D', 'D_0_D_93'),
(NOW(), 'group', 1240, 'D', 'D_0_D_94'),
(NOW(), 'group', 1250, 'D', 'D_0_D_95'),
(NOW(), 'group', 1260, 'D', 'D_0_D_100'),
(NOW(), 'group', 1270, 'D', 'D_0_D_0'),
(NOW(), 'group', 1280, 'D', 'D_0_D_42'),
(NOW(), 'group', 1290, 'D', 'D_0_D_43'),
(NOW(), 'group', 1300, 'D', 'D_0_D_44'),
(NOW(), 'group', 1310, 'D', 'D_0_D_46'),
(NOW(), 'group', 1320, 'D', 'D_0_D_47'),
(NOW(), 'group', 1330, 'D', 'D_0_D_48'),
(NOW(), 'group', 1340, 'D', 'D_0_D_49'),
(NOW(), 'group', 1350, 'D', 'D_0_D_50'),
(NOW(), 'group', 1360, 'D', 'D_0_D_51'),
(NOW(), 'group', 1370, 'D', 'D_0_D_52'),
(NOW(), 'group', 1380, 'D', 'D_0_D_53'),
(NOW(), 'group', 1390, 'D', 'D_0_D_54'),
(NOW(), 'group', 1400, 'D', 'D_0_D_55'),
(NOW(), 'group', 1410, 'D', 'D_0_D_56'),
(NOW(), 'group', 1420, 'D', 'D_0_D_68'),
(NOW(), 'group', 1430, 'D', 'D_0_D_69'),
(NOW(), 'group', 1440, 'D', 'D_0_D_70'),
(NOW(), 'group', 1450, 'D', 'D_0_D_71'),
(NOW(), 'group', 1460, 'D', 'D_0_D_72'),
(NOW(), 'group', 1470, 'D', 'D_0_D_73'),
(NOW(), 'group', 1480, 'D', 'D_0_D_74'),
(NOW(), 'group', 1490, 'D', 'D_0_D_75'),
(NOW(), 'group', 1500, 'D', 'D_0_D_76'),
(NOW(), 'group', 1510, 'D', 'D_0_D_77'),
(NOW(), 'group', 1520, 'D', 'D_0_D_78'),
(NOW(), 'group', 1530, 'D', 'D_0_D_79'),
(NOW(), 'group', 1540, 'D', 'D_0_D_80'),
(NOW(), 'group', 1550, 'D', 'D_0_D_81'),
(NOW(), 'group', 1560, 'D', 'D_0_D_82'),
(NOW(), 'group', 1570, 'D', 'D_0_D_83'),
(NOW(), 'group', 1580, 'D', 'D_0_D_84'),
(NOW(), 'group', 1590, 'D', 'D_0_D_85'),
(NOW(), 'group', 1600, 'D', 'D_0_D_86'),
(NOW(), 'group', 1610, 'D', 'D_0_D_87'),
(NOW(), 'group', 1620, 'D', 'D_0_D_96'),
(NOW(), 'group', 1630, 'D', 'D_0_D_97'),
(NOW(), 'group', 1640, 'D', 'D_0_D_98'),
(NOW(), 'group', 1650, 'D', 'D_0_D_99');

CREATE TABLE IF NOT EXISTS `iw_par_ca_rivacold_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_ca_rivacold_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'D_0_D_1', '0_D_1', 'Defrost count type', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_2', '0_D_2', 'Defrost at poweron', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_3', '0_D_3', 'Fan OFF (with opened) door', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_4', '0_D_4', 'Alarm emperature', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_5', '0_D_5', 'Defrost alarm Timeout', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_6', '0_D_6', 'Alarm output polarity', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'D_0_D_7', '0_D_7', 'Starting light with opened door', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_8', '0_D_8', 'Switch light alwais on with deactivating', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_9', '0_D_9', 'Fans and compressor deativating switch with opened door', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_10', '0_D_10', 'Decimal dot display', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_11', '0_D_11', '°C or °F Selection', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"°C"},"1":{"t":"°F"}}}'),
(NOW(), 'D_0_D_12', '0_D_12', 'Secondary terminal unit', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_58', '0_D_58', 'status of input 1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_59', '0_D_59', 'status of input 2', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_60', '0_D_60', 'status of input 3', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_61', '0_D_61', 'status of input 4', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_62', '0_D_62', 'status of relay 1 (Compressor)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_63', '0_D_63', 'status of relay 2 (Defrost)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_64', '0_D_64', 'status of relay 3 (Fan)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_65', '0_D_65', 'status of relay 4 (Alarm)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_66', '0_D_66', 'status of relay 5 (Light)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_67', '0_D_67', 'status of relay 6 (On)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_88', '0_D_88', 'ON OFF Command', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_90', '0_D_90', 'Synchronise network end defrost (master)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_91', '0_D_91', 'Synchronise network end defrost (slave)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_92', '0_D_92', 'Synchronise network start defrost (master)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_93', '0_D_93', 'Synchronise network start defrost (slave)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_94', '0_D_94', 'Disable cooling function during network defrost', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_95', '0_D_95', 'Network cooling function', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'D_0_D_100', '0_D_100', 'Defrost command', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"On"}}}'),
(NOW(), 'A_0_A_1', '0_A_1', 'Setpoint', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_2', '0_A_2', 'Differential', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_3', '0_A_3', 'High set', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_4', '0_A_4', 'Low set', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_5', '0_A_5', 'Offset Setpoint', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_6', '0_A_6', 'Probe 1 calibration (control)', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_7', '0_A_7', 'Probe 2 calibration (evaporator)', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_8', '0_A_8', 'Probe 3 calibration (condenser)', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_9', '0_A_9', 'Defrost stop temperature', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_10', '0_A_10', 'Defrost stop temperature at evap', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_11', '0_A_11', 'Fan stop temperature', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_12', '0_A_12', 'Fan run temperature', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_13', '0_A_13', 'Fan run stop differential', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_14', '0_A_14', 'Condenser fans stop temperature', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_15', '0_A_15', 'Condenser fans stop diferential', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_16', '0_A_16', 'Alarm temperature differential', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_17', '0_A_17', 'High alarm', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_18', '0_A_18', 'Low alarm', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_19', '0_A_19', 'Probe 3 alarm setpoint', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_20', '0_A_20', 'Probe 3 alarm differential', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_52', '0_A_52', 'Network probe', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_53', '0_A_53', 'Network set point', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_54', '0_A_54', 'Room temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_55', '0_A_55', 'Evaporator temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_56', '0_A_56', 'Condenser 2 evaporator temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_57', '0_A_57', 'Room temperature shown on the display', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_58', '0_A_58', 'Evaporator temperature shown on the display', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_59', '0_A_59', 'Condenser 2 evaporator temperature shown on the display', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_60', '0_A_60', 'Master probe ', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'A_0_A_61', '0_A_61', 'Temperature displayed by master', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_1', '0_I_1', 'Release software', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_6', '0_I_6', 'Network functions', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_7', '0_I_7', 'Network display during defrost', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_8', '0_I_8', 'Measurement stability', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_9', '0_I_9', 'Temperature probes present', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_10', '0_I_10', 'Probe calibration mode', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_11', '0_I_11', 'Minimum compressor ON time', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_12', '0_I_12', 'Compressor ON time in dutycycling', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_13', '0_I_13', 'Compressor OFF time in dutycycling', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_14', '0_I_14', 'Compressor start delay', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_15', '0_I_15', 'Minimum compressor OFF time', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_16', '0_I_16', 'Minimum time between successive compressor starts', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_17', '0_I_17', 'Delay at poweron', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_18', '0_I_18', 'Defrost type selection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_19', '0_I_19', 'Defrost interval time', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_20', '0_I_20', 'Unit of measurement (dit)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_21', '0_I_21', 'Defrost tenure unit of measurement (dit)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_22', '0_I_22', 'Defrost delay at poweron', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_23', '0_I_23', 'Defrost timeout', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_24', '0_I_24', 'Fan parameter', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_25', '0_I_25', 'After drainege delay time', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_26', '0_I_26', 'Drainage time', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_27', '0_I_27', 'Defrost fan deactivating', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_28', '0_I_28', 'Fan compressor OFF', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_29', '0_I_29', 'Fan off delay from compressor stop', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_30', '0_I_30', 'Fan on time in case of duty cicle (FCO=2)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_31', '0_I_31', 'Fan off time incase of duty cicle (FCO=2)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_32', '0_I_32', 'Condenser fans stop delay', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_33', '0_I_33', 'Power ON temperature alarm delay', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_34', '0_I_34', 'Defrost temperature alarm delay', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_35', '0_I_35', 'Closed door temperature alarm delay', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_36', '0_I_36', 'Timeout door open', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_37', '0_I_37', 'Time alarm delay', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_38', '0_I_38', 'Probe 3 alarm delay', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_39', '0_I_39', 'Pressure input thermal compressor max errors', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_40', '0_I_40', 'AT Pen counting interval', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_41', '0_I_41', 'Deactivating light delay with closed door', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_42', '0_I_42', 'Input door starting delay', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_43', '0_I_43', 'Defrosting phase display', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_44', '0_I_44', 'Display timeout indefrost', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_45', '0_I_45', 'Standard display', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_46', '0_I_46', 'Keyboard lock', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_47', '0_I_47', 'Configuration of digital input 1', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_48', '0_I_48', 'Configuration of digital input 2', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_49', '0_I_49', 'Configuration of digital input 3', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_50', '0_I_50', 'Configuration of digital input 4', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_52', '0_I_52', 'Alarm relay configuration', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_53', '0_I_53', 'Probe 3 configuration', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_54', '0_I_54', 'Setpoint direct parameters protection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_55', '0_I_55', 'Level 1 parameters protection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_56', '0_I_56', 'Vectorial set', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_57', '0_I_57', 'Device address (master only)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_58', '0_I_58', 'Master slave LAN address', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_59', '0_I_59', 'Number of slaves connected', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_60', '0_I_60', 'Master alarms control', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_61', '0_I_61', 'Master probe control', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_62', '0_I_62', 'Master network control', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_63', '0_I_63', 'Defrost control', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_64', '0_I_64', 'Network controls', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_65', '0_I_65', 'Master display', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_66', '0_I_66', 'Master setpoint', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_97', '0_I_97', 'Activate connection to the master', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_98', '0_I_98', 'Refrigeration unit status', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_99', '0_I_99', 'Light status', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_100', '0_I_100', 'Network virtual input', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'I_0_I_101', '0_I_101', 'Network virtual output', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'D_0_D_0', '0_D_0', 'Failed connection', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_42', '0_D_42', 'High temperature alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_43', '0_D_43', 'Low temperature alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_44', '0_D_44', 'Defrost ended by timeout alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_46', '0_D_46', 'High condenser temperature alarm (clean filter)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_47', '0_D_47', 'Thermal cutout alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_48', '0_D_48', 'Shutdown alarm due to repeated thermal cutout', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_49', '0_D_49', 'Pressure switch 1 cutout alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_50', '0_D_50', 'Pressure switch 1 repeated cutout shutdown alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_51', '0_D_51', 'Pressure switch 2 cutout alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_52', '0_D_52', 'Pressure switch 2 repeated cutout shutdown alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_53', '0_D_53', 'Temperature probe 3 fault alarm (second evaporator)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_54', '0_D_54', 'Temperature probe 1 fault alarm (control)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_55', '0_D_55', 'Temperature probe 3 fault alarm (condenser)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_56', '0_D_56', 'Temperature probe 2 fault alarm (evaporator)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_68', '0_D_68', 'Parameter memory fault alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_69', '0_D_69', 'Programming key fault alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_70', '0_D_70', 'Master offline alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_71', '0_D_71', 'Slave 1 offline alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_72', '0_D_72', 'Slave 2 offline alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_73', '0_D_73', 'Slave 3 offline alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_74', '0_D_74', 'Slave 4 offline alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_75', '0_D_75', 'Slave 5 offline alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_76', '0_D_76', 'Slave 1 alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_77', '0_D_77', 'Slave 2 alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_78', '0_D_78', 'Slave 3 alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_79', '0_D_79', 'Slave 4 alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_80', '0_D_80', 'Slave 5 alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_81', '0_D_81', 'Active alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_82', '0_D_82', 'Minor alarm active', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_83', '0_D_83', 'Slave 1 minor alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_84', '0_D_84', 'Slave 2 minor alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_85', '0_D_85', 'Slave 3 minor alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_86', '0_D_86', 'Slave 4 minor alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_87', '0_D_87', 'Slave 5 minor alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_96', '0_D_96', 'Open door alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_97', '0_D_97', 'Terminal 1 offline alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_98', '0_D_98', 'Terminal 2 offline alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'D_0_D_99', '0_D_99', 'Network alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}');

CREATE TABLE IF NOT EXISTS `iw_set_ca_rivacold` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='4.0.0';

REPLACE INTO `iw_set_ca_rivacold` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'D_0_D_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_11', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_12', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_58', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_59', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_60', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_61', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_62', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_63', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_64', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_65', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_66', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_67', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_88', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_90', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_91', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_92', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_93', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_94', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_95', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_100', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_11', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_12', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_13', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_14', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_15', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_16', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_17', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_18', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_19', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_20', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'A_0_A_52', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'A_0_A_53', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'A_0_A_54', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'A_0_A_55', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'A_0_A_56', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'A_0_A_57', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'A_0_A_58', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'A_0_A_59', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'A_0_A_60', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'A_0_A_61', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'I_0_I_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_11', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_12', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_13', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_14', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_15', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_16', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_17', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_18', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_19', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_20', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_21', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_22', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_23', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_24', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_25', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_26', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_27', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_28', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_29', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_30', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_31', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_32', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_33', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_34', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_35', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_36', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_37', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_38', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_39', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_40', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_41', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_42', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_43', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_44', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_45', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_46', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_47', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_48', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_49', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_50', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_52', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_53', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_54', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_55', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_56', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_57', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_58', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_59', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_60', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_61', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_62', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_63', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_64', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_65', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_66', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_97', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_98', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_99', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_100', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'I_0_I_101', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'D_0_D_0', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_42', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_43', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_44', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_46', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_47', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_48', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_49', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_50', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_51', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_52', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_53', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_54', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_55', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_56', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'D_0_D_68', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_69', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_70', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_71', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_72', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_73', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_74', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_75', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_76', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_77', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_78', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_79', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_80', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_81', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_82', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_83', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_84', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_85', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_86', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_87', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_96', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_97', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_98', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'D_0_D_99', '1', '0', 'slow', 'change', '', 'B', '', 0);



-- Changelog
--
-- v1 Orginal
--
--
--