

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'IR33UN', 'ca_ir33_universial_param', 'ca_ir33_universial_groups');

CREATE TABLE IF NOT EXISTS `iw_par_ca_ir33_universial_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_ca_ir33_universial_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'status', 'Status'),
(NOW(), 'group_alias', 2, 'configurations', 'Configurations'),
(NOW(), 'group_alias', 3, 'alarms', 'Alarms'),
(NOW(), 'group_alias', 4, 'on_off', 'On/Off'),
(NOW(), 'group_alias', 5, 'date_time', 'Date/Time'),
(NOW(), 'group', 26, 'status', 'Set_point_1'),
(NOW(), 'group', 27, 'status', 'Set_point_2'),
(NOW(), 'group', 1, 'configurations', 'Operating_mode'),
(NOW(), 'group', 77, 'configurations', 'Set_point_diff_erential_1'),
(NOW(), 'group', 78, 'configurations', 'Set_point_diff_erential_2'),
(NOW(), 'group', 79, 'configurations', 'Dead_zone_diff_erential'),
(NOW(), 'group', 2, 'configurations', 'Authority_Validity_mode_1_or_2'),
(NOW(), 'group', 3, 'configurations', 'Type_control'),
(NOW(), 'group', 4, 'configurations', 'Delay_between_activations_of_2_different_relay_outputs'),
(NOW(), 'group', 5, 'configurations', 'Minimum_time_between_activations_of_same_relay_output'),
(NOW(), 'group', 60, 'configurations', 'Minimum_time_between_deactivations_of_2_diff_relay_outputs'),
(NOW(), 'group', 6, 'configurations', 'Minimum_relay_output_off_time'),
(NOW(), 'group', 7, 'configurations', 'Minimum_relay_output_on_time'),
(NOW(), 'group', 8, 'configurations', 'Status_of_control_outputs_with_probe_alarm'),
(NOW(), 'group', 9, 'configurations', 'Output_rotation'),
(NOW(), 'group', 10, 'configurations', 'PWM_cycle_time'),
(NOW(), 'group', 11, 'configurations', 'Type_of_probe'),
(NOW(), 'group', 80, 'configurations', 'Calibration_of_probe_1'),
(NOW(), 'group', 81, 'configurations', 'Calibration_of_probe_2'),
(NOW(), 'group', 12, 'configurations', 'Probe_disturbance_filter'),
(NOW(), 'group', 13, 'configurations', 'Temperature_unit_of_measure'),
(NOW(), 'group', 14, 'configurations', 'Operation_of_probe_2'),
(NOW(), 'group', 15, 'configurations', 'Minimum_value_of_set_point_1'),
(NOW(), 'group', 16, 'configurations', 'Maximum_value_of_set_point_1'),
(NOW(), 'group', 17, 'configurations', 'Minimum_value_of_set_point_2'),
(NOW(), 'group', 18, 'configurations', 'Maximum_value_of_set_point_2'),
(NOW(), 'group', 82, 'configurations', 'Low_temperature_alarm_threshold'),
(NOW(), 'group', 83, 'configurations', 'High_temperature_alarm_threshold'),
(NOW(), 'group', 84, 'configurations', 'Alarm_differential'),
(NOW(), 'group', 85, 'configurations', 'Alarm_delay_time'),
(NOW(), 'group', 86, 'configurations', 'Type_of_alarm_threshold'),
(NOW(), 'group', 19, 'configurations', 'Digital_input_1'),
(NOW(), 'group', 20, 'configurations', 'Digital_input_2'),
(NOW(), 'group', 21, 'configurations', 'Status_of_control_outputs_with_alarm_from_digital_input'),
(NOW(), 'group', 22, 'configurations', 'Serial_connection_address'),
(NOW(), 'group', 23, 'configurations', 'Special_operation'),
(NOW(), 'group', 24, 'configurations', 'Dependence_of_output_1'),
(NOW(), 'group', 25, 'configurations', 'Type_of_output_1'),
(NOW(), 'group', 26, 'configurations', 'Activation_of_output_1'),
(NOW(), 'group', 27, 'configurations', 'Differential_logic_of_output_1'),
(NOW(), 'group', 61, 'configurations', 'Activation_restriction_for_output_1'),
(NOW(), 'group', 62, 'configurations', 'Deactivation_restriction_for_output_1'),
(NOW(), 'group', 63, 'configurations', 'Minimum_value_of_modulating_output_1'),
(NOW(), 'group', 64, 'configurations', 'Maximum_value_of_modulating_output_1'),
(NOW(), 'group', 28, 'configurations', 'Dependence_of_output_2'),
(NOW(), 'group', 29, 'configurations', 'Type_of_output_2'),
(NOW(), 'group', 30, 'configurations', 'Activation_of_output_2'),
(NOW(), 'group', 31, 'configurations', 'Differential_logic_of_output_2'),
(NOW(), 'group', 65, 'configurations', 'Activation_restriction_for_output_2'),
(NOW(), 'group', 66, 'configurations', 'Deactivation_restriction_for_output_2'),
(NOW(), 'group', 67, 'configurations', 'Minimum_value_of_modulating_output_2'),
(NOW(), 'group', 68, 'configurations', 'Maximum_value_of_modulating_output_2'),
(NOW(), 'group', 32, 'configurations', 'Dependence_of_output_3'),
(NOW(), 'group', 33, 'configurations', 'Type_of_output_3'),
(NOW(), 'group', 34, 'configurations', 'Activation_of_output_3'),
(NOW(), 'group', 35, 'configurations', 'Differential_logic_of_output_3'),
(NOW(), 'group', 69, 'configurations', 'Activation_restriction_for_output_3'),
(NOW(), 'group', 70, 'configurations', 'Deactivation_restriction_for_output_3'),
(NOW(), 'group', 71, 'configurations', 'Minimum_value_of_modulating_output_3'),
(NOW(), 'group', 72, 'configurations', 'Maximum_value_of_modulating_output_3'),
(NOW(), 'group', 36, 'configurations', 'Dependence_of_output_4'),
(NOW(), 'group', 37, 'configurations', 'Type_of_output_4'),
(NOW(), 'group', 38, 'configurations', 'Activation_of_output_4'),
(NOW(), 'group', 39, 'configurations', 'Differential_logic_of_output_4'),
(NOW(), 'group', 73, 'configurations', 'Activation_restriction_for_output_4'),
(NOW(), 'group', 74, 'configurations', 'Deactivation_restriction_for_output_4'),
(NOW(), 'group', 75, 'configurations', 'Minimum_value_of_modulating_output_4'),
(NOW(), 'group', 76, 'configurations', 'Maximum_value_of_modulating_output_4'),
(NOW(), 'group', 40, 'configurations', 'Disable_keypad_and_remote_control'),
(NOW(), 'group', 41, 'configurations', 'Code_for_enabling_the_remote_control'),
(NOW(), 'group', 42, 'configurations', 'Display'),
(NOW(), 'group', 43, 'configurations', 'Buzzer'),
(NOW(), 'group', 44, 'configurations', 'Delay_at_start_up'),
(NOW(), 'group', 45, 'configurations', 'Soft_start'),
(NOW(), 'group', 46, 'configurations', 'ti_PID'),
(NOW(), 'group', 47, 'configurations', 'td_PID'),
(NOW(), 'group', 48, 'configurations', 'Auto_Tuning'),
(NOW(), 'group', 49, 'configurations', 'Enabling_direct_threshold'),
(NOW(), 'group', 50, 'configurations', 'Enabling_reverse_threshold'),
(NOW(), 'group', 51, 'configurations', 'Enable_Cut_off_operation'),
(NOW(), 'group', 87, 'configurations', 'Enable_operating_cycle'),
(NOW(), 'group', 88, 'configurations', 'Operating_cycle_duration_of_step_1'),
(NOW(), 'group', 89, 'configurations', 'Operating_cycle_temperature_set_point_step_1'),
(NOW(), 'group', 90, 'configurations', 'Operating_cycle_duration_of_step_2'),
(NOW(), 'group', 91, 'configurations', 'Operating_cycle_temperature_set_point_step_2'),
(NOW(), 'group', 92, 'configurations', 'Operating_cycle_duration_of_step_3'),
(NOW(), 'group', 93, 'configurations', 'Operating_cycle_temperature_set_point_step_3'),
(NOW(), 'group', 94, 'configurations', 'Operating_cycle_duration_of_step_4'),
(NOW(), 'group', 95, 'configurations', 'Operating_cycle_temperature_set_point_step_4'),
(NOW(), 'group', 96, 'configurations', 'Operating_cycle_duration_of_step_5'),
(NOW(), 'group', 97, 'configurations', 'Operating_cycle_temperature_set_point_step_5'),
(NOW(), 'group', 1, 'alarms', 'AL0_y_year_of_alarm'),
(NOW(), 'group', 2, 'alarms', 'AL0_M_month_of_alarm'),
(NOW(), 'group', 3, 'alarms', 'AL0_d_day_of_alarm'),
(NOW(), 'group', 4, 'alarms', 'AL0_h_hours_of_alarm'),
(NOW(), 'group', 5, 'alarms', 'AL0_m_minutes_of_alarm'),
(NOW(), 'group', 6, 'alarms', 'AL0_t_type_of_alarm'),
(NOW(), 'group', 7, 'alarms', 'AL1_y_year_of_alarm'),
(NOW(), 'group', 8, 'alarms', 'AL1_M_month_of_alarm'),
(NOW(), 'group', 9, 'alarms', 'AL1_d_day_of_alarm'),
(NOW(), 'group', 10, 'alarms', 'AL1_h_hours_of_alarm'),
(NOW(), 'group', 11, 'alarms', 'AL1_m_minutes_of_alarm'),
(NOW(), 'group', 12, 'alarms', 'AL1_t_type_of_alarm'),
(NOW(), 'group', 13, 'alarms', 'AL2_y_year_of_alarm'),
(NOW(), 'group', 14, 'alarms', 'AL2_M_month_of_alarm'),
(NOW(), 'group', 15, 'alarms', 'AL2_d_day_of_alarm'),
(NOW(), 'group', 16, 'alarms', 'AL2_h_hours_of_alarm'),
(NOW(), 'group', 17, 'alarms', 'AL2_m_minutes_of_alarm'),
(NOW(), 'group', 18, 'alarms', 'AL2_t_type_of_alarm'),
(NOW(), 'group', 19, 'alarms', 'AL3_y_year_of_alarm'),
(NOW(), 'group', 20, 'alarms', 'AL3_M_month_of_alarm'),
(NOW(), 'group', 21, 'alarms', 'AL3_d_day_of_alarm'),
(NOW(), 'group', 22, 'alarms', 'AL3_h_hours_of_alarm'),
(NOW(), 'group', 23, 'alarms', 'AL3_m_minutes_of_alarm'),
(NOW(), 'group', 24, 'alarms', 'AL3_t_type_of_alarm'),
(NOW(), 'group', 25, 'alarms', 'AL4_y_year_of_alarm'),
(NOW(), 'group', 26, 'alarms', 'AL4_M_month_of_alarm'),
(NOW(), 'group', 27, 'alarms', 'AL4_d_day_of_alarm'),
(NOW(), 'group', 28, 'alarms', 'AL4_h_hours_of_alarm'),
(NOW(), 'group', 29, 'alarms', 'AL4_m_minutes_of_alarm'),
(NOW(), 'group', 30, 'alarms', 'AL4_t_type_of_alarm'),
(NOW(), 'group', 1, 'on_off', 'tON_d_on_day'),
(NOW(), 'group', 2, 'on_off', 'tON_h_on_hours'),
(NOW(), 'group', 3, 'on_off', 'tON_m_on_minutes'),
(NOW(), 'group', 4, 'on_off', 'tOFF_d_off_day'),
(NOW(), 'group', 5, 'on_off', 'tOFF_h_off_hours'),
(NOW(), 'group', 6, 'on_off', 'tOFF_m_off_minutes'),
(NOW(), 'group', 1, 'date_time', 'Date_year'),
(NOW(), 'group', 2, 'date_time', 'Date_month'),
(NOW(), 'group', 3, 'date_time', 'Date_day'),
(NOW(), 'group', 4, 'date_time', 'Date_day_of_the_week'),
(NOW(), 'group', 5, 'date_time', 'Hours'),
(NOW(), 'group', 6, 'date_time', 'Minutes'),
(NOW(), 'group', 1, 'status', 'Reading_of_probe_1'),
(NOW(), 'group', 2, 'status', 'Reading_of_probe_2'),
(NOW(), 'group', 3, 'status', 'Status_of_relay_1'),
(NOW(), 'group', 4, 'status', 'Status_of_relay_2'),
(NOW(), 'group', 5, 'status', 'Status_of_relay_3'),
(NOW(), 'group', 6, 'status', 'Status_of_relay_4'),
(NOW(), 'group', 7, 'status', 'Status_of_digital_input_1'),
(NOW(), 'group', 8, 'status', 'Status_of_digital_input_2'),
(NOW(), 'group', 9, 'status', 'Probe_1_fault_alarm'),
(NOW(), 'group', 10, 'status', 'Probe_2_fault_alarm'),
(NOW(), 'group', 11, 'status', 'Immediate_external_alarm'),
(NOW(), 'group', 12, 'status', 'High_temperature_alarm'),
(NOW(), 'group', 13, 'status', 'Low_temperature_alarm'),
(NOW(), 'group', 14, 'status', 'Delayed_external_alarm'),
(NOW(), 'group', 15, 'status', 'Immediate_external_alarm_with_manual_reset'),
(NOW(), 'group', 16, 'status', 'RTC_fault_alarm'),
(NOW(), 'group', 17, 'status', 'EEPROM_unit_parameters_alarm'),
(NOW(), 'group', 18, 'status', 'EEPROM_operating_parameters_alarm'),
(NOW(), 'group', 19, 'status', 'Maximum_time_in_calculation_of_PID_parameters'),
(NOW(), 'group', 20, 'status', 'PID_gain_null'),
(NOW(), 'group', 21, 'status', 'PID_gain_negative'),
(NOW(), 'group', 22, 'status', 'Integral_and_derivative_time_negative'),
(NOW(), 'group', 23, 'status', 'Maximum_time_in_calculation_of_continuous_gain'),
(NOW(), 'group', 24, 'status', 'Starting_situation_not_suitable'),
(NOW(), 'group', 25, 'status', 'Switch_controller_On_Off'),
(NOW(), 'group', 33, 'status', 'output_percent_1'),
(NOW(), 'group', 34, 'status', 'output_percent_2'),
(NOW(), 'group', 35, 'status', 'output_percent_3'),
(NOW(), 'group', 36, 'status', 'output_percent_4');

CREATE TABLE IF NOT EXISTS `iw_par_ca_ir33_universial_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(50) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_ca_ir33_universial_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'Set_point_1', '0_A_4', 'Set point 1', 'ST1', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Set_point_2', '0_A_5', 'Set point 2', 'ST2', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_mode', '0_I_12', 'Operating mode', 'c0', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Set_point_diff_erential_1', '0_A_6', 'Set point diff erential 1', 'P1', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Set_point_diff_erential_2', '0_A_7', 'Set point diff erential 2', 'P2', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Dead_zone_diff_erential', '0_A_8', 'Dead zone diff erential', 'P3', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Authority_Validity_mode_1_or_2', '0_A_9', 'Authority. Validity : mode 1 or 2', 'c4', 'Analog Values', 'float', '', '-1', 'rw', '', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Type_control', '0_D_25', 'Type control', 'c5', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Delay_between_activations_of_2_different_relay_outputs', '0_I_13', 'Delay between activations of 2 different relay outputs', 'c6', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_time_between_activations_of_same_relay_output', '0_I_14', 'Minimum time between activations of same relay output', 'c7', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_time_between_deactivations_of_2_diff_relay_outputs', '0_I_15', 'Minimum time between deactivations of 2 diff. relay outputs', 'd1', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_relay_output_off_time', '0_I_16', 'Minimum relay output off time', 'c8', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_relay_output_on_time', '0_I_17', 'Minimum relay output on time', 'c9', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Status_of_control_outputs_with_probe_alarm', '0_I_18', 'Status of control outputs with probe alarm', 'c10', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Output_rotation', '0_I_19', 'Output rotation', 'c11', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'PWM_cycle_time', '0_A_10', 'PWM cycle time', 'c12', 'Analog Values', 'float', '', '-1', 'rw', 's', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Type_of_probe', '0_I_20', 'Type of probe', 'c13', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Calibration_of_probe_1', '0_A_11', 'Calibration of probe 1', 'P14', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Calibration_of_probe_2', '0_A_12', 'Calibration of probe 2', 'P15', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Probe_disturbance_filter', '0_I_21', 'Probe disturbance filter', 'c17', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Temperature_unit_of_measure', '0_D_26', 'Temperature unit of measure', 'c18', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Operation_of_probe_2', '0_I_22', 'Operation of probe 2', 'c19', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_value_of_set_point_1', '0_A_15', 'Minimum value of set point 1', 'c21', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Maximum_value_of_set_point_1', '0_A_16', 'Maximum value of set point 1', 'c22', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_value_of_set_point_2', '0_A_17', 'Minimum value of set point 2', 'c23', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Maximum_value_of_set_point_2', '0_A_18', 'Maximum value of set point 2', 'c24', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Low_temperature_alarm_threshold', '0_A_19', 'Low temperature alarm threshold', 'P25', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'High_temperature_alarm_threshold', '0_A_20', 'High temperature alarm threshold', 'P26', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Alarm_differential', '0_A_21', 'Alarm differential', 'P27', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Alarm_delay_time', '0_I_23', 'Alarm delay time', 'P28', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Type_of_alarm_threshold', '0_D_27', 'Type of alarm threshold', 'P29', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Digital_input_1', '0_I_24', 'Digital input 1', 'c29', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Digital_input_2', '0_I_25', 'Digital input 2', 'c30', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Status_of_control_outputs_with_alarm_from_digital_input', '0_I_26', 'Status of control outputs with alarm from digital input', 'c31', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Serial_connection_address', '0_I_27', 'Serial connection address', 'c32', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Special_operation', '0_D_28', 'Special operation', 'c33', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Dependence_of_output_1', '0_I_28', 'Dependence of output 1', 'c34', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Type_of_output_1', '0_D_29', 'Type of output 1', 'c35', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Activation_of_output_1', '0_I_29', 'Activation of output 1', 'c36', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Differential_logic_of_output_1', '0_I_30', 'Differential/logic of output 1', 'c37', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Activation_restriction_for_output_1', '0_I_31', 'Activation restriction for output 1', 'd34', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Deactivation_restriction_for_output_1', '0_I_32', 'Deactivation restriction for output 1', 'd35', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_value_of_modulating_output_1', '0_I_33', 'Minimum value of modulating output 1', 'd36', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Maximum_value_of_modulating_output_1', '0_I_34', 'Maximum value of modulating output 1', 'd37', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Dependence_of_output_2', '0_I_35', 'Dependence of output 2', 'c38', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Type_of_output_2', '0_D_30', 'Type of output 2', 'c39', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Activation_of_output_2', '0_I_36', 'Activation of output 2', 'c40', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Differential_logic_of_output_2', '0_I_37', 'Differential/logic of output 2', 'c41', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Activation_restriction_for_output_2', '0_I_38', 'Activation restriction for output 2', 'd38', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Deactivation_restriction_for_output_2', '0_I_39', 'Deactivation restriction for output 2', 'd39', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_value_of_modulating_output_2', '0_I_40', 'Minimum value of modulating output 2', 'd40', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Maximum_value_of_modulating_output_2', '0_I_41', 'Maximum value of modulating output 2', 'd41', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Dependence_of_output_3', '0_I_42', 'Dependence of output 3', 'c42', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Type_of_output_3', '0_D_31', 'Type of output 3', 'c43', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Activation_of_output_3', '0_I_43', 'Activation of output 3', 'c44', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Differential_logic_of_output_3', '0_I_44', 'Differential/logic of output 3', 'c45', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Activation_restriction_for_output_3', '0_I_45', 'Activation restriction for output 3', 'd42', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Deactivation_restriction_for_output_3', '0_I_46', 'Deactivation restriction for output 3', 'd43', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_value_of_modulating_output_3', '0_I_47', 'Minimum value of modulating output 3', 'd44', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Maximum_value_of_modulating_output_3', '0_I_48', 'Maximum value of modulating output 3', 'd45', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Dependence_of_output_4', '0_I_49', 'Dependence of output 4', 'c46', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Type_of_output_4', '0_D_32', 'Type of output 4', 'c47', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Activation_of_output_4', '0_I_50', 'Activation of output 4', 'c48', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Differential_logic_of_output_4', '0_I_51', 'Differential/logic of output 4', 'c49', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Activation_restriction_for_output_4', '0_I_52', 'Activation restriction for output 4', 'd46', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Deactivation_restriction_for_output_4', '0_I_53', 'Deactivation restriction for output 4', 'd47', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_value_of_modulating_output_4', '0_I_54', 'Minimum value of modulating output 4', 'd48', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Maximum_value_of_modulating_output_4', '0_I_55', 'Maximum value of modulating output 4', 'd49', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Disable_keypad_and_remote_control', '0_I_56', 'Disable keypad and remote control', 'c50', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Code_for_enabling_the_remote_control', '0_I_57', 'Code for enabling the remote control', 'c51', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Display', '0_I_58', 'Display', 'c52', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Buzzer', '0_D_33', 'Buzzer', 'c53', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Delay_at_start_up', '0_I_59', 'Delay at start-up', 'c56', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Soft_start', '0_I_60', 'Soft start', 'c57', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ti_PID', '0_I_61', 'ti_PID', 'c62', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'td_PID', '0_I_62', 'td_PID', 'c63', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Auto_Tuning', '0_D_34', 'Auto-Tuning', 'c64', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Enabling_direct_threshold', '0_A_22', 'Enabling direct threshold', 'c66', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Enabling_reverse_threshold', '0_A_23', 'Enabling reverse threshold', 'c67', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Enable_Cut_off_operation', '0_D_35', 'Enable Cut off operation', 'c68', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Enable_operating_cycle', '0_I_70', 'Enable operating cycle', 'P70', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_cycle_duration_of_step_1', '0_I_71', 'Operating cycle: duration of step 1', 'P71', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_cycle_temperature_set_point_step_1', '0_A_24', 'Operating cycle: temperature set point step 1', 'P72', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_cycle_duration_of_step_2', '0_I_72', 'Operating cycle: duration of step 2', 'P73', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_cycle_temperature_set_point_step_2', '0_A_25', 'Operating cycle: temperature set point step 2', 'P74', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_cycle_duration_of_step_3', '0_I_73', 'Operating cycle: duration of step 3', 'P75', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_cycle_temperature_set_point_step_3', '0_A_26', 'Operating cycle: temperature set point step 3', 'P76', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_cycle_duration_of_step_4', '0_I_74', 'Operating cycle: duration of step 4', 'P77', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_cycle_temperature_set_point_step_4', '0_A_27', 'Operating cycle: temperature set point step 4', 'P78', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_cycle_duration_of_step_5', '0_I_75', 'Operating cycle: duration of step 5', 'P79', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Operating_cycle_temperature_set_point_step_5', '0_A_28', 'Operating cycle: temperature set point step 5', 'P80', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C/&deg;F', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL0_y_year_of_alarm', '0_I_76', 'AL0_y = year of alarm', 'y', 'Integral Values', 'integer', '', '-1', 'r', 'year', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL0_M_month_of_alarm', '0_I_77', 'AL0_M = month of alarm', 'M', 'Integral Values', 'integer', '', '-1', 'r', 'month', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL0_d_day_of_alarm', '0_I_78', 'AL0_d = day of alarm', 'd', 'Integral Values', 'integer', '', '-1', 'r', 'day', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL0_h_hours_of_alarm', '0_I_79', 'AL0_h = hours of alarm', 'h', 'Integral Values', 'integer', '', '-1', 'r', 'hours', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL0_m_minutes_of_alarm', '0_I_80', 'AL0_m = minutes of alarm', 'm', 'Integral Values', 'integer', '', '-1', 'r', 'minutes', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL0_t_type_of_alarm', '0_I_81', 'AL0_t = type of alarm', 'E', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL1_y_year_of_alarm', '0_I_82', 'AL1_y = year of alarm', 'y', 'Integral Values', 'integer', '', '-1', 'r', 'year', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL1_M_month_of_alarm', '0_I_83', 'AL1_M = month of alarm', 'M', 'Integral Values', 'integer', '', '-1', 'r', 'month', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL1_d_day_of_alarm', '0_I_84', 'AL1_d = day of alarm', 'd', 'Integral Values', 'integer', '', '-1', 'r', 'day', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL1_h_hours_of_alarm', '0_I_85', 'AL1_h = hours of alarm', 'h', 'Integral Values', 'integer', '', '-1', 'r', 'hours', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL1_m_minutes_of_alarm', '0_I_86', 'AL1_m = minutes of alarm', 'm', 'Integral Values', 'integer', '', '-1', 'r', 'minutes', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL1_t_type_of_alarm', '0_I_87', 'AL1_t = type of alarm', 'E', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL2_y_year_of_alarm', '0_I_88', 'AL2_y = year of alarm', 'y', 'Integral Values', 'integer', '', '-1', 'r', 'year', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL2_M_month_of_alarm', '0_I_89', 'AL2_M = month of alarm', 'M', 'Integral Values', 'integer', '', '-1', 'r', 'month', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL2_d_day_of_alarm', '0_I_90', 'AL2_d = day of alarm', 'd', 'Integral Values', 'integer', '', '-1', 'r', 'day', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL2_h_hours_of_alarm', '0_I_91', 'AL2_h = hours of alarm', 'h', 'Integral Values', 'integer', '', '-1', 'r', 'hours', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL2_m_minutes_of_alarm', '0_I_92', 'AL2_m = minutes of alarm', 'm', 'Integral Values', 'integer', '', '-1', 'r', 'minutes', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL2_t_type_of_alarm', '0_I_93', 'AL2_t = type of alarm', 'E', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL3_y_year_of_alarm', '0_I_94', 'AL3_y = year of alarm', 'y', 'Integral Values', 'integer', '', '-1', 'r', 'year', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL3_M_month_of_alarm', '0_I_95', 'AL3_M = month of alarm', 'M', 'Integral Values', 'integer', '', '-1', 'r', 'month', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL3_d_day_of_alarm', '0_I_96', 'AL3_d = day of alarm', 'd', 'Integral Values', 'integer', '', '-1', 'r', 'day', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL3_h_hours_of_alarm', '0_I_97', 'AL3_h = hours of alarm', 'h', 'Integral Values', 'integer', '', '-1', 'r', 'hours', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL3_m_minutes_of_alarm', '0_I_98', 'AL3_m = minutes of alarm', 'm', 'Integral Values', 'integer', '', '-1', 'r', 'minutes', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL3_t_type_of_alarm', '0_I_99', 'AL3_t = type of alarm', 'E', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL4_y_year_of_alarm', '0_I_100', 'AL4_y = year of alarm', 'y', 'Integral Values', 'integer', '', '-1', 'r', 'year', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL4_M_month_of_alarm', '0_I_101', 'AL4_M = month of alarm', 'M', 'Integral Values', 'integer', '', '-1', 'r', 'month', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL4_d_day_of_alarm', '0_I_102', 'AL4_d = day of alarm', 'd', 'Integral Values', 'integer', '', '-1', 'r', 'day', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL4_h_hours_of_alarm', '0_I_103', 'AL4_h = hours of alarm', 'h', 'Integral Values', 'integer', '', '-1', 'r', 'hours', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL4_m_minutes_of_alarm', '0_I_104', 'AL4_m = minutes of alarm', 'm', 'Integral Values', 'integer', '', '-1', 'r', 'mins.', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'AL4_t_type_of_alarm', '0_I_105', 'AL4_t = type of alarm', 'E', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'tON_d_on_day', '0_I_106', 'tON_d = on day', 'd', 'Integral Values', 'integer', '', '-1', 'rw', 'day', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'tON_h_on_hours', '0_I_107', 'tON_h = on hours', 'h', 'Integral Values', 'integer', '', '-1', 'rw', 'hours', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'tON_m_on_minutes', '0_I_108', 'tON_m = on minutes', 'm', 'Integral Values', 'integer', '', '-1', 'rw', 'mins.', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'tOFF_d_off_day', '0_I_109', 'tOFF_d = off day', 'd', 'Integral Values', 'integer', '', '-1', 'rw', 'day', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'tOFF_h_off_hours', '0_I_110', 'tOFF_h = off hours', 'h', 'Integral Values', 'integer', '', '-1', 'rw', 'hours', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'tOFF_m_off_minutes', '0_I_111', 'tOFF_m = off minutes', 'm', 'Integral Values', 'integer', '', '-1', 'rw', 'mins', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Date_year', '0_I_1', 'Date: year', 'y', 'Integral Values', 'integer', '', '-1', 'rw', 'year', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Date_month', '0_I_2', 'Date: month', 'M', 'Integral Values', 'integer', '', '-1', 'rw', 'month', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Date_day', '0_I_3', 'Date: day', 'd', 'Integral Values', 'integer', '', '-1', 'rw', 'day', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Date_day_of_the_week', '0_I_4', 'Date: day of the week', 'u', 'Integral Values', 'integer', '', '-1', 'rw', 'day', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Hours', '0_I_5', 'Hours', 'h', 'Integral Values', 'integer', '', '-1', 'rw', 'hours', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Minutes', '0_I_6', 'Minutes', 'M', 'Integral Values', 'integer', '', '-1', 'rw', 'mins.', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Reading_of_probe_1', '0_A_2', 'Reading of probe 1', '', 'Analog Values', 'float', '', '-1', 'r', '', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Reading_of_probe_2', '0_A_3', 'Reading of probe 2', '', 'Analog Values', 'float', '', '-1', 'r', '', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Status_of_relay_1', '0_D_1', 'Output 1 status', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Status_of_relay_2', '0_D_2', 'Output 2 status', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Status_of_relay_3', '0_D_3', 'Output 3 status', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Status_of_relay_4', '0_D_4', 'Output 4 status', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Status_of_digital_input_1', '0_D_6', 'Status of digital input 1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Status_of_digital_input_2', '0_D_7', 'Status of digital input 2', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Probe_1_fault_alarm', '0_D_9', 'Probe 1 fault alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Probe_2_fault_alarm', '0_D_10', 'Probe 2 fault alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Immediate_external_alarm', '0_D_11', 'Immediate external alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'High_temperature_alarm', '0_D_12', 'High temperature alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Low_temperature_alarm', '0_D_13', 'Low temperature alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Delayed_external_alarm', '0_D_14', 'Delayed external alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Immediate_external_alarm_with_manual_reset', '0_D_15', 'Immediate external alarm with manual reset', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'RTC_fault_alarm', '0_D_16', 'RTC fault alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'EEPROM_unit_parameters_alarm', '0_D_17', 'EEPROM unit parameters alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'EEPROM_operating_parameters_alarm', '0_D_18', 'EEPROM operating parameters alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Maximum_time_in_calculation_of_PID_parameters', '0_D_19', 'Maximum time in calculation of PID parameters', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'PID_gain_null', '0_D_20', 'PID gain null', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'PID_gain_negative', '0_D_21', 'PID gain negative', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Integral_and_derivative_time_negative', '0_D_22', 'Integral and derivative time negative', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Maximum_time_in_calculation_of_continuous_gain', '0_D_23', 'Maximum time in calculation of continuous gain', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Starting_situation_not_suitable', '0_D_24', 'Starting situation not suitable', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Switch_controller_On_Off', '0_D_36', 'Switch controller On/Off', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'output_percent_1', '0_I_127', 'Output 1 percentage', '', 'Integral Values', 'integer', '', '-1', 'r', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'output_percent_2', '0_I_128', 'Output 2 percentage', '', 'Integral Values', 'integer', '', '-1', 'r', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'output_percent_3', '0_I_129', 'Output 3 percentage', '', 'Integral Values', 'integer', '', '-1', 'r', '&#037', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'output_percent_4', '0_I_130', 'Output 4 percentage', '', 'Integral Values', 'integer', '', '-1', 'r', '&#037', '', '', '', '', '', '', '', '', '', '');

CREATE TABLE IF NOT EXISTS `iw_set_ca_ir33_universial` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_ca_ir33_universial` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'Set_point_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Set_point_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_mode', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Set_point_diff_erential_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Set_point_diff_erential_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Dead_zone_diff_erential', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Authority_Validity_mode_1_or_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Type_control', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Delay_between_activations_of_2_different_relay_outputs', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_time_between_activations_of_same_relay_output', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_time_between_deactivations_of_2_diff_relay_outputs', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_relay_output_off_time', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_relay_output_on_time', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Status_of_control_outputs_with_probe_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Output_rotation', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'PWM_cycle_time', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Type_of_probe', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Calibration_of_probe_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Calibration_of_probe_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Probe_disturbance_filter', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Temperature_unit_of_measure', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operation_of_probe_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_value_of_set_point_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Maximum_value_of_set_point_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_value_of_set_point_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Maximum_value_of_set_point_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Low_temperature_alarm_threshold', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'High_temperature_alarm_threshold', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Alarm_differential', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Alarm_delay_time', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Type_of_alarm_threshold', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Digital_input_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Digital_input_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Status_of_control_outputs_with_alarm_from_digital_input', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Serial_connection_address', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Special_operation', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Dependence_of_output_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Type_of_output_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Activation_of_output_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Differential_logic_of_output_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Activation_restriction_for_output_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Deactivation_restriction_for_output_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_value_of_modulating_output_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Maximum_value_of_modulating_output_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Dependence_of_output_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Type_of_output_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Activation_of_output_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Differential_logic_of_output_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Activation_restriction_for_output_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Deactivation_restriction_for_output_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_value_of_modulating_output_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Maximum_value_of_modulating_output_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Dependence_of_output_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Type_of_output_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Activation_of_output_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Differential_logic_of_output_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Activation_restriction_for_output_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Deactivation_restriction_for_output_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_value_of_modulating_output_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Maximum_value_of_modulating_output_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Dependence_of_output_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Type_of_output_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Activation_of_output_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Differential_logic_of_output_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Activation_restriction_for_output_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Deactivation_restriction_for_output_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_value_of_modulating_output_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Maximum_value_of_modulating_output_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Disable_keypad_and_remote_control', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Code_for_enabling_the_remote_control', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Display', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Buzzer', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Delay_at_start_up', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Soft_start', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ti_PID', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'td_PID', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Auto_Tuning', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Enabling_direct_threshold', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Enabling_reverse_threshold', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Enable_Cut_off_operation', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Enable_operating_cycle', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_cycle_duration_of_step_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_cycle_temperature_set_point_step_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_cycle_duration_of_step_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_cycle_temperature_set_point_step_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_cycle_duration_of_step_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_cycle_temperature_set_point_step_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_cycle_duration_of_step_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_cycle_temperature_set_point_step_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_cycle_duration_of_step_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Operating_cycle_temperature_set_point_step_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL0_y_year_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL0_M_month_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL0_d_day_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL0_h_hours_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL0_m_minutes_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL0_t_type_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL1_y_year_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL1_M_month_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL1_d_day_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL1_h_hours_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL1_m_minutes_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL1_t_type_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL2_y_year_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL2_M_month_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL2_d_day_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL2_h_hours_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL2_m_minutes_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL2_t_type_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL3_y_year_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL3_M_month_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL3_d_day_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL3_h_hours_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL3_m_minutes_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL3_t_type_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL4_y_year_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL4_M_month_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL4_d_day_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL4_h_hours_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL4_m_minutes_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'AL4_t_type_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'tON_d_on_day', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'tON_h_on_hours', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'tON_m_on_minutes', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'tOFF_d_off_day', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'tOFF_h_off_hours', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'tOFF_m_off_minutes', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Date_year', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Date_month', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Date_day', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Date_day_of_the_week', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Hours', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minutes', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Reading_of_probe_1', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Reading_of_probe_2', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Status_of_relay_1', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'Status_of_relay_2', '1', '1', 'norm', 'change', '', '', '', 0),
(NOW(), 'Status_of_relay_3', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'Status_of_relay_4', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'Status_of_digital_input_1', '1', '1', 'norm', 'change', '', '', '', 0),
(NOW(), 'Status_of_digital_input_2', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'Probe_1_fault_alarm', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Probe_2_fault_alarm', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Immediate_external_alarm', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'High_temperature_alarm', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Low_temperature_alarm', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Delayed_external_alarm', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Immediate_external_alarm_with_manual_reset', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'RTC_fault_alarm', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'EEPROM_unit_parameters_alarm', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'EEPROM_operating_parameters_alarm', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Maximum_time_in_calculation_of_PID_parameters', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'PID_gain_null', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'PID_gain_negative', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'Integral_and_derivative_time_negative', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'Maximum_time_in_calculation_of_continuous_gain', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'Starting_situation_not_suitable', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'Switch_controller_On_Off', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'output_percent_1', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'output_percent_2', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'output_percent_3', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'output_percent_4', '1', '1', 'norm', 'min', '1', '', '', 0);




-- Changelog
--
-- v1 Orginal
--
--