REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'ID01', 'Pos 01', 'ca_ir32', 'CAREL485', '0_1', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID02', 'Pos 02', 'ca_ir32', 'CAREL485', '0_2', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID03', 'Pos 03', 'ca_ir32', 'CAREL485', '0_3', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID04', 'Pos 04', 'ca_ir32', 'CAREL485', '0_4', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID05', 'Pos 05', 'ca_ir32', 'CAREL485', '0_5', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID06', 'Pos 06', 'ca_ir32', 'CAREL485', '0_6', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID07', 'Pos 07', 'ca_ir32', 'CAREL485', '0_7', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID08', 'Pos 08', 'ca_ir32', 'CAREL485', '0_8', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID09', 'Pos 09', 'ca_ir32', 'CAREL485', '0_9', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID10', 'Pos 10', 'ca_ir32', 'CAREL485', '0_10', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID11', 'Pos 11', 'ca_ir32', 'CAREL485', '0_11', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID12', 'Pos 12', 'ca_ir32', 'CAREL485', '0_12', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID13', 'Pos 13', 'ca_ir32', 'CAREL485', '0_13', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID14', 'Pos 14', 'ca_ir32', 'CAREL485', '0_14', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID15', 'Pos 15', 'ca_ir32', 'CAREL485', '0_15', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID16', 'Pos 16', 'ca_ir32', 'CAREL485', '0_16', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID17', 'Pos 17', 'ca_ir32', 'CAREL485', '0_17', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID18', 'Pos 18', 'ca_ir32', 'CAREL485', '0_18', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID19', 'Pos 19', 'ca_ir32', 'CAREL485', '0_19', 'IR32', 'IR32', 0, ''),
(NOW(), '1', '0', 'ID20', 'Pos 20', 'ca_ir32', 'CAREL485', '0_20', 'IR32', 'IR32', 0, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'com_port', 'CAREL485', '1', '', '', ''),
(NOW(), 'reopen_timer', 'CAREL485', 'never', '', 'never,x min,x hour', ''),
(NOW(), 'count_com_ports', 'CAREL485', '1', '', '', ''),
(NOW(), 'alarm_handler', 'CAREL485', '', '', '', ''),
(NOW(), 'startup_delay', 'CAREL485', '15', 'Sec.', '', ''),
(NOW(), 'show_queue_info', 'CAREL485', '0', '', '', ''),
(NOW(), 'unblock_timer', 'CAREL485', '2 min', 'Time string', '', ''),
(NOW(), 'sql_queue_poll_time', 'CAREL485', '1000', 'msec', '', ''),
(NOW(), 'speed_index_slow', 'CAREL485', '1', '', '', ''),
(NOW(), 'timeout_supermarket', 'IWS', '10800', 'Sec', '', ''),
(NOW(), 'timeout_ioc', 'IWS', '300', 'Sec', '', ''),
(NOW(), 'timeout_print', 'IWS', '180', 'Sec', '', ''),
(NOW(), 'defult_printer_name', 'ALL', '', '', '', ''),
(NOW(), 'speed_index_norm', 'CAREL485', '1', '', '', ''),
(NOW(), 'speed_index_block', 'CAREL485', '10', '', '', ''),
(NOW(), 'packet_timeout', 'CAREL485', '0', 'sec', '', ''),
(NOW(), 'max_param_block_time', 'CAREL485', '2', 'hours', '', ''),
(NOW(), 'max_outstanding_packets', 'CAREL485', '-1', '', '', ''),
(NOW(), 'max_group_count', 'CAREL485', '1', '', '', ''),
(NOW(), 'max_error_count', 'CAREL485', '2', '', '', ''),
(NOW(), 'idle_event_rate', 'CAREL485', '250', 'msec', '', ''),
(NOW(), 'gateway_type', 'CAREL485', '485N', '', '', ''),
(NOW(), 'baud_rate', 'CAREL485', '19200', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'CAREL485', '60', 'min.', '', ''),
(NOW(), 'speed_index_offline', 'CAREL485', '10', '', '', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_carel485.exe', 'CAREL485', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'IR32', 'ca_ir32_param', 'ca_ir32_groups');

CREATE TABLE IF NOT EXISTS `iw_par_ca_ir32_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_ca_ir32_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'often_used', 'Often used'),
(NOW(), 'group_alias', 2, 'cmd', 'Commands'),
(NOW(), 'group_alias', 3, 'PAlarm', 'Alarm and digital inputs configuration'),
(NOW(), 'group_alias', 4, 'Params', 'Main parameters'),
(NOW(), 'group_alias', 5, 'PDef', 'Defrost parameters'),
(NOW(), 'group_alias', 6, 'PFan', 'Fan parameters'),
(NOW(), 'group_alias', 7, 'Pprobe', 'Probe parameters'),
(NOW(), 'group_alias', 8, 'Pcompr', 'Compressor parameters'),
(NOW(), 'group_alias', 9, 'Alarms', 'Alarms'),
(NOW(), 'group', 1, 'often_used', 'OFFLINE'),
(NOW(), 'group', 2, 'often_used', 'ciclo_continuo'),
(NOW(), 'group', 3, 'often_used', 'temp_ambiente'),
(NOW(), 'group', 4, 'often_used', 'temp_evap'),
(NOW(), 'group', 5, 'often_used', 'ventilatori'),
(NOW(), 'group', 6, 'often_used', 'valv_inv_ciclo'),
(NOW(), 'group', 7, 'often_used', 'compressor'),
(NOW(), 'group', 8, 'often_used', 'set_point'),
(NOW(), 'group', 9, 'often_used', 'dripping_iyme'),
(NOW(), 'group', 1, 'cmd', 'm_def'),
(NOW(), 'group', 2, 'cmd', 'aux_out'),
(NOW(), 'group', 1, 'PAlarm', 'diff_alarm_fan'),
(NOW(), 'group', 2, 'PAlarm', 'sgl_alarm_min_rel'),
(NOW(), 'group', 3, 'PAlarm', 'sgl_alarl_max_rel'),
(NOW(), 'group', 4, 'PAlarm', 'rit_all_temp'),
(NOW(), 'group', 5, 'PAlarm', 'config_dig_in1'),
(NOW(), 'group', 6, 'PAlarm', 'config_dig_in2'),
(NOW(), 'group', 7, 'PAlarm', 'look_comp_ext'),
(NOW(), 'group', 8, 'PAlarm', 'delay_activ_alr'),
(NOW(), 'group', 1, 'Params', 'control_delta'),
(NOW(), 'group', 2, 'Params', 'set_point_min'),
(NOW(), 'group', 3, 'Params', 'set_point_max'),
(NOW(), 'group', 4, 'Params', 'en_ed_alarm'),
(NOW(), 'group', 5, 'Params', 'delta_set_point'),
(NOW(), 'group', 6, 'Params', 'en_max_min'),
(NOW(), 'group', 7, 'Params', 'oper_mode_h1'),
(NOW(), 'group', 8, 'Params', 'Key_lock'),
(NOW(), 'group', 9, 'Params', 'enabling_telecom'),
(NOW(), 'group', 1, 'PDef', 'type_defrost'),
(NOW(), 'group', 2, 'PDef', 'Interval_between_defrost'),
(NOW(), 'group', 3, 'PDef', 'defrost_end_temperature'),
(NOW(), 'group', 4, 'PDef', 'duration_def'),
(NOW(), 'group', 5, 'PDef', 'def_uni_up'),
(NOW(), 'group', 6, 'PDef', 'delay_def_after_sturt_up'),
(NOW(), 'group', 7, 'PDef', 'blocco_vis_sbrin'),
(NOW(), 'group', 8, 'PDef', 'duration_of_alarm'),
(NOW(), 'group', 9, 'PDef', 'def_pri'),
(NOW(), 'group', 10, 'PDef', 'time_base_dC'),
(NOW(), 'group', 1, 'PFan', 'fan_man_f0'),
(NOW(), 'group', 2, 'PFan', 'set_fan_off_rel'),
(NOW(), 'group', 3, 'PFan', 'stop_fan_f2'),
(NOW(), 'group', 4, 'PFan', 'stop_fan_f3'),
(NOW(), 'group', 5, 'PFan', 'sto_after_drip'),
(NOW(), 'group', 1, 'Pprobe', 'offset_probe'),
(NOW(), 'group', 2, 'Pprobe', 'filter_digital'),
(NOW(), 'group', 3, 'Pprobe', 'derivata'),
(NOW(), 'group', 4, 'Pprobe', 'virtual_probe'),
(NOW(), 'group', 5, 'Pprobe', 'c_f__5'),
(NOW(), 'group', 6, 'Pprobe', 'int_display'),
(NOW(), 'group', 1, 'Pcompr', 'delay_from_startup'),
(NOW(), 'group', 2, 'Pcompr', 'interval_between_2_start_up'),
(NOW(), 'group', 3, 'Pcompr', 'time_min_off'),
(NOW(), 'group', 4, 'Pcompr', 'time_min_on'),
(NOW(), 'group', 5, 'Pcompr', 'safety_relay'),
(NOW(), 'group', 6, 'Pcompr', 'duration_cc'),
(NOW(), 'group', 7, 'Pcompr', 'no_alarm_after_cc'),
(NOW(), 'group', 1, 'Alarms', 'all_sonda_def'),
(NOW(), 'group', 2, 'Alarms', 'all_eeprom'),
(NOW(), 'group', 3, 'Alarms', 'all_timeout_def'),
(NOW(), 'group', 4, 'Alarms', 'all_bassa_temp'),
(NOW(), 'group', 5, 'Alarms', 'all_alta_temp'),
(NOW(), 'group', 6, 'Alarms', 'all_sonda_amb'),
(NOW(), 'group', 7, 'Alarms', 'all_imm_ai'),
(NOW(), 'group', 8, 'Alarms', 'all_rit_ad'),
(NOW(), 'group', 11, 'PDef', 'defrost_require'),
(NOW(), 'group', 12, 'PDef', 'defrost_forced_or_not_running'),
(NOW(), 'group', 13, 'PDef', 'dripping_forced_or_not_running'),
(NOW(), 'group', 10, 'often_used', 'digital_input_1_status'),
(NOW(), 'group', 11, 'often_used', 'digital_input_2_status'),
(NOW(), 'group', 14, 'PDef', 'defrost_input_enabling_activated'),
(NOW(), 'group', 15, 'PDef', 'forced_defrost_running'),
(NOW(), 'group', 10, 'Params', 'opened_door_signalisation'),
(NOW(), 'group', 16, 'PDef', 'defrost_enabling'),
(NOW(), 'group', 11, 'Params', 'direct_reverse_input_selection'),
(NOW(), 'group', 7, 'Pprobe', 'probe_type'),
(NOW(), 'group', 12, 'Params', 'buzzer_on'),
(NOW(), 'group', 13, 'Params', 'on_off_status'),
(NOW(), 'group', 14, 'Params', 'on_off_require'),
(NOW(), 'group', 15, 'Params', 'rt_rh_and_rl_reset'),
(NOW(), 'group', 16, 'Params', 'buzzer_output_status'),
(NOW(), 'group', 17, 'Params', 'model');

CREATE TABLE IF NOT EXISTS `iw_par_ca_ir32_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(50) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_ca_ir32_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'OFFLINE', '0_D_0', 'no connection', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'ciclo_continuo', '0_D_1', 'Continuos cycle', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'temp_ambiente', '0_A_1', 'Room temperature', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'temp_evap', '0_A_2', 'Evaporator temperature', 'd/', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ventilatori', '0_D_2', 'Fan', 'Fan', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'valv_inv_ciclo', '0_D_6', 'Defrost', 'Def', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'compressor', '0_D_4', 'Compressor', 'Comp', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'set_point', '0_A_3', 'Setpoint', 'ST', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-50.0', '199.0', '', '', '', '', '', '', ''),
(NOW(), 'dripping_iyme', '0_I_16', 'Dripping time after defrost', 'dD', 'Integral Values', 'integer', '2', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '', ''),
(NOW(), 'm_def', '0_D_39', 'manual defrost', 'Defrost', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'aux_out', '0_D_5', 'Auxiliary output', 'Aux', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'diff_alarm_fan', '0_A_9', 'Differential alarms and fans', 'A0', 'Analog Values', 'float', '0.2', '-1', 'rw', '&deg;C', '%.1f', '0.1', '20.0', '', '', '', '', '', '', ''),
(NOW(), 'sgl_alarm_min_rel', '0_A_10', 'Low temperature alarm', 'AL', 'Analog Values', 'float', '0.0', '-1', 'rw', '&deg;C', '%.1f', '0', '199', '', '', '', '', '', '', ''),
(NOW(), 'sgl_alarl_max_rel', '0_A_11', 'High temperature alarm', 'AH', 'Analog Values', 'float', '0.0', '-1', 'rw', '&deg;C', '%.1f', '0', '199.0', '', '', '', '', '', '', ''),
(NOW(), 'rit_all_temp', '0_I_18', 'Temperature alarm delay', 'Ad', 'Integral Values', 'integer', '120', '-1', 'rw', 'min', '', '0', '199', '', '', '', '', '', '', ''),
(NOW(), 'config_dig_in1', '0_I_19', 'Configuration of the multifunction digital input no. 1', 'A4', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '7', '', '', '', '', '', '', ''),
(NOW(), 'config_dig_in2', '0_I_20', 'Configuration of the 2nd digital input', 'A5', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '7', '', '', '', '', '', '', ''),
(NOW(), 'look_comp_ext', '0_I_21', 'Compr. clooking from external alarm', 'A6', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '100', '', '', '', '', '', '', ''),
(NOW(), 'delay_activ_alr', '0_I_22', 'Delay in registration of external alarm', 'A7', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '199', '', '', '', '', '', '', ''),
(NOW(), 'control_delta', '0_A_5', 'Differential', 'rd', 'Analog Values', 'float', '2.0', '-1', 'rw', '&deg;C', '%.1f', '0.1', '19.9', '', '', '', '', '', '', ''),
(NOW(), 'set_point_min', '0_A_6', 'Minimun set point value', 'r1', 'Analog Values', 'float', '-50.0', '-1', 'rw', '&deg;C', '%.1f', '-50.0', '199.0', '', '', '', '', '', '', ''),
(NOW(), 'set_point_max', '0_A_7', 'Maximun set point value', 'r2', 'Analog Values', 'float', '60.0', '-1', 'rw', '&deg;C', '%.1f', '-50.0', '199.0', '', '', '', '', '', '', ''),
(NOW(), 'en_ed_alarm', '0_D_27', 'Direct/reverse(SE) - ED alarm enabling all mods exc. ME', 'r3', 'Digital IO', 'boolean', '0', '-1', 'rw', 'flag', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'delta_set_point', '0_A_13', 'Automatic set-point variation for night-time operation', 'r4', 'Analog Values', 'float', '3.0', '-1', 'rw', '&deg;C', '%.1f', '0', '+20', '', '', '', '', '', '', ''),
(NOW(), 'en_max_min', '0_D_43', 'Enable Min and Max temperature monitorin', 'r5', 'Digital IO', 'boolean', '0', '-1', 'rw', 'flag', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'oper_mode_h1', '0_I_27', 'Operating mode', 'H1', 'Integral Values', 'integer', 'IR32SE=0;IR32YE=0; IR32CE=1', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Key_lock', '0_I_25', 'Disable keypad and/or the remote inhibition', 'H2', 'Integral Values', 'integer', '1', '-1', 'rw', 'flag', '', '0', '3', '', '', '', '', '', '', ''),
(NOW(), 'enabling_telecom', '0_I_23', 'Remote control programming enabling code', 'H3', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '199', '', '', '', '', '', '', ''),
(NOW(), 'type_defrost', '0_I_2', 'Defrost parameters', 'd0', 'Integral Values', 'integer', '0', '-1', 'rw', 'flag', '', '0', '3', '', '', '', '', '', '', ''),
(NOW(), 'Interval_between_defrost', '0_I_13', 'Interval between defrost', 'dI', 'Integral Values', 'integer', '8', '-1', 'rw', 'hours', '', '0', '199', '', '', '', '', '', '', ''),
(NOW(), 'defrost_end_temperature', '0_A_8', 'Defrost end temperature set', 'dt', 'Analog Values', 'float', '4', '-1', 'rw', '&deg;C', '%.1f', '-50.0', '199.0', '', '', '', '', '', '', ''),
(NOW(), 'duration_def', '0_I_14', 'Maximum defrost time', 'dP', 'Integral Values', 'integer', '30', '-1', 'rw', 'min', '', '0', '199', '', '', '', '', '', '', ''),
(NOW(), 'def_uni_up', '0_D_29', 'Defrost on unit start-up', 'd4', 'Digital IO', 'boolean', '0', '-1', 'rw', 'flag', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'delay_def_after_sturt_up', '0_I_15', 'Def delay after unit start-up or multi-function input', 'd5', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '199', '', '', '', '', '', '', ''),
(NOW(), 'blocco_vis_sbrin', '0_D_44', 'Display blocking during defrosting', 'd6', 'Digital IO', 'boolean', '1', '-1', 'rw', 'flag', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'duration_of_alarm', '0_I_17', 'Duration of alarm cut-out after dripping', 'd8', 'Integral Values', 'integer', '1', '-1', 'rw', 'hours', '', '0', '15', '', '', '', '', '', '', ''),
(NOW(), 'def_pri', '0_D_30', 'Defrost priority over compressor protection', 'd9', 'Digital IO', 'boolean', '0', '-1', 'rw', 'flag', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'time_base_dC', '0_D_31', 'Time bases (0=hours, 1=minutes)', 'dC', 'Digital IO', 'boolean', '0', '-1', 'rw', 'flag', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'fan_man_f0', '0_I_26', 'Fan management', 'F0', 'Integral Values', 'integer', '0', '-1', 'rw', 'flag', '', '0', '2', '', '', '', '', '', '', ''),
(NOW(), 'set_fan_off_rel', '0_A_12', 'Fan switching on temperature', 'F1', 'Analog Values', 'float', '5', '-1', 'rw', 'R &deg;C', '%.1f', '0.0', '20.0', '', '', '', '', '', '', ''),
(NOW(), 'stop_fan_f2', '0_D_33', 'Stop fans when compressor is off', 'F2', 'Digital IO', 'boolean', '1', '-1', 'rw', 'flag', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'stop_fan_f3', '0_D_34', 'Stop fans during defrosting', 'F3', 'Digital IO', 'boolean', '1', '-1', 'rw', 'flag', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'sto_after_drip', '0_I_24', 'Cut out after dripping', 'Fd', 'Integral Values', 'integer', '1', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '', ''),
(NOW(), 'offset_probe', '0_A_4', 'Calibration', '/C', 'Analog Values', 'float', '0.0', '-1', 'rw', '&deg;C', '%.1f', '-20.0', '20.0', '', '', '', '', '', '', ''),
(NOW(), 'filter_digital', '0_I_3', 'Stability measurement', '/2', 'Integral Values', 'integer', '4', '-1', 'rw', '', '', '1', '15', '', '', '', '', '', '', ''),
(NOW(), 'derivata', '0_I_4', 'Probe reading speed', '/3', 'Integral Values', 'integer', '8', '-1', 'rw', '', '', '1', '15', '', '', '', '', '', '', ''),
(NOW(), 'virtual_probe', '0_I_5', 'Probe average (virtual probe)', '/4', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '100', '', '', '', '', '', '', ''),
(NOW(), 'c_f__5', '0_D_26', 'Celsius/Fahrenheit', '/5', 'Digital IO', 'boolean', '0', '-1', 'rw', 'flag', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'int_display', '0_D_42', 'Display decimals', '/6', 'Digital IO', 'boolean', '0', '-1', 'rw', 'flag', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'delay_from_startup', '0_I_6', 'Compressor start-up delay after unit start-up', 'c0', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '', ''),
(NOW(), 'interval_between_2_start_up', '0_I_7', 'Minimun interval between two compressor start-ups', 'c1', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '', ''),
(NOW(), 'time_min_off', '0_I_8', 'Minimun compressor off-time', 'c2', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '', ''),
(NOW(), 'time_min_on', '0_I_9', 'Minimun compressor on-time', 'c3', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '', ''),
(NOW(), 'safety_relay', '0_I_10', 'Relay safety see duty setting', 'c4', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '100', '', '', '', '', '', '', ''),
(NOW(), 'duration_cc', '0_I_11', 'Duration of continuos cycle', 'cc', 'Integral Values', 'integer', '4', '-1', 'rw', 'hour', '', '0', '15', '', '', '', '', '', '', ''),
(NOW(), 'no_alarm_after_cc', '0_I_12', 'Alarm cut-out after continuous cycle', 'c6', 'Integral Values', 'integer', '2', '-1', 'rw', 'hour', '', '0', '15', '', '', '', '', '', '', ''),
(NOW(), 'all_sonda_def', '0_D_13', 'defrost probe error (e1)', 'E1', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'all_eeprom', '0_D_8', 'Data memorization error (ea, ee, eb)', 'E(AEb)', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'all_timeout_def', '0_D_9', 'Timeout defrost end', 'Ed', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'all_bassa_temp', '0_D_10', 'Low temperature alarm (lo)', 'L0', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'all_alta_temp', '0_D_11', 'High temperature alarm (hi)', 'HI', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'all_sonda_amb', '0_D_12', 'Room probe error', 'E0', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'all_imm_ai', '0_D_14', 'Immediate external alarm (ai)', 'ai', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'all_rit_ad', '0_D_15', 'Delayed external alarm (ad)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_require', '0_D_16', 'Defrost require', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_forced_or_not_running', '0_D_17', 'Defrost (forced or not) running', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'dripping_forced_or_not_running', '0_D_18', 'Dripping (forced or not) running', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'digital_input_1_status', '0_D_19', 'Digital input 1 status', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'digital_input_2_status', '0_D_20', 'Digital input 2 status', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_input_enabling_activated', '0_D_21', 'Defrost input enabling activated', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'forced_defrost_running', '0_D_22', 'Forced defrost running', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'opened_door_signalisation', '0_D_23', 'Opened door signalisation', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_enabling', '0_D_24', 'Defrost enabling', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'direct_reverse_input_selection', '0_D_25', 'Direct/reverse input selection', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'probe_type', '0_D_28', 'Type of sensor (0=NTC 1=PTC)', '/0', 'Digital IO', 'boolean', '0', '1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'buzzer_on', '0_D_3', 'Buzzer ON', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'on_off_status', '0_D_37', 'On/off status', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'on_off_require', '0_D_38', 'On/off require', '', 'Digital IO', 'boolean', '0', '1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'rt_rh_and_rl_reset', '0_D_40', 'rt, rH and rL reset', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'buzzer_output_status', '0_D_7', 'Buzzer output status', '', 'Digital IO', 'boolean', '0', '1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'model', '0_I_1', 'Model', '', 'Integral values', 'integer', '0', '2', 'r', '', '', '-32000', '32000', '', '', '', '', '', '', '');

CREATE TABLE IF NOT EXISTS `iw_set_ca_ir32` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_ca_ir32` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'OFFLINE', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ciclo_continuo', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'temp_ambiente', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'temp_evap', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ventilatori', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'valv_inv_ciclo', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'compressor', '1', '1', 'norm', 'change', '', '', '', 0),
(NOW(), 'set_point', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dripping_iyme', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'm_def', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'aux_out', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'diff_alarm_fan', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sgl_alarm_min_rel', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sgl_alarl_max_rel', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'rit_all_temp', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'config_dig_in1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'config_dig_in2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'look_comp_ext', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'delay_activ_alr', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'control_delta', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'set_point_min', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'set_point_max', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'en_ed_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'delta_set_point', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'en_max_min', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'oper_mode_h1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Key_lock', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'enabling_telecom', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'type_defrost', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Interval_between_defrost', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_end_temperature', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'duration_def', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'def_uni_up', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'delay_def_after_sturt_up', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'blocco_vis_sbrin', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'duration_of_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'def_pri', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'time_base_dC', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'fan_man_f0', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'set_fan_off_rel', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'stop_fan_f2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'stop_fan_f3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sto_after_drip', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'offset_probe', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'filter_digital', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'derivata', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'virtual_probe', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'c_f__5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_display', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'delay_from_startup', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'interval_between_2_start_up', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'time_min_off', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'time_min_on', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'safety_relay', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'duration_cc', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'no_alarm_after_cc', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'all_sonda_def', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'all_eeprom', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'all_timeout_def', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'all_bassa_temp', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'all_alta_temp', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'all_sonda_amb', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'all_imm_ai', '1', '0', 'norm', 'change', '', 'B', '', 0),
(NOW(), 'all_rit_ad', '1', '0', 'norm', 'change', '', 'B', '', 0),
(NOW(), 'defrost_require', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_forced_or_not_running', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dripping_forced_or_not_running', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'digital_input_1_status', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'digital_input_2_status', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'defrost_input_enabling_activated', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'forced_defrost_running', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'opened_door_signalisation', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_enabling', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'direct_reverse_input_selection', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'probe_type', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'buzzer_on', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'on_off_status', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'on_off_require', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'rt_rh_and_rl_reset', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'buzzer_output_status', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'model', '1', '0', 'slow', 'change', '', '', '', 0);







-- Changelog
--
-- v1 Orginal
--
--