REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'ID01', 'Carel EVD 01', 'ca_evdevo', 'CAREL485', '0_1', 'EVDEVO', 'EVDEVO', 0, ''),
(NOW(), '1', '0', 'ID02', 'Carel EVD 02', 'ca_evdevo', 'CAREL485', '0_2', 'EVDEVO', 'EVDEVO', 0, ''),
(NOW(), '1', '0', 'ID03', 'Carel EVD 03', 'ca_evdevo', 'CAREL485', '0_3', 'EVDEVO', 'EVDEVO', 0, ''),
(NOW(), '1', '0', 'ID04', 'Carel EVD 04', 'ca_evdevo', 'CAREL485', '0_4', 'EVDEVO', 'EVDEVO', 0, ''),
(NOW(), '1', '0', 'ID05', 'Carel EVD 05', 'ca_evdevo', 'CAREL485', '0_5', 'EVDEVO', 'EVDEVO', 0, ''),
(NOW(), '1', '0', 'ID06', 'Carel EVD 06', 'ca_evdevo', 'CAREL485', '0_6', 'EVDEVO', 'EVDEVO', 0, ''),
(NOW(), '1', '0', 'ID07', 'Carel EVD 07', 'ca_evdevo', 'CAREL485', '0_7', 'EVDEVO', 'EVDEVO', 0, ''),
(NOW(), '1', '0', 'ID08', 'Carel EVD 08', 'ca_evdevo', 'CAREL485', '0_8', 'EVDEVO', 'EVDEVO', 0, ''),
(NOW(), '1', '0', 'ID09', 'Carel EVD 09', 'ca_evdevo', 'CAREL485', '0_9', 'EVDEVO', 'EVDEVO', 0, ''),
(NOW(), '1', '0', 'ID10', 'Carel EVD 10', 'ca_evdevo', 'CAREL485', '0_10', 'EVDEVO', 'EVDEVO', 0, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'baud_rate', 'CAREL485', '19200', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'CAREL485', '60', 'min.', '', ''),
(NOW(), 'com_port', 'CAREL485', '7', '', '', ''),
(NOW(), 'gateway_type', 'CAREL485', '485N', '', '', ''),
(NOW(), 'idle_event_rate', 'CAREL485', '250', 'msec', '', ''),
(NOW(), 'max_error_count', 'CAREL485', '4', '', '', ''),
(NOW(), 'max_group_count', 'CAREL485', '1', '', '', ''),
(NOW(), 'max_outstanding_packets', 'CAREL485', '-1', '', '', ''),
(NOW(), 'max_param_block_time', 'CAREL485', '2', 'hours', '', ''),
(NOW(), 'packet_timeout', 'CAREL485', '0', 'sec', '', ''),
(NOW(), 'speed_index_block', 'CAREL485', '10', '', '', ''),
(NOW(), 'speed_index_norm', 'CAREL485', '1', '', '', ''),
(NOW(), 'speed_index_offline', 'CAREL485', '10', '', '', ''),
(NOW(), 'speed_index_slow', 'CAREL485', '1', '', '', ''),
(NOW(), 'sql_queue_poll_time', 'CAREL485', '1000', 'msec', '', ''),
(NOW(), 'unblock_timer', 'CAREL485', '2 min', 'Time string', '', ''),
(NOW(), 'show_queue_info', 'CAREL485', '0', '', '', ''),
(NOW(), 'startup_delay', 'CAREL485', '15', 'Sec.', '', ''),
(NOW(), 'alarm_handler', 'CAREL485', '', '', '', ''),
(NOW(), 'count_com_ports', 'CAREL485', '1', '', '', ''),
(NOW(), 'reopen_timer', 'CAREL485', 'never', '', 'never,x min,x hour', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_carel485.exe', 'CAREL485', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'EVDEVO', 'ca_evdevo_param', 'ca_evdevo_groups');

CREATE TABLE IF NOT EXISTS `iw_par_ca_evdevo_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_ca_evdevo_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 2, '', ''),
(NOW(), 'group_alias', 1, 'conf', 'Configuration'),
(NOW(), 'group_alias', 2, 'probe', 'Probes'),
(NOW(), 'group_alias', 3, 'contr', 'Control'),
(NOW(), 'group_alias', 4, 'spc', 'Special'),
(NOW(), 'group_alias', 5, 'alconf', 'Alarm Configuration'),
(NOW(), 'group_alias', 6, 'val', 'Valve'),
(NOW(), 'group_alias', 7, 'al', 'Alarms'),
(NOW(), 'group', 1, 'conf', 'Network_address'),
(NOW(), 'group', 2, 'conf', 'Refrigerant'),
(NOW(), 'group', 3, 'conf', 'Valve'),
(NOW(), 'group', 4, 'conf', 'Sensor_S1_conf'),
(NOW(), 'group', 5, 'conf', 'Main_Control'),
(NOW(), 'group', 6, 'conf', 'Sensor_S2_conf'),
(NOW(), 'group', 7, 'conf', 'Auxillary_control'),
(NOW(), 'group', 8, 'conf', 'Sensor_S3_conf'),
(NOW(), 'group', 9, 'conf', 'Relay_Config'),
(NOW(), 'group', 10, 'conf', 'Sensor_S4_conf'),
(NOW(), 'group', 11, 'conf', 'Configuration_of_DI2'),
(NOW(), 'group', 12, 'conf', 'Variable_1_on_display'),
(NOW(), 'group', 13, 'conf', 'Variable_2_on_display'),
(NOW(), 'group', 14, 'conf', 'Sensor_S1_alarm_manag'),
(NOW(), 'group', 15, 'conf', 'Sensor_S2_alarm_manag'),
(NOW(), 'group', 16, 'conf', 'Sensor_S3_alarm_manag'),
(NOW(), 'group', 17, 'conf', 'Sensor_S4_alarm_manag'),
(NOW(), 'group', 18, 'conf', 'Unit_of_measure'),
(NOW(), 'group', 25, 'probe', 'S1_Calibration_offset'),
(NOW(), 'group', 26, 'probe', 'S1_Calibration_gain_4t20mA'),
(NOW(), 'group', 27, 'probe', 'Pressure_S1_Min_value'),
(NOW(), 'group', 28, 'probe', 'Pressure_S1_Max_value'),
(NOW(), 'group', 29, 'probe', 'Pressure_S1_Min_alarm_value'),
(NOW(), 'group', 30, 'probe', 'Pressure_S1_Max_alarm_value'),
(NOW(), 'group', 31, 'probe', 'S2_Calibration_offset'),
(NOW(), 'group', 32, 'probe', 'S2_Calibration_gain_0to10'),
(NOW(), 'group', 33, 'probe', 'Temperature_S2_Min_alarm_value'),
(NOW(), 'group', 34, 'probe', 'Temperature_S2_Max_alarm_value'),
(NOW(), 'group', 35, 'probe', 'S3_Calibration_offset'),
(NOW(), 'group', 36, 'probe', 'Pressure_S3_Min_value'),
(NOW(), 'group', 37, 'probe', 'Pressure_S3_Max_value'),
(NOW(), 'group', 38, 'probe', 'Pressure_S3_Min_alarm_value'),
(NOW(), 'group', 39, 'probe', 'Pressure_S3_Max_alarm_value'),
(NOW(), 'group', 40, 'probe', 'S4_Calibration_offset'),
(NOW(), 'group', 41, 'probe', 'Temp_S4_Min_value'),
(NOW(), 'group', 42, 'probe', 'Temp_S4_Max_value'),
(NOW(), 'group', 1, 'contr', 'Superheat_set_point'),
(NOW(), 'group', 2, 'contr', 'Valve_opening_at_start'),
(NOW(), 'group', 3, 'contr', 'Valve_open_in_standby'),
(NOW(), 'group', 4, 'contr', 'Start_delay_after_defrost'),
(NOW(), 'group', 5, 'contr', 'Hot_gas_bypass_temp_set_point'),
(NOW(), 'group', 6, 'contr', 'Hot_gas_bypass_press_set_point'),
(NOW(), 'group', 7, 'contr', 'EPR_Pressure_set_point'),
(NOW(), 'group', 8, 'contr', 'PIDproportional_gain'),
(NOW(), 'group', 9, 'contr', 'PIDIntegration_time'),
(NOW(), 'group', 10, 'contr', 'PIDderivative_time'),
(NOW(), 'group', 11, 'contr', 'LowSH_Protect_threshold'),
(NOW(), 'group', 12, 'contr', 'LowSH_Protect_Integration_time'),
(NOW(), 'group', 13, 'contr', 'LOP_Protectionthreshold'),
(NOW(), 'group', 14, 'contr', 'LOP_Protection_Integration_time'),
(NOW(), 'group', 15, 'contr', 'MOP_Protection_threshold'),
(NOW(), 'group', 16, 'contr', 'MOP_Protection_Integration_time'),
(NOW(), 'group', 17, 'contr', 'Enable_manuel_valve_positioning'),
(NOW(), 'group', 18, 'contr', 'Manual_valve_position'),
(NOW(), 'group', 1, 'spc', 'HITcondthreshold'),
(NOW(), 'group', 2, 'spc', 'HITcondIntegration_time'),
(NOW(), 'group', 3, 'spc', 'Modulating_therm_set_point'),
(NOW(), 'group', 4, 'spc', 'Modulating_therm_differential'),
(NOW(), 'group', 5, 'spc', 'Modulating_therm_sheat_set_point'),
(NOW(), 'group', 6, 'spc', 'CoefficientAfor_CO2_control'),
(NOW(), 'group', 7, 'spc', 'CoefficientBfor_CO2_control'),
(NOW(), 'group', 1, 'alconf', 'Low_superheat_alarm_delay'),
(NOW(), 'group', 2, 'alconf', 'Low_evaporation_temp_al_del'),
(NOW(), 'group', 3, 'alconf', 'High_evaporation_temp_al_del'),
(NOW(), 'group', 4, 'alconf', 'High_condensing_temp_al_del'),
(NOW(), 'group', 5, 'alconf', 'Low_suction_temperature_al_thres'),
(NOW(), 'group', 6, 'alconf', 'Low_suction_temperature_al_delay'),
(NOW(), 'group', 1, 'val', 'Minimum_EEV_Steps'),
(NOW(), 'group', 2, 'val', 'Maximum_EEV_Steps'),
(NOW(), 'group', 3, 'val', 'EEV_closing_steps'),
(NOW(), 'group', 4, 'val', 'Rated_EEV_Speed'),
(NOW(), 'group', 5, 'val', 'Rated_EEV_current'),
(NOW(), 'group', 6, 'val', 'EEV_holding_current'),
(NOW(), 'group', 7, 'val', 'EEV_duty_cycle'),
(NOW(), 'group', 8, 'val', 'Synchronise_position_in_open'),
(NOW(), 'group', 9, 'val', 'Synchronise_position_in_clos'),
(NOW(), 'group', 1, 'probe', 'Sensor_S1_reading'),
(NOW(), 'group', 2, 'probe', 'Sensor_S2_reading'),
(NOW(), 'group', 3, 'probe', 'Sensor_S3_reading'),
(NOW(), 'group', 4, 'probe', 'Sensor_S4_reading'),
(NOW(), 'group', 5, 'probe', 'Suction_temperature'),
(NOW(), 'group', 6, 'probe', 'Evaporation_temperature'),
(NOW(), 'group', 7, 'probe', 'Evaporation_pressure'),
(NOW(), 'group', 8, 'probe', 'Hot_gas_bypass_temp'),
(NOW(), 'group', 9, 'probe', 'EPR_Pressure_set_point_back'),
(NOW(), 'group', 10, 'probe', 'Superheat'),
(NOW(), 'group', 11, 'probe', 'Condensing_pressure'),
(NOW(), 'group', 12, 'probe', 'Condensing_temperature'),
(NOW(), 'group', 13, 'probe', 'Modulating_thermostat_temp'),
(NOW(), 'group', 14, 'probe', 'Hot_gas_bypass_pressure'),
(NOW(), 'group', 15, 'probe', 'CO2_gas_cooler_outlet_press'),
(NOW(), 'group', 16, 'probe', 'CO2_gas_cooler_outlet_temp'),
(NOW(), 'group', 17, 'probe', 'Valve_opening'),
(NOW(), 'group', 18, 'probe', 'CO2_gas_cooler_pressure_set'),
(NOW(), 'group', 19, 'probe', '4_to_20_mA_input_valve'),
(NOW(), 'group', 20, 'probe', '0_to_10V_input_valve'),
(NOW(), 'group', 21, 'probe', 'Control_set_point'),
(NOW(), 'group', 22, 'probe', 'Driver_firmware_version'),
(NOW(), 'group', 23, 'probe', 'Valve_position'),
(NOW(), 'group', 24, 'probe', 'Current_unit_cooling_capacity'),
(NOW(), 'group', 1, 'al', 'Low_suction_temperature'),
(NOW(), 'group', 2, 'al', 'LAN_error'),
(NOW(), 'group', 3, 'al', 'EEPROM_damaged'),
(NOW(), 'group', 4, 'al', 'Sensor_S1'),
(NOW(), 'group', 5, 'al', 'Sensor_S2'),
(NOW(), 'group', 6, 'al', 'Sensor_S3'),
(NOW(), 'group', 7, 'al', 'Sensor_S4'),
(NOW(), 'group', 8, 'al', 'EEV_motor_error'),
(NOW(), 'group', 9, 'al', 'Relay_status'),
(NOW(), 'group', 10, 'al', 'LOP'),
(NOW(), 'group', 11, 'al', 'MOP'),
(NOW(), 'group', 12, 'al', 'LOWSH'),
(NOW(), 'group', 13, 'al', 'HITcond'),
(NOW(), 'group', 1, 'spc', 'Status_of_digital_input_DI1'),
(NOW(), 'group', 2, 'spc', 'Status_of_digital_input_DI2'),
(NOW(), 'group', 3, 'spc', 'Enable_EVD_control');

CREATE TABLE IF NOT EXISTS `iw_par_ca_evdevo_param` (
  `row_date` datetime NOT NULL DEFAULT '2002-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_ca_evdevo_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'Network_address', '0_I_11', 'Network address', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Refrigerant', '0_I_13', 'Refrigerant', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Valve', '0_I_14', 'Valve', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S1_conf', '0_I_16', 'Sensor S1 Config', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Main_Control', '0_I_15', 'Main Control', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S2_conf', '0_I_17', 'Sensor S2 Config', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Auxillary_control', '0_I_18', 'Auxillary control', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S3_conf', '0_I_19', 'Sensor S3 Config', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Relay_Config', '0_I_12', 'Relay Configuration', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S4_conf', '0_I_20', 'Sensor S4 Config', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Configuration_of_DI2', '0_I_10', 'Configuration of DI2', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Variable_1_on_display', '0_I_45', 'Variable 1 on display', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Variable_2_on_display', '0_I_46', 'Variable 2 on display', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S1_alarm_manag', '0_I_24', 'Sensor S1 alarm management', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S2_alarm_manag', '0_I_25', 'Sensor S2 alarm management', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S3_alarm_manag', '0_I_26', 'Sensor S3 alarm management', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S4_alarm_manag', '0_I_27', 'Sensor S4 alarm management', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Unit_of_measure', '0_I_21', 'Unit of measure', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'S1_Calibration_offset', '0_A_34', 'S1 Calibration offset', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-60', '60', '', '', '', '', '', '', ''),
(NOW(), 'S1_Calibration_gain_4t20mA', '0_A_36', 'S1 Calibration gain, 4 to 20 mA', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-20', '20', '', '', '', '', '', '', ''),
(NOW(), 'Pressure_S1_Min_value', '0_A_32', 'Pressure S1 Minimum value', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-20', '9,3', '', '', '', '', '', '', ''),
(NOW(), 'Pressure_S1_Max_value', '0_A_30', 'Pressure S1 Maximum value', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-1', '200', '', '', '', '', '', '', ''),
(NOW(), 'Pressure_S1_Min_alarm_value', '0_A_39', 'Pressure S1 Minimum alarm value', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-20', '9,3', '', '', '', '', '', '', ''),
(NOW(), 'Pressure_S1_Max_alarm_value', '0_A_37', 'Pressure S1 Maximum alarm value', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-1', '200', '', '', '', '', '', '', ''),
(NOW(), 'S2_Calibration_offset', '0_A_41', 'S2 Calibration offset', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-20', '20', '', '', '', '', '', '', ''),
(NOW(), 'S2_Calibration_gain_0to10', '0_A_43', 'S2 Calibration gain, 0 to 10 V', '', 'Analog Values', 'float', '', '-1', 'rw', '', '', '-20', '20', '', '', '', '', '', '', ''),
(NOW(), 'Temperature_S2_Min_alarm_value', '0_A_46', 'Temperature S2 Minimum alarm value', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-60', '105', '', '', '', '', '', '', ''),
(NOW(), 'Temperature_S2_Max_alarm_value', '0_A_44', 'Temperature S2 Maximum alarm value', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '', '', '', '', '', '', ''),
(NOW(), 'S3_Calibration_offset', '0_A_35', 'S3 Calibration offset', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-60', '60', '', '', '', '', '', '', ''),
(NOW(), 'Pressure_S3_Min_value', '0_A_33', 'Pressure S3 Minimum value', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-20', '9,3', '', '', '', '', '', '', ''),
(NOW(), 'Pressure_S3_Max_value', '0_A_31', 'Pressure S3 Maximum value', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-1', '200', '', '', '', '', '', '', ''),
(NOW(), 'Pressure_S3_Min_alarm_value', '0_A_40', 'Pressure S3 Minimum alarm value', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-20', '9,3', '', '', '', '', '', '', ''),
(NOW(), 'Pressure_S3_Max_alarm_value', '0_A_38', 'Pressure S3 Maximum alarm value', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-1', '200', '', '', '', '', '', '', ''),
(NOW(), 'S4_Calibration_offset', '0_A_42', 'S4 Calibration offset', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-20', '20', '', '', '', '', '', '', ''),
(NOW(), 'Temp_S4_Min_value', '0_A_47', 'Temperature S4 Minimum value', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-60', '105', '', '', '', '', '', '', ''),
(NOW(), 'Temp_S4_Max_value', '0_A_45', 'Temperature S4 Maximum value', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '', '', '', '', '', '', ''),
(NOW(), 'Superheat_set_point', '0_A_50', 'Superheat set point', '', 'Analog Values', 'float', '', '-1', 'rw', 'K', '', '5', '180', '', '', '', '', '', '', ''),
(NOW(), 'Valve_opening_at_start', '0_I_37', 'Valve opening at start', '', 'Integral Values', 'integer', '', '-1', 'rw', '&#037', '%.1f', '0', '100', '', '', '', '', '', '', ''),
(NOW(), 'Valve_open_in_standby', '0_D_23', 'Valve open in standby', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Start_delay_after_defrost', '0_I_40', 'Start delay after defrost', '', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '0', '60', '', '', '', '', '', '', ''),
(NOW(), 'Hot_gas_bypass_temp_set_point', '0_A_28', 'Hot gas bypass temperature set point', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Hot_gas_bypass_press_set_point', '0_A_62', 'Hot gas bypass pressure set point', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-20', '200', '', '', '', '', '', '', ''),
(NOW(), 'EPR_Pressure_set_point', '0_A_29', 'EPR Pressure set point', '', 'Analog Values', 'float', '', '-1', 'rw', 'barg', '%.1f', '-20', '200', '', '', '', '', '', '', ''),
(NOW(), 'PIDproportional_gain', '0_A_48', 'PID:proportional gain', '', 'Analog Values', 'float', '', '-1', 'rw', '', '', '0', '800', '', '', '', '', '', '', ''),
(NOW(), 'PIDIntegration_time', '0_I_38', 'PID:Integration time', '', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '0', '1000', '', '', '', '', '', '', ''),
(NOW(), 'PIDderivative_time', '0_A_49', 'PID:derivative time', '', 'Analog Values', 'float', '', '-1', 'rw', 's', '', '0', '800', '', '', '', '', '', '', ''),
(NOW(), 'LowSH_Protect_threshold', '0_A_56', 'LowSH Protection:threshold', '', 'Analog Values', 'float', '', '-1', 'rw', 'K', '', '-40', '11', '', '', '', '', '', '', ''),
(NOW(), 'LowSH_Protect_Integration_time', '0_A_55', 'LowSH Protection: Integration time', '', 'Analog Values', 'float', '', '-1', 'rw', 's', '', '0', '800', '', '', '', '', '', '', ''),
(NOW(), 'LOP_Protectionthreshold', '0_A_52', 'LOP Protection:threshold', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-60', '50', '', '', '', '', '', '', ''),
(NOW(), 'LOP_Protection_Integration_time', '0_A_51', 'LOP Protection: Integration time', '', 'Analog Values', 'float', '', '-1', 'rw', 's', '', '0', '800', '', '', '', '', '', '', ''),
(NOW(), 'MOP_Protection_threshold', '0_A_54', 'MOP Protection: threshold', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '', '', '', '', '', '', ''),
(NOW(), 'MOP_Protection_Integration_time', '0_A_53', 'MOP Protection: Integration time', '', 'Analog Values', 'float', '', '-1', 'rw', 's', '', '0', '800', '', '', '', '', '', '', ''),
(NOW(), 'Enable_manuel_valve_positioning', '0_D_24', 'Enable manuel valve positioning', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Manual_valve_position', '0_I_39', 'Manual valve position', '', 'Integral Values', 'integer', '', '-1', 'rw', 'step', '', '0', '9999', '', '', '', '', '', '', ''),
(NOW(), 'HITcondthreshold', '0_A_58', 'HITcond:threshold', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'HITcondIntegration_time', '0_A_57', 'HITcond:Integration time', '', 'Analog Values', 'float', '', '-1', 'rw', 's', '%.1f', '0', '800', '', '', '', '', '', '', ''),
(NOW(), 'Modulating_therm_set_point', '0_A_61', 'Modulating thermostat: set point', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Modulating_therm_differential', '0_A_60', 'Modulating thermostat: differential', '', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '0,1', '100', '', '', '', '', '', '', ''),
(NOW(), 'Modulating_therm_sheat_set_point', '0_A_59', 'Modulating thermostat: superheat set point offset', '', 'Analog Values', 'float', '', '-1', 'rw', 'K', '', '0', '100', '', '', '', '', '', '', ''),
(NOW(), 'CoefficientAfor_CO2_control', '0_A_63', 'Coefficient''A''for CO2 control', '', 'Analog Values', 'float', '', '-1', 'rw', '', '', '-100', '800', '', '', '', '', '', '', ''),
(NOW(), 'CoefficientBfor_CO2_control', '0_A_64', 'Coefficient''B''for CO2 control', '', 'Analog Values', 'float', '', '-1', 'rw', '', '', '-100', '800', '', '', '', '', '', '', ''),
(NOW(), 'Low_superheat_alarm_delay', '0_I_43', 'Low superheat alarm delay(LowSH)', '', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '0', '18000', '', '', '', '', '', '', ''),
(NOW(), 'Low_evaporation_temp_al_del', '0_I_41', 'Low evaporation temperature alarm delay(LOP)', '', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '0', '18000', '', '', '', '', '', '', ''),
(NOW(), 'High_evaporation_temp_al_del', '0_I_42', 'High evaporation temperature alarm delay(MOP)', '', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '0', '18000', '', '', '', '', '', '', ''),
(NOW(), 'High_condensing_temp_al_del', '0_I_44', 'High condensing temperature alarm delay (HITcond)', '', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '0', '18000', '', '', '', '', '', '', ''),
(NOW(), 'Low_suction_temperature_al_thres', '0_I_26', 'Low suction temperature alarm threshold', '', 'Integral Values', 'integer', '', '-1', 'rw', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Low_suction_temperature_al_delay', '0_I_9', 'Low suction temperature alarm delay 0=alarm disabled', '', 'Integral Values', 'integer', '', '-1', 'rw', 's', '', '0', '18000', '', '', '', '', '', '', ''),
(NOW(), 'Minimum_EEV_Steps', '0_I_30', 'Minimum EEV Steps', '', 'Integral Values', 'integer', '', '-1', 'r', 'step', '', '0', '9999', '', '', '', '', '', '', ''),
(NOW(), 'Maximum_EEV_Steps', '0_I_31', 'Maximum EEV Steps', '', 'Integral Values', 'integer', '', '-1', 'r', 'step', '', '0', '9999', '', '', '', '', '', '', ''),
(NOW(), 'EEV_closing_steps', '0_I_36', 'EEV closing steps', '', 'Integral Values', 'integer', '', '-1', 'r', 'step', '', '0', '9999', '', '', '', '', '', '', ''),
(NOW(), 'Rated_EEV_Speed', '0_I_32', 'Rated EEV Speed ', '', 'Integral Values', 'integer', '', '-1', 'r', 'step/s', '', '1', '2000', '', '', '', '', '', '', ''),
(NOW(), 'Rated_EEV_current', '0_I_33', 'Rated EEV current', '', 'Integral Values', 'integer', '', '-1', 'r', 'mA', '', '0', '800', '', '', '', '', '', '', ''),
(NOW(), 'EEV_holding_current', '0_I_35', 'EEV holding current', '', 'Integral Values', 'integer', '', '-1', 'r', 'mA', '', '0', '800', '', '', '', '', '', '', ''),
(NOW(), 'EEV_duty_cycle', '0_I_34', 'EEV duty cycle', '', 'Integral Values', 'integer', '', '-1', 'r', '&#037', '%.1f', '1', '100', '', '', '', '', '', '', ''),
(NOW(), 'Synchronise_position_in_open', '0_D_20', 'Synchronise position in opening', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Synchronise_position_in_clos', '0_D_21', 'Synchronise position in closing', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S1_reading', '0_A_1', 'Sensor S1 reading', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-20', '200', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S2_reading', '0_A_2', 'Sensor S2 reading', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S3_reading', '0_A_3', 'Sensor S3 reading', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-20', '200', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S4_reading', '0_A_4', 'Sensor S4 reading', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Suction_temperature', '0_A_5', 'Suction temperature', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Evaporation_temperature', '0_A_6', 'Evaporation temperature', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Evaporation_pressure', '0_A_7', 'Evaporation pressure', '', 'Analog Values', 'float', '', '-1', 'r', 'barg', '%.1f', '-20', '200', '', '', '', '', '', '', ''),
(NOW(), 'Hot_gas_bypass_temp', '0_A_8', 'Hot gas bypass temperature', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'EPR_Pressure_set_point_back', '0_A_9', 'EPR Pressure set point (back pressure)', '', 'Analog Values', 'float', '', '-1', 'r', 'barg', '%.1f', '-20', '200', '', '', '', '', '', '', ''),
(NOW(), 'Superheat', '0_A_10', 'Superheat', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-40', '180', '', '', '', '', '', '', ''),
(NOW(), 'Condensing_pressure', '0_A_11', 'Condensing pressure', '', 'Analog Values', 'float', '', '-1', 'r', 'barg', '%.1f', '-20', '200', '', '', '', '', '', '', ''),
(NOW(), 'Condensing_temperature', '0_A_12', 'Condensing temperature ', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Modulating_thermostat_temp', '0_A_13', 'Modulating thermostat temperature', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Hot_gas_bypass_pressure', '0_A_14', 'Hot gas bypass pressure', '', 'Analog Values', 'float', '', '-1', 'r', 'barg', '%.1f', '-20', '200', '', '', '', '', '', '', ''),
(NOW(), 'CO2_gas_cooler_outlet_press', '0_A_15', 'CO2 gas cooler outlet pressure', '', 'Analog Values', 'float', '', '-1', 'r', 'barg', '%.1f', '-20', '200', '', '', '', '', '', '', ''),
(NOW(), 'CO2_gas_cooler_outlet_temp', '0_A_16', 'CO2 gas cooler outlet temperature', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Valve_opening', '0_A_17', 'Valve opening', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '0', '100', '', '', '', '', '', '', ''),
(NOW(), 'CO2_gas_cooler_pressure_set', '0_A_18', 'CO2 gas cooler pressure set point', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-20', '200', '', '', '', '', '', '', ''),
(NOW(), '4_to_20_mA_input_valve', '0_A_19', '4 to 20 mA input valve', '', 'Analog Values', 'float', '', '-1', 'r', '', '', '4', '20', '', '', '', '', '', '', ''),
(NOW(), '0_to_10V_input_valve', '0_A_20', '0 to 10V input valve', '', 'Analog Values', 'float', '', '-1', 'r', '', '%.1f', '0', '10', '', '', '', '', '', '', ''),
(NOW(), 'Control_set_point', '0_A_21', 'Control set point', '', 'Analog Values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '-60', '200', '', '', '', '', '', '', ''),
(NOW(), 'Driver_firmware_version', '0_A_25', 'Driver firmware version', '', 'Analog Values', 'float', '', '-1', 'r', '', '', '0', '10', '', '', '', '', '', '', ''),
(NOW(), 'Valve_position', '0_I_4', 'Valve position', '', 'Integral Values', 'integer', '', '-1', 'r', '', '', '0', '9999', '', '', '', '', '', '', ''),
(NOW(), 'Current_unit_cooling_capacity', '0_I_7', 'Current unit cooling capacity', '', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '0', '100', '', '', '', '', '', '', ''),
(NOW(), 'Low_suction_temperature', '0_D_1', 'Low suction temperature', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'LAN_error', '0_D_2', 'LAN error', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'EEPROM_damaged', '0_D_3', 'EEPROM damaged', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S1', '0_D_4', 'Sensor S1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S2', '0_D_5', 'Sensor S2', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S3', '0_D_6', 'Sensor S3', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Sensor_S4', '0_D_7', 'Sensor S4', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'EEV_motor_error', '0_D_8', 'EEV motor error', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Relay_status', '0_D_9', 'Relay status', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'LOP', '0_D_10', 'Low evaporation temperature', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'MOP', '0_D_11', 'High evaporation temperature', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'LOWSH', '0_D_12', 'Low superheat', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'HITcond', '0_D_13', 'High condensing temperature', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Status_of_digital_input_DI1', '0_D_14', 'Status of digital input DI1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Status_of_digital_input_DI2', '0_D_15', 'Status of digital input DI2', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'Enable_EVD_control', '0_D_22', 'Enable EVD control', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '', '');

CREATE TABLE IF NOT EXISTS `iw_set_ca_evdevo` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_ca_evdevo` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'Network_address', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Refrigerant', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Valve', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Sensor_S1_conf', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Main_Control', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Sensor_S2_conf', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Auxillary_control', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Sensor_S3_conf', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Relay_Config', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Sensor_S4_conf', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Configuration_of_DI2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Variable_1_on_display', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Variable_2_on_display', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Sensor_S1_alarm_manag', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Sensor_S2_alarm_manag', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Sensor_S3_alarm_manag', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Sensor_S4_alarm_manag', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Unit_of_measure', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S1_Calibration_offset', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S1_Calibration_gain_4t20mA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Pressure_S1_Min_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Pressure_S1_Max_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Pressure_S1_Min_alarm_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Pressure_S1_Max_alarm_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S2_Calibration_offset', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S2_Calibration_gain_0to10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Temperature_S2_Min_alarm_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Temperature_S2_Max_alarm_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S3_Calibration_offset', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Pressure_S3_Min_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Pressure_S3_Max_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Pressure_S3_Min_alarm_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Pressure_S3_Max_alarm_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S4_Calibration_offset', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Temp_S4_Min_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Temp_S4_Max_value', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Superheat_set_point', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Valve_opening_at_start', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Valve_open_in_standby', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Start_delay_after_defrost', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Hot_gas_bypass_temp_set_point', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Hot_gas_bypass_press_set_point', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'EPR_Pressure_set_point', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'PIDproportional_gain', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'PIDIntegration_time', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'PIDderivative_time', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'LowSH_Protect_threshold', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'LowSH_Protect_Integration_time', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'LOP_Protectionthreshold', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'LOP_Protection_Integration_time', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'MOP_Protection_threshold', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'MOP_Protection_Integration_time', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Enable_manuel_valve_positioning', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Manual_valve_position', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HITcondthreshold', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HITcondIntegration_time', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Modulating_therm_set_point', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Modulating_therm_differential', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Modulating_therm_sheat_set_point', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CoefficientAfor_CO2_control', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CoefficientBfor_CO2_control', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Low_superheat_alarm_delay', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Low_evaporation_temp_al_del', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'High_evaporation_temp_al_del', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'High_condensing_temp_al_del', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Low_suction_temperature_al_thres', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Low_suction_temperature_al_delay', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Minimum_EEV_Steps', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Maximum_EEV_Steps', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'EEV_closing_steps', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Rated_EEV_Speed', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Rated_EEV_current', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'EEV_holding_current', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'EEV_duty_cycle', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Synchronise_position_in_open', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Synchronise_position_in_clos', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Sensor_S1_reading', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Sensor_S2_reading', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Sensor_S3_reading', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Sensor_S4_reading', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Suction_temperature', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Evaporation_temperature', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Evaporation_pressure', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Hot_gas_bypass_temp', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'EPR_Pressure_set_point_back', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Superheat', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Condensing_pressure', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Condensing_temperature', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Modulating_thermostat_temp', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Hot_gas_bypass_pressure', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CO2_gas_cooler_outlet_press', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'CO2_gas_cooler_outlet_temp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'Valve_opening', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CO2_gas_cooler_pressure_set', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), '4_to_20_mA_input_valve', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), '0_to_10V_input_valve', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Control_set_point', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Driver_firmware_version', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Valve_position', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Current_unit_cooling_capacity', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Low_suction_temperature', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'LAN_error', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'EEPROM_damaged', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Sensor_S1', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Sensor_S2', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Sensor_S3', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Sensor_S4', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'EEV_motor_error', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Relay_status', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'LOP', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'MOP', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'LOWSH', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'HITcond', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'Status_of_digital_input_DI1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Status_of_digital_input_DI2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'Enable_EVD_control', '1', '0', 'slow', 'change', '', '', '', 0);



-- Changelog
--
-- v1 Orginal
--
--