REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'ID01', 'Microchiller 1', 'ca_microchiller_2SE', 'CAREL485', '0_1', 'MS2SE', 'MS2SE', 0, ''),
(NOW(), '1', '0', 'ID02', 'Microchiller 2', 'ca_microchiller_2SE', 'CAREL485', '0_2', 'MS2SE', 'MS2SE', 0, ''),
(NOW(), '1', '0', 'ID03', 'Microchiller 3', 'ca_microchiller_2SE', 'CAREL485', '0_3', 'MS2SE', 'MS2SE', 0, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'com_port', 'CAREL485', '1', '', '', ''),
(NOW(), 'baud_rate', 'CAREL485', '19200', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'CAREL485', '60', 'min.', '', ''),
(NOW(), 'gateway_type', 'CAREL485', '485N', '', '', ''),
(NOW(), 'idle_event_rate', 'CAREL485', '250', 'msec', '', ''),
(NOW(), 'max_error_count', 'CAREL485', '4', '', '', ''),
(NOW(), 'max_group_count', 'CAREL485', '1', '', '', ''),
(NOW(), 'max_outstanding_packets', 'CAREL485', '-1', '', '', ''),
(NOW(), 'max_param_block_time', 'CAREL485', '2', 'hours', '', ''),
(NOW(), 'packet_timeout', 'CAREL485', '0', 'sec', '', ''),
(NOW(), 'speed_index_block', 'CAREL485', '10', '', '', ''),
(NOW(), 'speed_index_norm', 'CAREL485', '1', '', '', ''),
(NOW(), 'speed_index_offline', 'CAREL485', '10', '', '', ''),
(NOW(), 'speed_index_slow', 'CAREL485', '1', '', '', ''),
(NOW(), 'sql_queue_poll_time', 'CAREL485', '1000', 'msec', '', ''),
(NOW(), 'unblock_timer', 'CAREL485', '2 min', 'Time string', '', ''),
(NOW(), 'show_queue_info', 'CAREL485', '0', '', '', ''),
(NOW(), 'startup_delay', 'CAREL485', '15', 'Sec.', '', ''),
(NOW(), 'alarm_handler', 'CAREL485', '', '', '', ''),
(NOW(), 'reopen_timer', 'CAREL485', 'never', '', 'never,x min,x hour', ''),
(NOW(), 'count_com_ports', 'CAREL485', '1', '', '', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_carel485.exe', 'CAREL485', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'MS2SE', 'iw_set_ca_microchiller_2SE_param', 'ca_microchiller_2SE_groups');

CREATE TABLE IF NOT EXISTS `iw_par_ca_microchiller_2SE_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_ca_microchiller_2SE_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'ana', 'Analog Values'),
(NOW(), 'group_alias', 2, 'dig', 'Digital Values'),
(NOW(), 'group_alias', 3, 'int', 'Integer Values'),
(NOW(), 'group', 1, 'ana', 'ana_0_A_1'),
(NOW(), 'group', 2, 'ana', 'ana_0_A_2'),
(NOW(), 'group', 3, 'ana', 'ana_0_A_3'),
(NOW(), 'group', 4, 'ana', 'ana_0_A_4'),
(NOW(), 'group', 5, 'ana', 'ana_0_A_5'),
(NOW(), 'group', 6, 'ana', 'ana_0_A_6'),
(NOW(), 'group', 7, 'ana', 'ana_0_A_7'),
(NOW(), 'group', 8, 'ana', 'ana_0_A_8'),
(NOW(), 'group', 9, 'ana', 'ana_0_A_9'),
(NOW(), 'group', 10, 'ana', 'ana_0_A_10'),
(NOW(), 'group', 11, 'ana', 'ana_0_A_11'),
(NOW(), 'group', 12, 'ana', 'ana_0_A_12'),
(NOW(), 'group', 13, 'ana', 'ana_0_A_13'),
(NOW(), 'group', 14, 'ana', 'ana_0_A_14'),
(NOW(), 'group', 15, 'ana', 'ana_0_A_15'),
(NOW(), 'group', 16, 'ana', 'ana_0_A_16'),
(NOW(), 'group', 17, 'ana', 'ana_0_A_17'),
(NOW(), 'group', 18, 'ana', 'ana_0_A_18'),
(NOW(), 'group', 19, 'ana', 'ana_0_A_19'),
(NOW(), 'group', 20, 'ana', 'ana_0_A_20'),
(NOW(), 'group', 21, 'ana', 'ana_0_A_21'),
(NOW(), 'group', 22, 'ana', 'ana_0_A_22'),
(NOW(), 'group', 23, 'ana', 'ana_0_A_23'),
(NOW(), 'group', 24, 'ana', 'ana_0_A_24'),
(NOW(), 'group', 25, 'ana', 'ana_0_A_25'),
(NOW(), 'group', 26, 'ana', 'ana_0_A_26'),
(NOW(), 'group', 27, 'ana', 'ana_0_A_27'),
(NOW(), 'group', 28, 'ana', 'ana_0_A_28'),
(NOW(), 'group', 29, 'ana', 'ana_0_A_29'),
(NOW(), 'group', 30, 'ana', 'ana_0_A_30'),
(NOW(), 'group', 31, 'ana', 'ana_0_A_31'),
(NOW(), 'group', 32, 'ana', 'ana_0_A_32'),
(NOW(), 'group', 33, 'ana', 'ana_0_A_33'),
(NOW(), 'group', 34, 'ana', 'ana_0_A_34'),
(NOW(), 'group', 35, 'ana', 'ana_0_A_35'),
(NOW(), 'group', 36, 'ana', 'ana_0_A_36'),
(NOW(), 'group', 37, 'ana', 'ana_0_A_37'),
(NOW(), 'group', 38, 'ana', 'ana_0_A_38'),
(NOW(), 'group', 39, 'ana', 'ana_0_A_39'),
(NOW(), 'group', 40, 'ana', 'ana_0_A_40'),
(NOW(), 'group', 41, 'ana', 'ana_0_A_41'),
(NOW(), 'group', 42, 'ana', 'ana_0_A_42'),
(NOW(), 'group', 43, 'ana', 'ana_0_A_43'),
(NOW(), 'group', 44, 'ana', 'ana_0_A_44'),
(NOW(), 'group', 45, 'ana', 'ana_0_A_45'),
(NOW(), 'group', 46, 'ana', 'ana_0_A_46'),
(NOW(), 'group', 47, 'ana', 'ana_0_A_47'),
(NOW(), 'group', 48, 'ana', 'ana_0_A_48'),
(NOW(), 'group', 49, 'ana', 'ana_0_A_49'),
(NOW(), 'group', 50, 'ana', 'ana_0_A_50'),
(NOW(), 'group', 51, 'ana', 'ana_0_A_51'),
(NOW(), 'group', 52, 'ana', 'ana_0_A_52'),
(NOW(), 'group', 53, 'ana', 'ana_0_A_53'),
(NOW(), 'group', 54, 'ana', 'ana_0_A_54'),
(NOW(), 'group', 55, 'ana', 'ana_0_A_55'),
(NOW(), 'group', 56, 'ana', 'ana_0_A_56'),
(NOW(), 'group', 57, 'ana', 'ana_0_A_57'),
(NOW(), 'group', 58, 'ana', 'ana_0_A_58'),
(NOW(), 'group', 59, 'ana', 'ana_0_A_59'),
(NOW(), 'group', 60, 'ana', 'ana_0_A_60'),
(NOW(), 'group', 61, 'ana', 'ana_0_A_61'),
(NOW(), 'group', 62, 'ana', 'ana_0_A_62'),
(NOW(), 'group', 63, 'ana', 'ana_0_A_63'),
(NOW(), 'group', 64, 'ana', 'ana_0_A_64'),
(NOW(), 'group', 65, 'ana', 'ana_0_A_65'),
(NOW(), 'group', 66, 'ana', 'ana_0_A_66'),
(NOW(), 'group', 67, 'ana', 'ana_0_A_67'),
(NOW(), 'group', 68, 'ana', 'ana_0_A_68'),
(NOW(), 'group', 69, 'ana', 'ana_0_A_69'),
(NOW(), 'group', 70, 'ana', 'ana_0_A_70'),
(NOW(), 'group', 71, 'ana', 'ana_0_A_71'),
(NOW(), 'group', 72, 'ana', 'ana_0_A_72'),
(NOW(), 'group', 73, 'ana', 'ana_0_A_73'),
(NOW(), 'group', 74, 'ana', 'ana_0_A_74'),
(NOW(), 'group', 75, 'ana', 'ana_0_A_75'),
(NOW(), 'group', 76, 'ana', 'ana_0_A_76'),
(NOW(), 'group', 77, 'ana', 'ana_0_A_77'),
(NOW(), 'group', 78, 'ana', 'ana_0_A_78'),
(NOW(), 'group', 79, 'ana', 'ana_0_A_79'),
(NOW(), 'group', 80, 'ana', 'ana_0_A_80'),
(NOW(), 'group', 81, 'ana', 'ana_0_A_81'),
(NOW(), 'group', 82, 'ana', 'ana_0_A_82'),
(NOW(), 'group', 83, 'ana', 'ana_0_A_83'),
(NOW(), 'group', 84, 'ana', 'ana_0_A_97'),
(NOW(), 'group', 85, 'ana', 'ana_0_A_98'),
(NOW(), 'group', 86, 'ana', 'ana_0_A_99'),
(NOW(), 'group', 87, 'ana', 'ana_0_A_100'),
(NOW(), 'group', 88, 'ana', 'ana_0_A_101'),
(NOW(), 'group', 89, 'ana', 'ana_0_A_102'),
(NOW(), 'group', 90, 'ana', 'ana_0_A_103'),
(NOW(), 'group', 91, 'ana', 'ana_0_A_104'),
(NOW(), 'group', 92, 'ana', 'ana_0_A_105'),
(NOW(), 'group', 93, 'ana', 'ana_0_A_106'),
(NOW(), 'group', 94, 'ana', 'ana_0_A_107'),
(NOW(), 'group', 95, 'ana', 'ana_0_A_108'),
(NOW(), 'group', 96, 'ana', 'ana_0_A_109'),
(NOW(), 'group', 97, 'ana', 'ana_0_A_110'),
(NOW(), 'group', 98, 'ana', 'ana_0_A_111'),
(NOW(), 'group', 99, 'ana', 'ana_0_A_112'),
(NOW(), 'group', 100, 'ana', 'ana_0_A_113'),
(NOW(), 'group', 101, 'ana', 'ana_0_A_114'),
(NOW(), 'group', 102, 'ana', 'ana_0_A_115'),
(NOW(), 'group', 103, 'ana', 'ana_0_A_116'),
(NOW(), 'group', 104, 'ana', 'ana_0_A_117'),
(NOW(), 'group', 105, 'ana', 'ana_0_A_118'),
(NOW(), 'group', 106, 'ana', 'ana_0_A_119'),
(NOW(), 'group', 107, 'ana', 'ana_0_A_120'),
(NOW(), 'group', 108, 'ana', 'ana_0_A_121'),
(NOW(), 'group', 109, 'ana', 'ana_0_A_122'),
(NOW(), 'group', 110, 'ana', 'ana_0_A_123'),
(NOW(), 'group', 111, 'ana', 'ana_0_A_124'),
(NOW(), 'group', 112, 'ana', 'ana_0_A_125'),
(NOW(), 'group', 113, 'ana', 'ana_0_A_126'),
(NOW(), 'group', 114, 'ana', 'ana_0_A_127'),
(NOW(), 'group', 115, 'ana', 'ana_0_A_128'),
(NOW(), 'group', 1, 'dig', 'dig_0_D_1'),
(NOW(), 'group', 2, 'dig', 'dig_0_D_2'),
(NOW(), 'group', 3, 'dig', 'dig_0_D_3'),
(NOW(), 'group', 4, 'dig', 'dig_0_D_4'),
(NOW(), 'group', 5, 'dig', 'dig_0_D_5'),
(NOW(), 'group', 6, 'dig', 'dig_0_D_6'),
(NOW(), 'group', 7, 'dig', 'dig_0_D_7'),
(NOW(), 'group', 8, 'dig', 'dig_0_D_8'),
(NOW(), 'group', 9, 'dig', 'dig_0_D_9'),
(NOW(), 'group', 10, 'dig', 'dig_0_D_10'),
(NOW(), 'group', 11, 'dig', 'dig_0_D_11'),
(NOW(), 'group', 12, 'dig', 'dig_0_D_12'),
(NOW(), 'group', 13, 'dig', 'dig_0_D_13'),
(NOW(), 'group', 14, 'dig', 'dig_0_D_14'),
(NOW(), 'group', 15, 'dig', 'dig_0_D_15'),
(NOW(), 'group', 16, 'dig', 'dig_0_D_16'),
(NOW(), 'group', 17, 'dig', 'dig_0_D_17'),
(NOW(), 'group', 18, 'dig', 'dig_0_D_18'),
(NOW(), 'group', 19, 'dig', 'dig_0_D_19'),
(NOW(), 'group', 20, 'dig', 'dig_0_D_20'),
(NOW(), 'group', 21, 'dig', 'dig_0_D_21'),
(NOW(), 'group', 22, 'dig', 'dig_0_D_22'),
(NOW(), 'group', 23, 'dig', 'dig_0_D_23'),
(NOW(), 'group', 24, 'dig', 'dig_0_D_24'),
(NOW(), 'group', 25, 'dig', 'dig_0_D_41'),
(NOW(), 'group', 26, 'dig', 'dig_0_D_42'),
(NOW(), 'group', 27, 'dig', 'dig_0_D_43'),
(NOW(), 'group', 28, 'dig', 'dig_0_D_44'),
(NOW(), 'group', 29, 'dig', 'dig_0_D_45'),
(NOW(), 'group', 30, 'dig', 'dig_0_D_46'),
(NOW(), 'group', 31, 'dig', 'dig_0_D_47'),
(NOW(), 'group', 32, 'dig', 'dig_0_D_48'),
(NOW(), 'group', 33, 'dig', 'dig_0_D_49'),
(NOW(), 'group', 34, 'dig', 'dig_0_D_50'),
(NOW(), 'group', 35, 'dig', 'dig_0_D_51'),
(NOW(), 'group', 36, 'dig', 'dig_0_D_52'),
(NOW(), 'group', 37, 'dig', 'dig_0_D_53'),
(NOW(), 'group', 38, 'dig', 'dig_0_D_54'),
(NOW(), 'group', 39, 'dig', 'dig_0_D_55'),
(NOW(), 'group', 40, 'dig', 'dig_0_D_56'),
(NOW(), 'group', 41, 'dig', 'dig_0_D_57'),
(NOW(), 'group', 42, 'dig', 'dig_0_D_58'),
(NOW(), 'group', 43, 'dig', 'dig_0_D_59'),
(NOW(), 'group', 44, 'dig', 'dig_0_D_60'),
(NOW(), 'group', 45, 'dig', 'dig_0_D_61'),
(NOW(), 'group', 46, 'dig', 'dig_0_D_62'),
(NOW(), 'group', 47, 'dig', 'dig_0_D_63'),
(NOW(), 'group', 48, 'dig', 'dig_0_D_64'),
(NOW(), 'group', 49, 'dig', 'dig_0_D_65'),
(NOW(), 'group', 50, 'dig', 'dig_0_D_66'),
(NOW(), 'group', 51, 'dig', 'dig_0_D_67'),
(NOW(), 'group', 52, 'dig', 'dig_0_D_68'),
(NOW(), 'group', 53, 'dig', 'dig_0_D_69'),
(NOW(), 'group', 54, 'dig', 'dig_0_D_70'),
(NOW(), 'group', 55, 'dig', 'dig_0_D_71'),
(NOW(), 'group', 56, 'dig', 'dig_0_D_72'),
(NOW(), 'group', 57, 'dig', 'dig_0_D_73'),
(NOW(), 'group', 58, 'dig', 'dig_0_D_74'),
(NOW(), 'group', 59, 'dig', 'dig_0_D_75'),
(NOW(), 'group', 60, 'dig', 'dig_0_D_76'),
(NOW(), 'group', 61, 'dig', 'dig_0_D_77'),
(NOW(), 'group', 1, 'int', 'int_0_I_1'),
(NOW(), 'group', 2, 'int', 'int_0_I_2'),
(NOW(), 'group', 3, 'int', 'int_0_I_3'),
(NOW(), 'group', 4, 'int', 'int_0_I_4'),
(NOW(), 'group', 5, 'int', 'int_0_I_5'),
(NOW(), 'group', 6, 'int', 'int_0_I_6'),
(NOW(), 'group', 7, 'int', 'int_0_I_7'),
(NOW(), 'group', 8, 'int', 'int_0_I_8'),
(NOW(), 'group', 9, 'int', 'int_0_I_9'),
(NOW(), 'group', 10, 'int', 'int_0_I_10'),
(NOW(), 'group', 11, 'int', 'int_0_I_11'),
(NOW(), 'group', 12, 'int', 'int_0_I_12'),
(NOW(), 'group', 13, 'int', 'int_0_I_13'),
(NOW(), 'group', 14, 'int', 'int_0_I_14'),
(NOW(), 'group', 15, 'int', 'int_0_I_15'),
(NOW(), 'group', 16, 'int', 'int_0_I_16'),
(NOW(), 'group', 17, 'int', 'int_0_I_17'),
(NOW(), 'group', 18, 'int', 'int_0_I_18'),
(NOW(), 'group', 19, 'int', 'int_0_I_19'),
(NOW(), 'group', 20, 'int', 'int_0_I_20'),
(NOW(), 'group', 21, 'int', 'int_0_I_21'),
(NOW(), 'group', 22, 'int', 'int_0_I_22'),
(NOW(), 'group', 23, 'int', 'int_0_I_23'),
(NOW(), 'group', 24, 'int', 'int_0_I_24'),
(NOW(), 'group', 25, 'int', 'int_0_I_25'),
(NOW(), 'group', 26, 'int', 'int_0_I_26'),
(NOW(), 'group', 27, 'int', 'int_0_I_27'),
(NOW(), 'group', 28, 'int', 'int_0_I_28'),
(NOW(), 'group', 29, 'int', 'int_0_I_29'),
(NOW(), 'group', 30, 'int', 'int_0_I_30'),
(NOW(), 'group', 31, 'int', 'int_0_I_31'),
(NOW(), 'group', 32, 'int', 'int_0_I_32'),
(NOW(), 'group', 33, 'int', 'int_0_I_33'),
(NOW(), 'group', 34, 'int', 'int_0_I_34'),
(NOW(), 'group', 35, 'int', 'int_0_I_35'),
(NOW(), 'group', 36, 'int', 'int_0_I_36'),
(NOW(), 'group', 37, 'int', 'int_0_I_37'),
(NOW(), 'group', 38, 'int', 'int_0_I_38'),
(NOW(), 'group', 39, 'int', 'int_0_I_39'),
(NOW(), 'group', 40, 'int', 'int_0_I_40'),
(NOW(), 'group', 41, 'int', 'int_0_I_41'),
(NOW(), 'group', 42, 'int', 'int_0_I_42'),
(NOW(), 'group', 43, 'int', 'int_0_I_43'),
(NOW(), 'group', 44, 'int', 'int_0_I_44'),
(NOW(), 'group', 45, 'int', 'int_0_I_45'),
(NOW(), 'group', 46, 'int', 'int_0_I_46'),
(NOW(), 'group', 47, 'int', 'int_0_I_47'),
(NOW(), 'group', 48, 'int', 'int_0_I_48'),
(NOW(), 'group', 49, 'int', 'int_0_I_49'),
(NOW(), 'group', 50, 'int', 'int_0_I_50'),
(NOW(), 'group', 51, 'int', 'int_0_I_51'),
(NOW(), 'group', 52, 'int', 'int_0_I_52'),
(NOW(), 'group', 53, 'int', 'int_0_I_53'),
(NOW(), 'group', 54, 'int', 'int_0_I_54'),
(NOW(), 'group', 55, 'int', 'int_0_I_55'),
(NOW(), 'group', 56, 'int', 'int_0_I_56'),
(NOW(), 'group', 57, 'int', 'int_0_I_57'),
(NOW(), 'group', 58, 'int', 'int_0_I_58'),
(NOW(), 'group', 59, 'int', 'int_0_I_59'),
(NOW(), 'group', 60, 'int', 'int_0_I_60'),
(NOW(), 'group', 61, 'int', 'int_0_I_61'),
(NOW(), 'group', 62, 'int', 'int_0_I_62'),
(NOW(), 'group', 63, 'int', 'int_0_I_63'),
(NOW(), 'group', 64, 'int', 'int_0_I_64'),
(NOW(), 'group', 65, 'int', 'int_0_I_65'),
(NOW(), 'group', 66, 'int', 'int_0_I_66'),
(NOW(), 'group', 67, 'int', 'int_0_I_67'),
(NOW(), 'group', 68, 'int', 'int_0_I_68'),
(NOW(), 'group', 69, 'int', 'int_0_I_69'),
(NOW(), 'group', 70, 'int', 'int_0_I_70'),
(NOW(), 'group', 71, 'int', 'int_0_I_71'),
(NOW(), 'group', 72, 'int', 'int_0_I_72'),
(NOW(), 'group', 73, 'int', 'int_0_I_73'),
(NOW(), 'group', 74, 'int', 'int_0_I_74'),
(NOW(), 'group', 75, 'int', 'int_0_I_75'),
(NOW(), 'group', 76, 'int', 'int_0_I_76'),
(NOW(), 'group', 77, 'int', 'int_0_I_77'),
(NOW(), 'group', 78, 'int', 'int_0_I_78'),
(NOW(), 'group', 79, 'int', 'int_0_I_79'),
(NOW(), 'group', 80, 'int', 'int_0_I_80'),
(NOW(), 'group', 81, 'int', 'int_0_I_81'),
(NOW(), 'group', 82, 'int', 'int_0_I_82'),
(NOW(), 'group', 83, 'int', 'int_0_I_83'),
(NOW(), 'group', 84, 'int', 'int_0_I_84'),
(NOW(), 'group', 85, 'int', 'int_0_I_85'),
(NOW(), 'group', 86, 'int', 'int_0_I_86'),
(NOW(), 'group', 87, 'int', 'int_0_I_87'),
(NOW(), 'group', 88, 'int', 'int_0_I_88'),
(NOW(), 'group', 89, 'int', 'int_0_I_89'),
(NOW(), 'group', 90, 'int', 'int_0_I_90'),
(NOW(), 'group', 91, 'int', 'int_0_I_91'),
(NOW(), 'group', 92, 'int', 'int_0_I_92'),
(NOW(), 'group', 93, 'int', 'int_0_I_93'),
(NOW(), 'group', 94, 'int', 'int_0_I_94'),
(NOW(), 'group', 95, 'int', 'int_0_I_95'),
(NOW(), 'group', 96, 'int', 'int_0_I_96'),
(NOW(), 'group', 97, 'int', 'int_0_I_97'),
(NOW(), 'group', 98, 'int', 'int_0_I_98'),
(NOW(), 'group', 99, 'int', 'int_0_I_99'),
(NOW(), 'group', 100, 'int', 'int_0_I_100'),
(NOW(), 'group', 101, 'int', 'int_0_I_101'),
(NOW(), 'group', 102, 'int', 'int_0_I_102'),
(NOW(), 'group', 103, 'int', 'int_0_I_103'),
(NOW(), 'group', 104, 'int', 'int_0_I_104'),
(NOW(), 'group', 105, 'int', 'int_0_I_105'),
(NOW(), 'group', 106, 'int', 'int_0_I_106'),
(NOW(), 'group', 107, 'int', 'int_0_I_107'),
(NOW(), 'group', 108, 'int', 'int_0_I_108'),
(NOW(), 'group', 109, 'int', 'int_0_I_109'),
(NOW(), 'group', 110, 'int', 'int_0_I_110'),
(NOW(), 'group', 111, 'int', 'int_0_I_111'),
(NOW(), 'group', 112, 'int', 'int_0_I_112'),
(NOW(), 'group', 113, 'int', 'int_0_I_113'),
(NOW(), 'group', 114, 'int', 'int_0_I_114'),
(NOW(), 'group', 115, 'int', 'int_0_I_115'),
(NOW(), 'group', 116, 'int', 'int_0_I_116'),
(NOW(), 'group', 117, 'int', 'int_0_I_117'),
(NOW(), 'group', 118, 'int', 'int_0_I_118'),
(NOW(), 'group', 119, 'int', 'int_0_I_119'),
(NOW(), 'group', 120, 'int', 'int_0_I_120'),
(NOW(), 'group', 121, 'int', 'int_0_I_121'),
(NOW(), 'group', 122, 'int', 'int_0_I_122'),
(NOW(), 'group', 123, 'int', 'int_0_I_123'),
(NOW(), 'group', 124, 'int', 'int_0_I_129'),
(NOW(), 'group', 125, 'int', 'int_0_I_130'),
(NOW(), 'group', 126, 'int', 'int_0_I_131'),
(NOW(), 'group', 127, 'int', 'int_0_I_132'),
(NOW(), 'group', 128, 'int', 'int_0_I_133'),
(NOW(), 'group', 129, 'int', 'int_0_I_134');

CREATE TABLE IF NOT EXISTS `iw_par_ca_microchiller_2SE_param` (
  `row_date` datetime NOT NULL DEFAULT '2002-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_ca_microchiller_2SE_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'ana_0_A_1', '0_A_1', '(11) Min. value of pressure', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_2', '0_A_2', '(12) Max. value of pressure', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_3', '0_A_3', '(13) Probe B1 calibration', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_4', '0_A_4', '(14) Probe B2 calibration', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_5', '0_A_5', '(15) Probe B3 calibration', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_6', '0_A_6', '(16) Probe B4 calibration', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_7', '0_A_7', '(17) Probe B5 calibration', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_8', '0_A_8', '(18) Probe B6 calibration', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_9', '0_A_9', '(19) Probe B7 calibration', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_10', '0_A_10', '(20) Probe B8 calibration', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_11', '0_A_11', 'A01 Antifreeze/low ambient temp. (air/air) alarm set point', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_12', '0_A_12', 'A02 Differential for antifreeze/low ambient temperature alarm', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_13', '0_A_13', 'A04 Set-point for the activation of antifreeze', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_14', '0_A_14', 'A05 Differential for antifreeze in cooling', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_15', '0_A_15', 'A07 Limit antifreeze alarm set', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_16', '0_A_16', 'A08 Auxiliary 1 heater set point in heating mode', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_17', '0_A_17', 'A09 Differential for antifreeze supporting heaters', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_18', '0_A_18', 'd03 Start defrosting pressure', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_19', '0_A_19', 'd03 Start defrosting temperature', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_20', '0_A_20', 'd04 End defrosting pressure', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_21', '0_A_21', 'd04 End defrosting temperature', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_22', '0_A_22', 'd17 Min. temperature of start defrost light', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_23', '0_A_23', 'F05 Set-point pressure value for summer speed', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_24', '0_A_24', 'F05 Set-point temp value for summer speed', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_25', '0_A_25', 'F06 Pressure value for differential summer speed', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_26', '0_A_26', 'F06 Temp. value for differential summer speed', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_27', '0_A_27', 'F07 Diff. pressure to turn OFF the fan in cooling', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_28', '0_A_28', 'F07 Differential temp. to turn OFF the fan in cooling', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_29', '0_A_29', 'F08 Set-point pressure value for winter speed', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_30', '0_A_30', 'F08 Set-point temp value for winter speed', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_31', '0_A_31', 'F09 Pressure value for differential winter speed', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_32', '0_A_32', 'F09 Temp. value for differential winter speed', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_33', '0_A_33', 'F10 Diff. pressure to turn OFF the fan in heating', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_34', '0_A_34', 'F10 Differential temp. to turn OFF the fan in heating', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_35', '0_A_35', 'F16 Differential Low Noise in Cooling', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_36', '0_A_36', 'F17 Differential Low Noise in Heating', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_37', '0_A_37', 'H14 Min. pressure pump down', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_38', '0_A_38', 'P16 High temperature alarm set', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_39', '0_A_39', 'P18 Pressure probe set for HP alarms', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_40', '0_A_40', 'P19 Low  temperature alarm set', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_41', '0_A_41', 'r01 Cooling set-point', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_42', '0_A_42', 'r02 Cooling differential', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_43', '0_A_43', 'r03 Heating set-point', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_44', '0_A_44', 'r04 Heating differential', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_45', '0_A_45', 'r07 Differential neutral zone/ Change over automatico', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_46', '0_A_46', 'r12 Differential compressor disable', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_47', '0_A_47', 'r13 Min. cooling set-point', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_48', '0_A_48', 'r14 Max. cooling set-point', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_49', '0_A_49', 'r15 Min. heating set-point', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_50', '0_A_50', 'r16 Max. heating set-point', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_51', '0_A_51', 'r17 Cooling Compensation constant', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_52', '0_A_52', 'r18 Maximum deviation from set-point', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_53', '0_A_53', 'r19 Start compensation temperature in cooling', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_54', '0_A_54', 'r20 Start compensation temperature in heating', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_55', '0_A_55', 'r21 Summer setpoint from digital input', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_56', '0_A_56', 'r22 Winter setpoint from digital input', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_57', '0_A_57', 'A12 Set DeltaT for  dirty filters', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_58', '0_A_58', 'r29 Differential temperature on low load Chiller', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_59', '0_A_59', 'r30 Differential temperature on low load PdC', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_60', '0_A_60', 'r31 Heating compensation constant', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_61', '0_A_61', 'r24 Set point change over automatic', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_62', '0_A_62', 'd18 Max external temperature (SLIDING DEFROST)', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_63', '0_A_63', 'd19 Differential start defrost (SLIDING DEFROST)', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_64', '0_A_64', 'd20 Differential external temperatire (SLIDING DEFROST)', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_65', '0_A_65', 'r25 Set point external temperature for stop cpmpressor', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_66', '0_A_66', 'r26 Cooling Set point in Dehumification mode ', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_67', '0_A_67', 'A11 Auxiliary 2 heater set point in heating mode', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_68', '0_A_68', 'H17 Minimum value  DTE allow', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_69', '0_A_69', 'H18 Maximum value  DTE allow', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_70', '0_A_70', 'H19 Maximum value  DTC allow', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_71', '0_A_71', 'r32 Set point  Hot start', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_72', '0_A_72', 'r33 Differenziale Hot start', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_73', '0_A_73', 'r37 Differential Duty cycle opening rolling', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_74', '0_A_74', 'r38 Differential Duty cycle closing rolling', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_75', '0_A_75', 'r39 Coefficient corrective autotuning', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_76', '0_A_76', 'P33 Set alarm low pressure', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_77', '0_A_77', 'A04 Differential for antifreeze in heating', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_78', '0_A_78', 'A08 Differential for antifreeze in heating 2', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_79', '0_A_79', 'A11 Differential for antifreeze 2 in heating', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_80', '0_A_80', 'A13 Set alarm antifreeze  for EVD', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_81', '0_A_81', 'r42 Threshold activation only freecooling ', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_82', '0_A_82', 'A14 Antifreeze/low ambient temp. (air/air) alarm set point', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_83', '0_A_83', 'A15 Antifreeze/low ambient temp. (air/air) alarm set point', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_97', '0_A_97', 'Internal set with compensation in autotuning', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_98', '0_A_98', 'DTE value full load', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_99', '0_A_99', 'dtE Actual DTE value', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_100', '0_A_100', 'dC1 Actual DTE value circuit 0', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_101', '0_A_101', 'dC2 Actual DTE value circuit 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_102', '0_A_102', 'b01 Temperature of probe 1', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_103', '0_A_103', 'b02 Temperature of probe 2', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_104', '0_A_104', 'b03 Temperature of probe 3', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_105', '0_A_105', 'b04 Temperature of probe 4', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_106', '0_A_106', 'b05 Temperature of probe 5', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_107', '0_A_107', 'b06 Temperature of probe 6', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_108', '0_A_108', 'b07 Temperature of probe 7', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_109', '0_A_109', 'b08 Temperature of probe 8', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_110', '0_A_110', 'b09 Evaporator temperature of EVD 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_111', '0_A_111', 'b10 Evaporator pressure of EVD 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_112', '0_A_112', 'b11 Superheat temperature of EVD 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_113', '0_A_113', 'b12 Saturation temperature of EVD 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_114', '0_A_114', 'b13 Valve position of EVD 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_115', '0_A_115', 'b14 Evaporator temperature of EVD 2', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_116', '0_A_116', 'b15 Evaporator pressure of EVD 2', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_117', '0_A_117', 'b16 Superheat temperature of EVD 2', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_118', '0_A_118', 'b17 Saturation temperature of EVD 2', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_119', '0_A_119', 'b18 Valve position of EVD 2', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_120', '0_A_120', 'b19 Extern air temperature of EVD 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_121', '0_A_121', 'b20 Extern air temperature of EVD 2', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_122', '0_A_122', 'c10 Timer compressor 1', '', 'Analog values', 'float', '', '-1', 'r', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_123', '0_A_123', 'c11 Timer compressor 2', '', 'Analog values', 'float', '', '-1', 'r', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_124', '0_A_124', 'c12 Timer compressor 3', '', 'Analog values', 'float', '', '-1', 'r', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_125', '0_A_125', 'c13 Timer compressor 4', '', 'Analog values', 'float', '', '-1', 'r', 'hour', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_126', '0_A_126', 'c15 Pump/inlet evaporation fan timer', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_127', '0_A_127', 'c16 Pump/inlet fan condensation timer', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'ana_0_A_128', '0_A_128', 'b21 Terminal probe ( for Terminal uAD)', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_1', '0_D_1', '(01) Probe B1 present', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_2', '0_D_2', '(02) Probe B2 present', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_3', '0_D_3', '(05) Probe B5 present', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_4', '0_D_4', '(06) Probe B6 present', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_5', '0_D_5', '(23) Measure unit', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_6', '0_D_6', 'A06 Supporting heaters probe', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_7', '0_D_7', 'd01 Defrosting cycle/Condensation antifreeze', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_8', '0_D_8', 'P21 Alarm relay management', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_9', '0_D_9', 'd11 Antifreeze heaters activated while defrosting', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_10', '0_D_10', 'F01 Fans output enabled', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_11', '0_D_11', 'H23 Enable Modbus protocol', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_12', '0_D_12', 'H02 Number of condenser', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_13', '0_D_13', 'H03 Number of evaporators', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_14', '0_D_14', 'H06 Cooling/Heating digital input', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_15', '0_D_15', 'H07 ON/OFF digital input', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_16', '0_D_16', 'H09 Keyboard lock-up', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_17', '0_D_17', 'H13 Pump Down activation', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_18', '0_D_18', 'H22 Disable load default parameters at the start', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_19', '0_D_19', 'P06 Summer/Winter invertion logic.', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_20', '0_D_20', 'P20 Enable plant protection at the start of instrument', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_21', '0_D_21', 'P24 Compressor disable on HP and LP part load', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_22', '0_D_22', 'H16 Auto Tuning Activation', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_23', '0_D_23', 'P35 Reset alarms with command MUTE', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_24', '0_D_24', 'P36 Typemanage  alarm high pressure', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_41', '0_D_41', 'Circuit 1 alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_42', '0_D_42', 'Circuit 2 alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_43', '0_D_43', 'Driver valve 1 alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_44', '0_D_44', 'Driver valve 2 alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_45', '0_D_45', 'General alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_46', '0_D_46', 'Probe alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_47', '0_D_47', 'Compressor notice', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_48', '0_D_48', 'Driver valve 1 notice', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_49', '0_D_49', 'Driver valve 2 notice', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_50', '0_D_50', 'General notice', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_51', '0_D_51', 'Low and High temperature notice', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_52', '0_D_52', 'Fun notice', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_53', '0_D_53', 'Digital input 1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_54', '0_D_54', 'Digital input 2', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_55', '0_D_55', 'Digital input 3', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_56', '0_D_56', 'Digital input 4', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_57', '0_D_57', 'Digital input 5', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_58', '0_D_58', 'Digital input probe B4', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_59', '0_D_59', 'Digital output 1', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_60', '0_D_60', 'Digital output 2', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_61', '0_D_61', 'Digital output 3', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_62', '0_D_62', 'Digital output 4', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_63', '0_D_63', 'Digital output 5', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_64', '0_D_64', 'Machine status (On or Stand by)', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_65', '0_D_65', 'Summer or winter', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_66', '0_D_66', 'Digital input 6 (2° circuit)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_67', '0_D_67', 'Digital input 7 (2° circuit)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_68', '0_D_68', 'Digital input 8 (2° circuit)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_69', '0_D_69', 'Digital input 9 (2° circuit)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_70', '0_D_70', 'Digital input 10 (2° circuit)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_71', '0_D_71', 'Digital input probe B8 (2° circuit)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_72', '0_D_72', 'Digital output 6', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_73', '0_D_73', 'Digital output 7', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_74', '0_D_74', 'Digital output 8', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_75', '0_D_75', 'Digital output 9', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_76', '0_D_76', 'Digital output 10', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'dig_0_D_77', '0_D_77', 'Alarm DTE or DTC out of range', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_1', '0_I_1', 'H99 Software release', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_2', '0_I_2', 'H98 Expansion software release', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_3', '0_I_3', 'H97 Driver valve 1 software release', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_4', '0_I_4', 'H96 Driver valve 2 software release', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_5', '0_I_5', 'Probe 1- Gain costant', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_6', '0_I_6', 'Probe 2- Gain costant', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_7', '0_I_7', 'Probe 3- Gain costant', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_8', '0_I_8', 'Probe 4- Gain costant', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_9', '0_I_9', 'Offset for probe 1', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_10', '0_I_10', 'Offset for probe 2', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_11', '0_I_11', 'Offset for probe 3', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_12', '0_I_12', 'Offset for probe 4', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_13', '0_I_13', 'Digital output enable from supervisor', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_14', '0_I_14', '(03) Type of probe B3', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_15', '0_I_15', '(04) Type of probe B4', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_16', '0_I_16', '(07) Type of probe B7', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_17', '0_I_17', '(08) Type of probe B8', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_18', '0_I_18', '(09) Min. input voltage value', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_19', '0_I_19', '(10) Max. input voltage value', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_20', '0_I_20', '(21) Digital Filter', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_21', '0_I_21', '(22) Input Limit', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_22', '0_I_22', 'A03 Bypass time for antifreeze alarm/Low ambient temp.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_23', '0_I_23', 'A10 Automatic start in antifreeze', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_24', '0_I_24', 'b00 Probe watched on display', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_25', '0_I_25', 'c01 Minimum running time', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_26', '0_I_26', 'c02 Minimum stopping time', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_27', '0_I_27', 'c03 Time-interval between 2 starts', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_28', '0_I_28', 'c04 Time-delay between starts of compr.s when starting', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_29', '0_I_29', 'c05 Time-delay between turning OFF the two compressor', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_30', '0_I_30', 'c06 Time delay at start-up', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_31', '0_I_31', 'c07 Delay in swit. on comp. after swit. on the pump', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_32', '0_I_32', 'c08 Delay in swit. OFF comp. after swit. OFF the pump', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_33', '0_I_33', 'c09 Max. time tandem compressor on.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_34', '0_I_34', 'c14 Timer thresold for maintenance alarm', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_35', '0_I_35', 'c17 Minimum time between two pump starts', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_36', '0_I_36', 'c18 Minimum pump on time', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_37', '0_I_37', 'd05 Min. time-interval to start a defrosting cycle', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_38', '0_I_38', 'd06 Min. duration of a defrosting cycle', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_39', '0_I_39', 'd07 Max. duration of a defrosting cycle', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_40', '0_I_40', 'd08 Time delay between 2 defrosting', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_41', '0_I_41', 'd09 Defrosting time-interval between the 2 circuits', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_42', '0_I_42', 'd10 Defrost start/end by external contact', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_43', '0_I_43', 'd12 Delay before defrosting', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_44', '0_I_44', 'd13 Delay after defrosting', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_45', '0_I_45', 'd14 End defrosting with 2 refrigerating circuits', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_46', '0_I_46', 'd15 Start defrost with 2 circuit', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_47', '0_I_47', 'd16 Time max. speed fan at the end defrost', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_48', '0_I_48', 'F02 Fans operating mode', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_49', '0_I_49', 'F03 Min. tension thresold for Triac', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_50', '0_I_50', 'F04 Max. tension thresold for Triac', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_51', '0_I_51', 'F11 Starting time of fans', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_52', '0_I_52', 'F12 Triac pulse lenght', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_53', '0_I_53', 'F13 Type of fan during defrost', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_54', '0_I_54', 'H01 Unit model', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_55', '0_I_55', 'H04 Compressor configuration of micro chiller and exp.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_56', '0_I_56', 'H05 Workinglogic of pump/inlet fan (air-air)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_57', '0_I_57', 'H08 Lan configuration', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_58', '0_I_58', 'H10 Serial address', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_59', '0_I_59', 'H11 Type of digital output', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_60', '0_I_60', 'H12 Compressor partialization logic', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_61', '0_I_61', 'H15 Max. time pump down', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_62', '0_I_62', 'H21 Second pump function', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_63', '0_I_63', 'P01 Flowmeter down delayed when starting the pump', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_64', '0_I_64', 'P02 Flowswitch alarm delayed during normal operating', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_65', '0_I_65', 'P03 Low pressure alarm delay at start-up', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_66', '0_I_66', 'P04 Enable part load in high pressure', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_67', '0_I_67', 'P05 Reset of alarms', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_68', '0_I_68', 'P07 Low pressure alarm from transducer', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_69', '0_I_69', 'P08 Selection of the digital input 1', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_70', '0_I_70', 'P09 Selection of the digital input 2', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_71', '0_I_71', 'P10 Selection of the digital input 6', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_72', '0_I_72', 'P11 Selection of the digital input 7', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_73', '0_I_73', 'P12 Selection of the digital input 10', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_74', '0_I_74', 'P13 Selection of the probe B4 if /4 =1', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_75', '0_I_75', 'P14 Selection of the probe B8 if /8 =1', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_76', '0_I_76', 'P15 Selection low pressure alarm', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_77', '0_I_77', 'P17 High temperature alarm delayed at start-up', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_78', '0_I_78', 'r05 Compressor rotation', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_79', '0_I_79', 'r06 Type of compressor regolation', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_80', '0_I_80', 'r08 Max. time output control enable.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_81', '0_I_81', 'r09 Min. time output control enable.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_82', '0_I_82', 'r10 Max. time output control disable.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_83', '0_I_83', 'r11 Min. time output control disable.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_84', '0_I_84', 'r23 Change over selection probe', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_85', '0_I_85', 'F15 Low Noise Activation', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_86', '0_I_86', 'P22 Delay Alarm LP start compressor in heat pump', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_87', '0_I_87', 'P23 Delay Alarm LP start compressor in defrost mode', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_88', '0_I_88', 'r27 Enable/Selection type of low load', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_89', '0_I_89', 'r28 Time run rolling', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_90', '0_I_90', 'd02 Type of defrost', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_91', '0_I_91', 'F14 Ventilation', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_92', '0_I_92', 't06 Hour start  2° setpoint summer', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_93', '0_I_93', 't07 Minute start  2° setpoint summer', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_94', '0_I_94', 't08 Hour end  2° setpoint summer', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_95', '0_I_95', 't09 Minute end  2° setpoint summer', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_96', '0_I_96', 't10 Hour start  2° setpoint winter', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_97', '0_I_97', 't11 Minute start  2° setpoint winter', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_98', '0_I_98', 't12 Hour end  2° setpoint winter', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_99', '0_I_99', 't13 Minute end  2° setpoint winter', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_100', '0_I_100', 't14 Hour start 2° low noise summer', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_101', '0_I_101', 't15 Minute start 2° low-noise summer', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_102', '0_I_102', 't16 Hour end 2° low noise summer', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_103', '0_I_103', 't17 Minute end 2° low-noise summer', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_104', '0_I_104', 't18 Hour start 2° low noise winter', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_105', '0_I_105', 't19 Minute start 2° low-noise winter', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_106', '0_I_106', 't20 Hour end 2° low noise winter', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_107', '0_I_107', 't21 Minute end 2° low-noise winter', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_108', '0_I_108', 'P25 Digital output 2 selection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', '');
REPLACE INTO `iw_par_ca_microchiller_2SE_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'int_0_I_109', '0_I_109', 'P26 Digital output 3 selection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_110', '0_I_110', 'P27 Digital output 4 selection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_111', '0_I_111', 'P28 Digital output 5 selection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_112', '0_I_112', 'P29 Digital output 7 selection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_113', '0_I_113', 'P30 Digital output 8 selection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_114', '0_I_114', 'P31 Digital output 9 selection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_115', '0_I_115', 'P32 Digital output 10 selection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_116', '0_I_116', 'r34 FreeCooling/FreeHeating enabled', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_117', '0_I_117', 'r35 Time disactivation Compr. FreeC./FreeH. Enable', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_118', '0_I_118', 'r36 Time cycle rolling', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_119', '0_I_119', 'r40 Type  use of minimum opening rolling', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_120', '0_I_120', 'r41 Minimum opening rolling', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_121', '0_I_121', 'r43 Set point resistence', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_122', '0_I_122', 'P34 Digital input  5selection', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_123', '0_I_123', 'r44 Time inactivity of freeccoling regulation', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_129', '0_I_129', 't01 RTC Hour', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_130', '0_I_130', 't02 RTC Minute', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_131', '0_I_131', 't03 RTC Day', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_132', '0_I_132', 't04 RTC Month', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_133', '0_I_133', 't05 RTC Year', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'int_0_I_134', '0_I_134', 'Defrost status', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '', '');

CREATE TABLE IF NOT EXISTS `iw_set_ca_microchiller_2SE` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='4.0.0';

REPLACE INTO `iw_set_ca_microchiller_2SE` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'ana_0_A_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_11', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_12', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_13', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_14', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_15', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_16', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_17', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_18', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_19', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_20', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_21', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_22', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_23', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_24', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_25', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_26', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_27', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_28', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_29', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_30', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_31', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_32', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_33', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_34', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_35', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_36', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_37', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_38', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_39', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_40', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_41', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_42', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_43', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_44', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_45', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_46', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_47', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_48', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_49', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_50', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_51', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_52', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_53', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_54', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_55', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_56', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_57', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_58', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_59', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_60', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_61', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_62', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_63', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_64', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_65', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_66', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_67', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_68', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_69', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_70', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_71', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_72', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_73', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_74', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_75', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_76', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_77', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_78', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_79', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_80', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_81', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_82', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_83', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ana_0_A_97', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_98', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_99', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_100', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_101', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_102', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_103', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_104', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_105', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_106', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_107', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_108', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_109', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_110', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_111', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_112', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_113', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_114', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_115', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_116', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_117', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_118', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_119', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_120', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_121', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_122', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_123', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_124', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_125', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_126', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_127', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'ana_0_A_128', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'dig_0_D_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_11', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_12', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_13', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_14', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_15', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_16', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_17', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_18', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_19', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_20', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_21', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_22', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_23', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_24', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_41', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'dig_0_D_42', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'dig_0_D_43', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'dig_0_D_44', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'dig_0_D_45', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'dig_0_D_46', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'dig_0_D_47', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'dig_0_D_48', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'dig_0_D_49', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'dig_0_D_50', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'dig_0_D_51', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'dig_0_D_52', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'dig_0_D_53', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_54', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_55', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_56', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_57', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_58', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_59', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_60', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_61', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_62', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_63', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_64', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_65', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_66', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_67', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_68', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_69', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_70', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_71', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_72', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_73', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_74', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_75', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_76', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dig_0_D_77', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'int_0_I_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_6', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_8', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_11', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_12', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_13', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_14', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_15', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_16', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_17', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_18', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_19', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_20', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_21', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_22', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_23', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_24', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_25', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_26', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_27', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_28', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_29', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_30', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_31', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_32', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_33', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_34', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_35', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_36', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_37', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_38', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_39', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_40', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_41', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_42', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_43', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_44', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_45', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_46', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_47', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_48', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_49', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_50', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_51', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_52', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_53', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_54', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_55', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_56', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_57', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_58', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_59', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_60', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_61', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_62', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_63', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_64', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_65', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_66', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_67', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_68', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_69', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_70', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_71', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_72', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_73', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_74', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_75', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_76', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_77', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_78', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_79', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_80', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_81', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_82', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_83', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_84', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_85', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_86', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_87', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_88', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_89', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_90', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_91', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_92', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_93', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_94', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_95', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_96', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_97', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_98', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_99', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_100', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_101', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_102', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_103', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_104', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_105', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_106', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_107', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_108', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_109', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_110', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_111', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_112', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_113', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_114', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_115', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_116', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_117', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_118', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_119', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_120', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_121', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_122', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_123', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_129', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_130', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_131', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_132', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_133', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'int_0_I_134', '1', '0', 'slow', 'change', '', '', '', 0);



-- Changelog
--
-- v1 Orginal
--
--