REPLACE INTO `iw_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'U01', 'PJ-Easy - 1', 'ca_pjeasy', 'CARELBOSS', '0_1', 'PJEASY', 'PJEASY', '', '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'idle_event_rate', 'CAREL485', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'CAREL485', '2000', 'msec.', '', ''),
(NOW(), 'packet_timeout', 'CAREL485', '1', 'sec.', '', ''),
(NOW(), 'max_outstanding_packets', 'CAREL485', '-1', '', '', ''),
(NOW(), 'max_error_count', 'CAREL485', '2', '', '', ''),
(NOW(), 'max_group_count', 'CAREL485', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'CAREL485', '2', 'hours', '', ''),
(NOW(), 'speed_index_norm', 'CAREL485', '1', '', '', ''),
(NOW(), 'speed_index_slow', 'CAREL485', '1', '', '', ''),
(NOW(), 'speed_index_offline', 'CAREL485', '10', '', '', ''),
(NOW(), 'speed_index_block', 'CAREL485', '10', '', '', ''),
(NOW(), 'show_queue_info', 'CAREL485', '0', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'CAREL485', '10', 'min.', '', ''),
(NOW(), 'com_port', 'CAREL485', '1', '', '', ''),
(NOW(), 'baud_rate', 'CAREL485', '19200', '', '', ''),
(NOW(), 'gateway_type', 'CAREL485', '485N', '', '485=485 (old, black), 485N=485_232 (new, blue), 422=422 (very old)', ''),
(NOW(), 'startup_delay', 'CAREL485', '15', 'Sec.', '', ''),
(NOW(), 'reopen_timer', 'CAREL485', 'never', '', 'never,x min,x hour', ''),
(NOW(), 'count_com_ports', 'CAREL485', '1', '', '', ''),
(NOW(), 'alarm_handler', 'CAREL485', '', '', '', '');
REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'com_port', 'CAREL485', '1', '', '', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_carel485.exe', 'CAREL485', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'PJEASY', 'ca_pjeasy_param', 'ca_pjeasy_groups');

CREATE TABLE IF NOT EXISTS `iw_par_ca_pjeasy_groups` (
  `row_date` datetime NOT NULL DEFAULT '2017-01-01 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='4.0.0';

REPLACE INTO `iw_par_ca_pjeasy_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'group', 101, '3', '146_A_14'),
(NOW(), 'group', 102, '36', '700_I_18'),
(NOW(), 'group', 103, '17', '554_I_2'),
(NOW(), 'group', 104, '5', '239_D_34'),
(NOW(), 'group', 105, '17', '811_I_38'),
(NOW(), 'group', 106, '17', '68_I_49'),
(NOW(), 'group', 107, '4', '186_D_26'),
(NOW(), 'group', 108, '15', '499_A_12'),
(NOW(), 'group', 109, '4', '192_I_9'),
(NOW(), 'group', 110, '4', '627_I_33'),
(NOW(), 'group', 111, '2', '79_D_38'),
(NOW(), 'group', 112, '17', '810_I_35'),
(NOW(), 'group', 113, '17', '250_I_48'),
(NOW(), 'group', 114, '6', '42_A_8'),
(NOW(), 'group', 115, '17', '102_I_47'),
(NOW(), 'group', 116, '1', '782_D_4'),
(NOW(), 'group', 117, '3', '896_I_25'),
(NOW(), 'group', 118, '36', '152_I_19'),
(NOW(), 'group', 119, '17', '172_I_57'),
(NOW(), 'group', 120, '17', '714_I_34'),
(NOW(), 'group', 121, '1', '858_D_3'),
(NOW(), 'group', 122, '17', '24_I_56'),
(NOW(), 'group', 123, '1', '944_I_4'),
(NOW(), 'group', 124, '17', '164_I_50'),
(NOW(), 'group', 125, '17', '813_I_44'),
(NOW(), 'group', 126, '1', '748_D_21'),
(NOW(), 'group', 127, '15', '269_A_9'),
(NOW(), 'group', 128, '7', '889_I_13'),
(NOW(), 'group', 129, '36', '663_D_30'),
(NOW(), 'group', 130, '4', '886_D_27'),
(NOW(), 'group', 131, '36', '158_I_20'),
(NOW(), 'group', 132, '17', '716_I_40'),
(NOW(), 'group', 133, '3', '232_I_24'),
(NOW(), 'group', 134, '1', '183_I_5'),
(NOW(), 'group', 135, '17', '717_I_43'),
(NOW(), 'group', 136, '3', '214_I_27'),
(NOW(), 'group', 137, '3', '329_I_26'),
(NOW(), 'group', 138, '17', '960_I_42'),
(NOW(), 'group', 139, '1', '757_A_1'),
(NOW(), 'group', 140, '17', '961_I_45'),
(NOW(), 'group', 141, '36', '575_I_21'),
(NOW(), 'group', 142, '17', '804_I_3'),
(NOW(), 'group', 143, '36', '447_D_29'),
(NOW(), 'group', 144, '17', '715_I_37'),
(NOW(), 'group', 145, '15', '395_I_10'),
(NOW(), 'group', 146, '4', '111_I_31'),
(NOW(), 'group', 147, '17', '866_I_52'),
(NOW(), 'group', 148, '17', '928_I_55'),
(NOW(), 'group', 149, '4', '209_I_32'),
(NOW(), 'group', 150, '1', '788_I_6'),
(NOW(), 'group', 151, '36', '611_A_13'),
(NOW(), 'group', 152, '3', '268_A_16'),
(NOW(), 'group', 153, '1', '541_D_1'),
(NOW(), 'group', 154, '17', '355_I_1'),
(NOW(), 'group', 155, '36', '212_I_22'),
(NOW(), 'group', 156, '36', '947_D_28'),
(NOW(), 'group', 157, '17', '312_I_51'),
(NOW(), 'group', 158, '1', '697_A_4'),
(NOW(), 'group', 159, '3', '272_A_15'),
(NOW(), 'group', 160, '1', '696_A_3'),
(NOW(), 'group', 161, '1', '695_A_2'),
(NOW(), 'group', 162, '17', '962_I_53'),
(NOW(), 'group', 163, '7', '732_I_11'),
(NOW(), 'group', 164, '7', '837_I_17'),
(NOW(), 'group', 165, '3', '267_D_32'),
(NOW(), 'group', 166, '1', '807_D_5'),
(NOW(), 'group', 167, '4', '114_I_30'),
(NOW(), 'group', 168, '7', '158_I_12'),
(NOW(), 'group', 169, '2', '866_D_22'),
(NOW(), 'group', 170, '5', '327_I_28'),
(NOW(), 'group', 171, '4', '701_I_8'),
(NOW(), 'group', 172, '15', '876_A_10'),
(NOW(), 'group', 173, '15', '878_A_11'),
(NOW(), 'group', 174, '7', '827_I_14'),
(NOW(), 'group', 175, '7', '507_I_15'),
(NOW(), 'group', 176, '4', '77_D_36'),
(NOW(), 'group', 177, '1', '61_I_29'),
(NOW(), 'group', 178, '5', '350_A_19'),
(NOW(), 'group', 179, '3', '83_A_17'),
(NOW(), 'group', 180, '7', '678_I_16'),
(NOW(), 'group', 181, '2', '321_D_20'),
(NOW(), 'group', 182, '5', '668_D_35'),
(NOW(), 'group', 183, '17', '6_I_46'),
(NOW(), 'group', 184, '17', '958_I_36'),
(NOW(), 'group', 185, '17', '110_I_54'),
(NOW(), 'group', 186, '36', '393_I_23'),
(NOW(), 'group', 187, '17', '751_D_37'),
(NOW(), 'group', 188, '36', '145_D_31'),
(NOW(), 'group', 189, '1', '215_D_23'),
(NOW(), 'group', 190, '3', '128_A_18'),
(NOW(), 'group', 191, '17', '959_I_39'),
(NOW(), 'group', 192, '6', '539_A_5'),
(NOW(), 'group', 193, '6', '541_A_7'),
(NOW(), 'group', 194, '6', '540_A_6'),
(NOW(), 'group', 195, '1', '203_D_19'),
(NOW(), 'group', 196, '5', '48_D_33'),
(NOW(), 'group', 197, '1', '872_D_2'),
(NOW(), 'group', 198, '17', '812_I_41'),
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 3, '3', 'Alarm and digital inputs configuration'),
(NOW(), 'group_alias', 36, '36', 'Defrost parameters'),
(NOW(), 'group_alias', 17, '17', 'RTC parameters'),
(NOW(), 'group_alias', 5, '5', 'Fan parameters'),
(NOW(), 'group_alias', 4, '4', 'Configuration parameters'),
(NOW(), 'group_alias', 15, '15', 'Main parameters'),
(NOW(), 'group_alias', 2, '2', 'Commands'),
(NOW(), 'group_alias', 6, '6', 'Probe parameters'),
(NOW(), 'group_alias', 1, '1', 'General'),
(NOW(), 'group_alias', 7, '7', 'Compressor/solenoid parameters'),
(NOW(), 'group', 199, '47', '515_D_0'),
(NOW(), 'group', 200, '39', '568_D_25'),
(NOW(), 'group', 201, '0', '186_D_10'),
(NOW(), 'group', 202, '0', '573_D_15'),
(NOW(), 'group', 203, '0', '258_D_9'),
(NOW(), 'group', 204, '0', '687_D_18'),
(NOW(), 'group', 205, '0', '640_D_17'),
(NOW(), 'group', 206, '0', '795_D_11'),
(NOW(), 'group', 207, '39', '899_D_14'),
(NOW(), 'group', 208, '0', '812_D_12'),
(NOW(), 'group', 209, '39', '286_D_16'),
(NOW(), 'group', 210, '0', '8_D_6'),
(NOW(), 'group', 211, '0', '9_D_7'),
(NOW(), 'group', 212, '0', '10_D_8'),
(NOW(), 'group', 213, '39', '672_D_13'),
(NOW(), 'group', 214, '39', '894_D_24'),
(NOW(), 'group_alias', 47, '47', 'Connection alarm'),
(NOW(), 'group_alias', 39, '39', 'Temperature setting alarm'),
(NOW(), 'group_alias', 0, '0', '0');

CREATE TABLE IF NOT EXISTS `iw_par_ca_pjeasy_param` (
  `row_date` datetime NOT NULL DEFAULT '2017-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='4.0.0';

REPLACE INTO `iw_par_ca_pjeasy_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), '146_A_14', '146_A_14', 'Alarms and fan differential', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '-20', '20', '', '', '', '', '', 'ALARM_TEMP_DIFF', ''),
(NOW(), '700_I_18', '700_I_18', 'Type of defrost', '', 'Integral Values', 'integer', '', '', 'r', '', '', '0', '4', '', '', '', '', '', 'DEFR_TIPO', ''),
(NOW(), '554_I_2', '554_I_2', 'RTC hour', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '23', '', '', '', '', '', 'RTC_ORA', ''),
(NOW(), '239_D_34', '239_D_34', 'Stop evaporator fans if compressor stops', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'FAN_OFF_COMP_OFF', ''),
(NOW(), '811_I_38', '811_I_38', 'Time band 2nd hour', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '23', '', '', '', '', '', 'FASCIA_ORARIA_DEFR2_HOUR', ''),
(NOW(), '68_I_49', '68_I_49', 'Night time band OFF day', '', 'Integral Values', 'integer', '', '', 'rw', 'day', '', '0', '11', '', '', '', '', '', 'FASCIA_ORARIA_NIGHT_OFF_DAY', ''),
(NOW(), '186_D_26', '186_D_26', 'Select C/F', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '', '', '', '', '', '', '', 'SONDE_SELEZ_C_F', ''),
(NOW(), '499_A_12', '499_A_12', 'Night-time set point delta', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '-50', '50', '', '', '', '', '', 'REG_DELTA_SET_NOTTE', ''),
(NOW(), '192_I_9', '192_I_9', 'Select display probe', '', 'Integral Values', 'integer', '', '', 'r', '', '', '1', '3', '', '', '', '', '', 'VIS_SONDA_SELEZ', ''),
(NOW(), '627_I_33', '627_I_33', 'Select set of default parameters', '', 'Integral Values', 'integer', '', '', 'r', '', '', '0', '4', '', '', '', '', '', 'EZY_BANK', ''),
(NOW(), '79_D_38', '79_D_38', 'Unit ON/OFF command', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '', '', '', '', '', '', '', 'COMANDO_ON_OFF', ''),
(NOW(), '810_I_35', '810_I_35', 'Time band 1st hour', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '23', '', '', '', '', '', 'FASCIA_ORARIA_DEFR1_HOUR', ''),
(NOW(), '250_I_48', '250_I_48', 'Night time band ON minutes', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '59', '', '', '', '', '', 'FASCIA_ORARIA_NIGHT_ON_MINUTE', ''),
(NOW(), '42_A_8', '42_A_8', 'Working temperature setpoint', '', 'Analog Values', 'float', '', '', 'rw', '°C/°F', '%.1f', 'pk54279', 'pk54278', '', '', '', '', '', 'REG_SET_POINT', ''),
(NOW(), '102_I_47', '102_I_47', 'Night time band ON hour', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '23', '', '', '', '', '', 'FASCIA_ORARIA_NIGHT_ON_HOUR', ''),
(NOW(), '782_D_4', '782_D_4', 'Fan relay status', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_RELE_FAN', ''),
(NOW(), '896_I_25', '896_I_25', '3rd input conf.', '', 'Integral Values', 'integer', '', '', 'r', '', '', '0', '11', '', '', '', '', '', 'DIGIN_CONFIG', ''),
(NOW(), '152_I_19', '152_I_19', 'Interval between defrosts', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '199', '', '', '', '', '', 'DEFR_INTERVALLO', ''),
(NOW(), '172_I_57', '172_I_57', 'AUX time band OFF minutes', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '59', '', '', '', '', '', 'FASCIA_ORARIA_AUX_OFF_MINUTE', ''),
(NOW(), '714_I_34', '714_I_34', 'Defrost time band 1st day', '', 'Integral Values', 'integer', '', '', 'rw', 'day', '', '0', '11', '', '', '', '', '', 'FASCIA_ORARIA_DEFR1_DAY', ''),
(NOW(), '858_D_3', '858_D_3', 'Defrost relay status', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_RELE_DEFR', ''),
(NOW(), '24_I_56', '24_I_56', 'AUX time band OFF hour', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '23', '', '', '', '', '', 'FASCIA_ORARIA_AUX_OFF_HOUR', ''),
(NOW(), '944_I_4', '944_I_4', 'RTC presence', '', 'Integral Values', 'integer', '', '', 'r', '', '', '0', '1', '', '', '', '', '', 'PRESENZA_RTC', ''),
(NOW(), '164_I_50', '164_I_50', 'Night time band OFF hour', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '23', '', '', '', '', '', 'FASCIA_ORARIA_NIGHT_OFF_HOUR', ''),
(NOW(), '813_I_44', '813_I_44', 'Time band 4th hour', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '23', '', '', '', '', '', 'FASCIA_ORARIA_DEFR4_HOUR', ''),
(NOW(), '748_D_21', '748_D_21', 'Continuous cycle status', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_STATO_CICLO_CONTINUO', ''),
(NOW(), '269_A_9', '269_A_9', 'Working temperature differential', '', 'Analog Values', 'float', '', '', 'rw', '°C/°F', '%.1f', '0', '19', '', '', '', '', '', 'REG_DIFFERENZIALE', ''),
(NOW(), '889_I_13', '889_I_13', 'Minimum compressor OFF time', '', 'Integral Values', 'integer', '', '', 'r', 'min', '', '0', '100', '', '', '', '', '', 'COMP_TEMPO_MINIMO_DI_OFF', ''),
(NOW(), '663_D_30', '663_D_30', 'Defrost priority over compressor protectors', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'DEFR_PRIORITA_SU_COMP', ''),
(NOW(), '886_D_27', '886_D_27', 'Disable decimal point', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '', '', '', '', '', '', '', 'DISABILITA_PUNTO_DECIMALE', ''),
(NOW(), '158_I_20', '158_I_20', 'Maximum defrost duration', '', 'Integral Values', 'integer', '', '', 'r', 'min', '', '1', '199', '', '', '', '', '', 'DEFR_DURATA_MAX', ''),
(NOW(), '716_I_40', '716_I_40', 'Defrost time band 3rd day', '', 'Integral Values', 'integer', '', '', 'rw', 'day', '', '0', '11', '', '', '', '', '', 'FASCIA_ORARIA_DEFR3_DAY', ''),
(NOW(), '232_I_24', '232_I_24', 'Temperature alarm delay', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '199', '', '', '', '', '', 'ALARM_TEMP_DELAY', ''),
(NOW(), '183_I_5', '183_I_5', 'Machine model', '', 'Integral Values', 'integer', '', '', 'r', '', '', '0', '255', '', '', '', '', '', 'MODELLO_MACCHINA', ''),
(NOW(), '717_I_43', '717_I_43', 'Defrost time band 4th day', '', 'Integral Values', 'integer', '', '', 'rw', 'day', '', '0', '11', '', '', '', '', '', 'FASCIA_ORARIA_DEFR4_DAY', ''),
(NOW(), '214_I_27', '214_I_27', 'Dirty cond. alarm delay', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '250', '', '', '', '', '', 'ALARM_COND_DELAY', ''),
(NOW(), '329_I_26', '329_I_26', 'Digital input alarm delay', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '199', '', '', '', '', '', 'ALARM_EXT_RITARDO', ''),
(NOW(), '960_I_42', '960_I_42', 'Time band 3rd minutes', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '59', '', '', '', '', '', 'FASCIA_ORARIA_DEFR3_MINUTE', ''),
(NOW(), '757_A_1', '757_A_1', 'Defrost probe value', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '0', '0', '', '', '', '', '', 'DEFR_SONDA', ''),
(NOW(), '961_I_45', '961_I_45', 'Time band 4th minutes', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '59', '', '', '', '', '', 'FASCIA_ORARIA_DEFR4_MINUTE', ''),
(NOW(), '575_I_21', '575_I_21', 'Defrost delay from power-on or when enabled by digital input', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '199', '', '', '', '', '', 'DEFR_STARTUP_RITARDO', ''),
(NOW(), '804_I_3', '804_I_3', 'RTC minutes', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '59', '', '', '', '', '', 'RTC_MINUTO', ''),
(NOW(), '447_D_29', '447_D_29', 'Display of control temperature frozen during defrost', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '', '', '', '', '', '', '', 'DEFR_BLOCCO_DISPLAY', ''),
(NOW(), '715_I_37', '715_I_37', 'Defrost time band 2nd day', '', 'Integral Values', 'integer', '', '', 'rw', 'day', '', '0', '11', '', '', '', '', '', 'FASCIA_ORARIA_DEFR2_DAY', ''),
(NOW(), '395_I_10', '395_I_10', 'Direct/reverse', '', 'Integral Values', 'integer', '', '', 'r', '', '', '0', '2', '', '', '', '', '', 'REG_DIRECT_REVERSE', ''),
(NOW(), '111_I_31', '111_I_31', 'Enable keypad', '', 'Integral Values', 'integer', '', '', 'rw', '', '', '0', '2', '', '', '', '', '', 'KEYBOARD_ENABLE', ''),
(NOW(), '866_I_52', '866_I_52', 'AUX time band ON day', '', 'Integral Values', 'integer', '', '', 'rw', 'day', '', '0', '11', '', '', '', '', '', 'FASCIA_ORARIA_AUX_ON_DAY', ''),
(NOW(), '928_I_55', '928_I_55', 'AUX time band OFF day', '', 'Integral Values', 'integer', '', '', 'rw', 'day', '', '0', '11', '', '', '', '', '', 'FASCIA_ORARIA_AUX_OFF_DAY', ''),
(NOW(), '209_I_32', '209_I_32', 'ID code (read-only)', '', 'Integral Values', 'integer', '', '', 'r', '', '', '1', '199', '', '', '', '', '', 'CODE_MODIF_PARAM', ''),
(NOW(), '788_I_6', '788_I_6', 'Probe type NTC/PTC', '', 'Integral Values', 'integer', '', '', 'r', '', '', '0', '1', '', '', '', '', '', 'TIPO_SONDE', ''),
(NOW(), '611_A_13', '611_A_13', 'End defrost temperature set point/defrost temperature threshold with temp. control', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '-50', '127', '', '', '', '', '', 'DEFR_TEMPERATURA_FINE', ''),
(NOW(), '268_A_16', '268_A_16', 'High temperature alarm threshold ', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '-50', '150', '', '', '', '', '', 'ALARM_TEMP_SET_H', ''),
(NOW(), '541_D_1', '541_D_1', 'Digital input status', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_DIGIN', ''),
(NOW(), '355_I_1', '355_I_1', 'RTC day of the week', '', 'Integral Values', 'integer', '', '', 'rw', 'day', '', '1', '7', '', '', '', '', '', 'RTC_GIORNO_SETTIM', ''),
(NOW(), '212_I_22', '212_I_22', 'Dripping time', '', 'Integral Values', 'integer', '', '', 'r', 'min', '', '0', '15', '', '', '', '', '', 'DEFR_GOCC_DURATA', ''),
(NOW(), '947_D_28', '947_D_28', 'Defrost at instrument power-on', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'DEFR_STARTUP', ''),
(NOW(), '312_I_51', '312_I_51', 'Night time band OFF minutes', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '59', '', '', '', '', '', 'FASCIA_ORARIA_NIGHT_OFF_MINUTE', ''),
(NOW(), '697_A_4', '697_A_4', 'Probe 3 value', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '0', '0', '', '', '', '', '', 'S_SONDA_3', ''),
(NOW(), '272_A_15', '272_A_15', 'Low temperature  alarm threshold', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '-50', '150', '', '', '', '', '', 'ALARM_TEMP_SET_L', ''),
(NOW(), '696_A_3', '696_A_3', 'Probe 2 value', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '0', '0', '', '', '', '', '', 'S_SONDA_2', ''),
(NOW(), '695_A_2', '695_A_2', 'Regulation temperature', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '0', '0', '', '', '', '', '', 'S_SONDA_1', ''),
(NOW(), '962_I_53', '962_I_53', 'AUX time band ON hour', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '23', '', '', '', '', '', 'FASCIA_ORARIA_AUX_ON_HOUR', ''),
(NOW(), '732_I_11', '732_I_11', 'Start delay after power-on', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '100', '', '', '', '', '', 'COMP_FAN_RITARDO_START', ''),
(NOW(), '837_I_17', '837_I_17', 'Temperature alarm bypass after c.c.', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '15', '', '', '', '', '', 'CC_ESCL_ALM', ''),
(NOW(), '267_D_32', '267_D_32', 'Enable alarm Ed (end defrost by timeout)', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'ALARM_DEFR_ENABLE', ''),
(NOW(), '807_D_5', '807_D_5', 'AUX relay status', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_RELE_AUX', ''),
(NOW(), '114_I_30', '114_I_30', 'AUX output configuration', '', 'Integral Values', 'integer', '', '', 'r', '', '', '0', '3', '', '', '', '', '', 'OUT_AUX_CONFIG', ''),
(NOW(), '158_I_12', '158_I_12', 'Delay between 2 consecutive starts', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '100', '', '', '', '', '', 'COMP_TEMPO_MINIMO_TRA_START', ''),
(NOW(), '866_D_22', '866_D_22', 'Continuos cycle command', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '', '', '', '', '', '', '', 'S_COMANDO_CICLO_CONTINUO', ''),
(NOW(), '327_I_28', '327_I_28', 'Post-dripping timeout', '', 'Integral Values', 'integer', '', '', 'r', 'min', '', '0', '15', '', '', '', '', '', 'FAN_OFF_POST_GOCC', ''),
(NOW(), '701_I_8', '701_I_8', 'Probe measurement stability', '', 'Integral Values', 'integer', '', '', 'r', '', '', '1', '15', '', '', '', '', '', 'SONDE_STABILITA_MISURA', ''),
(NOW(), '876_A_10', '876_A_10', 'Minimum set point allowed', '', 'Analog Values', 'float', '', '', 'rw', '°C/°F', '%.1f', '-50', 'pk54278', '', '', '', '', '', 'REG_SET_MIN', ''),
(NOW(), '878_A_11', '878_A_11', 'Maximum set point allowed', '', 'Analog Values', 'float', '', '', 'rw', '°C/°F', '%.1f', 'pk54279', '150', '', '', '', '', '', 'REG_SET_MAX', ''),
(NOW(), '827_I_14', '827_I_14', 'Minimum compressor ON time', '', 'Integral Values', 'integer', '', '', 'r', 'min', '', '0', '100', '', '', '', '', '', 'COMP_TEMPO_MINIMO_DI_ON', ''),
(NOW(), '507_I_15', '507_I_15', 'Duty setting time', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '100', '', '', '', '', '', 'DUTY_SETTING_DURATA', ''),
(NOW(), '77_D_36', '77_D_36', 'Disable buzzer', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '', '', '', '', '', '', '', 'BUZZER_DISABLE', ''),
(NOW(), '61_I_29', '61_I_29', 'Serial address', '', 'Integral Values', 'integer', '', '', 'r', '', '', '0', '207', '', '', '', '', '', 'SERIAL_ADDRESS', ''),
(NOW(), '350_A_19', '350_A_19', 'Evaporator fan control set point', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '-50', '127', '', '', '', '', '', 'FAN_REG_SET_POINT', ''),
(NOW(), '83_A_17', '83_A_17', 'Dirty cond. alarm set point', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '-50', '150', '', '', '', '', '', 'ALARM_COND_SET', ''),
(NOW(), '678_I_16', '678_I_16', 'Continuous cycle duration', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '15', '', '', '', '', '', 'CC_DURATA', ''),
(NOW(), '321_D_20', '321_D_20', 'Defrost command', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '', '', '', '', '', '', '', 'S_COMANDO_DEFROST', ''),
(NOW(), '668_D_35', '668_D_35', 'Stop evaporator fans during defrost', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'FAN_STATUS_IN_DEFROST', ''),
(NOW(), '6_I_46', '6_I_46', 'Night time band ON day', '', 'Integral Values', 'integer', '', '', 'rw', 'day', '', '0', '11', '', '', '', '', '', 'FASCIA_ORARIA_NIGHT_ON_DAY', ''),
(NOW(), '958_I_36', '958_I_36', 'Time band 1st minutes', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '59', '', '', '', '', '', 'FASCIA_ORARIA_DEFR1_MINUTE', ''),
(NOW(), '110_I_54', '110_I_54', 'AUX time band ON minutes', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '59', '', '', '', '', '', 'FASCIA_ORARIA_AUX_ON_MINUTE', ''),
(NOW(), '393_I_23', '393_I_23', 'Alarm bypass time after defrost', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '15', '', '', '', '', '', 'DEFR_ESCL_ALM_DOPO', ''),
(NOW(), '751_D_37', '751_D_37', 'Enable RTC', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '', '', '', '', '', '', '', 'RTC_ENABLE', ''),
(NOW(), '145_D_31', '145_D_31', 'Time base', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'DEFR_BASE_TEMPI', ''),
(NOW(), '215_D_23', '215_D_23', 'Set point started by RTC', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_SET_NIGHT_RTC', ''),
(NOW(), '128_A_18', '128_A_18', 'Dirty cond. alarm temp. diff.', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '0.1', '20', '', '', '', '', '', 'ALARM_COND_DIFF', ''),
(NOW(), '959_I_39', '959_I_39', 'Time band 2nd minutes', '', 'Integral Values', 'integer', '', '', 'rw', 'min', '', '0', '59', '', '', '', '', '', 'FASCIA_ORARIA_DEFR2_MINUTE', ''),
(NOW(), '539_A_5', '539_A_5', 'Probe 1 offset', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '-12.6', '12', '', '', '', '', '', 'SONDE_OFFSET_SONDA_1', ''),
(NOW(), '541_A_7', '541_A_7', 'Probe 3 offset', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '-12.6', '12', '', '', '', '', '', 'SONDE_OFFSET_SONDA_3', ''),
(NOW(), '540_A_6', '540_A_6', 'Probe 2 offset', '', 'Analog Values', 'float', '', '', 'r', '°C/°F', '%.1f', '-12.6', '12', '', '', '', '', '', 'SONDE_OFFSET_SONDA_2', ''),
(NOW(), '203_D_19', '203_D_19', 'Defrost status', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_STATO_DEFROST', ''),
(NOW(), '48_D_33', '48_D_33', 'Enable evaporator fan control', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'FAN_REG_ENABLE', ''),
(NOW(), '872_D_2', '872_D_2', 'Compressor relay status', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_RELE_COMP', ''),
(NOW(), '812_I_41', '812_I_41', 'Time band 3rd hour', '', 'Integral Values', 'integer', '', '', 'rw', 'hour', '', '0', '23', '', '', '', '', '', 'FASCIA_ORARIA_DEFR3_HOUR', ''),
(NOW(), '515_D_0', '515_D_0', 'OFFLINE', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'OFFLINE', ''),
(NOW(), '568_D_25', '568_D_25', 'Open door alarm status', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALARM_PORTA_APERTA', ''),
(NOW(), '186_D_10', '186_D_10', 'High temperature alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_ALTA_TEMP', ''),
(NOW(), '573_D_15', '573_D_15', 'High temperature condenser alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_ALTA_TEMP_COND', ''),
(NOW(), '258_D_9', '258_D_9', 'Low temperature alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_BASSA_TEMP', ''),
(NOW(), '687_D_18', '687_D_18', 'Functions parameters eeprom alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_EEPROM_PAR_FUNZ', ''),
(NOW(), '640_D_17', '640_D_17', 'Machine parameters eeprom alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_EEPROM_PAR_MACC', ''),
(NOW(), '795_D_11', '795_D_11', 'External immediate alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_IMMEDIATO_ESTERNO', ''),
(NOW(), '899_D_14', '899_D_14', 'High temperature condenser pre-alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_PRE_ALTA_TEMP_COND', ''),
(NOW(), '812_D_12', '812_D_12', 'External delay alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_RITARDATO_ESTERNO', ''),
(NOW(), '286_D_16', '286_D_16', 'Broken RTC alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_RTC_GUASTO', ''),
(NOW(), '8_D_6', '8_D_6', '1st probe alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_SONDA_1', ''),
(NOW(), '9_D_7', '9_D_7', '2nd probe alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_SONDA_2', ''),
(NOW(), '10_D_8', '10_D_8', '3rd probe alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_SONDA_3', ''),
(NOW(), '672_D_13', '672_D_13', 'Timeout defrost alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_ALM_TIMEOUT_DEFROST', ''),
(NOW(), '894_D_24', '894_D_24', 'Open door pre-alarm status', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '', '', '', '', '', '', '', 'S_PRE_ALARM_PORTA_APERTA', '');

CREATE TABLE IF NOT EXISTS `iw_set_ca_pjeasy` (
  `row_date` datetime NOT NULL DEFAULT '2017-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='4.0.0';

REPLACE INTO `iw_set_ca_pjeasy` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), '146_A_14', '1', '1', 'norm', 'change', '', '', '', 0),
(NOW(), '700_I_18', '1', '1', 'norm', 'change', '', '', '', 0),
(NOW(), '554_I_2', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '239_D_34', '1', '1', 'norm', 'change', '', '', '', 0),
(NOW(), '811_I_38', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '68_I_49', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '186_D_26', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '499_A_12', '1', '1', 'norm', 'change', '', '', '', 0),
(NOW(), '192_I_9', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '627_I_33', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '79_D_38', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '810_I_35', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '250_I_48', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '42_A_8', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '102_I_47', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '782_D_4', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '896_I_25', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '152_I_19', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '172_I_57', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '714_I_34', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '858_D_3', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '24_I_56', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '944_I_4', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '164_I_50', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '813_I_44', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '748_D_21', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '269_A_9', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '889_I_13', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '663_D_30', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '886_D_27', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '158_I_20', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '716_I_40', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '232_I_24', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '183_I_5', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '717_I_43', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '214_I_27', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '329_I_26', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '960_I_42', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '757_A_1', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '961_I_45', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '575_I_21', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '804_I_3', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '447_D_29', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '715_I_37', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '395_I_10', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '111_I_31', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '866_I_52', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '928_I_55', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '209_I_32', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '788_I_6', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '611_A_13', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '268_A_16', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '541_D_1', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '355_I_1', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '212_I_22', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '947_D_28', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '312_I_51', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '697_A_4', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '272_A_15', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '696_A_3', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '695_A_2', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '962_I_53', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '732_I_11', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '837_I_17', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '267_D_32', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '807_D_5', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '114_I_30', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '158_I_12', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '866_D_22', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '327_I_28', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '701_I_8', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '876_A_10', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '878_A_11', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '827_I_14', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '507_I_15', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '77_D_36', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '61_I_29', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '350_A_19', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '83_A_17', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '678_I_16', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '321_D_20', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '668_D_35', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '6_I_46', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '958_I_36', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '110_I_54', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '393_I_23', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '751_D_37', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '145_D_31', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '215_D_23', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '128_A_18', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '959_I_39', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '539_A_5', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '541_A_7', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '540_A_6', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '203_D_19', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '48_D_33', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '872_D_2', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), '812_I_41', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), '515_D_0', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '568_D_25', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '186_D_10', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '573_D_15', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '258_D_9', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '687_D_18', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '640_D_17', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '795_D_11', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '899_D_14', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '812_D_12', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '286_D_16', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '8_D_6', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '9_D_7', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '10_D_8', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), '672_D_13', '1', '0', 'norm', 'change', '', 'B', '', 0),
(NOW(), '894_D_24', '1', '0', 'norm', 'change', '', 'B', '', 0);

-- Changelog
--
-- v1 Orginal
--
--
