REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'ID01', 'Carel MasterCella 01', 'ca_mcella_modbus', 'CAREL', '0_3', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID02', 'Carel MasterCella 02', 'ca_mcella_modbus', 'CAREL', '0_2', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID03', 'Carel MasterCella 03', 'ca_mcella_modbus', 'CAREL', '0_1', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID04', 'Carel MasterCella 04', 'ca_mcella_modbus', 'CAREL', '0_4', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID05', 'Carel MasterCella 05', 'ca_mcella_modbus', 'CAREL', '0_5', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID06', 'Carel MasterCella 06', 'ca_mcella_modbus', 'CAREL', '0_6', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID07', 'Carel MasterCella 07', 'ca_mcella_modbus', 'CAREL', '0_7', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID08', 'Carel MasterCella 08', 'ca_mcella_modbus', 'CAREL', '0_8', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID09', 'Carel MasterCella 09', 'ca_mcella_modbus', 'CAREL', '0_9', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID10', 'Carel MasterCella 10', 'ca_mcella_modbus', 'CAREL', '0_10', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID11', 'Carel MasterCella 11', 'ca_mcella_modbus', 'CAREL', '0_11', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID12', 'Carel MasterCella 12', 'ca_mcella_modbus', 'CAREL', '0_12', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID13', 'Carel MasterCella 13', 'ca_mcella_modbus', 'CAREL', '0_13', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '0', '0', 'ID14', 'Carel MasterCella 14', 'ca_mcella_modbus', 'CAREL', '0_14', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID15', 'Carel MasterCella 15', 'ca_mcella_modbus', 'CAREL', '0_15', 'MCELLA', 'MCELLA', 0, ''),
(NOW(), '1', '0', 'ID16', 'Carel MasterCella 16', 'ca_mcella_modbus', 'CAREL', '0_17', 'MCELLA', 'MCELLA', 0, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'mb_mode', 'CAREL', '0', '', '0=RTU|1=ASCII|3=TCP', ''),
(NOW(), 'comm_port', 'CAREL', '6', '', '', ''),
(NOW(), 'comm_parity', 'CAREL', '0', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'comm_data_bits', 'CAREL', '8', '', '', ''),
(NOW(), 'comm_stop_bits', 'CAREL', '2', '', '', ''),
(NOW(), 'comm_baudrate', 'CAREL', '19200', '', '', ''),
(NOW(), 'force_word_not_byte', 'CAREL', '0', '', '0|1', ''),
(NOW(), 'handshake', 'CAREL', '0', '', '0|1|2', ''),
(NOW(), 'check_rate', 'CAREL', '1', 'ms', '', ''),
(NOW(), 'max_outstanding_packets', 'CAREL', '-1', '', '', ''),
(NOW(), 'packet_timeout', 'CAREL', '1', 'sec.', '', ''),
(NOW(), 'idle_event_rate', 'CAREL', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'CAREL', '2000', 'msec.', '', ''),
(NOW(), 'max_error_count', 'CAREL', '2', '', '', ''),
(NOW(), 'mb_request_timeout', 'CAREL', '1000', 'ms', '', ''),
(NOW(), 'mb_request_retries', 'CAREL', '2', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'CAREL', '10', 'min.', '', ''),
(NOW(), 'show_queue_info', 'CAREL', '0', '', '', ''),
(NOW(), 'speed_index_block', 'CAREL', '10', '', '', ''),
(NOW(), 'speed_index_offline', 'CAREL', '10', '', '', ''),
(NOW(), 'speed_index_slow', 'CAREL', '1', '', '', ''),
(NOW(), 'speed_index_norm', 'CAREL', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'CAREL', '2', 'hours', '', ''),
(NOW(), 'max_group_count', 'CAREL', '1', '', '', ''),
(NOW(), 'value_quality_check_limit', 'CAREL', '0', '', '0 = disabled', ''),
(NOW(), 'mux_settle_time', 'CAREL', '1500', 'ms', 'Time for the muxed input to settle. The value shuld be a multiple off 100.', ''),
(NOW(), 'startup_delay', 'CAREL', '15', 'Sec.', '', ''),
(NOW(), 'alarm_handler', 'CAREL', '', '', '', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_mb.exe', 'CAREL', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'MCELLA', 'ca_mcella_modbus_param', 'ca_mcella_modbus_groups');

CREATE TABLE IF NOT EXISTS `iw_par_ca_mcella_modbus_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_ca_mcella_modbus_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 4, '', ''),
(NOW(), 'group_alias', 1, 'cmd', 'Commands'),
(NOW(), 'group_alias', 2, 'Palarm', 'Alarm and digital inputs configuration'),
(NOW(), 'group_alias', 3, 'PConf', 'Configuration parameters'),
(NOW(), 'group_alias', 4, 'Params', 'Main parameters'),
(NOW(), 'group_alias', 5, 'Pdef', 'Defrost parameters'),
(NOW(), 'group_alias', 6, 'Pfan', 'Fan parameters'),
(NOW(), 'group_alias', 7, 'Pprobe', 'Probe parameters'),
(NOW(), 'group_alias', 8, 'Pcompr', 'Compressor parameters'),
(NOW(), 'group_alias', 9, 'RTC', 'RTC parameters'),
(NOW(), 'group_alias', 10, 'HACCP', 'HACCP'),
(NOW(), 'group_alias', 11, 'Status', 'System status'),
(NOW(), 'group_alias', 12, 'Alarms', 'Alarms'),
(NOW(), 'group', 1, 'cmd', 'S_COMANDO_DEFROST'),
(NOW(), 'group', 2, 'cmd', 'S_COMANDO_CICLO_CONTINUO'),
(NOW(), 'group', 3, 'cmd', 'S_COMANDO_BUR'),
(NOW(), 'group', 4, 'cmd', 'S_COMANDO_AUX'),
(NOW(), 'group', 5, 'cmd', 'S_COMANDO_LUCE'),
(NOW(), 'group', 6, 'cmd', 'S_COMANDO_ON_OFF'),
(NOW(), 'group', 1, 'PAlarm', 'ALM_ALTA_TEMP_COND'),
(NOW(), 'group', 2, 'PAlarm', 'DIFFERENZIALE_ALM_FAN'),
(NOW(), 'group', 3, 'Palarm', 'TIPO_SOGLIA_AL_AH'),
(NOW(), 'group', 4, 'Palarm', 'CONFIG_DIGIN_1'),
(NOW(), 'group', 5, 'Palarm', 'CONFIG_DIGIN_2'),
(NOW(), 'group', 6, 'PAlarm', 'STOP_DEFROST_EXT_ALM'),
(NOW(), 'group', 7, 'Palarm', 'RITARDO_EXT_ALM'),
(NOW(), 'group', 8, 'PAlarm', 'ENABLE_ALM_ED1_ED2'),
(NOW(), 'group', 9, 'PAlarm', 'DEFR_STAT_CMD'),
(NOW(), 'group', 10, 'Palarm', 'RIT_ALM_ALTA_TEMP_COND'),
(NOW(), 'group', 11, 'PAlarm', 'DIFFERENZIALE_ALM_AE'),
(NOW(), 'group', 12, 'Palarm', 'TEMPO_SENSORE_DI_LUCE'),
(NOW(), 'group', 13, 'PAlarm', 'THREDHOLD_ALR_HIGH_TEMP'),
(NOW(), 'group', 14, 'PAlarm', 'THREDHOLD_ALR_LOW_TEMP'),
(NOW(), 'group', 1, 'PConf', 'STABILITA_MISURA'),
(NOW(), 'group', 2, 'PConf', 'RALL_VIS_SONDA'),
(NOW(), 'group', 3, 'Pconf', 'SONDA_VIRTUALE'),
(NOW(), 'group', 4, 'PConf', 'SELECT_UM'),
(NOW(), 'group', 5, 'PConf', 'DECIMAL_POINT'),
(NOW(), 'group', 6, 'PConf', 'CONFIG_SONDA2'),
(NOW(), 'group', 7, 'PConf', 'CONFIG_SONDA3'),
(NOW(), 'group', 8, 'PConf', 'CONFIG_SONDA4'),
(NOW(), 'group', 9, 'PConf', 'TIPO_NTC'),
(NOW(), 'group', 10, 'PConf', 'EXTERNAL_TERMINAL'),
(NOW(), 'group', 11, 'Pconf', 'INTERNAL_TERMINAL'),
(NOW(), 'group', 12, 'Pconf', 'RELE4'),
(NOW(), 'group', 13, 'Pconf', 'DISABLE_KEY_IR'),
(NOW(), 'group', 14, 'Pconf', 'CODICE_ABILIT_RC'),
(NOW(), 'group', 15, 'Pconf', 'DISABLE_BUZZER'),
(NOW(), 'group', 16, 'Pconf', 'RELE5'),
(NOW(), 'group', 17, 'PConf', 'BLOCCO_TASTI'),
(NOW(), 'group', 18, 'Pconf', 'RTC_LUCE_AUX'),
(NOW(), 'group', 1, 'Params', 'SET_POINT'),
(NOW(), 'group', 2, 'Params', 'CALIB_SONDA1'),
(NOW(), 'group', 3, 'Params', 'CALIB_SONDA2'),
(NOW(), 'group', 4, 'Params', 'CALIB_SONDA3'),
(NOW(), 'group', 5, 'Params', 'CALIB_SONDA4'),
(NOW(), 'group', 6, 'PArams', 'PROFILO_STAMPA'),
(NOW(), 'group', 7, 'Params', 'RITARDO_ALM_HACCP'),
(NOW(), 'group', 8, 'Params', 'S_SONDA_1'),
(NOW(), 'group', 9, 'Params', 'EVAP_TEMP'),
(NOW(), 'group', 10, 'Params', 'S_SONDA_3'),
(NOW(), 'group', 11, 'Params', 'S_SONDA_4'),
(NOW(), 'group', 12, 'Params', 'S_SONDA_5'),
(NOW(), 'group', 13, 'Params', 'AMB_TEMP'),
(NOW(), 'group', 1, 'PDef', 'DURATA_NOMINALE_DEFROST'),
(NOW(), 'group', 2, 'PDef', 'TIPO_DEFROST'),
(NOW(), 'group', 3, 'Pdef', 'VIS_SONDA_DEF_1'),
(NOW(), 'group', 4, 'Pdef', 'VIS_SONDA_DEF_2'),
(NOW(), 'group', 5, 'Pdef', 'RITARDO_INS_DEFROST'),
(NOW(), 'group', 6, 'Pdef', 'ENABLE_DISABLE_DEFR'),
(NOW(), 'group', 7, 'Pdef', 'RITARDO_DEFROST_STARTUP'),
(NOW(), 'group', 8, 'Pdef', 'BLOCCO_DISPLAY_DEFROST'),
(NOW(), 'group', 9, 'Pdef', 'ESCL_ALM_DOPO_DEFROST'),
(NOW(), 'group', 10, 'Pdef', 'PRIORITA_DEFROST_COMP'),
(NOW(), 'group', 11, 'Pdef', 'RUNNING_TIME_COMP'),
(NOW(), 'group', 12, 'Pdef', 'TEMP_RUNNING_TIME'),
(NOW(), 'group', 13, 'Pdef', 'DEFROST_AVANZATI'),
(NOW(), 'group', 14, 'Pdef', 'BASE_TEMPI_DEFROST'),
(NOW(), 'group', 15, 'Pdef', 'DRIPPING_TIME'),
(NOW(), 'group', 16, 'Pdef', 'PROP_DURATA_DEFROST'),
(NOW(), 'group', 17, 'Pdef', 'TIME_FROM_EACH_DEFR'),
(NOW(), 'group', 18, 'Pdef', 'TIMEOUT_DEFR'),
(NOW(), 'group', 19, 'Pdef', 'DURATA_MAX_DEFROST_E2'),
(NOW(), 'group', 20, 'Pdef', 'TEMP_FINE_DEFROST_E1'),
(NOW(), 'group', 21, 'Pdef', 'TEMP_FINE_DEFROST_E2'),
(NOW(), 'group', 1, 'Pfan', 'MANAG_FAN'),
(NOW(), 'group', 2, 'Pfan', 'TEMP_ON_FAN'),
(NOW(), 'group', 3, 'Pfan', 'TEMP_OFF_FAN'),
(NOW(), 'group', 4, 'Pfan', 'FAN_IN_DEFROST'),
(NOW(), 'group', 5, 'Pfan', 'TEMP_OFF_FAN_COND'),
(NOW(), 'group', 6, 'PFan', 'DIFF_FAN_COND'),
(NOW(), 'group', 7, 'Pfan', 'TIME_STOP_FANS_AFTER_DEFR'),
(NOW(), 'group', 1, 'Pprobe', 'SETPT_MIN'),
(NOW(), 'group', 2, 'Pprobe', 'SETPT_MAX'),
(NOW(), 'group', 3, 'Pprobe', 'MODALITA_FUNZIONAMENTO'),
(NOW(), 'group', 4, 'Pprobe', 'SET_POINT_NOTTURNO'),
(NOW(), 'group', 5, 'Pprobe', 'ENABLE_MONITOR_TEMP'),
(NOW(), 'group', 6, 'Pprobe', 'HYST_SETPT'),
(NOW(), 'group', 7, 'PProbe', 'MAX_TEMP_LETTA'),
(NOW(), 'group', 8, 'PProbe', 'MIN_TEMP_LETTA'),
(NOW(), 'group', 9, 'PProbe', 'INTEVALLO_MONITOR_TEMP'),
(NOW(), 'group', 10, 'PProbe', 'S_DI_VARIATION_CALC'),
(NOW(), 'group', 1, 'PCompr', 'RITARDO_START_COMP_FAN'),
(NOW(), 'group', 2, 'Pcompr', 'TEMPO_MINIMO_TRA_START'),
(NOW(), 'group', 3, 'Pcompr', 'TEMPO_MINIMO_DI_OFF'),
(NOW(), 'group', 4, 'Pcompr', 'TEMPO_MINIMO_DI_ON'),
(NOW(), 'group', 5, 'Pcompr', 'DUTY_SETTING'),
(NOW(), 'group', 6, 'Pcompr', 'ESCL_ALM_DOPO_CC'),
(NOW(), 'group', 7, 'Pcompr', 'TEMPO_MAX_PUMP_DOWN'),
(NOW(), 'group', 8, 'Pcompr', 'RIT_START_COMP_DOPO_PD'),
(NOW(), 'group', 9, 'Pcompr', 'ENABLE_AUTOSTART_PD'),
(NOW(), 'group', 10, 'Pcompr', 'PD_TEMPO_PRESS'),
(NOW(), 'group', 11, 'Pcompr', 'DELAY_2_COMP'),
(NOW(), 'group', 12, 'Pcompr', 'DURATA_CICLO_CONT'),
(NOW(), 'group', 1, 'RTC', 'RTC_ANNO'),
(NOW(), 'group', 2, 'RTC', 'RTC_MESE'),
(NOW(), 'group', 3, 'RTC', 'RTC_GIORNO_MESE'),
(NOW(), 'group', 4, 'RTC', 'RTC_GIORNO_SETTIM'),
(NOW(), 'group', 5, 'RTC', 'RTC_ORA'),
(NOW(), 'group', 6, 'RTC', 'RTC_MINUTO'),
(NOW(), 'group', 7, 'RTC', 'FASCIA_ORARIA_1_GIORNO'),
(NOW(), 'group', 8, 'RTC', 'FASCIA_ORARIA_1_ORA'),
(NOW(), 'group', 9, 'RTC', 'FASCIA_ORARIA_1_MINUTO'),
(NOW(), 'group', 10, 'RTC', 'FASCIA_ORARIA_2_GIORNO'),
(NOW(), 'group', 11, 'RTC', 'FASCIA_ORARIA_2_ORA'),
(NOW(), 'group', 12, 'RTC', 'FASCIA_ORARIA_2_MINUTO'),
(NOW(), 'group', 13, 'RTC', 'FASCIA_ORARIA_3_GIORNO'),
(NOW(), 'group', 14, 'RTC', 'FASCIA_ORARIA_3_ORA'),
(NOW(), 'group', 15, 'RTC', 'FASCIA_ORARIA_3_MINUTO'),
(NOW(), 'group', 16, 'RTC', 'FASCIA_ORARIA_4_GIORNO'),
(NOW(), 'group', 17, 'RTC', 'FASCIA_ORARIA_4_ORA'),
(NOW(), 'group', 18, 'RTC', 'FASCIA_ORARIA_4_MINUTO'),
(NOW(), 'group', 19, 'RTC', 'FASCIA_ORARIA_5_GIORNO'),
(NOW(), 'group', 20, 'RTC', 'FASCIA_ORARIA_5_ORA'),
(NOW(), 'group', 21, 'RTC', 'FASCIA_ORARIA_5_MINUTO'),
(NOW(), 'group', 22, 'RTC', 'FASCIA_ORARIA_6_GIORNO'),
(NOW(), 'group', 23, 'RTC', 'FASCIA_ORARIA_6_ORA'),
(NOW(), 'group', 24, 'RTC', 'FASCIA_ORARIA_6_MINUTO'),
(NOW(), 'group', 25, 'RTC', 'FASCIA_ORARIA_7_GIORNO'),
(NOW(), 'group', 26, 'RTC', 'FASCIA_ORARIA_7_ORA'),
(NOW(), 'group', 27, 'RTC', 'FASCIA_ORARIA_7_MINUTO'),
(NOW(), 'group', 28, 'RTC', 'FASCIA_ORARIA_8_GIORNO'),
(NOW(), 'group', 29, 'RTC', 'FASCIA_ORARIA_8_ORA'),
(NOW(), 'group', 30, 'RTC', 'FASCIA_ORARIA_8_MINUTO'),
(NOW(), 'group', 31, 'RTC', 'FASCIA_ORARIA_ON_GIORNO'),
(NOW(), 'group', 32, 'RTC', 'FASCIA_ORARIA_ON_ORA'),
(NOW(), 'group', 33, 'RTC', 'FASCIA_ORARIA_ON_MINUTO'),
(NOW(), 'group', 34, 'RTC', 'FASCIA_ORARIA_OFF_GIORNO'),
(NOW(), 'group', 35, 'RTC', 'FASCIA_ORARIA_OFF_ORA'),
(NOW(), 'group', 36, 'RTC', 'FASCIA_ORARIA_OFF_MINUTO'),
(NOW(), 'group', 1, 'HACCP', 'HA_ANNO'),
(NOW(), 'group', 2, 'HACCP', 'HA_MESE'),
(NOW(), 'group', 3, 'HACCP', 'HA_GIORNO'),
(NOW(), 'group', 4, 'HACCP', 'HA_ORA'),
(NOW(), 'group', 5, 'HACCP', 'HA_MINUTO'),
(NOW(), 'group', 6, 'HACCP', 'HA_DURATA'),
(NOW(), 'group', 7, 'HACCP', 'HA1_ANNO'),
(NOW(), 'group', 8, 'HACCP', 'HA1_MESE'),
(NOW(), 'group', 9, 'HACCP', 'HA1_GIORNO'),
(NOW(), 'group', 10, 'HACCP', 'HA1_ORA'),
(NOW(), 'group', 11, 'HACCP', 'HA1_MINUTO'),
(NOW(), 'group', 12, 'HACCP', 'HA1_DURATA'),
(NOW(), 'group', 13, 'HACCP', 'HA2_ANNO'),
(NOW(), 'group', 14, 'HACCP', 'HA2_MESE'),
(NOW(), 'group', 15, 'HACCP', 'HA2_GIORNO'),
(NOW(), 'group', 16, 'HACCP', 'HA2_ORA'),
(NOW(), 'group', 17, 'HACCP', 'HA2_MINUTO'),
(NOW(), 'group', 18, 'HACCP', 'HA2_DURATA'),
(NOW(), 'group', 19, 'HACCP', 'HF_ANNO'),
(NOW(), 'group', 20, 'HACCP', 'HF_MESE'),
(NOW(), 'group', 21, 'HACCP', 'HF_GIORNO'),
(NOW(), 'group', 22, 'HACCP', 'HF_ORA'),
(NOW(), 'group', 23, 'HACCP', 'HF_MINUTO'),
(NOW(), 'group', 24, 'HACCP', 'HF_DURATA'),
(NOW(), 'group', 25, 'HACCP', 'HF1_ANNO'),
(NOW(), 'group', 26, 'HACCP', 'HF1_MESE'),
(NOW(), 'group', 27, 'HACCP', 'HF1_GIORNO'),
(NOW(), 'group', 28, 'HACCP', 'HF1_ORA'),
(NOW(), 'group', 29, 'HACCP', 'HF1_MINUTO'),
(NOW(), 'group', 30, 'HACCP', 'HF1_DURATA'),
(NOW(), 'group', 31, 'HACCP', 'HF2_ANNO'),
(NOW(), 'group', 32, 'HACCP', 'HF2_MESE'),
(NOW(), 'group', 33, 'HACCP', 'HF2_GIORNO'),
(NOW(), 'group', 34, 'HACCP', 'HF2_ORA'),
(NOW(), 'group', 35, 'HACCP', 'HF2_MINUTO'),
(NOW(), 'group', 36, 'HACCP', 'HF2_DURATA'),
(NOW(), 'group', 37, 'HACCP', 'NUMERO_HA'),
(NOW(), 'group', 38, 'HACCP', 'NUMERO_HF'),
(NOW(), 'group', 1, 'Status', 'S_STATO_PORTA'),
(NOW(), 'group', 2, 'Status', 's_rl1'),
(NOW(), 'group', 22, 'PDef', 's_rl3'),
(NOW(), 'group', 3, 'Status', 's_rl4'),
(NOW(), 'group', 4, 'Status', 's_rl5'),
(NOW(), 'group', 5, 'Status', 'S_DIGIN_1'),
(NOW(), 'group', 6, 'Status', 'S_DIGIN_2'),
(NOW(), 'group', 7, 'Status', 'DEFROST_STAT'),
(NOW(), 'group', 8, 'Status', 'S_STATO_CICLO_CONTINUO'),
(NOW(), 'group', 8, 'PFan', 's_rl2'),
(NOW(), 'group', 1, 'Alarms', 'OFFLINE'),
(NOW(), 'group', 2, 'Alarms', 'ALR_VIRTUAL_PROBE'),
(NOW(), 'group', 3, 'Alarms', 'S_ALM_SONDA_1'),
(NOW(), 'group', 4, 'Alarms', 'S_ALM_SONDA_2'),
(NOW(), 'group', 5, 'Alarms', 'S_ALM_SONDA_3'),
(NOW(), 'group', 6, 'Alarms', 'S_ALM_SONDA_4'),
(NOW(), 'group', 7, 'Alarms', 'S_ALM_SONDA_5'),
(NOW(), 'group', 8, 'Alarms', 'ALR_LOW_TEMP'),
(NOW(), 'group', 9, 'Alarms', 'ALR_HIGH_TEMP'),
(NOW(), 'group', 10, 'Alarms', 'S_ALM_IMMEDIATO_ESTERNO'),
(NOW(), 'group', 11, 'Alarms', 'S_ALM_RITARDATO_ESTERNO'),
(NOW(), 'group', 12, 'Alarms', 'S_ALM_TIMEOUT_DEF_EVAP1'),
(NOW(), 'group', 13, 'Alarms', 'S_ALM_TIMEOUT_DEF_EVAP2'),
(NOW(), 'group', 14, 'Alarms', 'S_ALM_BASSA_PRESSIONE'),
(NOW(), 'group', 15, 'Alarms', 'S_ALM_ALTA_TEMP_COND'),
(NOW(), 'group', 16, 'Alarms', 'S_ALM_TIMEOUT_PORTA'),
(NOW(), 'group', 17, 'Alarms', 'S_ALM_RTC_GUASTO'),
(NOW(), 'group', 18, 'Alarms', 'ALR_EEPROM_MAC'),
(NOW(), 'group', 19, 'Alarms', 'ALR_EEPROM_FUNZ'),
(NOW(), 'group', 20, 'Alarms', 'S_ALM_HA'),
(NOW(), 'group', 21, 'Alarms', 'S_ALM_HF'),
(NOW(), 'group', 22, 'Alarms', 'S_ALM_AUTOSTART_PD'),
(NOW(), 'group', 50, 'PAlarm', 'SOGLIA_ALM_ANTIFREEZE'),
(NOW(), 'group', 51, 'PAlarm', 'RITARDO_ALM_ANTIFREEZE'),
(NOW(), 'group', 52, 'Alarms', 'S_ALM_ANTIFREEZE'),
(NOW(), 'group', 60, 'cmd', 'TIPO_SONDA'),
(NOW(), 'group', 61, 'cmd', 'TIPO_CONTROLLO'),
(NOW(), 'group', 62, 'cmd', 'MODELLO_MACCHINA'),
(NOW(), 'group', 63, 'cmd', 'PRESENZA_RTC'),
(NOW(), 'group', 64, 'cmd', 'PASSWORD');

CREATE TABLE IF NOT EXISTS `iw_par_ca_mcella_modbus_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_ca_mcella_modbus_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'S_COMANDO_DEFROST', '0_D_34', 'Defrost request command', 'Defr', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_33_X_N_5_33_X_N', ''),
(NOW(), 'S_COMANDO_CICLO_CONTINUO', '0_D_36', 'Continuous cycle request command', 'C.Cycle', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_35_X_N_5_35_X_N', ''),
(NOW(), 'S_COMANDO_BUR', '0_D_56', 'Low relative humidity command', '%.rel.hum.', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_55_X_N_5_55_X_N', ''),
(NOW(), 'S_COMANDO_AUX', '0_D_57', 'AUX enabling command', 'Aux', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_56_X_N_5_56_X_N', ''),
(NOW(), 'S_COMANDO_LUCE', '0_D_58', 'LIGHT enabling command', 'Light', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_57_X_N_5_57_X_N', ''),
(NOW(), 'S_COMANDO_ON_OFF', '0_D_59', 'Control ON/OFF command', 'On/Off', 'Digital IO', 'boolean', '1', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_58_X_N_5_58_X_N', ''),
(NOW(), 'ALM_ALTA_TEMP_COND', '0_A_29', 'Condenser high temperature alarm threshold', 'Ac', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '0', '200', '1', '0', '1000', '0', '100', '3_28_I16_N_6_28_I16_N', ''),
(NOW(), 'DIFFERENZIALE_ALM_FAN', '0_A_26', 'Alarm and fan differential', 'A0', 'Analog Values', 'float', '2', '-1', 'rw', '&deg;C', '%.1f', '0,1', '20', '1', '0', '1000', '0', '100', '3_25_I16_N_6_25_I16_N', ''),
(NOW(), 'TIPO_SOGLIA_AL_AH', '0_D_48', 'AL and AH threshold type', 'A1', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_47_X_N_5_47_X_N', ''),
(NOW(), 'CONFIG_DIGIN_1', '0_I_51', 'Digital input 1 configuration', 'A4', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '12', '', '', '', '', '', '3_150_I16_N_6_150_I16_N', ''),
(NOW(), 'CONFIG_DIGIN_2', '0_I_52', 'Digital input 2 configuration', 'A5', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '12', '', '', '', '', '', '3_151_I16_N_6_151_I16_N', ''),
(NOW(), 'STOP_DEFROST_EXT_ALM', '0_I_53', 'Compressor cut-out from external alarm', 'A6', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '100', '', '', '', '', '', '3_152_I16_N_6_152_I16_N', ''),
(NOW(), 'RITARDO_EXT_ALM', '0_I_54', 'External alarm delay detection', 'A7', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '250', '', '', '', '', '', '3_153_I16_N_6_153_I16_N', ''),
(NOW(), 'ENABLE_ALM_ED1_ED2', '0_D_49', 'Enable Ed1 and Ed2 alarms', 'A8', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_48_X_N_5_48_X_N', ''),
(NOW(), 'DEFR_STAT_CMD', '0_I_50', 'Delay alarm low and high temperature', 'Ad', 'Integral Values', 'integer', '120', '-1', 'rw', 'min', '', '0', '250', '', '', '', '', '', '3_149_I16_N_6_149_I16_N', ''),
(NOW(), 'RIT_ALM_ALTA_TEMP_COND', '0_I_56', 'Condenser high temperature alarm delay', 'Acd', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '250', '', '', '', '', '', '3_155_I16_N_6_155_I16_N', ''),
(NOW(), 'DIFFERENZIALE_ALM_AE', '0_A_30', 'Differential alarm condencer high temp.', 'AE', 'Analog Values', 'float', '10', '-1', 'rw', '&deg;C', '%.1f', '0,1', '20', '1', '0', '1000', '0', '100', '3_29_I16_N_6_29_I16_N', ''),
(NOW(), 'TEMPO_SENSORE_DI_LUCE', '0_I_57', 'Light off time by light sensor', 'AF', 'Integral Values', 'integer', '0', '-1', 'rw', 'Sec', '', '0', '250', '', '', '', '', '', '3_156_I16_N_6_156_I16_N', ''),
(NOW(), 'THREDHOLD_ALR_HIGH_TEMP', '0_A_28', 'High temperature alarm threshold', 'AH', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '1', '0', '1000', '0', '100', '3_27_I16_N_6_27_I16_N', ''),
(NOW(), 'THREDHOLD_ALR_LOW_TEMP', '0_A_27', 'Low temperature alarm threshold', 'AL', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '1', '0', '1000', '0', '100', '3_26_I16_N_6_26_I16_N', ''),
(NOW(), 'STABILITA_MISURA', '0_I_15', 'Measurement stability', '/2', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '1', '15', '', '', '', '', '', '3_114_I16_N_6_114_I16_N', ''),
(NOW(), 'RALL_VIS_SONDA', '0_I_16', 'Probe display slowdown', '/3', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '15', '', '', '', '', '', '3_115_I16_N_6_115_I16_N', ''),
(NOW(), 'SONDA_VIRTUALE', '0_I_17', 'Virtual probe', '/4', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '100', '', '', '', '', '', '3_116_I16_N_6_116_I16_N', ''),
(NOW(), 'SELECT_UM', '0_D_40', 'Select °C/°F  (0 = °C; 1 = °F)', '/5', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_39_X_N_5_39_X_N', ''),
(NOW(), 'DECIMAL_POINT', '0_D_41', 'Decimal point (0 =YES, 1 =NO)', '/6', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_40_X_N_5_40_X_N', ''),
(NOW(), 'CONFIG_SONDA2', '0_I_21', 'Evaporator probe configuration', '/A2', 'Integral Values', 'integer', '2', '-1', 'rw', '', '', '0', '3', '', '', '', '', '', '3_120_I16_N_6_120_I16_N', ''),
(NOW(), 'CONFIG_SONDA3', '0_I_22', 'Probe 3 configuration', '/A3', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '3', '', '', '', '', '', '3_121_I16_N_6_121_I16_N', ''),
(NOW(), 'CONFIG_SONDA4', '0_I_23', 'Probe 4 configuration', '/A4', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '3', '', '', '', '', '', '3_122_I16_N_6_122_I16_N', ''),
(NOW(), 'TIPO_NTC', '0_I_20', 'Select probe type', '/P', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '2', '', '', '', '', '', '3_119_I16_N_6_119_I16_N', ''),
(NOW(), 'EXTERNAL_TERMINAL', '0_I_19', 'Display on external terminal', '/tE', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '6', '', '', '', '', '', '3_118_I16_N_6_118_I16_N', ''),
(NOW(), 'INTERNAL_TERMINAL', '0_I_18', 'Display on internal terminal', '/tI', 'Integral Values', 'integer', '1', '-1', 'rw', '', '', '1', '6', '', '', '', '', '', '3_117_I16_N_6_117_I16_N', ''),
(NOW(), 'RELE4', '0_I_61', 'Relay 4', 'H1', 'Integral Values', 'integer', '1', '-1', 'rw', '', '', '0', '10', '', '', '', '', '', '3_160_I16_N_6_160_I16_N', ''),
(NOW(), 'DISABLE_KEY_IR', '0_I_62', 'Disable keyboard/IR', 'H2', 'Integral Values', 'integer', '1', '-1', 'rw', '', '', '0', '6', '', '', '', '', '', '3_161_I16_N_6_161_I16_N', ''),
(NOW(), 'CODICE_ABILIT_RC', '0_I_63', 'Code to enable remote control', 'H3', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '255', '', '', '', '', '', '3_162_I16_N_6_162_I16_N', ''),
(NOW(), 'DISABLE_BUZZER', '0_D_53', 'Disable buzzer', 'H4', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_52_X_N_5_52_X_N', ''),
(NOW(), 'RELE5', '0_I_64', 'Relay 5', 'H5', 'Integral Values', 'integer', '1', '-1', 'rw', '', '', '0', '10', '', '', '', '', '', '3_163_I16_N_6_163_I16_N', ''),
(NOW(), 'BLOCCO_TASTI', '0_I_65', 'Key block', 'H6', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '255', '', '', '', '', '', '3_164_I16_N_6_164_I16_N', ''),
(NOW(), 'RTC_LUCE_AUX', '0_D_60', 'Light or Aux selection from RTC', 'H8', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_59_X_N_5_59_X_N', ''),
(NOW(), 'SET_POINT', '0_A_16', 'Set point', 'St', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '1', '0', '1000', '0', '100', '3_15_I16_N_6_15_I16_N', ''),
(NOW(), 'CALIB_SONDA1', '0_A_11', 'Room probe calibration', '/c1', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '-20', '20', '1', '0', '1000', '0', '100', '3_10_I16_N_6_10_I16_N', ''),
(NOW(), 'CALIB_SONDA2', '0_A_12', 'Evaporator probe calibration', '/c2', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '-20', '20', '1', '0', '1000', '0', '100', '3_11_I16_N_6_11_I16_N', ''),
(NOW(), 'CALIB_SONDA3', '0_A_13', 'Probe 3 calibration', '/c3', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '-20', '20', '1', '0', '1000', '0', '100', '3_12_I16_N_6_12_I16_N', ''),
(NOW(), 'CALIB_SONDA4', '0_A_14', 'Probe 4 calibration', '/c4', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '-20', '20', '1', '0', '1000', '0', '100', '3_13_I16_N_6_13_I16_N', ''),
(NOW(), 'PROFILO_STAMPA', '0_I_66', 'Report printed', 'HPr', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '15', '', '', '', '', '', '3_165_I16_N_6_165_I16_N', ''),
(NOW(), 'RITARDO_ALM_HACCP', '0_I_69', 'HACCP alarm delay', 'Htd', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '250', '', '', '', '', '', '3_168_I16_N_6_168_I16_N', ''),
(NOW(), 'S_SONDA_1', '0_A_4', 'Room temperature', 's_pr1', 'Analog Values', 'float', '0', '-1', 'r', '&deg;C', '%.1f', '0', '0', '1', '0', '1000', '0', '100', '3_3_I16_N_-_-_-_-', ''),
(NOW(), 'EVAP_TEMP', '0_A_5', 'Evaporator temperature', 's_pr2', 'Analog Values', 'float', '0', '-1', 'r', '&deg;C', '%.1f', '0', '0', '1', '0', '1000', '0', '100', '3_4_I16_N_-_-_-_-', ''),
(NOW(), 'S_SONDA_3', '0_A_6', 'Probe 3 value', 's_pr3', 'Analog Values', 'float', '0', '-1', 'r', '&deg;C', '%.1f', '0', '0', '1', '0', '1000', '0', '100', '3_5_I16_N_-_-_-_-', ''),
(NOW(), 'S_SONDA_4', '0_A_7', 'Probe 4 value', 's_pr4', 'Analog Values', 'float', '0', '-1', 'r', '&deg;C', '%.1f', '0', '0', '1', '0', '1000', '0', '100', '3_6_I16_N_-_-_-_-', ''),
(NOW(), 'S_SONDA_5', '0_A_8', 'Probe 5 value', 's_pr5', 'Analog Values', 'float', '120', '-1', 'r', '&deg;C', '%.1f', '0', '0', '1', '0', '1000', '0', '100', '3_7_I16_N_-_-_-_-', ''),
(NOW(), 'AMB_TEMP', '0_A_3', 'Virtual probe', 's_prre', 'Analog Values', 'float', '50', '-1', 'r', '&deg;C', '%.1f', '0', '0', '1', '0', '1000', '0', '100', '3_2_I16_N_-_-_-_-', ''),
(NOW(), 'DURATA_NOMINALE_DEFROST', '0_I_48', 'Duration nominal defrost', 'dn', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '1', '100', '', '', '', '', '', '3_147_I16_N_6_147_I16_N', ''),
(NOW(), 'TIPO_DEFROST', '0_I_37', 'Defrost type', 'd0', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '3', '', '', '', '', '', '3_136_I16_N_6_136_I16_N', ''),
(NOW(), 'VIS_SONDA_DEF_1', '0_A_1', '1 defrost probe display', 'd/1', 'Analog Values', 'float', '0', '-1', 'r', '&deg;C', '%.1f', '0', '0', '1', '0', '1000', '0', '100', '3_0_I16_N_-_-_-_-', ''),
(NOW(), 'VIS_SONDA_DEF_2', '0_A_2', '2 defrost probe display', 'd/2', 'Analog Values', 'float', '0', '-1', 'r', '&deg;C', '%.1f', '0', '0', '1', '0', '1000', '0', '100', '3_1_I16_N_-_-_-_-', ''),
(NOW(), 'RITARDO_INS_DEFROST', '0_I_41', 'defrost start-up delay', 'd3', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '250', '', '', '', '', '', '3_140_I16_N_6_140_I16_N', ''),
(NOW(), 'ENABLE_DISABLE_DEFR', '0_D_45', 'Defrost at power on', 'd4', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_44_X_N_5_44_X_N', ''),
(NOW(), 'RITARDO_DEFROST_STARTUP', '0_I_42', 'Defrost delay at power on', 'd5', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '250', '', '', '', '', '', '3_141_I16_N_6_141_I16_N', ''),
(NOW(), 'BLOCCO_DISPLAY_DEFROST', '0_I_43', 'Display locked during defrost', 'd6', 'Integral Values', 'integer', '1', '-1', 'rw', '', '', '0', '2', '', '', '', '', '', '3_142_I16_N_6_142_I16_N', ''),
(NOW(), 'ESCL_ALM_DOPO_DEFROST', '0_I_45', 'Alarm cut-out after defrost', 'd8', 'Integral Values', 'integer', '1', '-1', 'rw', 'hour', '', '0', '15', '', '', '', '', '', '3_144_I16_N_6_144_I16_N', ''),
(NOW(), 'PRIORITA_DEFROST_COMP', '0_D_46', 'Defrost priority over compr. protection', 'd9', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_45_X_N_5_45_X_N', ''),
(NOW(), 'RUNNING_TIME_COMP', '0_I_46', 'Defrost start-up based on compressor running time', 'd10', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '250', '', '', '', '', '', '3_145_I16_N_6_145_I16_N', ''),
(NOW(), 'TEMP_RUNNING_TIME', '0_A_25', 'Temperature threshold of running time', 'd11', 'Analog Values', 'float', '1', '-1', 'rw', '&deg;C', '%.1f', '-20', '20', '1', '0', '1000', '0', '100', '3_24_I16_N_6_24_I16_N', ''),
(NOW(), 'DEFROST_AVANZATI', '0_I_47', 'Advanced defrosts', 'd12', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '3', '', '', '', '', '', '3_146_I16_N_6_146_I16_N', ''),
(NOW(), 'BASE_TEMPI_DEFROST', '0_D_47', 'Time basis for defrost', 'dC', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_46_X_N_5_46_X_N', ''),
(NOW(), 'DRIPPING_TIME', '0_I_44', 'Dripping time after defrost', 'dd', 'Integral Values', 'integer', '1', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '3_143_I16_N_6_143_I16_N', ''),
(NOW(), 'PROP_DURATA_DEFROST', '0_I_49', 'Proportional factor of dl variation', 'dH', 'Integral Values', 'integer', '50', '-1', 'rw', '', '', '0', '100', '', '', '', '', '', '3_148_I16_N_6_148_I16_N', ''),
(NOW(), 'TIME_FROM_EACH_DEFR', '0_I_38', 'Interval between defrost', 'dI', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '250', '', '', '', '', '', '3_137_I16_N_6_137_I16_N', ''),
(NOW(), 'TIMEOUT_DEFR', '0_I_39', 'Maximum duration of defrost', 'dP1', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '1', '250', '', '', '', '', '', '3_138_I16_N_6_138_I16_N', ''),
(NOW(), 'DURATA_MAX_DEFROST_E2', '0_I_40', 'Maximum defrost duration of aux. evaporator', 'dP2', 'Integral Values', 'integer', '30', '-1', 'rw', 'min', '', '1', '250', '', '', '', '', '', '3_139_I16_N_6_139_I16_N', ''),
(NOW(), 'TEMP_FINE_DEFROST_E1', '0_A_23', 'Evaporator defrost end temperature', 'dt1', 'Analog Values', 'float', '4', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '1', '0', '1000', '0', '100', '3_22_I16_N_6_22_I16_N', ''),
(NOW(), 'TEMP_FINE_DEFROST_E2', '0_A_24', 'Aux. evaporator defrost end temperature', 'dt2', 'Analog Values', 'float', '4', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '1', '0', '1000', '0', '100', '3_23_I16_N_6_23_I16_N', ''),
(NOW(), 'MANAG_FAN', '0_I_58', 'Fan management', 'F0', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '2', '', '', '', '', '', '3_157_I16_N_6_157_I16_N', ''),
(NOW(), 'TEMP_ON_FAN', '0_A_31', 'Temperature fan start-up', 'F1', 'Analog Values', 'float', '5', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '1', '0', '1000', '0', '100', '3_30_I16_N_6_30_I16_N', ''),
(NOW(), 'TEMP_OFF_FAN', '0_D_51', 'Fan off with compressor off', 'F2', 'Digital IO', 'boolean', '1', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_50_X_N_5_50_X_N', ''),
(NOW(), 'FAN_IN_DEFROST', '0_D_52', 'Fans on defrost', 'F3', 'Digital IO', 'boolean', '1', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_51_X_N_5_51_X_N', ''),
(NOW(), 'TEMP_OFF_FAN_COND', '0_A_32', 'Temperature fan stopped', 'F4', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '1', '0', '1000', '0', '100', '3_31_I16_N_6_31_I16_N', ''),
(NOW(), 'DIFF_FAN_COND', '0_A_33', 'Differential of start condenser fan', 'F5', 'Analog Values', 'float', '0', '-1', 'rw', '', '%.1f', '0,1', '20', '1', '0', '1000', '0', '100', '3_32_I16_N_6_32_I16_N', ''),
(NOW(), 'TIME_STOP_FANS_AFTER_DEFR', '0_I_59', 'Fan off time after defrost', 'Fd', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '3_158_I16_N_6_158_I16_N', ''),
(NOW(), 'SETPT_MIN', '0_A_18', 'Set point min. value', 'r1', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '-50', '18', '1', '0', '1000', '0', '100', '3_17_I16_N_6_17_I16_N', ''),
(NOW(), 'SETPT_MAX', '0_A_19', 'Set point max. value', 'r2', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '17', '200', '1', '0', '1000', '0', '100', '3_18_I16_N_6_18_I16_N', ''),
(NOW(), 'MODALITA_FUNZIONAMENTO', '0_I_25', 'Operation mode', 'r3', 'Integral Values', 'integer', '0', '-1', 'rw', '', '', '0', '2', '', '', '', '', '', '3_124_I16_N_6_124_I16_N', ''),
(NOW(), 'SET_POINT_NOTTURNO', '0_A_20', 'Automatic variation of night time set point', 'r4', 'Analog Values', 'float', '3', '-1', 'rw', '&deg;C', '%.1f', '0', '20', '1', '0', '1000', '0', '100', '3_19_I16_N_6_19_I16_N', ''),
(NOW(), 'ENABLE_MONITOR_TEMP', '0_D_42', 'Enable temperature monitoring', 'r5', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_41_X_N_5_41_X_N', ''),
(NOW(), 'HYST_SETPT', '0_A_17', 'Hysteresis set point', 'rd', 'Analog Values', 'float', '0', '-1', 'rw', '&deg;C', '%.1f', '0,1', '20', '1', '0', '1000', '0', '100', '3_16_I16_N_6_16_I16_N', ''),
(NOW(), 'MAX_TEMP_LETTA', '0_A_21', 'Max. read temperature ', 'rH', 'Analog Values', 'float', '0', '-1', 'r', '&deg;C', '%.1f', '0', '0', '1', '0', '1000', '0', '100', '3_20_I16_N_-_-_-_-', ''),
(NOW(), 'MIN_TEMP_LETTA', '0_A_22', 'Min. read temperature  ', 'rL', 'Analog Values', 'float', '0', '-1', 'r', '&deg;C', '%.1f', '0', '0', '1', '0', '1000', '0', '100', '3_21_I16_N_-_-_-_-', ''),
(NOW(), 'INTEVALLO_MONITOR_TEMP', '0_I_26', 'Temperature monitoring interval', 'rt', 'Integral Values', 'integer', '0', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_125_I16_N_-_-_-_-', ''),
(NOW(), 'S_DI_VARIATION_CALC', '0_I_7', 'dI interval calculated', 's_vdI', 'Integral Values', 'integer', '0', '-1', 'r', '', '', '-7500', '15000', '', '', '', '', '', '3_106_I16_N_-_-_-_-', ''),
(NOW(), 'RITARDO_START_COMP_FAN', '0_I_27', 'Compr. and fan start-up at power on', 'c0', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '3_126_I16_N_6_126_I16_N', ''),
(NOW(), 'TEMPO_MINIMO_TRA_START', '0_I_28', 'Min. interval time between 2 comp. start-ups', 'c1', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '3_127_I16_N_6_127_I16_N', ''),
(NOW(), 'TEMPO_MINIMO_DI_OFF', '0_I_29', 'Minimum compressor OFF time', 'c2', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '3_128_I16_N_6_128_I16_N', ''),
(NOW(), 'TEMPO_MINIMO_DI_ON', '0_I_30', 'Minimum compressor ON time', 'c3', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '15', '', '', '', '', '', '3_129_I16_N_6_129_I16_N', ''),
(NOW(), 'DUTY_SETTING', '0_I_31', 'Duty setting', 'c4', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '100', '', '', '', '', '', '3_130_I16_N_6_130_I16_N', ''),
(NOW(), 'ESCL_ALM_DOPO_CC', '0_I_33', 'Alarm cut-out after cc', 'c6', 'Integral Values', 'integer', '2', '-1', 'rw', 'hour', '', '0', '15', '', '', '', '', '', '3_132_I16_N_6_132_I16_N', ''),
(NOW(), 'TEMPO_MAX_PUMP_DOWN', '0_I_34', 'Maximum time of pump down', 'c7', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '30', '', '', '', '', '', '3_133_I16_N_6_133_I16_N', ''),
(NOW(), 'RIT_START_COMP_DOPO_PD', '0_I_35', 'Compr. start-up delay after pump-down valve opening', 'c8', 'Integral Values', 'integer', '5', '-1', 'rw', 'Sec', '', '0', '60', '', '', '', '', '', '3_134_I16_N_6_134_I16_N', ''),
(NOW(), 'ENABLE_AUTOSTART_PD', '0_D_43', 'Enable auto-start operation in PD', 'c9', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_42_X_N_5_42_X_N', ''),
(NOW(), 'PD_TEMPO_PRESS', '0_D_44', 'Select PD by time or pressure', 'c10', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_43_X_N_5_43_X_N', ''),
(NOW(), 'DELAY_2_COMP', '0_I_36', 'Second compressor start-up delay ', 'c11', 'Integral Values', 'integer', '4', '-1', 'rw', 'Sec', '', '0', '250', '', '', '', '', '', '3_135_I16_N_6_135_I16_N', ''),
(NOW(), 'DURATA_CICLO_CONT', '0_I_32', 'Continuous cycle duration', 'cc', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '15', '', '', '', '', '', '3_131_I16_N_6_131_I16_N', ''),
(NOW(), 'RTC_ANNO', '0_I_1', 'Current year', 'tc_y', 'Integral Values', 'integer', '0', '-1', 'rw', 'year', '', '0', '99', '', '', '', '', '', '3_100_I16_N_6_100_I16_N', ''),
(NOW(), 'RTC_MESE', '0_I_2', 'Current month', 'tc_M', 'Integral Values', 'integer', '0', '-1', 'rw', 'month', '', '1', '12', '', '', '', '', '', '3_101_I16_N_6_101_I16_N', ''),
(NOW(), 'RTC_GIORNO_MESE', '0_I_3', 'Current day', 'tc_d', 'Integral Values', 'integer', '1', '-1', 'rw', 'day', '', '1', '31', '', '', '', '', '', '3_102_I16_N_6_102_I16_N', ''),
(NOW(), 'RTC_GIORNO_SETTIM', '0_I_4', 'Current week day', 'tc_u', 'Integral Values', 'integer', '1', '-1', 'rw', 'day', '', '1', '7', '', '', '', '', '', '3_103_I16_N_6_103_I16_N', ''),
(NOW(), 'RTC_ORA', '0_I_5', 'Current hours', 'tc_h', 'Integral Values', 'integer', '6', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_104_I16_N_6_104_I16_N', ''),
(NOW(), 'RTC_MINUTO', '0_I_6', 'Current minutes', 'tc_m', 'Integral Values', 'integer', '65', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_105_I16_N_6_105_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_1_GIORNO', '0_I_106', 'Defrost first time band (day)', 'td1_d', 'Integral Values', 'integer', '0', '-1', 'rw', 'day', '', '0', '11', '', '', '', '', '', '3_205_I16_N_6_205_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_1_ORA', '0_I_107', 'Defrost first time band (hours)', 'td1_h', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_206_I16_N_6_206_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_1_MINUTO', '0_I_108', 'Defrost first time band (min)', 'td1_m', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_207_I16_N_6_207_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_2_GIORNO', '0_I_109', 'Defrost second time band (day)', 'td2_d', 'Integral Values', 'integer', '0', '-1', 'rw', 'day', '', '0', '11', '', '', '', '', '', '3_208_I16_N_6_208_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_2_ORA', '0_I_110', 'Defrost second time band (hours)', 'td2_h', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_209_I16_N_6_209_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_2_MINUTO', '0_I_111', 'Defrost second time band (min)', 'td2_m', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_210_I16_N_6_210_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_3_GIORNO', '0_I_112', 'Defrost third time band (day)', 'td3_d', 'Integral Values', 'integer', '0', '-1', 'rw', 'day', '', '0', '11', '', '', '', '', '', '3_211_I16_N_6_211_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_3_ORA', '0_I_113', 'Defrost third time band (hours)', 'td3_h', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_212_I16_N_6_212_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_3_MINUTO', '0_I_114', 'Defrost third time band (min)', 'td3_m', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_213_I16_N_6_213_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_4_GIORNO', '0_I_115', 'Defrost fourth time band (day)', 'td4_d', 'Integral Values', 'integer', '0', '-1', 'rw', 'day', '', '0', '11', '', '', '', '', '', '3_214_I16_N_6_214_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_4_ORA', '0_I_116', 'Defrost fourth time band (hours)', 'td4_h', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_215_I16_N_6_215_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_4_MINUTO', '0_I_117', 'Defrost fourth time band (min)', 'td4_m', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_216_I16_N_6_216_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_5_GIORNO', '0_I_118', 'Defrost fifth time band (day)', 'td5_d', 'Integral Values', 'integer', '0', '-1', 'rw', 'day', '', '0', '11', '', '', '', '', '', '3_217_I16_N_6_217_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_5_ORA', '0_I_119', 'Defrost fifth time band (hours)', 'td5_h', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_218_I16_N_6_218_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_5_MINUTO', '0_I_120', 'Defrost fifth time band (min)', 'td5_m', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_219_I16_N_6_219_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_6_GIORNO', '0_I_121', 'Defrost sixth time band (day)', 'td6_d', 'Integral Values', 'integer', '4', '-1', 'rw', 'day', '', '0', '11', '', '', '', '', '', '3_220_I16_N_6_220_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_6_ORA', '0_I_122', 'Defrost sixth time band (hours)', 'td6_h', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_221_I16_N_6_221_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_6_MINUTO', '0_I_123', 'Defrost sixth time band (min)', 'td6_m', 'Integral Values', 'integer', '8', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_222_I16_N_6_222_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_7_GIORNO', '0_I_124', 'Defrost seventh time band (day)', 'td7_d', 'Integral Values', 'integer', '0', '-1', 'rw', 'day', '', '0', '11', '', '', '', '', '', '3_223_I16_N_6_223_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_7_ORA', '0_I_125', 'Defrost seventh time band (hours)', 'td7_h', 'Integral Values', 'integer', '4', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_224_I16_N_6_224_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_7_MINUTO', '0_I_126', 'Defrost seventh time band (min)', 'td7_m', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_225_I16_N_6_225_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_8_GIORNO', '0_I_127', 'Defrost eighth time band (day)', 'td8_d', 'Integral Values', 'integer', '30', '-1', 'rw', 'day', '', '0', '11', '', '', '', '', '', '3_226_I16_N_6_226_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_8_ORA', '0_I_128', 'Defrost eighth time band (hours)', 'td8_h', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_227_I16_N_6_227_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_8_MINUTO', '0_I_129', 'Defrost eighth time band (min)', 'td8_m', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_228_I16_N_6_228_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_ON_GIORNO', '0_I_130', 'Light/aux start-up day', 'ton_d', 'Integral Values', 'integer', '0', '-1', 'rw', 'day', '', '0', '11', '', '', '', '', '', '3_229_I16_N_6_229_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_ON_ORA', '0_I_131', 'Light/aux start-up hours', 'ton_h', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_230_I16_N_6_230_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_ON_MINUTO', '0_I_132', 'Light/aux start-up minutes', 'ton_m', 'Integral Values', 'integer', '2', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_231_I16_N_6_231_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_OFF_GIORNO', '0_I_133', 'Light/aux shutdown day ', 'toff_d', 'Integral Values', 'integer', '0', '-1', 'rw', 'day', '', '0', '11', '', '', '', '', '', '3_232_I16_N_6_232_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_OFF_ORA', '0_I_134', 'Light/aux shutdown hours ', 'toff_h', 'Integral Values', 'integer', '0', '-1', 'rw', 'hour', '', '0', '23', '', '', '', '', '', '3_233_I16_N_6_233_I16_N', ''),
(NOW(), 'FASCIA_ORARIA_OFF_MINUTO', '0_I_135', 'Light/aux shutdown minutes ', 'toff_m', 'Integral Values', 'integer', '0', '-1', 'rw', 'min', '', '0', '59', '', '', '', '', '', '3_234_I16_N_6_234_I16_N', ''),
(NOW(), 'HA_ANNO', '0_I_70', 'Last HA event year', 'HA_y', 'Integral Values', 'integer', '', '-1', 'r', 'year', '', '', '', '', '', '', '', '', '3_169_I16_N_-_-_-_-', ''),
(NOW(), 'HA_MESE', '0_I_71', 'Last HA event month', 'HA_M', 'Integral Values', 'integer', '160', '-1', 'r', 'month', '', '0', '0', '', '', '', '', '', '3_170_I16_N_-_-_-_-', ''),
(NOW(), 'HA_GIORNO', '0_I_72', 'Last HA event day', 'HA_d', 'Integral Values', 'integer', '0', '-1', 'r', 'day', '', '0', '0', '', '', '', '', '', '3_171_I16_N_-_-_-_-', ''),
(NOW(), 'HA_ORA', '0_I_73', 'Last HA event hour', 'HA_h', 'Integral Values', 'integer', '1', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_172_I16_N_-_-_-_-', ''),
(NOW(), 'HA_MINUTO', '0_I_74', 'Last HA event minute', 'HA_m', 'Integral Values', 'integer', '0', '-1', 'r', 'min', '', '0', '0', '', '', '', '', '', '3_173_I16_N_-_-_-_-', ''),
(NOW(), 'HA_DURATA', '0_I_75', 'Last HA event length', 'HA_t', 'Integral Values', 'integer', '0', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_174_I16_N_-_-_-_-', ''),
(NOW(), 'HA1_ANNO', '0_I_76', 'Second-last HA event year', 'HA1_y', 'Integral Values', 'integer', '0', '-1', 'r', 'Year', '', '0', '0', '', '', '', '', '', '3_175_I16_N_-_-_-_-', ''),
(NOW(), 'HA1_MESE', '0_I_77', 'Second-last HA event month', 'HA1_M', 'Integral Values', 'integer', '0', '-1', 'r', 'month', '', '0', '0', '', '', '', '', '', '3_176_I16_N_-_-_-_-', ''),
(NOW(), 'HA1_GIORNO', '0_I_78', 'Second-last HA event day', 'HA1_d', 'Integral Values', 'integer', '0', '-1', 'r', 'day', '', '0', '0', '', '', '', '', '', '3_177_I16_N_-_-_-_-', ''),
(NOW(), 'HA1_ORA', '0_I_79', 'Second-last HA event hour', 'HA1_h', 'Integral Values', 'integer', '1', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_178_I16_N_-_-_-_-', ''),
(NOW(), 'HA1_MINUTO', '0_I_80', 'Second-last HA event minute', 'HA1_m', 'Integral Values', 'integer', '0', '-1', 'r', 'min', '', '0', '0', '', '', '', '', '', '3_179_I16_N_-_-_-_-', ''),
(NOW(), 'HA1_DURATA', '0_I_81', 'Second-last HA event length', 'HA1_t', 'Integral Values', 'integer', '0', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_180_I16_N_-_-_-_-', ''),
(NOW(), 'HA2_ANNO', '0_I_82', 'Third-last HA event year', 'HA2_y', 'Integral Values', 'integer', '0', '-1', 'r', 'Year', '', '0', '0', '', '', '', '', '', '3_181_I16_N_-_-_-_-', ''),
(NOW(), 'HA2_MESE', '0_I_83', 'Third-last HA event month', 'HA2_M', 'Integral Values', 'integer', '4', '-1', 'r', 'month', '', '0', '0', '', '', '', '', '', '3_182_I16_N_-_-_-_-', ''),
(NOW(), 'HA2_GIORNO', '0_I_84', 'Third-last HA event day', 'HA2_d', 'Integral Values', 'integer', '0', '-1', 'r', 'day', '', '0', '0', '', '', '', '', '', '3_183_I16_N_-_-_-_-', ''),
(NOW(), 'HA2_ORA', '0_I_85', 'Third-last HA event hour', 'HA2_h', 'Integral Values', 'integer', '0', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_184_I16_N_-_-_-_-', ''),
(NOW(), 'HA2_MINUTO', '0_I_86', 'Third-last HA event minute', 'HA2_m', 'Integral Values', 'integer', '0', '-1', 'r', 'min', '', '0', '0', '', '', '', '', '', '3_185_I16_N_-_-_-_-', ''),
(NOW(), 'HA2_DURATA', '0_I_87', 'Third-last HA event length', 'HA2_t', 'Integral Values', 'integer', '0', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_186_I16_N_-_-_-_-', ''),
(NOW(), 'HF_ANNO', '0_I_88', 'Last HF event year', 'HF_y', 'Integral Values', 'integer', '0', '-1', 'r', 'Year', '', '0', '0', '', '', '', '', '', '3_187_I16_N_-_-_-_-', ''),
(NOW(), 'HF_MESE', '0_I_89', 'Last HF event month', 'HF_M', 'Integral Values', 'integer', '0', '-1', 'r', 'month', '', '0', '0', '', '', '', '', '', '3_188_I16_N_-_-_-_-', ''),
(NOW(), 'HF_GIORNO', '0_I_90', 'Last HF event day', 'HF_d', 'Integral Values', 'integer', '0', '-1', 'r', 'day', '', '0', '0', '', '', '', '', '', '3_189_I16_N_-_-_-_-', ''),
(NOW(), 'HF_ORA', '0_I_91', 'Last HF event hour', 'HF_h', 'Integral Values', 'integer', '2', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_190_I16_N_-_-_-_-', ''),
(NOW(), 'HF_MINUTO', '0_I_92', 'Last HF event minute', 'HF_m', 'Integral Values', 'integer', '0', '-1', 'r', 'min', '', '0', '0', '', '', '', '', '', '3_191_I16_N_-_-_-_-', ''),
(NOW(), 'HF_DURATA', '0_I_93', 'Last HF event length', 'HF_t', 'Integral Values', 'integer', '0', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_192_I16_N_-_-_-_-', ''),
(NOW(), 'HF1_ANNO', '0_I_94', 'Second-last HF event year', 'HF1_y', 'Integral Values', 'integer', '0', '-1', 'r', 'Year', '', '0', '0', '', '', '', '', '', '3_193_I16_N_-_-_-_-', ''),
(NOW(), 'HF1_MESE', '0_I_95', 'Second-last HF event month', 'HF1_M', 'Integral Values', 'integer', '0', '-1', 'r', 'month', '', '0', '0', '', '', '', '', '', '3_194_I16_N_-_-_-_-', ''),
(NOW(), 'HF1_GIORNO', '0_I_96', 'Second-last HF event day', 'HF1_d', 'Integral Values', 'integer', '0', '-1', 'r', 'day', '', '0', '0', '', '', '', '', '', '3_195_I16_N_-_-_-_-', ''),
(NOW(), 'HF1_ORA', '0_I_97', 'Second-last HF event hour', 'HF1_h', 'Integral Values', 'integer', '0', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_196_I16_N_-_-_-_-', ''),
(NOW(), 'HF1_MINUTO', '0_I_98', 'Second-last HF event minute', 'HF1_m', 'Integral Values', 'integer', '0', '-1', 'r', 'min', '', '0', '0', '', '', '', '', '', '3_197_I16_N_-_-_-_-', ''),
(NOW(), 'HF1_DURATA', '0_I_99', 'Second-last HF event length', 'HF1_t', 'Integral Values', 'integer', '0', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_198_I16_N_-_-_-_-', ''),
(NOW(), 'HF2_ANNO', '0_I_100', 'Third-last HF event year', 'HF2_y', 'Integral Values', 'integer', '0', '-1', 'r', 'Year', '', '0', '0', '', '', '', '', '', '3_199_I16_N_-_-_-_-', ''),
(NOW(), 'HF2_MESE', '0_I_101', 'Third-last HF event month', 'HF2_M', 'Integral Values', 'integer', '2', '-1', 'r', 'month', '', '0', '0', '', '', '', '', '', '3_200_I16_N_-_-_-_-', ''),
(NOW(), 'HF2_GIORNO', '0_I_102', 'Third-last HF event day', 'HF2_d', 'Integral Values', 'integer', '0', '-1', 'r', 'day', '', '0', '0', '', '', '', '', '', '3_201_I16_N_-_-_-_-', ''),
(NOW(), 'HF2_ORA', '0_I_103', 'Third-last HF event hour', 'HF2_h', 'Integral Values', 'integer', '60', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_202_I16_N_-_-_-_-', ''),
(NOW(), 'HF2_MINUTO', '0_I_104', 'Third-last HF event minute', 'HF2_m', 'Integral Values', 'integer', '0', '-1', 'r', 'min', '', '0', '0', '', '', '', '', '', '3_203_I16_N_-_-_-_-', ''),
(NOW(), 'HF2_DURATA', '0_I_105', 'Third-last HF event length', 'HF2_t', 'Integral Values', 'integer', '3', '-1', 'r', 'hour', '', '0', '0', '', '', '', '', '', '3_204_I16_N_-_-_-_-', ''),
(NOW(), 'NUMERO_HA', '0_I_67', 'Number of HA events  ', 'HAn', 'Integral Values', 'integer', '0', '-1', 'r', '', '', '0', '0', '', '', '', '', '', '3_166_I16_N_-_-_-_-', ''),
(NOW(), 'NUMERO_HF', '0_I_68', 'Number of HF events  ', 'HFn', 'Integral Values', 'integer', '0', '-1', 'r', '', '', '0', '0', '', '', '', '', '', '3_167_I16_N_-_-_-_-', ''),
(NOW(), 'S_STATO_PORTA', '0_D_37', 'Status of door', 's_doors', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_36_X_N_-_-_-_-', ''),
(NOW(), 's_rl1', '0_D_1', 'Status of compressor relay ', 'rl.cmp', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_0_X_N_5_0_X_N', ''),
(NOW(), 's_rl3', '0_D_3', 'Status of fan relay', 'rl.fans', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_2_X_N_5_2_X_N', ''),
(NOW(), 's_rl4', '0_D_4', 'Status of aux 1 relay', 'rl.aux1', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_3_X_N_5_3_X_N', ''),
(NOW(), 's_rl5', '0_D_5', 'Status of aux 2 relay', 'rl.aux2', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_4_X_N_5_4_X_N', ''),
(NOW(), 'S_DIGIN_1', '0_D_6', 'Status of digital input 1', 'Din1', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_5_X_N_-_-_-_-', ''),
(NOW(), 'S_DIGIN_2', '0_D_7', 'Status of digital input 2', 'Din2', 'Digital IO', 'boolean', '10', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_6_X_N_-_-_-_-', ''),
(NOW(), 'DEFROST_STAT', '0_D_31', 'Defrost status', 'def', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_30_X_N_-_-_-_-', ''),
(NOW(), 'S_STATO_CICLO_CONTINUO', '0_D_35', 'Status of continuous cycle', 'c.cycle', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_34_X_N_-_-_-_-', ''),
(NOW(), 's_rl2', '0_D_2', 'Status of defrost relay', 'rl.defr', 'Digital IO', 'boolean', '0', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '2_1_X_N_5_1_X_N', ''),
(NOW(), 'OFFLINE', '0_D_0', 'no connection', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '2_0_X_N_-_-_-_-', ''),
(NOW(), 'ALR_VIRTUAL_PROBE', '0_D_9', 'Alarm virtual probe fault', 's_re', 'Digital IO', 'boolean', '1', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_8_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_SONDA_1', '0_D_10', 'Room probe fault alarm', 's_pre1', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_9_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_SONDA_2', '0_D_11', 'Evaporator probe fault alarm', 's_pre2', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_10_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_SONDA_3', '0_D_12', 'Probe 3 fault alarm', 's_pre3', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_11_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_SONDA_4', '0_D_13', 'Probe 4 fault alarm', 's_pre4', 'Digital IO', 'boolean', '1', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_12_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_SONDA_5', '0_D_14', 'Probe 5 fault alarm', 's_pre5', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_13_X_N_-_-_-_-', ''),
(NOW(), 'ALR_LOW_TEMP', '0_D_15', 'Low Temperature Alarm', 's_LO', 'Digital IO', 'boolean', '1', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_14_X_N_-_-_-_-', ''),
(NOW(), 'ALR_HIGH_TEMP', '0_D_16', 'High Temperature Alarm', 's_HI', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_15_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_IMMEDIATO_ESTERNO', '0_D_17', 'Immediate external alarm', 's_IA', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_16_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_RITARDATO_ESTERNO', '0_D_18', 'Delayed external alarm', 's_dA', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_17_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_TIMEOUT_DEF_EVAP1', '0_D_19', 'Evaporator 1 timeout defrost alarm', 's_Ed1', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_18_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_TIMEOUT_DEF_EVAP2', '0_D_20', 'Evaporator 2 timeout defrost alarm', 's_Ed2', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_19_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_BASSA_PRESSIONE', '0_D_22', 'Low pressure alarm', 's_LP', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_21_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_ALTA_TEMP_COND', '0_D_24', 'Condenser high temperature alarm', 's_CHT', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_23_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_TIMEOUT_PORTA', '0_D_25', 'Door open time-out alarm', 's_dor', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_24_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_RTC_GUASTO', '0_D_26', 'RTC fault alarm', 's_Etc', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_25_X_N_-_-_-_-', ''),
(NOW(), 'ALR_EEPROM_MAC', '0_D_27', 'Control parameter eeprom alarm', 's_EE', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_26_X_N_-_-_-_-', ''),
(NOW(), 'ALR_EEPROM_FUNZ', '0_D_28', 'Operation parameter eeprom alarm', 's_EF', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_27_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_HA', '0_D_29', 'HA type HACCP alarm', 's_HA', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_28_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_HF', '0_D_30', 'HF type HACCP alarm', 's_HF', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_29_X_N_-_-_-_-', ''),
(NOW(), 'S_ALM_AUTOSTART_PD', '0_D_32', 'Auto-start pump down alarm', 's_AtS', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_31_X_N_-_-_-_-', ''),
(NOW(), 'SOGLIA_ALM_ANTIFREEZE', '30_A_36', 'Antifreeze alarm threshold', 'ALF', 'Analog Values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '-50', '200', '1', '0', '1000', '0', '100', '3_35_I16_N_6_35_I16_N', ''),
(NOW(), 'RITARDO_ALM_ANTIFREEZE', '30_I_236', 'Antifreeze alarm delay', 'Adf', 'Integral Values', 'integer', '', '-1', 'rw', 'min', '', '0', '250', '', '', '', '', '', '3_235_I16_N_6_235_I16_N', ''),
(NOW(), 'S_ALM_ANTIFREEZE', '30_D_38', 'Antifreeze alarm', 's_Afr', 'Digital IO', 'boolean', '0', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_37_X_N_-_-_-_-', ''),
(NOW(), 'TIPO_SONDA', '0_I_110x', 'Type of probe NTC_PTC', 'ntcptc', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_109_I16_N_-_-_-_-', ''),
(NOW(), 'TIPO_CONTROLLO', '0_I_111x', 'Type of controller', 'ctrl', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_110_I16_N_-_-_-_-', ''),
(NOW(), 'MODELLO_MACCHINA', '0_I_112x', 'Unit model', 'model', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_111_I16_N_-_-_-_-', ''),
(NOW(), 'PRESENZA_RTC', '0_I_113x', 'RTC absent_present', 'pres_rtc', 'Integral Values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_112_I16_N_-_-_-_-', ''),
(NOW(), 'PASSWORD', '0_I_114x', 'Password', 'Pw', 'Integral Values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_113_I16_N_6_113_I16_N', '');

CREATE TABLE IF NOT EXISTS `iw_set_ca_mcella_modbus` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_ca_mcella_modbus` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'S_COMANDO_DEFROST', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S_COMANDO_CICLO_CONTINUO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S_COMANDO_BUR', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S_COMANDO_AUX', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S_COMANDO_LUCE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S_COMANDO_ON_OFF', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ALM_ALTA_TEMP_COND', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DIFFERENZIALE_ALM_FAN', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TIPO_SOGLIA_AL_AH', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CONFIG_DIGIN_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CONFIG_DIGIN_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'STOP_DEFROST_EXT_ALM', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RITARDO_EXT_ALM', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ENABLE_ALM_ED1_ED2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DEFR_STAT_CMD', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RIT_ALM_ALTA_TEMP_COND', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DIFFERENZIALE_ALM_AE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMPO_SENSORE_DI_LUCE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'THREDHOLD_ALR_HIGH_TEMP', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'THREDHOLD_ALR_LOW_TEMP', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'STABILITA_MISURA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RALL_VIS_SONDA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SONDA_VIRTUALE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SELECT_UM', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DECIMAL_POINT', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CONFIG_SONDA2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CONFIG_SONDA3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CONFIG_SONDA4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TIPO_NTC', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'EXTERNAL_TERMINAL', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'INTERNAL_TERMINAL', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RELE4', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'DISABLE_KEY_IR', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CODICE_ABILIT_RC', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DISABLE_BUZZER', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RELE5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'BLOCCO_TASTI', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RTC_LUCE_AUX', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SET_POINT', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CALIB_SONDA1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CALIB_SONDA2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CALIB_SONDA3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'CALIB_SONDA4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'PROFILO_STAMPA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RITARDO_ALM_HACCP', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S_SONDA_1', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'EVAP_TEMP', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'S_SONDA_3', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'S_SONDA_4', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'S_SONDA_5', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'AMB_TEMP', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'DURATA_NOMINALE_DEFROST', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TIPO_DEFROST', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'VIS_SONDA_DEF_1', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), 'VIS_SONDA_DEF_2', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), 'RITARDO_INS_DEFROST', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ENABLE_DISABLE_DEFR', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RITARDO_DEFROST_STARTUP', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'BLOCCO_DISPLAY_DEFROST', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ESCL_ALM_DOPO_DEFROST', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'PRIORITA_DEFROST_COMP', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RUNNING_TIME_COMP', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMP_RUNNING_TIME', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DEFROST_AVANZATI', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'BASE_TEMPI_DEFROST', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DRIPPING_TIME', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'PROP_DURATA_DEFROST', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TIME_FROM_EACH_DEFR', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TIMEOUT_DEFR', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DURATA_MAX_DEFROST_E2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMP_FINE_DEFROST_E1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMP_FINE_DEFROST_E2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'MANAG_FAN', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMP_ON_FAN', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMP_OFF_FAN', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FAN_IN_DEFROST', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMP_OFF_FAN_COND', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DIFF_FAN_COND', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TIME_STOP_FANS_AFTER_DEFR', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SETPT_MIN', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SETPT_MAX', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'MODALITA_FUNZIONAMENTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SET_POINT_NOTTURNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ENABLE_MONITOR_TEMP', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HYST_SETPT', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'MAX_TEMP_LETTA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'MIN_TEMP_LETTA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'INTEVALLO_MONITOR_TEMP', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S_DI_VARIATION_CALC', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RITARDO_START_COMP_FAN', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMPO_MINIMO_TRA_START', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMPO_MINIMO_DI_OFF', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMPO_MINIMO_DI_ON', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DUTY_SETTING', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ESCL_ALM_DOPO_CC', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TEMPO_MAX_PUMP_DOWN', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RIT_START_COMP_DOPO_PD', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ENABLE_AUTOSTART_PD', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'PD_TEMPO_PRESS', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DELAY_2_COMP', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DURATA_CICLO_CONT', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RTC_ANNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RTC_MESE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RTC_GIORNO_MESE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RTC_GIORNO_SETTIM', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RTC_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RTC_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_1_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_1_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_1_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_2_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_2_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_2_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_3_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_3_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_3_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_4_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_4_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_4_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_5_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_5_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_5_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_6_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_6_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_6_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_7_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_7_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_7_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_8_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_8_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_8_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_ON_GIORNO', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_ON_ORA', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_ON_MINUTO', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_OFF_GIORNO', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_OFF_ORA', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'FASCIA_ORARIA_OFF_MINUTO', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA_ANNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA_MESE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA_DURATA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA1_ANNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA1_MESE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA1_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA1_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA1_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA1_DURATA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA2_ANNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA2_MESE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA2_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA2_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA2_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HA2_DURATA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF_ANNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF_MESE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF_DURATA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF1_ANNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF1_MESE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF1_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF1_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF1_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF1_DURATA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF2_ANNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF2_MESE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF2_GIORNO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF2_ORA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF2_MINUTO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'HF2_DURATA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'NUMERO_HA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'NUMERO_HF', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S_STATO_PORTA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 's_rl1', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 's_rl3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 's_rl4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 's_rl5', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S_DIGIN_1', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'S_DIGIN_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'DEFROST_STAT', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'S_STATO_CICLO_CONTINUO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 's_rl2', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'OFFLINE', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ALR_VIRTUAL_PROBE', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_SONDA_1', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_SONDA_2', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_SONDA_3', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_SONDA_4', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_SONDA_5', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'ALR_LOW_TEMP', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'ALR_HIGH_TEMP', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_IMMEDIATO_ESTERNO', '1', '0', 'norm', 'change', '', 'B', '', 0),
(NOW(), 'S_ALM_RITARDATO_ESTERNO', '1', '0', 'norm', 'change', '', 'B', '', 0),
(NOW(), 'S_ALM_TIMEOUT_DEF_EVAP1', '1', '0', 'norm', 'change', '', 'B', '', 0),
(NOW(), 'S_ALM_TIMEOUT_DEF_EVAP2', '1', '0', 'norm', 'change', '', 'B', '', 0),
(NOW(), 'S_ALM_BASSA_PRESSIONE', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_ALTA_TEMP_COND', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_TIMEOUT_PORTA', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_RTC_GUASTO', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'ALR_EEPROM_MAC', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'ALR_EEPROM_FUNZ', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_HA', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_HF', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'S_ALM_AUTOSTART_PD', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'SOGLIA_ALM_ANTIFREEZE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RITARDO_ALM_ANTIFREEZE', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'S_ALM_ANTIFREEZE', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'TIPO_SONDA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'TIPO_CONTROLLO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'MODELLO_MACCHINA', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'PRESENZA_RTC', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'PASSWORD', '1', '0', 'slow', 'change', '', '', '', 0);




-- Changelog
--
-- v1 Orginal
--
--
--