REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `driver_adr_extra`) VALUES 
(NOW(), '1', '0', 'E01', 'Energi 1', 'cge_em4nodi', 'EM4', '0_1', 'EM4', 'CGEEM4NODI', 'EM4'),
(NOW(), '1', '0', 'E02', 'Energi 2', 'cge_em4nodi', 'EM4', '0_1', 'EM4', 'CGEEM4NODI', 'EM4'),
(NOW(), '1', '0', 'E03', 'Energi 3', 'cge_em4nodi', 'EM4', '0_1', 'EM4', 'CGEEM4NODI', 'EM4');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES 
(NOW(), 'comm_port', 'EM4', '3', '', '', ''),
(NOW(), 'comm_parity', 'EM4', '0', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'comm_data_bits', 'EM4', '8', '', '', ''),
(NOW(), 'comm_stop_bits', 'EM4', '1', '', '', ''),
(NOW(), 'comm_baudrate', 'EM4', '9600', '', '', ''),
(NOW(), 'mb_mode', 'EM4', '0', '', '0=RTU|1=ASCII|3=TCP', ''),
(NOW(), 'force_word_not_byte', 'EM4', '0', '', '0|1', ''),
(NOW(), 'handshake', 'EM4', '0', '', '0|1|2', ''),
(NOW(), 'check_rate', 'EM4', '1', 'ms', '', ''),
(NOW(), 'max_outstanding_packets', 'EM4', '-1', '', '', ''),
(NOW(), 'packet_timeout', 'EM4', '1', 'sec.', '', ''),
(NOW(), 'idle_event_rate', 'EM4', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'EM4', '2000', 'msec.', '', ''),
(NOW(), 'max_error_count', 'EM4', '2', '', '', ''),
(NOW(), 'mb_request_timeout', 'EM4', '1000', 'ms', '', ''),
(NOW(), 'mb_request_retries', 'EM4', '2', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'EM4', '10', 'min.', '', ''),
(NOW(), 'show_queue_info', 'EM4', '0', '', '', ''),
(NOW(), 'speed_index_block', 'EM4', '10', '', '', ''),
(NOW(), 'speed_index_offline', 'EM4', '10', '', '', ''),
(NOW(), 'speed_index_slow', 'EM4', '1', '', '', ''),
(NOW(), 'speed_index_norm', 'EM4', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'EM4', '2', 'hours', '', ''),
(NOW(), 'max_group_count', 'EM4', '1', '', '', ''),
(NOW(), 'value_quality_check_limit', 'EM4', '0', '', '0 = disabled', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES 
(NOW(), '0', 'CG_Energy.exe', 'EM4', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES 
(NOW(), 'CGEEM4NODI', 'cge_em4nodi_param', 'cge_em4nodi_groups');

CREATE TABLE `iw_par_cge_em4nodi_groups` (
  `row_date` datetime NOT NULL default '2004-01-10 00:00:00',
  `TYPE` varchar(50) NOT NULL default '',
  `view_order` mediumint(6) NOT NULL default '0',
  `ref` varchar(100) NOT NULL default '',
  `value` varchar(200) NOT NULL default '',
  UNIQUE KEY `TYPE` (`TYPE`,`view_order`,`ref`,`value`)
) TYPE=MyISAM COMMENT='2.0.0';

REPLACE INTO `iw_par_cge_em4nodi_groups` (`row_date`, `TYPE`, `view_order`, `ref`, `value`) VALUES 
(NOW(), 'group_alias', 1, 'RAM0', 'Status'),
(NOW(), 'group', 1, 'RAM0', 'Delay_AL'),
(NOW(), 'group', 2, 'RAM0', 'STATUS'),
(NOW(), 'group', 3, 'RAM0', 'STATUS_REM_ALR'),
(NOW(), 'group', 4, 'RAM0', 'STATUS_ALARM'),
(NOW(), 'group', 5, 'RAM0', 'STATUS_DIP'),
(NOW(), 'group', 6, 'RAM0', 'STATUS_A0'),
(NOW(), 'group', 7, 'RAM0', 'STATUS_A1'),
(NOW(), 'group', 8, 'RAM0', 'STATUS_B0'),
(NOW(), 'group', 9, 'RAM0', 'STATUS_B1'),
(NOW(), 'group', 10, 'RAM0', 'STATUS_IN0'),
(NOW(), 'group', 10, 'RAM0', 'STATUS_IN1'),
(NOW(), 'group', 11, 'RAM0', 'STATUS_F0'),
(NOW(), 'group', 12, 'RAM0', 'STATUS_F1'),
(NOW(), 'group_alias', 2, 'RAM1', 'M�linger'),
(NOW(), 'group', 1, 'RAM1', 'V_L1-N'),
(NOW(), 'group', 2, 'RAM1', 'A_L1'),
(NOW(), 'group', 3, 'RAM1', 'W_L1'),
(NOW(), 'group', 4, 'RAM1', 'var_L1'),
(NOW(), 'group', 5, 'RAM1', 'VA_L1'),
(NOW(), 'group', 6, 'RAM1', 'PF_L1'),
(NOW(), 'group', 7, 'RAM1', 'V_L2-N'),
(NOW(), 'group', 8, 'RAM1', 'A_L2'),
(NOW(), 'group', 9, 'RAM1', 'W_L2'),
(NOW(), 'group', 10, 'RAM1', 'var_L2'),
(NOW(), 'group', 11, 'RAM1', 'VA_L2'),
(NOW(), 'group', 12, 'RAM1', 'PF_L2'),
(NOW(), 'group', 13, 'RAM1', 'V_L3-N'),
(NOW(), 'group', 14, 'RAM1', 'A_L3'),
(NOW(), 'group', 15, 'RAM1', 'W_L3'),
(NOW(), 'group', 16, 'RAM1', 'var_L3'),
(NOW(), 'group', 17, 'RAM1', 'VA_L3'),
(NOW(), 'group', 18, 'RAM1', 'PF_L3'),
(NOW(), 'group', 19, 'RAM1', 'V_SYS'),
(NOW(), 'group', 20, 'RAM1', 'W_SYS'),
(NOW(), 'group', 21, 'RAM1', 'var_SYS'),
(NOW(), 'group', 22, 'RAM1', 'VA_SYS'),
(NOW(), 'group', 23, 'RAM1', 'PF_SYS'),
(NOW(), 'group', 24, 'RAM1', 'VA_dmd'),
(NOW(), 'group', 25, 'RAM1', 'W_dmd'),
(NOW(), 'group', 26, 'RAM1', 'HZ'),
(NOW(), 'group', 27, 'RAM1', 'kWh_tot'),
(NOW(), 'group', 28, 'RAM1', 'kvarh_tot'),
(NOW(), 'group', 29, 'RAM1', 'kWh_par'),
(NOW(), 'group', 30, 'RAM1', 'kvarh_par'),
('2004-01-10 00:00:00', 'default_link', 0, 'RAM1', ''),
(NOW(), 'group_alias', 3, 'COUNTER', 'kWh og kvarh'),
(NOW(), 'group', 1, 'COUNTER', 'kWh_tot_c'),
(NOW(), 'group', 2, 'COUNTER', 'kvarh_tot_c'),
(NOW(), 'group', 3, 'COUNTER', 'kWh_par_c'),
(NOW(), 'group', 4, 'COUNTER', 'kvarh_par_c'),
(NOW(), 'group', 5, 'COUNTER', 'kWh_b2'),
(NOW(), 'group', 6, 'COUNTER', 'kvarh_b2'),
(NOW(), 'group', 7, 'COUNTER', 'kWh_b3'),
(NOW(), 'group', 8, 'COUNTER', 'kvarh_b3'),
(NOW(), 'group', 9, 'COUNTER', 'kWh_b4'),
(NOW(), 'group', 10, 'COUNTER', 'kvarh_b4'),
(NOW(), 'group_alias', 4, 'EEPROM', 'Innstillinger'),
(NOW(), 'group', 1, 'EEPROM', 'password'),
(NOW(), 'group', 1, 'EEPROM', 'system'),
(NOW(), 'group', 1, 'EEPROM', 'vt_ratio'),
(NOW(), 'group', 1, 'EEPROM', 'ct_ratio'),
(NOW(), 'group', 1, 'EEPROM', 'pt_ratio'),
(NOW(), 'group', 1, 'EEPROM', 'p_int'),
(NOW(), 'group', 1, 'EEPROM', 'counter'),
(NOW(), 'group', 1, 'EEPROM', 'pre_cn1'),
(NOW(), 'group', 1, 'EEPROM', 'pre_cn2'),
(NOW(), 'group', 1, 'EEPROM', 'sel_thd'),
(NOW(), 'group', 1, 'EEPROM', 'sel_dig1'),
(NOW(), 'group', 1, 'EEPROM', 'sel_dig2'),
(NOW(), 'group', 1, 'EEPROM', 'pulse1'),
(NOW(), 'group', 1, 'EEPROM', 'pulse2'),
(NOW(), 'group', 1, 'EEPROM', 'var_dig'),
(NOW(), 'group', 1, 'EEPROM', 'rel_type'),
(NOW(), 'group', 1, 'EEPROM', 'del_delay'),
(NOW(), 'group', 1, 'EEPROM', 'dig_on'),
(NOW(), 'group', 1, 'EEPROM', 'dig_off'),
(NOW(), 'group', 1, 'EEPROM', 'address'),
(NOW(), 'group', 1, 'EEPROM', 'filter_rng'),
(NOW(), 'group', 1, 'EEPROM', 'filter_coe');

DROP TABLE IF EXISTS `iw_par_cge_em4nodi_param`;
CREATE TABLE `iw_par_cge_em4nodi_param` (
  `row_date` datetime NOT NULL default '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL default '',
  `driver_id` varchar(100) NOT NULL default '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL default '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(50) NOT NULL default '',
  `format` varchar(20) NOT NULL default '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL default '',
  `raw_min` varchar(15) NOT NULL default '',
  `raw_max` varchar(15) NOT NULL default '',
  `eng_min` varchar(15) NOT NULL default '',
  `eng_max` varchar(15) NOT NULL default '',
  `driver_id_extra` varchar(255) NOT NULL default '',
  UNIQUE KEY `element_id` (`element_id`)
) TYPE=MyISAM COMMENT='2.0.0';

REPLACE INTO `iw_par_cge_em4nodi_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`) VALUES 
(NOW(), 'STATUS', '0_S_B0', 'Status', '', '', 'integer', '', '1', 'r', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'Delay_AL', '0_S_F8', 'Delay alarm', '', '', 'integer', '', '2', 'r', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'STATUS_REM_ALR', '0_S_B0.12', 'Status remote control alarm bit', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'STATUS_ALARM', '0_S_B0.13', 'Status alarm', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'STATUS_DIP', '0_S_B0.0', 'Status dip', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'STATUS_A0', '0_S_B0.2', 'Status A0', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'STATUS_A1', '0_S_B0.3', 'Status A1', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'STATUS_B0', '0_S_B0.4', 'Status B0', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'STATUS_B1', '0_S_B0.5', 'Status B1', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'STATUS_IN0', '0_S_B0.16', 'Status In 0', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'STATUS_IN1', '0_S_B0.17', 'Status In 1', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'STATUS_F0', '0_S_B0.18', 'Status F0', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'STATUS_F1', '0_S_B0.19', 'Status F1', '', '', 'boolean', '', '1', 'r', '', '', '0', '1', '', '', '', '', '', ''),
(NOW(), 'V_L1-N', 'R_V_200', 'Spenning L1-N', '', '', 'float', '', '1', 'r', 'V', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'A_L1', 'R_A_206', 'Str�m L1', '', '', 'float', '', '1', 'r', 'A', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'W_L1', 'R_P_20C', 'Effekt L1', '', '', 'float', '', '1', 'r', 'W', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'var_L1', 'R_P_215', 'VAR L1', '', '', 'float', '', '1', 'r', 'var', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'VA_L1', 'R_P_21E', 'Tilsynelatende effekt L1', '', '', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'PF_L1', 'R_C_227', 'Faseforskyvning L1', '', '', 'float', '', '1', 'r', '', '%.3f', '', '', '', '', '', '', '', ''),
(NOW(), 'V_L2-N', 'R_V_202', 'Spenning L2-N', '', '', 'float', '', '1', 'r', 'V', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'A_L2', 'R_A_208', 'Str�m L2', '', '', 'float', '', '1', 'r', 'A', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'W_L2', 'R_P_20F', 'Effekt L2', '', '', 'float', '', '1', 'r', 'W', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'var_L2', 'R_P_218', 'VAR L2', '', '', 'float', '', '1', 'r', 'var', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'VA_L2', 'R_P_221', 'Tilsynelatende effekt L2', '', '', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'PF_L2', 'R_C_228', 'Faseforskyvning L2', '', '', 'float', '', '1', 'r', '', '%.3f', '', '', '', '', '', '', '', ''),
(NOW(), 'V_L3-N', 'R_V_204', 'Spenning L3-N', '', '', 'float', '', '1', 'r', 'V', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'A_L3', 'R_A_20A', 'Str�m L3', '', '', 'float', '', '1', 'r', 'A', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'W_L3', 'R_P_212', 'Effekt L3', '', '', 'float', '', '1', 'r', 'W', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'var_L3', 'R_P_21B', 'VAR L3', '', '', 'float', '', '1', 'r', 'var', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'VA_L3', 'R_P_224', 'Tilsynelatende effekt L3', '', '', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'PF_L3', 'R_C_229', 'Faseforskyvning L3', '', '', 'float', '', '1', 'r', '', '%.3f', '', '', '', '', '', '', '', ''),
(NOW(), 'V_SYS', 'R_V_22A', 'V sys', '', '', 'float', '', '1', 'r', 'V', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'W_SYS', 'R_P_22C', 'kW sys', '', '', 'float', '', '1', 'r', 'kW', '%.1f', '', '', '1', '0', '10000', '0', '10', ''),
(NOW(), 'var_SYS', 'R_P_22F', 'kvar sys', '', '', 'float', '', '1', 'r', 'kvar', '%.1f', '', '', '1', '0', '10000', '0', '10', ''),
(NOW(), 'VA_SYS', 'R_P_232', 'kVA sys', '', '', 'float', '', '1', 'r', 'kVA', '%.1f', '', '', '1', '0', '10000', '0', '10', ''),
(NOW(), 'PF_SYS', 'R_C_235', 'PF sys', '', '', 'float', '', '1', 'r', '', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'VA_dmd', 'R_P_236', 'VA dmd', '', '', 'float', '', '1', 'r', '', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'W_dmd', 'R_P_239', 'W dmd', '', '', 'float', '', '1', 'r', '', '%.0f', '', '', '', '', '', '', '', ''),
(NOW(), 'HZ', 'R_H_23C', 'Hz', '', '', 'float', '', '1', 'r', 'Hz', '%.2f', '', '', '', '', '', '', '', ''),
(NOW(), 'kWh_tot', 'R_E_247', 'kWh total', '', '', 'float', '', '1', 'r', 'kWh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kvarh_tot', 'R_E_24B', 'kvarh total', '', '', 'float', '', '1', 'r', 'kvarh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kWh_par', 'R_E_24F', 'kWh par', '', '', 'float', '', '1', 'r', 'kWh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kvarh_par', 'R_E_253', 'kvarh par', '', '', 'float', '', '1', 'r', 'kvarh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kWh_tot_c', 'C_E_C90', 'Total aktiv energi', '', '', 'float', '', '1', 'r', 'kWh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kvarh_tot_c', 'C_E_C94', 'Total reaktiv energi', '', '', 'float', '', '1', 'r', 'kvarh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kWh_par_c', 'C_E_CA0', 'Partial aktiv energi', '', '', 'float', '', '1', 'r', 'kWh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kvarh_par_c', 'C_E_CA4', 'Partial reaktiv energi', '', '', 'float', '', '1', 'r', 'kvarh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kWh_b2', 'C_E_CA8', 'Band 2 aktiv energi tids periode 2', '', '', 'float', '', '1', 'r', 'kWh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kvarh_b2', 'C_E_CAC', 'Band 2 reaktiv energi tids periode 2', '', '', 'float', '', '1', 'r', 'kvarh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kWh_b3', 'C_E_CB0', 'Band 3 aktiv energi tids periode 3', '', '', 'float', '', '1', 'r', 'kWh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kvarh_b3', 'C_E_CB4', 'Band 3 reaktiv energi tids periode 3', '', '', 'float', '', '1', 'r', 'kvarh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kWh_b4', 'C_E_CB8', 'Band 4 aktiv energi tids periode 4', '', '', 'float', '', '1', 'r', 'kWh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'kvarh_b4', 'C_E_CBC', 'Band 4 reaktiv energi tids periode 4', '', '', 'float', '', '1', 'r', 'kvarh', '%.1f', '', '', '', '', '', '', '', ''),
(NOW(), 'var_dig', 'E_2_CDC', 'Variable associated with the alarm output', '', '', 'integer', '', '1', 'r', '', '%d', '0', '9', '', '', '', '', '', ''),
(NOW(), 'pulse2', 'E_2_CDA', 'N� impulse/energy digital output 2', '', '', 'integer', '', '1', 'r', '', '%d', '0', '100', '', '', '', '', '', ''),
(NOW(), 'pulse1', 'E_2_CD8', 'N� impulse/energy digital output 1', '', '', 'integer', '', '1', 'r', '', '%d', '0', '100', '', '', '', '', '', ''),
(NOW(), 'sel_dig2', 'E_2_CD6', 'Digital output 2 selection', '', '', 'integer', '', '1', 'r', '', '%d', '0', '1', '', '', '', '', '', ''),
(NOW(), 'sel_dig1', 'E_2_CD4', 'Digital output 1 selection', '', '', 'integer', '', '1', 'r', '', '%d', '0', '3', '', '', '', '', '', ''),
(NOW(), 'password', 'E_2_CC0', 'Password', '', '', 'integer', '', '1', 'r', '', '%d', '0', '1000', '', '', '', '', '', ''),
(NOW(), 'system', 'E_2_CC2', 'System type', '', '', 'integer', '', '1', 'r', '', '%d', '0', '1', '', '', '', '', '', ''),
(NOW(), 'vt_ratio', 'E_2_CC4', 'Voltage transformer ratio', '', '', 'integer', '', '1', 'r', '', '%.1f', '10.0', '50000.0', '', '', '', '', '', ''),
(NOW(), 'ct_ratio', 'E_2_CC6', 'Current transformer ratio', '', '', 'integer', '', '1', 'r', '', '%d', '1', '5000', '', '', '', '', '', ''),
(NOW(), 'pt_ratio', 'E_2_CC8', 'Power transformation ratio', '', '', 'float', '', '1', 'r', '', '%.1f', '1.0', '5000.0', '', '', '', '', '', ''),
(NOW(), 'p_int', 'E_2_CCA', 'Integration period (dmd)', '', '', 'integer', '', '1', 'r', 'min', '%d', '1', '30', '', '', '', '', '', ''),
(NOW(), 'counter', 'E_2_CCC', 'Counter mode selection', '', '', 'integer', '', '1', 'r', '', '%d', '0', '3', '', '', '', '', '', ''),
(NOW(), 'pre_cn1', 'E_2_CCE', 'Counter m3 input 1 prescaler', '', '', 'float', '', '1', 'r', '', '%.1f', '0.1', '100.0', '', '', '', '', '', ''),
(NOW(), 'pre_cn2', 'E_2_CD0', 'Counter m3 input 2 prescaler', '', '', 'float', '', '1', 'r', '', '%.1f', '0.1', '100.0', '', '', '', '', '', ''),
(NOW(), 'sel_thd', 'E_2_CD2', 'Calculation THD enable', '', '', 'integer', '', '1', 'r', '', '%d', '0', '1', '', '', '', '', '', ''),
(NOW(), 'rel_type', 'E_2_CDE', 'Normally energised/de-energised output', '', '', 'integer', '', '1', 'r', '', '%d', '0', '1', '', '', '', '', '', ''),
(NOW(), 'del_delay', 'E_2_CE0', 'Alarm delay time', '', '', 'integer', '', '1', 'r', 'sec', '%d', '0', '255', '', '', '', '', '', ''),
(NOW(), 'dig_on', 'E_3_CE2', 'Alarm activation point', '', '', 'integer', '', '1', 'r', '', '%d', '0', '100000', '', '', '', '', '', ''),
(NOW(), 'dig_off', 'E_3_CE5', 'Alarm deactivation point', '', '', 'integer', '', '1', 'r', '', '%d', '0', '100000', '', '', '', '', '', ''),
(NOW(), 'address', 'E_2_CF4', 'Input address', '', '', 'integer', '', '1', 'r', '', '%d', '0', '255', '', '', '', '', '', ''),
(NOW(), 'filter_rng', 'E_2_CF6', 'Operating range of the digital filter', '', '', 'integer', '', '1', 'r', '%', '%d', '0', '100', '', '', '', '', '', ''),
(NOW(), 'filter_coe', 'E_2_CF8', ' Filtering coefficient', '', '', 'integer', '', '1', 'r', '', '%d', '0', '16', '', '', '', '', '', '');

DROP TABLE IF EXISTS `iw_set_cge_em4nodi`;
CREATE TABLE `iw_set_cge_em4nodi` (
  `row_date` datetime NOT NULL default '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL default '',
  `active` enum('0','1') NOT NULL default '0',
  `onl_ind` enum('0','1') NOT NULL default '1',
  `update_freq` set('','fast','norm','slow','once') NOT NULL default 'norm',
  `save_data` enum('0','1','2') NOT NULL default '0',
  `save_freq` set('','fast','norm','slow') NOT NULL default 'norm',
  `plant_pri` char(1) NOT NULL default '',
  `sys_pri` char(1) NOT NULL default '',
  `alarm_type` tinyint(3) NOT NULL default '0',
  PRIMARY KEY  (`element_id`)
) TYPE=MyISAM COMMENT='2.0.3';

REPLACE INTO `iw_set_cge_em4nodi` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES 
(NOW(), 'STATUS', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'Delay_AL', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_REM_ALR', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_ALARM', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_DIP', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_A0', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_A1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_B0', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_B1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_IN0', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_IN1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_F0', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'STATUS_F1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'V_L1-N', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'A_L1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'W_L1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'var_L1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'VA_L1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'PF_L1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'V_L2-N', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'A_L2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'W_L2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'var_L2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'VA_L2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'PF_L2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'V_L3-N', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'A_L3', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'W_L3', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'var_L3', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'VA_L3', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'PF_L3', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'V_SYS', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'W_SYS', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'var_SYS', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'VA_SYS', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'PF_SYS', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'VA_dmd', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'W_dmd', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'HZ', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kWh_tot', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kvarh_tot', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kWh_par', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kvarh_par', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kWh_tot_c', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kvarh_tot_c', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kWh_par_c', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kvarh_par_c', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kWh_b2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kvarh_b2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kWh_b3', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kvarh_b3', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kWh_b4', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kvarh_b4', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'password', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'system', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'vt_ratio', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'ct_ratio', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'pt_ratio', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'p_int', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'counter', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'pre_cn1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'pre_cn2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'sel_thd', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'sel_dig1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'sel_dig2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'pulse1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'pulse2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'var_dig', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'rel_type', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'dig_off', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'dig_on', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'del_delay', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'address', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'filter_rng', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'filter_coe', '1', '1', 'norm', '1', 'norm', '', '', 0);



-- Changelog
--
-- v1 Orginal
--
--