REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'U01', 'Plugg-inn F1', 'dixell_xr72cx', 'DIXELL', '0_1', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U02', 'Plugg-inn F2', 'dixell_xr72cx', 'DIXELL', '0_2', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U03', 'Plugg-inn F3', 'dixell_xr72cx', 'DIXELL', '0_3', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U04', 'Plugg-inn F4', 'dixell_xr72cx', 'DIXELL', '0_4', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U05', 'Plugg-inn F5', 'dixell_xr72cx', 'DIXELL', '0_5', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U06', 'Plugg-inn F6', 'dixell_xr72cx', 'DIXELL', '0_6', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U07', 'Plugg-inn F7', 'dixell_xr72cx', 'DIXELL', '0_7', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U08', 'Plugg-inn F8', 'dixell_xr72cx', 'DIXELL', '0_8', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U09', 'Plugg-inn F9', 'dixell_xr72cx', 'DIXELL', '0_9', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U10', 'Plugg-inn F10', 'dixell_xr72cx', 'DIXELL', '0_10', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U11', 'Plugg-inn F11', 'dixell_xr72cx', 'DIXELL', '0_11', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U12', 'Plugg-inn F12', 'dixell_xr72cx', 'DIXELL', '0_12', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U13', 'Plugg-inn F13', 'dixell_xr72cx', 'DIXELL', '0_13', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U14', 'Plugg-inn F14', 'dixell_xr72cx', 'DIXELL', '0_14', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U15', 'Plugg-inn F15', 'dixell_xr72cx', 'DIXELL', '0_15', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U16', 'Plugg-inn F16', 'dixell_xr72cx', 'DIXELL', '0_16', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U17', 'Plugg-inn F17', 'dixell_xr72cx', 'DIXELL', '0_17', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U18', 'Plugg-inn F18', 'dixell_xr72cx', 'DIXELL', '0_18', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U19', 'Plugg-inn F19', 'dixell_xr72cx', 'DIXELL', '0_19', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U20', 'Plugg-inn F20', 'dixell_xr72cx', 'DIXELL', '0_20', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U21', 'Plugg-inn F21', 'dixell_xr72cx', 'DIXELL', '0_21', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U22', 'Plugg-inn F22', 'dixell_xr72cx', 'DIXELL', '0_22', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U23', 'Plugg-inn F23', 'dixell_xr72cx', 'DIXELL', '0_23', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U24', 'Plugg-inn F24', 'dixell_xr72cx', 'DIXELL', '0_24', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U25', 'Plugg-inn F25', 'dixell_xr72cx', 'DIXELL', '0_25', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U26', 'Plugg-inn F26', 'dixell_xr72cx', 'DIXELL', '0_26', 'DIXELL', 'XR72CX', ''),
(NOW(), '1', '0', 'U27', 'Plugg-inn F27', 'dixell_xr72cx', 'DIXELL', '0_27', 'DIXELL', 'XR72CX', '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'comm_port', 'DIXELL', '8', '', '', ''),
(NOW(), 'comm_baudrate', 'DIXELL', '9600', '', '', ''),
(NOW(), 'comm_stop_bits', 'DIXELL', '1', '', '', ''),
(NOW(), 'comm_data_bits', 'DIXELL', '8', '', '', ''),
(NOW(), 'comm_parity', 'DIXELL', '0', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'mb_mode', 'DIXELL', '0', '', '0=RTU|1=ASCII|2=TCP', ''),
(NOW(), 'idle_event_rate', 'DIXELL', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'DIXELL', '2000', 'msec.', '', ''),
(NOW(), 'value_quality_check_limit', 'DIXELL', '0', '', '0 = disabled', ''),
(NOW(), 'packet_timeout', 'DIXELL', '0', 'sec.', '', ''),
(NOW(), 'max_outstanding_packets', 'DIXELL', '-1', '', '', ''),
(NOW(), 'max_error_count', 'DIXELL', '2', '', '', ''),
(NOW(), 'max_group_count', 'DIXELL', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'DIXELL', '2', 'hours', '', ''),
(NOW(), 'speed_index_norm', 'DIXELL', '1', '', '', ''),
(NOW(), 'speed_index_slow', 'DIXELL', '1', '', '', ''),
(NOW(), 'speed_index_offline', 'DIXELL', '10', '', '', ''),
(NOW(), 'speed_index_block', 'DIXELL', '10', '', '', ''),
(NOW(), 'show_queue_info', 'DIXELL', '0', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'DIXELL', '10', 'min.', '', ''),
(NOW(), 'mb_request_retries', 'DIXELL', '0', '', '', ''),
(NOW(), 'mb_request_timeout', 'DIXELL', '500', 'ms', '', ''),
(NOW(), 'mux_settle_time', 'DIXELL', '1500', 'ms', 'Time for the muxed input to settle. The value shuld be a multiple off 100.', ''),
(NOW(), 'startup_delay', 'DIXELL', '15', 'Sec.', '', ''),
(NOW(), 'check_rate', 'DIXELL', '1', 'ms', '', ''),
(NOW(), 'handshake', 'DIXELL', '0', '', '0|1|2', ''),
(NOW(), 'force_word_not_byte', 'DIXELL', '0', '', '0|1', ''),
(NOW(), 'alarm_handler', 'DIXELL', '', '', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'XR72CX', 'dixell_xr72cx_param', 'dixell_xr72cx_groups');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_mb.exe', 'DIXELL', '', '');

CREATE TABLE IF NOT EXISTS `iw_par_dixell_xr72cx_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_dixell_xr72cx_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 2, '', ''),
(NOW(), 'group_alias', 1, 'device_identification', 'Device identification'),
(NOW(), 'group_alias', 2, 'analogue_inputs', 'Analogue inputs'),
(NOW(), 'group_alias', 3, 'status_elements_binary', 'Status elements binary'),
(NOW(), 'group_alias', 4, 'function_parameter', 'Function parameter'),
(NOW(), 'group', 1, 'device_identification', 'firmware_version'),
(NOW(), 'group', 2, 'device_identification', 'family_product_code'),
(NOW(), 'group', 3, 'device_identification', 'device_code_1_msword'),
(NOW(), 'group', 4, 'device_identification', 'device_code_2_lsword'),
(NOW(), 'group', 5, 'device_identification', 'series_number_1_msword'),
(NOW(), 'group', 6, 'device_identification', 'series_number_2_lsword'),
(NOW(), 'group', 7, 'device_identification', 'data_fw_version_year'),
(NOW(), 'group', 8, 'device_identification', 'data_fw_version_month'),
(NOW(), 'group', 9, 'device_identification', 'data_fw_version_day'),
(NOW(), 'group', 10, 'device_identification', 'descriptior_eeprom_1'),
(NOW(), 'group', 11, 'device_identification', 'probe_configuration_probe_1'),
(NOW(), 'group', 12, 'device_identification', 'probe_configuration_probe_2'),
(NOW(), 'group', 13, 'device_identification', 'probe_configuration_probe_3'),
(NOW(), 'group', 14, 'device_identification', 'probe_configuration_probe_4'),
(NOW(), 'group', 15, 'device_identification', 'configuration_relais_on_off'),
(NOW(), 'group', 16, 'device_identification', 'configuration_relais_defrost_1'),
(NOW(), 'group', 17, 'device_identification', 'configuration_relais_defrost_2'),
(NOW(), 'group', 18, 'device_identification', 'configuration_relais_alarm'),
(NOW(), 'group', 19, 'device_identification', 'configuration_relais_light'),
(NOW(), 'group', 20, 'device_identification', 'configuration_relais_fan'),
(NOW(), 'group', 21, 'device_identification', 'configuration_relais_auxiliary'),
(NOW(), 'group', 22, 'device_identification', 'configuration_relais_dead_band'),
(NOW(), 'group', 23, 'device_identification', 'configuration_relais_compressor_1'),
(NOW(), 'group', 24, 'device_identification', 'configuration_relais_compressor_2'),
(NOW(), 'group', 25, 'device_identification', 'configuration_digital_input_1'),
(NOW(), 'group', 26, 'device_identification', 'configuration_digital_input_2'),
(NOW(), 'group', 1, 'analogue_inputs', 'regulation_probe_value'),
(NOW(), 'group', 2, 'analogue_inputs', 'defrost_1_probe_value'),
(NOW(), 'group', 3, 'analogue_inputs', 'defrost_2_probe_value'),
(NOW(), 'group', 4, 'analogue_inputs', 'regulation_fan_probe_value'),
(NOW(), 'group', 5, 'analogue_inputs', 'probe_value_alarms_room_temp'),
(NOW(), 'group', 6, 'analogue_inputs', 'probe_value_alarms_condenser'),
(NOW(), 'group', 7, 'analogue_inputs', 'regulator_auxiliary_probe_value'),
(NOW(), 'group', 8, 'analogue_inputs', 'set_dynamic_probe_value'),
(NOW(), 'group', 9, 'analogue_inputs', 'probe_value_1'),
(NOW(), 'group', 10, 'analogue_inputs', 'probe_value_2'),
(NOW(), 'group', 11, 'analogue_inputs', 'probe_value_3'),
(NOW(), 'group', 12, 'analogue_inputs', 'probe_value_4'),
(NOW(), 'group', 1, 'function_parameter', 'regulation_set_point'),
(NOW(), 'group', 2, 'function_parameter', 'high_temp_alarm_set'),
(NOW(), 'group', 3, 'function_parameter', 'low_temp_alarm_set'),
(NOW(), 'group', 4, 'function_parameter', 'set_point_2'),
(NOW(), 'group', 5, 'function_parameter', 'high_temp_alarm_set_2'),
(NOW(), 'group', 6, 'function_parameter', 'low_temp_alarm_set_2'),
(NOW(), 'group', 1, 'status_elements_binary', 'on_off'),
(NOW(), 'group', 2, 'status_elements_binary', 'defrost'),
(NOW(), 'group', 3, 'status_elements_binary', 'continuos_cooling_heating'),
(NOW(), 'group', 4, 'status_elements_binary', 'keyboard_lock'),
(NOW(), 'group', 5, 'status_elements_binary', 'alarms_silence'),
(NOW(), 'group', 6, 'status_elements_binary', 'master_defrost'),
(NOW(), 'group', 7, 'status_elements_binary', 'energy_saving'),
(NOW(), 'group', 8, 'status_elements_binary', 'digital_input'),
(NOW(), 'group', 9, 'status_elements_binary', 'alarm_probe_p1'),
(NOW(), 'group', 10, 'status_elements_binary', 'alarm_probe_p2'),
(NOW(), 'group', 11, 'status_elements_binary', 'alarm_probe_p3'),
(NOW(), 'group', 12, 'status_elements_binary', 'alarm_probe_p4'),
(NOW(), 'group', 13, 'status_elements_binary', 'alarm_high_room_temp'),
(NOW(), 'group', 14, 'status_elements_binary', 'alarm_low_room_temp'),
(NOW(), 'group', 15, 'status_elements_binary', 'alarm_high_condenser_temp'),
(NOW(), 'group', 16, 'status_elements_binary', 'alarm_low_condenser_temp'),
(NOW(), 'group', 17, 'status_elements_binary', 'generic_alarm_digital_input_eal'),
(NOW(), 'group', 18, 'status_elements_binary', 'generic_alarm_digital_input_bal'),
(NOW(), 'group', 19, 'status_elements_binary', 'open_door_alarm'),
(NOW(), 'group', 20, 'status_elements_binary', 'eeprom_alarm'),
(NOW(), 'group', 21, 'status_elements_binary', 'measurement_unit_temp_c_f'),
(NOW(), 'group', 22, 'status_elements_binary', 'resolution_temp_value_decimal_integer'),
(NOW(), 'group', 23, 'status_elements_binary', 'relay_output_on_off'),
(NOW(), 'group', 24, 'status_elements_binary', 'relay_output_1_defrost'),
(NOW(), 'group', 25, 'status_elements_binary', 'relay_output_2_defrost'),
(NOW(), 'group', 26, 'status_elements_binary', 'relay_output_alarm'),
(NOW(), 'group', 27, 'status_elements_binary', 'relay_output_light'),
(NOW(), 'group', 28, 'status_elements_binary', 'relay_output_fan'),
(NOW(), 'group', 29, 'status_elements_binary', 'relay_output_auxiliary'),
(NOW(), 'group', 30, 'status_elements_binary', 'relay_output_dead_band'),
(NOW(), 'group', 31, 'status_elements_binary', 'relay_output_1_compressor'),
(NOW(), 'group', 32, 'status_elements_binary', 'relay_output_2_compressor'),
(NOW(), 'group', 33, 'status_elements_binary', 'relay_buzzer'),
(NOW(), 'group', 34, 'status_elements_binary', 'watch_dog_activation_device_reset'),
(NOW(), 'group', 35, 'status_elements_binary', 'umidity_function_status');

CREATE TABLE IF NOT EXISTS `iw_par_dixell_xr72cx_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(50) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_dixell_xr72cx_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'device_id', '0_3_0', 'Device ID', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_0_I16_N_-_-_-_-', ''),
(NOW(), 'firmware_version', '0_3_0.B0', 'Firmware version', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'family_product_code', '0_3_0.B1', 'Family product code', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'device_code_1_msword', '0_3_1', 'Device Code 1 (MSWord)', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_1_I16_N_-_-_-_-', ''),
(NOW(), 'device_code_2_lsword', '0_3_2', 'Device Code 2 (LSWord)', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_2_I16_N_-_-_-_-', ''),
(NOW(), 'series_number_1_msword', '0_3_3', 'Series number 1 (MSWord)', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_3_I16_N_-_-_-_-', ''),
(NOW(), 'series_number_2_lsword', '0_3_4', 'Series number 2 (LSWord)', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_4_I16_N_-_-_-_-', ''),
(NOW(), 'data_fw_version', '0_3_5', 'Data FW version', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_5_I16_N_-_-_-_-', ''),
(NOW(), 'data_fw_version_year', '0_3_5.0#7', 'Data FW version: Year', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'data_fw_version_month', '0_3_5.7#4', 'Data FW version: Month', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'data_fw_version_day', '0_3_5.11#5', 'Data FW version: Day', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'descriptior_eeprom', '0_3_6', 'Descriptior EEPROM', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_6_I16_N_-_-_-_-', ''),
(NOW(), 'descriptior_eeprom_1', '0_3_6.B0', 'Descriptior EEPROM', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'probe_configuration', '0_3_7', 'Probe Configuration', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_7_I16_N_-_-_-_-', ''),
(NOW(), 'probe_configuration_probe_1', '0_3_7.0', 'Probe Configuration, Probe 1', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'probe_configuration_probe_2', '0_3_7.1', 'Probe Configuration, Probe 2', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'probe_configuration_probe_3', '0_3_7.2', 'Probe Configuration, Probe 3', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'probe_configuration_probe_4', '0_3_7.3', 'Probe Configuration, Probe 4', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_relais', '0_3_8', 'Configuration relais', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_8_I16_N_-_-_-_-', ''),
(NOW(), 'configuration_relais_on_off', '0_3_8.0', 'Configuration relais, ON-OFF', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_relais_defrost_1', '0_3_8.1', 'Configuration relais, Defrost 1', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_relais_defrost_2', '0_3_8.2', 'Configuration relais, Defrost 2', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_relais_alarm', '0_3_8.3', 'Configuration relais, Alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_relais_light', '0_3_8.4', 'Configuration relais, Light', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_relais_fan', '0_3_8.5', 'Configuration relais, Fan', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_relais_auxiliary', '0_3_8.6', 'Configuration relais, Auxiliary', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_relais_dead_band', '0_3_8.7', 'Configuration relais, Dead band', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_relais_compressor_1', '0_3_8.8', 'Configuration relais, Compressor 1', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_relais_compressor_2', '0_3_8.9', 'Configuration relais, Compressor 2', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'configuration_digital_input_1', '0_3_10', 'Configuration Digital Input 1', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_10_I16_N_-_-_-_-', ''),
(NOW(), 'configuration_digital_input_2', '0_3_11', 'Configuration Digital Input 2', '', 'Integral value', 'integer', '', '', 'r', '', '', '', '', '', '', '', '', '', '3_11_I16_N_-_-_-_-', ''),
(NOW(), 'regulation_probe_value', '0_3_256', 'Regulation probe value', '', 'Analog values', 'float', '', '', 'r', '', '', '', '', '1', '0', '1000', '0', '100', '3_256_I16_N_-_-_-_-', ''),
(NOW(), 'defrost_1_probe_value', '0_3_257', 'Defrost 1 probe value', '', 'Analog values', 'float', '', '', 'r', '', '', '', '', '1', '0', '1000', '0', '100', '3_257_I16_N_-_-_-_-', ''),
(NOW(), 'defrost_2_probe_value', '0_3_258', 'Defrost 2 probe value', '', 'Analog values', 'float', '', '', 'r', '', '', '', '', '1', '0', '1000', '0', '100', '3_258_I16_N_-_-_-_-', ''),
(NOW(), 'regulation_fan_probe_value', '0_3_259', 'Regulation fan probe value', '', 'Analog values', 'float', '', '', 'r', '', '', '', '', '1', '0', '1000', '0', '100', '3_259_I16_N_-_-_-_-', ''),
(NOW(), 'probe_value_alarms_room_temp', '0_3_260', 'Probe value alarms room temp', '', 'Analog values', 'float', '', '', 'r', '', '', '', '', '1', '0', '1000', '0', '100', '3_260_I16_N_-_-_-_-', ''),
(NOW(), 'probe_value_alarms_condenser', '0_3_261', 'Probe value alarms condenser', '', 'Analog values', 'float', '', '', 'r', '', '', '', '', '1', '0', '1000', '0', '100', '3_261_I16_N_-_-_-_-', ''),
(NOW(), 'regulator_auxiliary_probe_value', '0_3_262', 'Regulator auxiliary probe value', '', 'Analog values', 'float', '', '', 'r', '', '', '', '', '1', '0', '1000', '0', '100', '3_262_I16_N_-_-_-_-', ''),
(NOW(), 'set_dynamic_probe_value', '0_3_263', 'Set dynamic probe value', '', 'Analog values', 'float', '', '', 'r', '', '', '', '', '1', '0', '1000', '0', '100', '3_263_I16_N_-_-_-_-', ''),
(NOW(), 'probe_value_1', '0_3_264', 'Probe value 1', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_264_I16_N_-_-_-_-', ''),
(NOW(), 'probe_value_2', '0_3_265', 'Probe value 2', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_265_I16_N_-_-_-_-', ''),
(NOW(), 'probe_value_3', '0_3_266', 'Probe value 3', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_266_I16_N_-_-_-_-', ''),
(NOW(), 'probe_value_4', '0_3_267', 'Probe value 4', '', 'Analog values', 'float', '', '', 'r', '', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_267_I16_N_-_-_-_-', ''),
(NOW(), 'regulation_set_point', '0_3_1536', 'Regulation Set point', '', 'Analog values', 'float', '', '', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_1536_I16_N_-_-_-_-', ''),
(NOW(), 'high_temp_alarm_set', '0_3_1537', 'High temp Alarm Set', '', 'Analog values', 'float', '', '', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_1537_I16_N_-_-_-_-', ''),
(NOW(), 'low_temp_alarm_set', '0_3_1538', 'Low temp Alarm Set', '', 'Analog values', 'float', '', '', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_1538_I16_N_-_-_-_-', ''),
(NOW(), 'set_point_2', '0_3_1539', 'Set point 2', '', 'Analog values', 'float', '', '', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_1539_I16_N_-_-_-_-', ''),
(NOW(), 'high_temp_alarm_set_2', '0_3_1540', 'High temp Alarm Set 2', '', 'Analog values', 'float', '', '', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_1540_I16_N_-_-_-_-', ''),
(NOW(), 'low_temp_alarm_set_2', '0_3_1541', 'Low temp Alarm Set 2', '', 'Analog values', 'float', '', '', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_1541_I16_N_-_-_-_-', ''),
(NOW(), 'on_off', '0_1_512', 'ON-OFF', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_512_X_N_5_512_X_N', ''),
(NOW(), 'defrost', '0_1_513', 'Defrost', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_513_X_N_5_513_X_N', ''),
(NOW(), 'continuos_cooling_heating', '0_1_514', 'Continuos cooling/heating', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_514_X_N_5_514_X_N', ''),
(NOW(), 'keyboard_lock', '0_1_515', 'Keyboard lock', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_515_X_N_5_515_X_N', ''),
(NOW(), 'alarms_silence', '0_1_516', 'Alarms silence', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_516_X_N_5_516_X_N', ''),
(NOW(), 'master_defrost', '0_1_517', 'Master defrost', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_517_X_N_5_517_X_N', ''),
(NOW(), 'energy_saving', '0_1_518', 'Energy saving', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_518_X_N_5_518_X_N', ''),
(NOW(), 'digital_input', '0_1_519', 'Digital input', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_519_X_N_-_-_-_-', ''),
(NOW(), 'alarm_probe_p1', '0_1_520', 'Alarm probe P1', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_520_X_N_-_-_-_-', ''),
(NOW(), 'alarm_probe_p2', '0_1_521', 'Alarm probe P2', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_521_X_N_-_-_-_-', ''),
(NOW(), 'alarm_probe_p3', '0_1_522', 'Alarm probe P3', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_522_X_N_-_-_-_-', ''),
(NOW(), 'alarm_probe_p4', '0_1_523', 'Alarm probe P4', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_523_X_N_-_-_-_-', ''),
(NOW(), 'alarm_high_room_temp', '0_1_524', 'Alarm high room temp', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_524_X_N_-_-_-_-', ''),
(NOW(), 'alarm_low_room_temp', '0_1_525', 'Alarm low room temp', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_525_X_N_-_-_-_-', ''),
(NOW(), 'alarm_high_condenser_temp', '0_1_526', 'Alarm high condenser temp', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_526_X_N_-_-_-_-', ''),
(NOW(), 'alarm_low_condenser_temp', '0_1_527', 'Alarm low condenser temp', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_527_X_N_-_-_-_-', ''),
(NOW(), 'generic_alarm_digital_input_eal', '0_1_528', 'Generic alarm digital input: EAL', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_528_X_N_-_-_-_-', ''),
(NOW(), 'generic_alarm_digital_input_bal', '0_1_529', 'Generic alarm digital input: BAL', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_529_X_N_-_-_-_-', ''),
(NOW(), 'open_door_alarm', '0_1_530', 'Open door alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_530_X_N_-_-_-_-', ''),
(NOW(), 'eeprom_alarm', '0_1_531', 'EEPROM alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_531_X_N_-_-_-_-', ''),
(NOW(), 'measurement_unit_temp_c_f', '0_1_532', 'Measurement unit temp: �C - �F', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_532_X_N_-_-_-_-', ''),
(NOW(), 'resolution_temp_value_decimal_integer', '0_1_533', 'Resolution temp value: Decimal - Integer', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_533_X_N_-_-_-_-', ''),
(NOW(), 'relay_output_on_off', '0_1_534', 'Relay output ON/OFF', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_534_X_N_-_-_-_-', ''),
(NOW(), 'relay_output_1_defrost', '0_1_535', 'Relay output 1 defrost', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_535_X_N_-_-_-_-', ''),
(NOW(), 'relay_output_2_defrost', '0_1_536', 'Relay output 2 defrost', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_536_X_N_-_-_-_-', ''),
(NOW(), 'relay_output_alarm', '0_1_537', 'Relay output alarm', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_537_X_N_-_-_-_-', ''),
(NOW(), 'relay_output_light', '0_1_538', 'Relay output light', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_538_X_N_5_538_X_N', ''),
(NOW(), 'relay_output_fan', '0_1_539', 'Relay output fan', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_539_X_N_-_-_-_-', ''),
(NOW(), 'relay_output_auxiliary', '0_1_540', 'Relay output auxiliary', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_540_X_N_5_540_X_N', ''),
(NOW(), 'relay_output_dead_band', '0_1_541', 'Relay output dead band', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_541_X_N_-_-_-_-', ''),
(NOW(), 'relay_output_1_compressor', '0_1_542', 'Relay output 1 compressor', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_542_X_N_-_-_-_-', ''),
(NOW(), 'relay_output_2_compressor', '0_1_543', 'Relay output 2 compressor', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_543_X_N_-_-_-_-', ''),
(NOW(), 'relay_buzzer', '0_1_544', 'Relay buzzer', '', 'Digital IO', 'boolean', '', '', 'r', '', '', '0', '1', '', '', '', '', '', '1_544_X_N_-_-_-_-', ''),
(NOW(), 'watch_dog_activation_device_reset', '0_1_545', 'Watch dog activation (device reset)', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_545_X_N_5_545_X_N', ''),
(NOW(), 'umidity_function_status', '0_1_546', 'Umidity function status', '', 'Digital IO', 'boolean', '', '', 'rw', '', '', '0', '1', '', '', '', '', '', '1_546_X_N_5_546_X_N', '');

CREATE TABLE IF NOT EXISTS `iw_set_dixell_xr72cx` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_dixell_xr72cx` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'device_id', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'firmware_version', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'family_product_code', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'device_code_1_msword', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'device_code_2_lsword', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'series_number_1_msword', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'series_number_2_lsword', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_fw_version', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_fw_version_year', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_fw_version_month', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_fw_version_day', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'descriptior_eeprom', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'descriptior_eeprom_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'probe_configuration', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'probe_configuration_probe_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'probe_configuration_probe_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'probe_configuration_probe_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'probe_configuration_probe_4', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais_on_off', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais_defrost_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais_defrost_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais_alarm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais_light', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais_fan', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais_auxiliary', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais_dead_band', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais_compressor_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_relais_compressor_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_digital_input_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'configuration_digital_input_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'regulation_probe_value', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'defrost_1_probe_value', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'defrost_2_probe_value', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'regulation_fan_probe_value', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'probe_value_alarms_room_temp', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'probe_value_alarms_condenser', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'regulator_auxiliary_probe_value', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'set_dynamic_probe_value', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'probe_value_1', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'probe_value_2', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'probe_value_3', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'probe_value_4', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'regulation_set_point', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'high_temp_alarm_set', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'low_temp_alarm_set', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'set_point_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'high_temp_alarm_set_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'low_temp_alarm_set_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'on_off', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'continuos_cooling_heating', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'keyboard_lock', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'alarms_silence', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'master_defrost', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'energy_saving', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'digital_input', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'alarm_probe_p1', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'alarm_probe_p2', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'alarm_probe_p3', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'alarm_probe_p4', '1', '1', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'alarm_high_room_temp', '1', '1', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'alarm_low_room_temp', '1', '1', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'alarm_high_condenser_temp', '1', '1', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'alarm_low_condenser_temp', '1', '1', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'generic_alarm_digital_input_eal', '1', '1', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'generic_alarm_digital_input_bal', '1', '1', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'open_door_alarm', '1', '1', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'eeprom_alarm', '1', '1', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'measurement_unit_temp_c_f', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'resolution_temp_value_decimal_integer', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_output_on_off', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_output_1_defrost', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_output_2_defrost', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_output_alarm', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_output_light', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_output_fan', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_output_auxiliary', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_output_dead_band', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_output_1_compressor', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_output_2_compressor', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'relay_buzzer', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'watch_dog_activation_device_reset', '1', '1', 'slow', 'change', '', '', '', 0),
(NOW(), 'umidity_function_status', '1', '1', 'slow', 'change', '', '', '', 0);



-- Changelog
--
-- v1 Orginal
--
--
