REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'ID01', 'Navn', 'MR42', 'MR42', '1_1', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID02', 'Navn', 'MR42', 'MR42', '1_2', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID03', 'Navn', 'MR42', 'MR42', '1_3', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID04', 'Navn', 'MR42', 'MR42', '1_4', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID05', 'Navn', 'MR42', 'MR42', '1_5', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID06', 'Navn', 'MR42', 'MR42', '1_6', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID07', 'Navn', 'MR42', 'MR42', '1_7', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID08', 'Navn', 'MR42', 'MR42', '1_8', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID09', 'Navn', 'MR42', 'MR42', '1_9', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID10', 'Navn', 'MR42', 'MR42', '1_10', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID11', 'Navn', 'MR42', 'MR42', '1_11', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID12', 'Navn', 'MR42', 'MR42', '1_12', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID13', 'Navn', 'MR42', 'MR42', '1_13', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID14', 'Navn', 'MR42', 'MR42', '1_14', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID15', 'Navn', 'MR42', 'MR42', '1_15', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID16', 'Navn', 'MR42', 'MR42', '1_16', 'MR42', 'MR42', ''),
(NOW(), '1', '0', 'ID17', 'Navn', 'MR42', 'MR42', '1_17', 'MR42', 'MR42', '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'com_port', 'MR42', '4', '', '', ''),
(NOW(), 'idle_event_rate', 'MR42', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'MR42', '2000', 'msec.', '', ''),
(NOW(), 'packet_timeout', 'MR42', '1', 'sec.', '', ''),
(NOW(), 'max_outstanding_packets', 'MR42', '-1', '', '', ''),
(NOW(), 'max_error_count', 'MR42', '1', '', '', ''),
(NOW(), 'max_group_count', 'MR42', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'MR42', '2', 'hours', '', ''),
(NOW(), 'speed_index_norm', 'MR42', '1', '', '', ''),
(NOW(), 'speed_index_slow', 'MR42', '1', '', '', ''),
(NOW(), 'speed_index_offline', 'MR42', '10', '', '', ''),
(NOW(), 'speed_index_block', 'MR42', '10', '', '', ''),
(NOW(), 'show_queue_info', 'MR42', '0', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'MR42', '10', 'min.', '', ''),
(NOW(), 'baud_rate', 'MR42', '9600', '', '', ''),
(NOW(), 'parity', 'MR42', '0', '', '0=N,1=O,2=E,3=M,4=S', ''),
(NOW(), 'data_bits', 'MR42', '8', '', '5..8', ''),
(NOW(), 'stop_bits', 'MR42', '1', '', '1,2', ''),
(NOW(), 'check_rate', 'MR42', '2', 'ms', '', ''),
(NOW(), 'timeout', 'MR42', '1000', 'ms', '', ''),
(NOW(), 'dx_password', 'MR42', '0000', '', '2 byte unsigned integer', ''),
(NOW(), 'module_timeout', 'MR42', '1500', 'ms', '', ''),
(NOW(), 'alarm_handler', 'MR42', '', '', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'MR42', 'mr42_param', 'mr42_groups');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_jc.exe', 'MR42', '', '');

CREATE TABLE IF NOT EXISTS `iw_par_mr42_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `TYPE` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `TYPE` (`TYPE`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_mr42_groups` (`row_date`, `TYPE`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, 'mest_brukt', ''),
(NOW(), 'group_alias', 2, 'group1', 'Parametre for temperaturkontroll'),
(NOW(), 'group_alias', 3, 'group2', 'Alarmparametre'),
(NOW(), 'group_alias', 4, 'group3', 'Avtiningsparametre'),
(NOW(), 'group_alias', 5, 'group4', 'Digitale inngangsparametre'),
(NOW(), 'group_alias', 6, 'group5', 'Parametre for viftekontroll'),
(NOW(), 'group_alias', 7, 'group6', 'Andre parametre'),
(NOW(), 'group_alias', 8, 'group7', 'Alarmer'),
(NOW(), 'group_alias', 1, 'mest_brukt', 'Mest brukt'),
(NOW(), 'group', 1, 'group1', 'hy'),
(NOW(), 'group', 2, 'group1', 'll'),
(NOW(), 'group', 3, 'group1', 'hl'),
(NOW(), 'group', 4, 'group1', 'cc'),
(NOW(), 'group', 5, 'group1', 'co'),
(NOW(), 'group', 1, 'group2', 'ah'),
(NOW(), 'group', 2, 'group2', 'al'),
(NOW(), 'group', 3, 'group2', 'ad'),
(NOW(), 'group', 4, 'group2', 'at'),
(NOW(), 'group', 5, 'group2', 'ac'),
(NOW(), 'group', 2, 'group3', 'dn'),
(NOW(), 'group', 5, 'group3', 'di'),
(NOW(), 'group', 6, 'group3', 'dd'),
(NOW(), 'group', 7, 'group3', 'dc'),
(NOW(), 'group', 8, 'group3', 'du'),
(NOW(), 'group', 9, 'group3', 'dp'),
(NOW(), 'group', 10, 'group3', 'dr'),
(NOW(), 'group', 1, 'group4', 'if'),
(NOW(), 'group', 2, 'group4', 'id'),
(NOW(), 'group', 3, 'group4', 'ib'),
(NOW(), 'group', 1, 'group6', 'sf'),
(NOW(), 'group', 2, 'group6', 'so'),
(NOW(), 'group', 4, 'group6', 'pd'),
(NOW(), 'group', 5, 'group6', 'aa'),
(NOW(), 'group', 8, 'group7', 'cooling_req'),
(NOW(), 'group', 9, 'group7', 'general_alm'),
(NOW(), 'group', 1, 'group7', 'evp_alm'),
(NOW(), 'group', 2, 'group7', 'rom_alm'),
(NOW(), 'group', 7, 'group7', 'alm_level'),
(NOW(), 'group', 3, 'group7', 'll_alm'),
(NOW(), 'group', 4, 'group7', 'hl_alm'),
(NOW(), 'group', 6, 'group7', 'door_open'),
(NOW(), 'group', 5, 'group7', 'cont_alm'),
(NOW(), 'group', 4, 'group4', 'cooling'),
(NOW(), 'group', 5, 'group4', 'fan'),
(NOW(), 'group', 6, 'group4', 'aux'),
(NOW(), 'group', 7, 'group4', 'defrost_out'),
(NOW(), 'group', 1, 'mest_brukt', 'airtemp'),
(NOW(), 'group', 3, 'mest_brukt', 'contwsp'),
(NOW(), 'group', 4, 'mest_brukt', 'contlsp'),
(NOW(), 'group', 11, 'group3', 'avtining'),
(NOW(), 'group', 12, 'group3', 'avtapping'),
(NOW(), 'group', 5, 'mest_brukt', 'avtining'),
(NOW(), 'group', 13, 'group3', 'defrost_2');

CREATE TABLE IF NOT EXISTS `iw_par_mr42_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(50) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_mr42_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'hy', '5_12_01', 'Hysterese', 'Hy', 'Analog values', 'float', '2', '101', 'rw', '', '', '1', '9', '', '', '', '', '', '', ''),
(NOW(), 'll', '5_15_01', 'Nedre grense for set-punkt', 'LL', 'Analog values', 'float', '-40', '102', 'rw', '&deg;C', '%.1f', '-40', '70', '', '', '', '', '', '', ''),
(NOW(), 'hl', '5_14_01', 'Øvre grense for set-punkt', 'HL', 'Analog values', 'float', '70', '103', 'rw', '&deg;C', '%.1f', '-40', '70', '', '', '', '', '', '', ''),
(NOW(), 'cc', '5_16_01', 'Unngå kort syklus', 'CC', 'Analog values', 'float', '2', '104', 'rw', '', '', '0', '9', '', '', '', '', '', '', ''),
(NOW(), 'co', '6_03_01', 'Tid til dypfrysing', 'Co', 'Analog values', 'float', '60', '105', 'rw', '', '', '0', '99', '', '', '', '', '', '', ''),
(NOW(), 'ah', '5_17_01', 'Høytemperatur alarmgrense', 'AH', 'Analog values', 'float', '10', '106', 'rw', '&deg;C', '%.1f', '0', '50', '', '', '', '', '', '', ''),
(NOW(), 'al', '5_18_01', 'Lavtemperatur alarmgrense', 'AL', 'Analog values', 'float', '-10', '107', 'rw', '&deg;C', '%.1f', '-50', '0', '', '', '', '', '', '', ''),
(NOW(), 'ad', '5_1A_01', 'Alarm differensial', 'Ad', 'Analog values', 'float', '1', '108', 'rw', '', '', '1', '9', '', '', '', '', '', '', ''),
(NOW(), 'at', '5_19_01', 'Tidsforsinkelse for alarm', 'At', 'Analog values', 'float', '30', '109', 'rw', 'sek', '', '0', '5940', '', '', '', '', '', '', ''),
(NOW(), 'ac', '6_09_01', 'Oppstart/defrost tidsforinkelse for alarm', 'AC', 'Analog values', 'float', '20', '110', 'rw', '', '', '0', '99', '', '', '', '', '', '', ''),
(NOW(), 'dn', '7_15_01', 'Avtiningsinitiering', 'dn', 'Digital IO', 'bit', '', '112', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'di', '6_06_01', 'Avtiningsinterval', 'di', 'Analog values', 'float', '6', '115', 'rw', '', '', '0', '5940', '', '', '', '', '', '', ''),
(NOW(), 'dd', '6_04_01', 'Maksimal avtiningstid', 'dd', 'Analog values', 'float', '40', '116', 'rw', '', '', '0', '99', '', '', '', '', '', '', ''),
(NOW(), 'dc', '6_05_01', 'Drypptid', 'dC', 'Analog values', 'float', '5', '117', 'rw', '', '', '0', '99', '', '', '', '', '', '', ''),
(NOW(), 'du', '6_07_01', 'Føste avtining etter oppstart', 'dU', 'Analog values', 'float', '', '118', 'rw', '', '', '0', '99', '', '', '', '', '', '', ''),
(NOW(), 'dp', '7_13_01', 'Skjermvisning under avtining', 'dP', 'Digital IO', 'bit', '', '119', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'dr', '6_08_01', 'Tidsforsinkelse for skjerm etter avtining', 'dr', 'Analog values', 'float', '20', '120', 'rw', '', '', '0', '99', '', '', '', '', '', '', ''),
(NOW(), 'if', '7_09_01', 'Digital inngangsfunksjon', 'iF', 'Integral values', 'integer', '', '121', 'rw', '', '', '0', '8', '', '', '', '', '', '', ''),
(NOW(), 'id', '6_02_01', 'Digital inngangsforsinkelse', 'id', 'Analog values', 'float', '5', '122', 'rw', '', '', '0', '99', '', '', '', '', '', '', ''),
(NOW(), 'ib', '5_13_01', 'Set-punkt bias', 'ib', 'Analog values', 'float', '3', '123', 'rw', '&deg;C', '%.1f', '-10', '10', '', '', '', '', '', '', ''),
(NOW(), 'sf', '7_10_01', 'Termostatfunksjon ved feil på sensor', 'SF', 'Integral values', 'integer', '', '129', 'rw', '', '', '0', '2', '', '', '', '', '', '', ''),
(NOW(), 'so', '5_10_01', 'Sensor offset', 'So', 'Analog values', 'float', '0', '130', 'rw', '', '', '-20', '20', '', '', '', '', '', '', ''),
(NOW(), 'pd', '5_0F_01', 'Virtuell temperaturvekting', 'Pd', 'Analog values', 'float', '0', '132', 'rw', '', '', '0', '100', '', '', '', '', '', '', ''),
(NOW(), 'aa', '7_0E_01', 'Programerbar digital utgang', 'AA', 'Digital IO', 'bit', '0', '133', 'rw', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'alarmword', '6_00_01', 'Alarmstatus', '', 'Digital IO', 'word', '', '1000', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'always_1', '6_00_01.0', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'cooling_req', '6_00_01.1', 'Behov for kjøling', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'bit3_alm', '6_00_01.2', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'bias_setpkt_ins', '6_00_01.3', 'Bias settpunkt', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'bit5_alm', '6_00_01.4', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'bit6_alm', '6_00_01.5', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'bit7_alm', '6_00_01.6', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'bit8_alm', '6_00_01.7', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'general_alm', '6_00_01.8', 'Generell alarm fra DI', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'evp_alm', '6_00_01.9', 'Feil på fordampersensor', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'rom_alm', '6_00_01.10', 'Feil på romsensor', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'alm_level', '6_00_01.11', 'Alarmnivå', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'll_alm', '6_00_01.12', 'Lavtemperaturalarm', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'hl_alm', '6_00_01.13', 'Høytemperaturalarm', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'door_open', '6_00_01.14', 'Åpen dør', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'cont_alm', '6_00_01.15', 'Alarm i regulator', '', 'Digital IO', 'bit', '', '1000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'status_out', '6_01_01', 'Utgangsstatus', '', 'Digital IO', 'byte', '', '2000', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'cooling', '6_01_01.0', 'Status kjøling', '', 'Digital IO', 'bit', '', '2000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'fan', '6_01_01.1', 'Status fordampervifte', '', 'Digital IO', 'bit', '', '2000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'aux', '6_01_01.2', 'Alarm/aux utgang', '', 'Digital IO', 'bit', '', '2000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_out', '6_01_01.3', 'Avtiningsutgang', '', 'Digital IO', 'bit', '', '2000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'bit5_stat', '6_01_01.4', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '2000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'bit6_stat', '6_01_01.5', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '2000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'bit7_stat', '6_01_01.6', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '2000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'bit8_stat', '6_01_01.7', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '2000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'airtemp', '5_00_01', 'Romtemperatur', '', 'Analog values', 'float', '', '1', 'r', '&deg;C', '%.1f', '-40', '70', '', '', '', '', '', '', ''),
(NOW(), 'contwsp', '5_01_01', 'Avlest arbeidende settpunkt', '', 'Analog values', 'float', '', '2', 'r', '&deg;C', '%.1f', '-40', '70', '', '', '', '', '', '', ''),
(NOW(), 'contlsp', '5_11_01', 'Innstilling av setpunkt', '', 'Analog values', 'float', '', '4', 'rw', '&deg;C', '%.1f', '-40', '70', '', '', '', '', '', '', ''),
(NOW(), 'defstat', '7_00_01', 'Avtiningsstatus', '', 'Digital IO', 'byte', '', '3000', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'avtapping', '7_00_01.0', 'Avtapping', '', 'Digital IO', 'bit', '', '3000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'avtining', '7_00_01.1', 'Avtiningsindikering', '', 'Digital IO', 'bit', '', '3000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defstat_3', '7_00_01.2', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '3000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defstat_4', '7_00_01.3', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '3000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defstat_5', '7_00_01.4', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '3000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defstat_6', '7_00_01.5', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '3000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defstat_7', '7_00_01.6', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '3000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defstat_8', '7_00_01.7', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '3000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost', '7_12_01', 'Avtining', '', 'Digital IO', 'byte', '', '4000', 'r', '', '', '', '', '', '', '', '', '', '', ''),
(NOW(), 'avtining_SD', '7_12_01.0', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '4000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_2', '7_12_01.1', 'Startsignal for avtining fra SD anlegg', '', 'Digital IO', 'bit', '', '4000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_3', '7_12_01.2', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '4000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_4', '7_12_01.3', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '4000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_5', '7_12_01.4', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '4000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_6', '7_12_01.5', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '4000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_7', '7_12_01.6', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '4000', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'defrost_8', '7_12_01.7', 'Ikke i bruk', '', 'Digital IO', 'bit', '', '4000', 'vr', '', '', '0', '1', '', '', '', '', '', '', '');

CREATE TABLE IF NOT EXISTS `iw_set_mr42` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='4.0.0';

REPLACE INTO `iw_set_mr42` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'hy', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'll', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'hl', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'cc', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'co', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ah', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'al', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ad', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'at', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ac', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dn', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dd', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dc', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'du', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dp', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'dr', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'if', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'id', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'ib', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sf', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'so', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'pd', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'aa', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'alarmword', '1', '1', 'norm', 'none', '', '', '', 0),
(NOW(), 'always_1', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'cooling_req', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'bit3_alm', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'bias_setpkt_ins', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'bit5_alm', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'bit6_alm', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'bit7_alm', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'bit8_alm', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'general_alm', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'evp_alm', '1', '0', 'norm', 'change', '', 'B', '', 0),
(NOW(), 'rom_alm', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'alm_level', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'll_alm', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'hl_alm', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'door_open', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'cont_alm', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'status_out', '1', '1', 'norm', 'none', '', '', '', 0),
(NOW(), 'cooling', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'fan', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'aux', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'defrost_out', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'bit5_stat', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'bit6_stat', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'bit7_stat', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'bit8_stat', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'airtemp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'contwsp', '1', '0', 'slow', 'min', '1', '', '', 0),
(NOW(), 'contlsp', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defstat', '1', '1', 'norm', 'none', '', '', '', 0),
(NOW(), 'avtapping', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'avtining', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'defstat_3', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defstat_4', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defstat_5', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defstat_6', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defstat_7', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defstat_8', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost', '1', '1', 'norm', 'none', '', '', '', 0),
(NOW(), 'avtining_SD', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_3', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_4', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_5', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_6', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_7', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'defrost_8', '0', '0', 'slow', 'change', '', '', '', 0);


-- Changelog
--
-- v1 Orginal
--
--