REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'E10', 'Energi Ventilasjon', 'qalcosonic_rev2', 'QALCOSONIC', '0_85', 'QALCOSONIC', 'QALCOSONICREV2', 8300, ''),
(NOW(), '1', '0', 'E11', 'Energi Aerotemper', 'qalcosonic_rev2', 'QALCOSONIC', '0_84', 'QALCOSONIC', 'QALCOSONICREV2', 8310, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'comm_port', 'QALCOSONIC', '5', '', '', ''),
(NOW(), 'comm_parity', 'QALCOSONIC', '2', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'comm_data_bits', 'QALCOSONIC', '8', '', '', ''),
(NOW(), 'comm_stop_bits', 'QALCOSONIC', '1', '', '', ''),
(NOW(), 'comm_baudrate', 'QALCOSONIC', '9600', '', '', ''),
(NOW(), 'mb_mode', 'QALCOSONIC', '0', '', '0=RTU|1=ASCII|3=TCP', ''),
(NOW(), 'force_word_not_byte', 'QALCOSONIC', '0', '', '0|1', ''),
(NOW(), 'handshake', 'QALCOSONIC', '0', '', '0|1|2', ''),
(NOW(), 'check_rate', 'QALCOSONIC', '1', 'ms', '', ''),
(NOW(), 'max_outstanding_packets', 'QALCOSONIC', '-1', '', '', ''),
(NOW(), 'packet_timeout', 'QALCOSONIC', '1', 'sec.', '', ''),
(NOW(), 'idle_event_rate', 'QALCOSONIC', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'QALCOSONIC', '2000', 'msec.', '', ''),
(NOW(), 'max_error_count', 'QALCOSONIC', '2', '', '', ''),
(NOW(), 'mb_request_timeout', 'QALCOSONIC', '1000', 'ms', '', ''),
(NOW(), 'mb_request_retries', 'QALCOSONIC', '2', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'QALCOSONIC', '10', 'min.', '', ''),
(NOW(), 'show_queue_info', 'QALCOSONIC', '0', '', '', ''),
(NOW(), 'speed_index_block', 'QALCOSONIC', '10', '', '', ''),
(NOW(), 'speed_index_offline', 'QALCOSONIC', '10', '', '', ''),
(NOW(), 'speed_index_slow', 'QALCOSONIC', '1', '', '', ''),
(NOW(), 'speed_index_norm', 'QALCOSONIC', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'QALCOSONIC', '2', 'hours', '', ''),
(NOW(), 'max_group_count', 'QALCOSONIC', '1', '', '', ''),
(NOW(), 'value_quality_check_limit', 'QALCOSONIC', '0', '', '0 = disabled', ''),
(NOW(), 'mux_settle_time', 'QALCOSONIC', '1500', 'ms', 'Time for the muxed input to settle. The value shuld be a multiple off 100.', ''),
(NOW(), 'startup_delay', 'QALCOSONIC', '15', 'Sec.', '', ''),
(NOW(), 'alarm_handler', 'QALCOSONIC', '', '', '', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_mb.exe', 'QALCOSONIC', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'QALCOSONICREV2', 'qalcosonic_rev2_param', 'qalcosonic_rev2_groups');

CREATE TABLE IF NOT EXISTS `iw_par_qalcosonic_rev2_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_qalcosonic_rev2_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'sys', 'Measurements'),
(NOW(), 'group', 1, 'sys', 'sys_0_3_0'),
(NOW(), 'group', 2, 'sys', 'sys_0_3_2'),
(NOW(), 'group', 3, 'sys', 'sys_0_3_3'),
(NOW(), 'group', 4, 'sys', 'sys_0_3_7'),
(NOW(), 'group', 5, 'sys', 'sys_0_3_9'),
(NOW(), 'group', 6, 'sys', 'sys_0_3_10'),
(NOW(), 'group', 7, 'sys', 'sys_0_3_14'),
(NOW(), 'group', 8, 'sys', 'sys_0_3_16'),
(NOW(), 'group', 9, 'sys', 'sys_0_3_17'),
(NOW(), 'group', 10, 'sys', 'sys_0_3_21'),
(NOW(), 'group', 11, 'sys', 'sys_0_3_23'),
(NOW(), 'group', 12, 'sys', 'sys_0_3_24'),
(NOW(), 'group', 13, 'sys', 'sys_0_3_28'),
(NOW(), 'group', 14, 'sys', 'sys_0_4_33'),
(NOW(), 'group', 15, 'sys', 'sys_0_3_30'),
(NOW(), 'group', 16, 'sys', 'sys_0_3_31'),
(NOW(), 'group', 17, 'sys', 'sys_0_3_35'),
(NOW(), 'group', 18, 'sys', 'sys_0_3_37'),
(NOW(), 'group', 19, 'sys', 'sys_0_3_38'),
(NOW(), 'group', 20, 'sys', 'sys_0_3_42'),
(NOW(), 'group', 21, 'sys', 'sys_0_3_44'),
(NOW(), 'group', 22, 'sys', 'sys_0_3_45'),
(NOW(), 'group', 23, 'sys', 'sys_0_3_49'),
(NOW(), 'group', 24, 'sys', 'sys_0_3_51'),
(NOW(), 'group', 25, 'sys', 'sys_0_3_52'),
(NOW(), 'group', 26, 'sys', 'sys_0_3_56'),
(NOW(), 'group', 27, 'sys', 'sys_0_3_58'),
(NOW(), 'group', 28, 'sys', 'sys_0_3_59'),
(NOW(), 'group', 29, 'sys', 'sys_0_3_63'),
(NOW(), 'group', 30, 'sys', 'sys_0_3_67'),
(NOW(), 'group', 31, 'sys', 'sys_0_3_71'),
(NOW(), 'group', 32, 'sys', 'sys_0_3_75'),
(NOW(), 'group', 33, 'sys', 'sys_0_3_77'),
(NOW(), 'group', 34, 'sys', 'sys_0_3_81'),
(NOW(), 'group', 35, 'sys', 'sys_0_3_2000'),
(NOW(), 'group', 36, 'sys', 'sys_0_3_2002'),
(NOW(), 'group', 37, 'sys', 'sys_0_3_2004'),
(NOW(), 'group', 38, 'sys', 'sys_0_3_1000'),
(NOW(), 'group', 39, 'sys', 'sys_0_3_1001'),
(NOW(), 'group', 40, 'sys', 'sys_0_3_1002'),
(NOW(), 'group', 41, 'sys', 'sys_0_3_1004'),
(NOW(), 'group', 42, 'sys', 'sys_0_3_1005'),
(NOW(), 'group', 43, 'sys', 'sys_0_3_1006'),
(NOW(), 'group', 99, 'sys', 'sys_0_3_1000_swap');

CREATE TABLE IF NOT EXISTS `iw_par_qalcosonic_rev2_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(50) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_qalcosonic_rev2_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'sys_0_3_0', '0_3_0', 'Heating Energy', '', 'Analog values', 'integer', '', '-1', 'r', 'kWh', '', '', '', '', '', '', '', '', '3_0_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_7', '0_3_7', 'Cooling Energy', '', 'Analog values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_7_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_9', '0_3_9', 'Cooling Energy (Unit Factor)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_9_U16_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_10', '0_3_10', 'Cooling Energy (Unit)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_10_str12_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_14', '0_3_14', 'Tariff Energy 1', '', 'Analog values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_14_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_16', '0_3_16', 'Tariff Energy 1 (Unit Factor)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_16_U16_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_17', '0_3_17', 'Tariff Energy 1 (Unit)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_17_str12_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_21', '0_3_21', 'Tariff Energy 2', '', 'Analog values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_21_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_23', '0_3_23', 'Tariff Energy 2 (Unit Factor)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_23_U16_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_24', '0_3_24', 'Tariff Energy 2 (Unit)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_24_str12_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_28', '0_3_28', 'Volume', '', 'Analog values', 'integer', '', '-1', 'r', 'm3', '', '', '', '1', '0', '1000', '0', '1', '3_28_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_4_33', '0_4_33', 'Volume (test med Float)', '', 'Analog values', 'integer', '', '-1', 'r', 'm3', '', '', '', '', '', '', '', '', '4_33_F_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_35', '0_3_35', 'Pulse Input Volume 1', '', 'Analog values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_35_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_37', '0_3_37', 'Pulse Input Volume 1 (Unit Factor)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_37_U16_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_38', '0_3_38', 'Pulse Input Volume 1 (Unit)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_38_str12_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_42', '0_3_42', 'Pulse Input Volume 2', '', 'Analog values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_42_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_44', '0_3_44', 'Pulse Input Volume 2 (Unit Factor)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_44_U16_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_45', '0_3_45', 'Pulse Input Volume 2 (Unit)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_45_str12_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_49', '0_3_49', 'Power', '', 'Analog values', 'integer', '', '-1', 'r', 'kW', '', '', '', '1', '0', '1000', '0', '1', '3_49_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_56', '0_3_56', 'Flow', '', 'Analog values', 'integer', '', '-1', 'r', 'm3/h', '', '', '', '1', '0', '1000', '0', '1', '3_56_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_63', '0_3_63', 'Forward temperature (Fixed)', '', 'Analog values', 'integer', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '100', '0', '1', '3_63_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_67', '0_3_67', 'Return temperature (Fixed)', '', 'Analog values', 'integer', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '100', '0', '1', '3_67_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_71', '0_3_71', 'Temperature difference (Fixed)', '', 'Analog values', 'integer', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '100', '0', '1', '3_71_I32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_75', '0_3_75', 'Heat Meter Serial Number (Fixed)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_75_U32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_77', '0_3_77', 'Heat Meter Serial Number (ASCII)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_77_str12_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_81', '0_3_81', 'Error Code', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_81_U32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_2000', '0_3_2000', 'Module Serial Number', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_2000_U32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_2002', '0_3_2002', 'Module Model Number', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_2002_U32_W_-_-_-_-', ''),
(NOW(), 'sys_0_3_2004', '0_3_2004', 'Firmware Version', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_2004_U16_N_-_-_-_-', ''),
(NOW(), 'sys_0_3_1000_swap', '0_3_1000_swap', 'Test av Byte swap på Modbus Slave ID: If the higher byte is set to 1, the Modbus address will be updated to the meter M-Bus address. If the higher byte is set to 0, the Modbus address is static.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_1000_U16_R_6_1000_U16_R', ''),
(NOW(), 'sys_0_3_1000', '0_3_1000', 'Modbus Slave ID', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_1000_U16_N_6_1000_U16_N', ''),
(NOW(), 'sys_0_3_1001', '0_3_1001', 'Update Rate Data from Meter', '', 'Integral values', 'integer', '', '-1', 'rw', 'sek', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_1001_U16_N_6_1001_U16_N', ''),
(NOW(), 'sys_0_3_1002', '0_3_1002', 'Baud Rate', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_1002_U32_W_6_1002_U32_W', ''),
(NOW(), 'sys_0_3_1004', '0_3_1004', 'Data Bits', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_1004_U16_N_6_1004_U16_N', ''),
(NOW(), 'sys_0_3_1005', '0_3_1005', 'Parity', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_1005_U16_N_6_1005_U16_N', '{"rev":"1","type":"num","v":{"69":{"t":"Even"},"79":{"t":"Odd"},"78":{"t":"None"}}}'),
(NOW(), 'sys_0_3_1006', '0_3_1006', 'Stop Bits', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_1006_U16_N_6_1006_U16_N', '');

CREATE TABLE IF NOT EXISTS `iw_set_qalcosonic_rev2` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_qalcosonic_rev2` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'sys_0_3_0', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_7', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_9', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_10', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_14', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_16', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_17', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_21', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_23', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_24', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_28', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_4_33', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_30', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_31', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_35', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_37', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_38', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_42', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_44', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_45', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_49', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_51', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_52', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_56', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_58', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_59', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_63', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_67', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_71', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'sys_0_3_75', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_77', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_81', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_2000', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_2002', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_2004', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_1000', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_1000_swap', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_1001', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_1002', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_1004', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_1005', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'sys_0_3_1006', '1', '0', 'slow', 'change', '', '', '', 0);
