REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'R01', 'Fan Coil', 'regin_rcf230ctd', 'REGINRCF', '0_1', 'RCF', 'RCF230CTD', 0, ''),
(NOW(), '1', '0', 'R02', 'Fan Coil', 'regin_rcf230ctd', 'REGINRCF', '0_2', 'RCF', 'RCF230CTD', 0, ''),
(NOW(), '1', '0', 'R03', 'Fan Coil', 'regin_rcf230ctd', 'REGINRCF', '0_3', 'RCF', 'RCF230CTD', 0, ''),
(NOW(), '1', '0', 'R04', 'Fan Coil', 'regin_rcf230ctd', 'REGINRCF', '0_4', 'RCF', 'RCF230CTD', 0, ''),
(NOW(), '1', '0', 'R05', 'Fan Coil', 'regin_rcf230ctd', 'REGINRCF', '0_5', 'RCF', 'RCF230CTD', 0, ''),
(NOW(), '1', '0', 'R06', 'Fan Coil', 'regin_rcf230ctd', 'REGINRCF', '0_6', 'RCF', 'RCF230CTD', 0, ''),
(NOW(), '1', '0', 'R07', 'Fan Coil', 'regin_rcf230ctd', 'REGINRCF', '0_7', 'RCF', 'RCF230CTD', 0, ''),
(NOW(), '1', '0', 'R08', 'Fan Coil', 'regin_rcf230ctd', 'REGINRCF', '0_8', 'RCF', 'RCF230CTD', 0, ''),
(NOW(), '1', '0', 'R09', 'Fan Coil', 'regin_rcf230ctd', 'REGINRCF', '0_9', 'RCF', 'RCF230CTD', 0, ''),
(NOW(), '1', '0', 'R10', 'Fan Coil', 'regin_rcf230ctd', 'REGINRCF', '0_10', 'RCF', 'RCF230CTD', 0, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'comm_port', 'REGINRCF', '2', '', '', ''),
(NOW(), 'comm_baudrate', 'REGINRCF', '9600', '', '', ''),
(NOW(), 'comm_stop_bits', 'REGINRCF', '1', '', '', ''),
(NOW(), 'comm_data_bits', 'REGINRCF', '8', '', '', ''),
(NOW(), 'mb_mode', 'REGINRCF', '0', '', '0=RTU|1=ASCII|2=TCP', ''),
(NOW(), 'alarm_handler', 'REGINRCF', '', '', '', ''),
(NOW(), 'idle_event_rate', 'REGINRCF', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'REGINRCF', '2000', 'msec.', '', ''),
(NOW(), 'value_quality_check_limit', 'REGINRCF', '0', '', '0 = disabled', ''),
(NOW(), 'packet_timeout', 'REGINRCF', '0', 'sec.', '', ''),
(NOW(), 'max_outstanding_packets', 'REGINRCF', '-1', '', '', ''),
(NOW(), 'max_error_count', 'REGINRCF', '2', '', '', ''),
(NOW(), 'max_group_count', 'REGINRCF', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'REGINRCF', '2', 'hours', '', ''),
(NOW(), 'speed_index_norm', 'REGINRCF', '1', '', '', ''),
(NOW(), 'speed_index_slow', 'REGINRCF', '1', '', '', ''),
(NOW(), 'speed_index_offline', 'REGINRCF', '10', '', '', ''),
(NOW(), 'speed_index_block', 'REGINRCF', '10', '', '', ''),
(NOW(), 'show_queue_info', 'REGINRCF', '0', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'REGINRCF', '10', 'min.', '', ''),
(NOW(), 'mb_request_retries', 'REGINRCF', '0', '', '', ''),
(NOW(), 'mb_request_timeout', 'REGINRCF', '500', 'ms', '', ''),
(NOW(), 'mux_settle_time', 'REGINRCF', '1500', 'ms', 'Time for the muxed input to settle. The value shuld be a multiple off 100.', ''),
(NOW(), 'startup_delay', 'REGINRCF', '15', 'Sec.', '', ''),
(NOW(), 'comm_parity', 'REGINRCF', '2', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'check_rate', 'REGINRCF', '1', 'ms', '', ''),
(NOW(), 'handshake', 'REGINRCF', '0', '', '0|1|2', ''),
(NOW(), 'force_word_not_byte', 'REGINRCF', '0', '', '0|1', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_mb.exe', 'REGINRCF', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'RCF230CTD', 'regin_rcf230ctd_param', 'regin_rcf230ctd_groups');

CREATE TABLE IF NOT EXISTS `iw_par_regin_rcf230ctd_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';


REPLACE INTO `iw_par_regin_rcf230ctd_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 3, '', ''),
(NOW(), 'group_alias', 1, 'discrete', 'Discrete inputs'),
(NOW(), 'group_alias', 2, 'coilstatus', 'Coil Status register'),
(NOW(), 'group_alias', 3, 'inputregister', 'Input register'),
(NOW(), 'group_alias', 4, 'holdingregister', 'Holding register'),
(NOW(), 'group', 1, 'discrete', 'RegioDigIn1'),
(NOW(), 'group', 4, 'discrete', 'RegioUDigIn1'),
(NOW(), 'group', 7, 'discrete', 'RegioDigOut1'),
(NOW(), 'group', 10, 'discrete', 'RegioDigOut2'),
(NOW(), 'group', 13, 'discrete', 'RegioDigOut3'),
(NOW(), 'group', 16, 'discrete', 'RegioUDigOut1'),
(NOW(), 'group', 19, 'discrete', 'RegioUDigOut2'),
(NOW(), 'group', 22, 'discrete', 'RegioDIOpenWindow'),
(NOW(), 'group', 25, 'discrete', 'RegioDIPresences'),
(NOW(), 'group', 28, 'discrete', 'RegioDIChangeOver'),
(NOW(), 'group', 31, 'discrete', 'RegioFanSpeed1'),
(NOW(), 'group', 34, 'discrete', 'RegioFanSpeed2'),
(NOW(), 'group', 37, 'discrete', 'RegioFanSpeed3'),
(NOW(), 'group', 40, 'discrete', 'RegioCVHeatPulsProp'),
(NOW(), 'group', 43, 'discrete', 'RegioCVCoolPulsProp'),
(NOW(), 'group', 46, 'discrete', 'RegioCVHeatInc'),
(NOW(), 'group', 49, 'discrete', 'RegioCVHeatDec'),
(NOW(), 'group', 52, 'discrete', 'RegioAIChangeOverState'),
(NOW(), 'group', 55, 'discrete', 'RegioChangeOverState'),
(NOW(), 'group', 58, 'discrete', ' RegioPresence'),
(NOW(), 'group', 1, 'coilstatus', 'RegioShutDown'),
(NOW(), 'group', 4, 'coilstatus', 'RegioFireAlarmStop'),
(NOW(), 'group', 7, 'coilstatus', 'RegioDi1NC'),
(NOW(), 'group', 10, 'coilstatus', 'RegioUDi1NC'),
(NOW(), 'group', 13, 'coilstatus', 'RegioDO4NC'),
(NOW(), 'group', 16, 'coilstatus', 'RegioDO5NC'),
(NOW(), 'group', 19, 'coilstatus', 'RegioDilAct'),
(NOW(), 'group', 22, 'coilstatus', 'RegioMPAct'),
(NOW(), 'group', 25, 'coilstatus', 'RegioTermoModel'),
(NOW(), 'group', 28, 'coilstatus', 'RegioMinFanSpeed'),
(NOW(), 'group', 31, 'coilstatus', 'RegioComFactoryDefaults'),
(NOW(), 'group', 34, 'coilstatus', 'RegioBlockConfig'),
(NOW(), 'group', 37, 'coilstatus', 'RegioPreventManualFanSp eed'),
(NOW(), 'group', 1, 'inputregister', 'RegioSoftware'),
(NOW(), 'group', 4, 'inputregister', 'RegioVerMajor'),
(NOW(), 'group', 7, 'inputregister', 'RegioVerMinor'),
(NOW(), 'group', 10, 'inputregister', 'RegioVerBranch'),
(NOW(), 'group', 13, 'inputregister', 'RegioRevision'),
(NOW(), 'group', 16, 'inputregister', 'RegioUnitState'),
(NOW(), 'group', 19, 'inputregister', 'RegioControllerState'),
(NOW(), 'group', 22, 'inputregister', 'RegioFanSpeed'),
(NOW(), 'group', 25, 'inputregister', 'RegioRoomTemp'),
(NOW(), 'group', 28, 'inputregister', 'RegioRoomTempExt'),
(NOW(), 'group', 31, 'inputregister', 'RegioRoomTempInt'),
(NOW(), 'group', 34, 'inputregister', 'RegioAIChangeOver'),
(NOW(), 'group', 37, 'inputregister', 'RegioAnaIn1'),
(NOW(), 'group', 40, 'inputregister', 'RegioUAnaIn1'),
(NOW(), 'group', 43, 'inputregister', 'RegioUAnaOut1'),
(NOW(), 'group', 46, 'inputregister', 'RegioUAnaOut2'),
(NOW(), 'group', 49, 'inputregister', 'RegioPIDSetP'),
(NOW(), 'group', 52, 'inputregister', 'RegioPIDOutput'),
(NOW(), 'group', 55, 'inputregister', 'RegioHeatOutput'),
(NOW(), 'group', 58, 'inputregister', 'RegioCoolOutput'),
(NOW(), 'group', 61, 'inputregister', 'RegioAI1Raw'),
(NOW(), 'group', 64, 'inputregister', 'RegioUI1Raw'),
(NOW(), 'group', 67, 'inputregister', 'RoomTemp_NTC2'),
(NOW(), 'group', 70, 'inputregister', 'RegioSupplyAirTemp'),
(NOW(), 'group', 73, 'inputregister', 'RegioSupplyAirPIDout'),
(NOW(), 'group', 76, 'inputregister', 'RegioPID2Setp'),
(NOW(), 'group', 1, 'holdingregister', 'RegioHeatOutputSelect'),
(NOW(), 'group', 4, 'holdingregister', 'RegioCoolOutputSelect'),
(NOW(), 'group', 7, 'holdingregister', 'RegioFanSelect'),
(NOW(), 'group', 10, 'holdingregister', ' RegioFanControlMode'),
(NOW(), 'group', 13, 'holdingregister', 'RegioFanSpeed1Start'),
(NOW(), 'group', 16, 'holdingregister', 'RegioFanSpeed2Start'),
(NOW(), 'group', 19, 'holdingregister', 'RegioFanSpeed3Start'),
(NOW(), 'group', 22, 'holdingregister', 'RegioFanSpeedHyst'),
(NOW(), 'group', 25, 'holdingregister', 'RegioFanSpeedMax'),
(NOW(), 'group', 28, 'holdingregister', 'RegioChangeOverSelect'),
(NOW(), 'group', 31, 'holdingregister', 'RegioRemoteState'),
(NOW(), 'group', 34, 'holdingregister', 'RegioUnitReturnState'),
(NOW(), 'group', 37, 'holdingregister', 'RegioControllerMode'),
(NOW(), 'group', 40, 'holdingregister', 'RegioCVHeatType'),
(NOW(), 'group', 43, 'holdingregister', 'RegioCVCoolType'),
(NOW(), 'group', 46, 'holdingregister', 'RegioCVHeatExerciseInterval'),
(NOW(), 'group', 49, 'holdingregister', 'RegioCVCoolExerciseInterval'),
(NOW(), 'group', 52, 'holdingregister', 'RegioAi1'),
(NOW(), 'group', 55, 'holdingregister', 'RegioUi1'),
(NOW(), 'group', 58, 'holdingregister', 'RegioUo1'),
(NOW(), 'group', 61, 'holdingregister', 'RegioUo2'),
(NOW(), 'group', 64, 'holdingregister', 'RegioModbusSlaveAddr'),
(NOW(), 'group', 67, 'holdingregister', 'RegioModbusParity'),
(NOW(), 'group', 70, 'holdingregister', 'RegioModbusCharTimeout'),
(NOW(), 'group', 73, 'holdingregister', 'RegioModbusAnswerDelay'),
(NOW(), 'group', 76, 'holdingregister', 'RegioDispBacklightLO'),
(NOW(), 'group', 79, 'holdingregister', 'RegioDispBacklightHi'),
(NOW(), 'group', 82, 'holdingregister', 'RegioDispContrast'),
(NOW(), 'group', 85, 'holdingregister', 'RegioDisplayViewMode'),
(NOW(), 'group', 88, 'holdingregister', 'RegioPresenceOffTime'),
(NOW(), 'group', 91, 'holdingregister', 'RegioPresenceOnTime'),
(NOW(), 'group', 94, 'holdingregister', 'RegioCVHeatPeriodTime'),
(NOW(), 'group', 97, 'holdingregister', 'RegioCVCoolPeriodTime'),
(NOW(), 'group', 100, 'holdingregister', 'RegioCVHeatRunTime'),
(NOW(), 'group', 103, 'holdingregister', 'RegioCVCoolRunTime'),
(NOW(), 'group', 106, 'holdingregister', 'RegioStandbySetPDeadBand'),
(NOW(), 'group', 109, 'holdingregister', 'RegioUnOccSetPHeat'),
(NOW(), 'group', 112, 'holdingregister', 'RegioUnOccSetPCool'),
(NOW(), 'group', 115, 'holdingregister', 'RegioSetpointOffsetPos'),
(NOW(), 'group', 118, 'holdingregister', 'RegioSetpointOffsetNeg'),
(NOW(), 'group', 121, 'holdingregister', 'RegioSetPOffset'),
(NOW(), 'group', 124, 'holdingregister', 'RegioPIDPGain'),
(NOW(), 'group', 127, 'holdingregister', 'RegioPIDITime'),
(NOW(), 'group', 130, 'holdingregister', 'RegioAIChangeOverLimitLow'),
(NOW(), 'group', 133, 'holdingregister', 'RegioAIChangeOverLimitHigh'),
(NOW(), 'group', 136, 'holdingregister', 'RegioAi1Comp'),
(NOW(), 'group', 139, 'holdingregister', ' RegioUi1Comp'),
(NOW(), 'group', 142, 'holdingregister', 'RegioInternalTempComp'),
(NOW(), 'group', 145, 'holdingregister', 'RegioTempFilterFactor'),
(NOW(), 'group', 148, 'holdingregister', 'RegioThermostatHyst'),
(NOW(), 'group', 151, 'holdingregister', 'RegioComfortSetPDeadBand'),
(NOW(), 'group', 154, 'holdingregister', 'RegioHeatOutputManual'),
(NOW(), 'group', 157, 'holdingregister', 'RegioCoolOutputManual'),
(NOW(), 'group', 160, 'holdingregister', 'RegioRoomTempRemote'),
(NOW(), 'group', 163, 'holdingregister', 'RegioMinECFanSpeed'),
(NOW(), 'group', 166, 'holdingregister', 'RegioMaxECFanSpeed'),
(NOW(), 'group', 169, 'holdingregister', 'RegioRCFSetPoint'),
(NOW(), 'group', 172, 'holdingregister', 'SupplyAirTLim_HeatHi'),
(NOW(), 'group', 175, 'holdingregister', 'SupplyAirTLim_HeatLo'),
(NOW(), 'group', 178, 'holdingregister', 'SupplyAirTLim_CoolHi'),
(NOW(), 'group', 181, 'holdingregister', 'SupplyAirTLim_CoolLo'),
(NOW(), 'group', 184, 'holdingregister', 'SupplyAirTLim_CascadeFact'),
(NOW(), 'group', 187, 'holdingregister', 'SupplyAirTLim_FrostProtect');



CREATE TABLE IF NOT EXISTS `iw_par_regin_rcf230ctd_param` (
  `row_date` datetime NOT NULL DEFAULT '2002-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';


REPLACE INTO `iw_par_regin_rcf230ctd_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'RegioDigIn1', '0_2_1', 'Value on digital input 1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_1_X_N_-_-_-_-', ''),
(NOW(), 'RegioUDigIn1', '0_2_3', 'Value on universal digital input 1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_3_X_N_-_-_-_-', ''),
(NOW(), 'RegioDigOut1', '0_2_5', 'Value on digital output 1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_5_X_N_-_-_-_-', ''),
(NOW(), 'RegioDigOut2', '0_2_6', 'Value on digital output 2', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_6_X_N_-_-_-_-', ''),
(NOW(), 'RegioDigOut3', '0_2_7', 'Value on digital output 3', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_7_X_N_-_-_-_-', ''),
(NOW(), 'RegioUDigOut1', '0_2_10', 'Heating (Value on digital output 4)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_10_X_N_-_-_-_-', ''),
(NOW(), 'RegioUDigOut2', '0_2_11', 'Cooling (Value on digital output 5)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_11_X_N_-_-_-_-', ''),
(NOW(), 'RegioDIOpenWindow', '0_2_12', 'Indicates open window', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_12_X_N_-_-_-_-', ''),
(NOW(), 'RegioDIPresences', '0_2_14', 'Indicates presence from digital input', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_14_X_N_-_-_-_-', ''),
(NOW(), 'RegioDIChangeOver', '0_2_15', 'Indicates change-over from digital input', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_15_X_N_-_-_-_-', ''),
(NOW(), 'RegioFanSpeed1', '0_2_16', 'Indicates fan speed 1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_16_X_N_-_-_-_-', ''),
(NOW(), 'RegioFanSpeed2', '0_2_17', 'Indicates fan speed 2', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_17_X_N_-_-_-_-', ''),
(NOW(), 'RegioFanSpeed3', '0_2_18', 'Indicates fan speed 3', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_18_X_N_-_-_-_-', ''),
(NOW(), 'RegioCVHeatPulsProp', '0_2_20', 'Indicates pulse prop. heating', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_20_X_N_-_-_-_-', ''),
(NOW(), 'RegioCVCoolPulsProp', '0_2_21', 'Indicates pulse prop. cooling', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_21_X_N_-_-_-_-', ''),
(NOW(), 'RegioCVHeatInc', '0_2_22', 'Indicates increase heating/cooling DO4', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_22_X_N_-_-_-_-', ''),
(NOW(), 'RegioCVHeatDec', '0_2_23', 'Indicates decrease heating/cooling DO5', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_23_X_N_-_-_-_-', ''),
(NOW(), 'RegioAIChangeOverState', '0_2_26', 'Indicates change-over status from analogue input', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_26_X_N_-_-_-_-', ''),
(NOW(), 'RegioChangeOverState', '0_2_27', 'Indicates change-over status from both digital and analogue input', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_27_X_N_-_-_-_-', ''),
(NOW(), ' RegioPresence', '0_2_30', 'Occupancy indication (with on- and switch-off delay)', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '2_30_X_N_-_-_-_-', ''),
(NOW(), 'RegioShutDown', '0_1_1', 'Puts the unit in Shutdown mode.', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_1_X_N_5_1_X_N', ''),
(NOW(), 'RegioFireAlarmStop', '0_1_2', 'Firealarm Places the unit in Shutdown mode', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_2_X_N_5_2_X_N', ''),
(NOW(), 'RegioDi1NC', '0_1_4', 'State digital input 1 (0=NO 1=NC)', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_4_X_N_5_4_X_N', ''),
(NOW(), 'RegioUDi1NC', '0_1_6', 'State universal input 1 (0=NO 1=NC)', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_6_X_N_5_6_X_N', ''),
(NOW(), 'RegioDO4NC', '0_1_8', 'State digital output 4 (0=NO 1=NC)', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_8_X_N_5_8_X_N', ''),
(NOW(), 'RegioDO5NC', '0_1_9', 'State digital output 5 (0=NO 1=NC)', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_9_X_N_5_9_X_N', ''),
(NOW(), 'RegioDilAct', '0_1_10', 'DI1-activation (presence/window) Economy/Off', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_10_X_N_5_10_X_N', ''),
(NOW(), 'RegioMPAct', '0_1_11', 'Activation of Mould protection.', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_11_X_N_5_11_X_N', ''),
(NOW(), 'RegioTermoModel', '0_1_12', 'EEPROM storage of Thermo model variable (3-point actuator)', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_12_X_N_5_12_X_N', ''),
(NOW(), 'RegioMinFanSpeed', '0_1_13', 'The fan is run at its minimum speed setting for off.', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_13_X_N_5_13_X_N', ''),
(NOW(), 'RegioComFactoryDefaults', '0_1_15', 'Set communication parameters to factory settings', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_15_X_N_5_15_X_N', ''),
(NOW(), 'RegioBlockConfig', '0_1_20', 'Blocks the option to enter the parameter list using the buttons on RCF.', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_20_X_N_5_20_X_N', ''),
(NOW(), 'RegioPreventManualFanSp eed', '0_1_21', 'Prevents the fan speed from being changed manually if the fan is not set to auto', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_21_X_N_5_21_X_N', ''),
(NOW(), 'RegioSoftware', '0_4_0', 'Type of Regio software (0=RCP 1=RC)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_0_I16_N_-_-_-_-', ''),
(NOW(), 'RegioVerMajor', '0_4_1', 'Major version', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_1_I16_N_-_-_-_-', ''),
(NOW(), 'RegioVerMinor', '0_4_2', 'Minor version', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_2_I16_N_-_-_-_-', ''),
(NOW(), 'RegioVerBranch', '0_4_3', 'Branch version', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_3_I16_N_-_-_-_-', ''),
(NOW(), 'RegioRevision', '0_4_4', 'Revision', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_4_I16_N_-_-_-_-', ''),
(NOW(), 'RegioUnitState', '0_4_6', 'Current running mode ( 0=Off1=Economy/Standby 2=Not used3=Not used 4=Comfort)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_6_I16_N_-_-_-_-', ''),
(NOW(), 'RegioControllerState', '0_4_7', 'Current control (0=Off 1=Heating 2=Cooling)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_7_I16_N_-_-_-_-', ''),
(NOW(), 'RegioFanSpeed', '0_4_8', 'Current fan speed (0=Off 1=speed1 2=speed2 3=speed3)', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_8_I16_N_-_-_-_-', ''),
(NOW(), 'RegioRoomTemp', '0_4_10', 'Room temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '4_10_I16_N_-_-_-_-', ''),
(NOW(), 'RegioRoomTempExt', '0_4_11', 'Room temperature from external sensor', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '4_11_I16_N_-_-_-_-', ''),
(NOW(), 'RegioRoomTempInt', '0_4_12', 'Room temperature from internal sensor', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '4_12_I16_N_-_-_-_-', ''),
(NOW(), 'RegioAIChangeOver', '0_4_13', 'Change-over temperature', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '4_13_I16_N_-_-_-_-', ''),
(NOW(), 'RegioAnaIn1', '0_4_14', 'Value on analogue input 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_14_I16_N_-_-_-_-', ''),
(NOW(), 'RegioUAnaIn1', '0_4_15', 'Value on universal analogue input 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_15_I16_N_-_-_-_-', ''),
(NOW(), 'RegioUAnaOut1', '0_4_16', 'Value on universal analogue output 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_16_I16_N_-_-_-_-', ''),
(NOW(), 'RegioUAnaOut2', '0_4_17', 'Value on universal analogue output 2', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_17_I16_N_-_-_-_-', ''),
(NOW(), 'RegioPIDSetP', '0_4_19', 'Controller setpoint', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '4_19_I16_N_-_-_-_-', ''),
(NOW(), 'RegioPIDOutput', '0_4_20', 'Controller output signal (0…100 %)', '', 'Analog values', 'float', '', '-1', 'r', '&#037', '', '', '', '', '', '', '', '', '4_20_I16_N_-_-_-_-', ''),
(NOW(), 'RegioHeatOutput', '0_4_21', 'Heating output signal (0…100 %)', '', 'Analog values', 'float', '', '-1', 'r', '&#037', '', '', '', '', '', '', '', '', '4_21_I16_N_-_-_-_-', ''),
(NOW(), 'RegioCoolOutput', '0_4_22', 'Cooling output signal (0…100 %)', '', 'Analog values', 'float', '', '-1', 'r', '&#037', '', '', '', '', '', '', '', '', '4_22_I16_N_-_-_-_-', ''),
(NOW(), 'RegioAI1Raw', '0_4_23', 'Raw value for analogue input 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_23_I16_N_-_-_-_-', ''),
(NOW(), 'RegioUI1Raw', '0_4_24', 'Raw value for universal input 1', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_24_I16_N_-_-_-_-', ''),
(NOW(), 'RoomTemp_NTC2', '0_4_25', 'Room temperature input value from secondary internal sensor', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '4_25_I16_N_-_-_-_-', ''),
(NOW(), 'RegioSupplyAirTemp', '0_4_46', 'Supply air temperature from sensor connected to AI1', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '4_46_I16_N_-_-_-_-', ''),
(NOW(), 'RegioSupplyAirPIDout', '0_4_47', 'Supply air controller output', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_47_I16_N_-_-_-_-', ''),
(NOW(), 'RegioPID2Setp', '0_4_48', 'Room controller output (scaled) and supply air controller setpoint', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '4_48_I16_N_-_-_-_-', ''),
(NOW(), 'RegioHeatOutputSelect', '0_3_2', 'Manual/Auto heating output', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_2_I16_N_6_2_I16_N', ''),
(NOW(), 'RegioCoolOutputSelect', '0_3_3', 'Manual/Auto cooling output', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_3_I16_N_6_3_I16_N', ''),
(NOW(), 'RegioFanSelect', '0_3_4', 'Select fan mode (0=Off 1=speed1 2=speed2 3=speed3 4=Auto)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_4_I16_N_6_4_I16_N', ''),
(NOW(), ' RegioFanControlMode', '0_3_5', 'Select fan control (0=No control 1=heating 2=cooling 3=heat/cool)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_5_I16_N_6_5_I16_N', ''),
(NOW(), 'RegioFanSpeed1Start', '0_3_6', 'Controller output signal in % for fan speed 1', '', 'Integral values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '3_6_I16_N_6_6_I16_N', ''),
(NOW(), 'RegioFanSpeed2Start', '0_3_7', 'Controller output signal in % for fan speed 2', '', 'Integral values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '3_7_I16_N_6_7_I16_N', ''),
(NOW(), 'RegioFanSpeed3Start', '0_3_8', 'Controller output signal in % for fan speed 3', '', 'Integral values', 'integer', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '3_8_I16_N_6_8_I16_N', ''),
(NOW(), 'RegioFanSpeedHyst', '0_3_9', 'Controller output signal hysteresis start/stop fan speed', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_9_I16_N_6_9_I16_N', ''),
(NOW(), 'RegioFanSpeedMax', '0_3_10', 'Number of fan speeds (1-3)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_10_I16_N_6_10_I16_N', ''),
(NOW(), 'RegioChangeOverSelect', '0_3_12', 'Manual/Auto Change-over (0=Heating 1=Cooling 2=Auto)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_12_I16_N_6_12_I16_N', ''),
(NOW(), 'RegioRemoteState', '0_3_13', 'Used for remote control (0=Off 1=Economy/Standby 4=Comfort 5=No remote)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_13_I16_N_6_13_I16_N', ''),
(NOW(), 'RegioUnitReturnState', '0_3_14', 'Pre-set running mode (0=Off 1=Standby) ', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_14_I16_N_6_14_I16_N', ''),
(NOW(), 'RegioControllerMode', '0_3_17', 'Control mode selection (2=Heat/cool change-over 3=Heating/Cooling 4=Electric heating)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_17_I16_N_6_17_I16_N', ''),
(NOW(), 'RegioCVHeatType', '0_3_18', 'Type of actuator heating (0=0…10 V 1=2…10 V 2=10…2 V 3=10…0 V)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_18_I16_N_6_18_I16_N', ''),
(NOW(), 'RegioCVCoolType', '0_3_19', 'Type of actuator cooling', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_19_I16_N_6_19_I16_N', ''),
(NOW(), 'RegioCVHeatExerciseInterval', '0_3_20', 'Time (in hours) between exercise of heating actuator.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_20_I16_N_6_20_I16_N', ''),
(NOW(), 'RegioCVCoolExerciseInterval', '0_3_21', 'Time (in hours) between exercise of cooling actuator.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_21_I16_N_6_21_I16_N', ''),
(NOW(), 'RegioAi1', '0_3_23', 'Signal connected on AI1 (0=Not used 1=External Room sensor 11=Supply air temperature limitation sensor)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_23_I16_N_6_23_I16_N', ''),
(NOW(), 'RegioUi1', '0_3_29', 'Signal connected on UI1 (0=Not used1=Change-over sensor digital 2=Change-over sensor analogue 3=Off mode)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_29_I16_N_6_29_I16_N', ''),
(NOW(), 'RegioUo1', '0_3_41', 'Signal connected on UO1 0=Not used 1=Thermo valve Heating/Cooling  3=Analogue valve Heating/Cooling 17=EC fan analogue out AO1)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_41_I16_N_6_41_I16_N', ''),
(NOW(), 'RegioUo2', '0_3_42', 'Signal connected on UO2 0=Not used 2=Thermo valve Cooling 3=Not used 4=Analogue valve Cooling', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_42_I16_N_6_42_I16_N', ''),
(NOW(), 'RegioModbusSlaveAddr', '0_3_43', 'Address Modbus slave', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_43_I16_N_6_43_I16_N', ''),
(NOW(), 'RegioModbusParity', '0_3_44', 'Parity and stop bits for Modbus communication (0=8N2 1=8O1 2=8E1 3=8N1)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_44_I16_N_6_44_I16_N', ''),
(NOW(), 'RegioModbusCharTimeout', '0_3_45', 'Modbus timeout for characters in ms.', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_45_I16_N_6_45_I16_N', ''),
(NOW(), 'RegioModbusAnswerDelay', '0_3_46', 'Response lag Modbus', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_46_I16_N_6_46_I16_N', ''),
(NOW(), 'RegioDispBacklightLO', '0_3_47', 'Display backlight low (0...100)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_47_I16_N_6_47_I16_N', ''),
(NOW(), 'RegioDispBacklightHi', '0_3_48', 'Display backlight high (0...100)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_48_I16_N_6_48_I16_N', ''),
(NOW(), 'RegioDispContrast', '0_3_49', 'Contrast (0…15)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_49_I16_N_6_49_I16_N', ''),
(NOW(), 'RegioDisplayViewMode', '0_3_50', 'Viewing options for the display(0=Room temp. and setpoint when adjusting 1=Room temp. and setpoint when adjusting 2=Setpoint 3=Setpoint displace.)', '', 'Integral values', 'integer', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_50_I16_N_6_50_I16_N', ''),
(NOW(), 'RegioPresenceOffTime', '0_3_56', 'Switch-off delay when changing to no presence', '', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '3_56_I16_N_6_56_I16_N', ''),
(NOW(), 'RegioPresenceOnTime', '0_3_57', 'Switch-on delay when changing to presence', '', 'Integral values', 'integer', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '3_57_I16_N_6_57_I16_N', ''),
(NOW(), 'RegioCVHeatPeriodTime', '0_3_58', 'Period time for pulse prop. control valve heating', '', 'Integral values', 'integer', '', '-1', 'rw', 'sec', '', '', '', '', '', '', '', '', '3_58_I16_N_6_58_I16_N', ''),
(NOW(), 'RegioCVCoolPeriodTime', '0_3_59', 'Period time for pulse prop. control valve cooling', '', 'Integral values', 'integer', '', '-1', 'rw', 'sec', '', '', '', '', '', '', '', '', '3_59_I16_N_6_59_I16_N', ''),
(NOW(), 'RegioCVHeatRunTime', '0_3_60', 'Run time closed valve to open heating', '', 'Integral values', 'integer', '', '-1', 'rw', 'sec', '', '', '', '', '', '', '', '', '3_60_I16_N_6_60_I16_N', ''),
(NOW(), 'RegioCVCoolRunTime', '0_3_61', 'Run time closed valve to open cooling', '', 'Integral values', 'integer', '', '-1', 'rw', 'sec', '', '', '', '', '', '', '', '', '3_61_I16_N_6_61_I16_N', ''),
(NOW(), 'RegioStandbySetPDeadBand', '0_3_69', 'Deadband for Economy mode', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_69_I16_N_6_69_I16_N', ''),
(NOW(), 'RegioUnOccSetPHeat', '0_3_70', 'Heating setpoint when in Unoccupied mode', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_70_I16_N_6_70_I16_N', ''),
(NOW(), 'RegioUnOccSetPCool', '0_3_71', 'Cooling setpoint when in Unoccupied mode', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_71_I16_N_6_71_I16_N', ''),
(NOW(), 'RegioSetpointOffsetPos', '0_3_73', 'Max. upward setpoint displacement', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_73_I16_N_6_73_I16_N', ''),
(NOW(), 'RegioSetpointOffsetNeg', '0_3_74', 'Max. downward setpoint displacement', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_74_I16_N_6_74_I16_N', ''),
(NOW(), 'RegioSetPOffset', '0_3_75', 'Setpoint displacement', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_75_I16_N_6_75_I16_N', ''),
(NOW(), 'RegioPIDPGain', '0_3_76', 'Room controller P-band', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_76_I16_N_6_76_I16_N', ''),
(NOW(), 'RegioPIDITime', '0_3_77', 'Room controller I time', '', 'Analog values', 'float', '', '-1', 'rw', 'sec', '', '', '', '', '', '', '', '', '3_77_I16_N_6_77_I16_N', ''),
(NOW(), 'RegioAIChangeOverLimitLow', '0_3_79', 'Controller switches over to control of cooling if change- over temperature is lower', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_79_I16_N_6_79_I16_N', ''),
(NOW(), 'RegioAIChangeOverLimitHigh', '0_3_80', 'Controller switches over to control of heating if change- over temperature is higher', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_80_I16_N_6_80_I16_N', ''),
(NOW(), 'RegioAi1Comp', '0_3_81', 'Compensation for analogue input 1', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_81_I16_N_6_81_I16_N', ''),
(NOW(), ' RegioUi1Comp', '0_3_82', 'Compensation for universal input 1', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_82_I16_N_6_82_I16_N', ''),
(NOW(), 'RegioInternalTempComp', '0_3_83', 'Compensation for internal room sensor', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_83_I16_N_6_83_I16_N', ''),
(NOW(), 'RegioTempFilterFactor', '0_3_84', 'Filter factor for temperature on analogue input (0=No filter 1=Max filter)', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_84_I16_N_6_84_I16_N', ''),
(NOW(), 'RegioThermostatHyst', '0_3_89', 'Room hysteresis', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_89_I16_N_6_89_I16_N', ''),
(NOW(), 'RegioComfortSetPDeadBand', '0_3_90', 'Deadband for Comfort mode (DB)', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_90_I16_N_6_90_I16_N', ''),
(NOW(), 'RegioHeatOutputManual', '0_3_93', 'Manual output heating output (0…100 %)', '', 'Analog values', 'float', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '3_93_I16_N_6_93_I16_N', ''),
(NOW(), 'RegioCoolOutputManual', '0_3_94', 'Manual output cooling output (0…100 %)', '', 'Analog values', 'float', '', '-1', 'rw', '&#037', '', '', '', '', '', '', '', '', '3_94_I16_N_6_94_I16_N', ''),
(NOW(), 'RegioRoomTempRemote', '0_3_95', 'Used for remote control of room temperature. External Room sensor must be selected.', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_95_I16_N_6_95_I16_N', ''),
(NOW(), 'RegioMinECFanSpeed', '0_3_281', 'Starting voltage for EC fan. ', '', 'Analog values', 'float', '', '-1', 'rw', 'V', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_281_I16_N_6_281_I16_N', ''),
(NOW(), 'RegioMaxECFanSpeed', '0_3_282', 'Maximum speed of the EC fan', '', 'Analog values', 'float', '', '-1', 'rw', 'V', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_282_I16_N_6_282_I16_N', ''),
(NOW(), 'RegioRCFSetPoint', '0_3_283', 'Basic setpoint', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_283_I16_N_6_283_I16_N', ''),
(NOW(), 'SupplyAirTLim_HeatHi', '0_3_288', 'Supply air max limitation for cascade control and heating control', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_288_I16_N_6_288_I16_N', ''),
(NOW(), 'SupplyAirTLim_HeatLo', '0_3_289', 'Supply air min limitation for cascade control and heating control', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_289_I16_N_6_289_I16_N', ''),
(NOW(), 'SupplyAirTLim_CoolHi', '0_3_290', 'Supply air max limitation for cascade control and cooling control', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_290_I16_N_6_290_I16_N', ''),
(NOW(), 'SupplyAirTLim_CoolLo', '0_3_291', 'Supply air min limitation for cascade control and cooling control', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_291_I16_N_6_291_I16_N', ''),
(NOW(), 'SupplyAirTLim_CascadeFact', '0_3_292', 'Cascade factor between room controller and supply air controller', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_292_I16_N_6_292_I16_N', ''),
(NOW(), 'SupplyAirTLim_FrostProtect', '0_3_293', 'Frost protection temperature for supply air when supply air temperature limitation is active', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_293_I16_N_6_293_I16_N', '');



CREATE TABLE IF NOT EXISTS `iw_set_regin_rcf230ctd` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='4.0.0';


REPLACE INTO `iw_set_regin_rcf230ctd` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'RegioDigIn1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUDigIn1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDigOut1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDigOut2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDigOut3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUDigOut1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUDigOut2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDIOpenWindow', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDIPresences', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDIChangeOver', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFanSpeed1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFanSpeed2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFanSpeed3', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVHeatPulsProp', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVCoolPulsProp', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVHeatInc', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVHeatDec', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioAIChangeOverState', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioChangeOverState', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), ' RegioPresence', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioShutDown', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFireAlarmStop', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDi1NC', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUDi1NC', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDO4NC', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDO5NC', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDilAct', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioMPAct', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioTermoModel', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioMinFanSpeed', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioComFactoryDefaults', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioBlockConfig', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioPreventManualFanSp eed', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioSoftware', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioVerMajor', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioVerMinor', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioVerBranch', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioRevision', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUnitState', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioControllerState', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFanSpeed', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioRoomTemp', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioRoomTempExt', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioRoomTempInt', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioAIChangeOver', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioAnaIn1', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioUAnaIn1', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioUAnaOut1', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioUAnaOut2', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioPIDSetP', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioPIDOutput', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioHeatOutput', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioCoolOutput', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioAI1Raw', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioUI1Raw', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RoomTemp_NTC2', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioSupplyAirTemp', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioSupplyAirPIDout', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioPID2Setp', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'RegioHeatOutputSelect', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCoolOutputSelect', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFanSelect', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), ' RegioFanControlMode', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFanSpeed1Start', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFanSpeed2Start', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFanSpeed3Start', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFanSpeedHyst', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioFanSpeedMax', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioChangeOverSelect', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioRemoteState', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUnitReturnState', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioControllerMode', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVHeatType', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVCoolType', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVHeatExerciseInterval', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVCoolExerciseInterval', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioAi1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUi1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUo1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUo2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioModbusSlaveAddr', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioModbusParity', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioModbusCharTimeout', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioModbusAnswerDelay', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDispBacklightLO', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDispBacklightHi', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDispContrast', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioDisplayViewMode', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioPresenceOffTime', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioPresenceOnTime', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVHeatPeriodTime', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVCoolPeriodTime', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVHeatRunTime', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCVCoolRunTime', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioStandbySetPDeadBand', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUnOccSetPHeat', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioUnOccSetPCool', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioSetpointOffsetPos', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioSetpointOffsetNeg', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioSetPOffset', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioPIDPGain', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioPIDITime', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioAIChangeOverLimitLow', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioAIChangeOverLimitHigh', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioAi1Comp', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), ' RegioUi1Comp', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioInternalTempComp', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioTempFilterFactor', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioThermostatHyst', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioComfortSetPDeadBand', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioHeatOutputManual', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioCoolOutputManual', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioRoomTempRemote', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioMinECFanSpeed', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioMaxECFanSpeed', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'RegioRCFSetPoint', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SupplyAirTLim_HeatHi', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SupplyAirTLim_HeatLo', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SupplyAirTLim_CoolHi', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SupplyAirTLim_CoolLo', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SupplyAirTLim_CascadeFact', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'SupplyAirTLim_FrostProtect', '1', '0', 'slow', 'change', '', '', '', 0);


