REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'E01', 'AWD3 EnergyMeter', 'awd3_energy', 'AWD3', '0_1', 'AWD3', 'AWD3', 0, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'comm_port', 'AWD3', '3', '', '', ''),
(NOW(), 'comm_baudrate', 'AWD3', '19200', '', '', ''),
(NOW(), 'comm_parity', 'AWD3', '0', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'comm_stop_bits', 'AWD3', '2', '', '', ''),
(NOW(), 'mb_tcp_servers', 'AWD3', '1;xxxxxxxxx;502;1000;2;1000\r\n', '', 'ID;IPadr;IPport;ConnTout;ConnRetries;RequestTout', ''),
(NOW(), 'mb_mode', 'AWD3', '0', '', '0=RTU|1=ASCII|2=TCP', ''),
(NOW(), 'force_word_not_byte', 'AWD3', '0', '', '0|1', ''),
(NOW(), 'handshake', 'AWD3', '0', '', '0|1|2', ''),
(NOW(), 'check_rate', 'AWD3', '1', 'ms', '', ''),
(NOW(), 'comm_data_bits', 'AWD3', '8', '', '', ''),
(NOW(), 'max_outstanding_packets', 'AWD3', '-1', '', '', ''),
(NOW(), 'packet_timeout', 'AWD3', '1', 'sec.', '', ''),
(NOW(), 'idle_event_rate', 'AWD3', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'AWD3', '2000', 'msec.', '', ''),
(NOW(), 'max_error_count', 'AWD3', '2', '', '', ''),
(NOW(), 'mb_request_timeout', 'AWD3', '1000', 'ms', '', ''),
(NOW(), 'mb_request_retries', 'AWD3', '2', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'AWD3', '10', 'min.', '', ''),
(NOW(), 'show_queue_info', 'AWD3', '0', '', '', ''),
(NOW(), 'speed_index_block', 'AWD3', '10', '', '', ''),
(NOW(), 'speed_index_offline', 'AWD3', '10', '', '', ''),
(NOW(), 'speed_index_slow', 'AWD3', '1', '', '', ''),
(NOW(), 'speed_index_norm', 'AWD3', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'AWD3', '2', 'hours', '', ''),
(NOW(), 'max_group_count', 'AWD3', '1', '', '', ''),
(NOW(), 'value_quality_check_limit', 'AWD3', '0', '', '0 = disabled', ''),
(NOW(), 'mux_settle_time', 'AWD3', '1500', 'ms', 'Time for the muxed input to settle. The value shuld be a multiple off 100.', ''),
(NOW(), 'startup_delay', 'AWD3', '15', 'Sec.', '', ''),
(NOW(), 'alarm_handler', 'AWD3', '', '', '', ''),
(NOW(), 'mb_tcp_connect_retries_default', 'AWD3', '2', '', '', ''),
(NOW(), 'mb_tcp_connect_timeout_default', 'AWD3', '1000', 'ms', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'AWD3', 'awd3_energy_param', 'awd3_energy_groups');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_mb.exe', 'AWD3', '', '');

CREATE TABLE IF NOT EXISTS `iw_par_awd3_energy_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_awd3_energy_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'data', 'Energy Meter'),
(NOW(), 'group', 1, 'data', 'data_0_3_25'),
(NOW(), 'group', 2, 'data', 'data_0_3_24'),
(NOW(), 'group', 3, 'data', 'data_0_3_35'),
(NOW(), 'group', 4, 'data', 'data_0_3_36'),
(NOW(), 'group', 5, 'data', 'data_0_3_37'),
(NOW(), 'group', 6, 'data', 'data_0_3_38'),
(NOW(), 'group', 7, 'data', 'data_0_3_39'),
(NOW(), 'group', 8, 'data', 'data_0_3_40'),
(NOW(), 'group', 9, 'data', 'data_0_3_41'),
(NOW(), 'group', 10, 'data', 'data_0_3_42'),
(NOW(), 'group', 11, 'data', 'data_0_3_43'),
(NOW(), 'group', 12, 'data', 'data_0_3_44'),
(NOW(), 'group', 13, 'data', 'data_0_3_45'),
(NOW(), 'group', 14, 'data', 'data_0_3_46'),
(NOW(), 'group', 15, 'data', 'data_0_3_47'),
(NOW(), 'group', 16, 'data', 'data_0_3_48'),
(NOW(), 'group', 17, 'data', 'data_0_3_49'),
(NOW(), 'group', 18, 'data', 'data_0_3_50'),
(NOW(), 'group', 19, 'data', 'data_0_3_51'),
(NOW(), 'group', 20, 'data', 'data_0_3_27'),
(NOW(), 'group', 21, 'data', 'data_0_3_29'),
(NOW(), 'group', 22, 'data', 'data_0_3_0'),
(NOW(), 'group', 23, 'data', 'data_0_3_1'),
(NOW(), 'group', 24, 'data', 'data_0_3_2'),
(NOW(), 'group', 25, 'data', 'data_0_3_3'),
(NOW(), 'group', 26, 'data', 'data_0_3_14'),
(NOW(), 'group', 27, 'data', 'data_0_3_15'),
(NOW(), 'group', 28, 'data', 'data_0_3_17'),
(NOW(), 'group', 29, 'data', 'data_0_3_21'),
(NOW(), 'group', 30, 'data', 'data_0_3_22'),
(NOW(), 'group', 31, 'data', 'data_0_3_23');

CREATE TABLE IF NOT EXISTS `iw_par_awd3_energy_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_awd3_energy_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'data_0_3_25', '0_3_25', 'Current Transformer Ratio', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_25_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_24', '0_3_24', 'Error register', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_24_I16_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"No error"},"1":{"t":"Error Phase 1"},"2":{"t":"Error Phase 2"},"3":{"t":"Error Phase 1 and 2"},"4":{"t":"Error Phase 3"},"5":{"t":"Error Phase 1 and 3"},"6":{"t":"Error Phase 2 and 3"},"7":{"t":"Error Phase 1 2 and 3"}}}'),
(NOW(), 'data_0_3_35', '0_3_35', 'Effective Voltage of Phase 1', '', 'Analog values', 'float', '', '-1', 'r', 'V', '', '', '', '', '', '', '', '', '3_35_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_36', '0_3_36', 'Effective Current of Phase 1', '', 'Analog values', 'float', '', '-1', 'r', 'A', '', '', '', '', '', '', '', '', '3_36_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_37', '0_3_37', 'Effective active Power of Phase 1', '', 'Analog values', 'float', '', '-1', 'r', 'kW', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_37_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_38', '0_3_38', 'Effective reactive Power of Phase 1', '', 'Analog values', 'float', '', '-1', 'r', 'kvar', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_38_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_39', '0_3_39', 'cos phi phase 1', '', 'Analog values', 'float', '', '-1', 'r', '', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_39_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_40', '0_3_40', 'Effective Voltage of Phase 2', '', 'Analog values', 'float', '', '-1', 'r', 'V', '', '', '', '', '', '', '', '', '3_40_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_41', '0_3_41', 'Effective Current of Phase 2', '', 'Analog values', 'float', '', '-1', 'r', 'A', '', '', '', '', '', '', '', '', '3_41_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_42', '0_3_42', 'Effective active Power of Phase 2', '', 'Analog values', 'float', '', '-1', 'r', 'kW', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_42_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_43', '0_3_43', 'Effective reactive Power of Phase 2', '', 'Analog values', 'float', '', '-1', 'r', 'kvar', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_43_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_44', '0_3_44', 'cos phi phase 2', '', 'Analog values', 'float', '', '-1', 'r', '', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_44_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_45', '0_3_45', 'Effective Voltage of Phase 3', '', 'Analog values', 'float', '', '-1', 'r', 'V', '', '', '', '', '', '', '', '', '3_45_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_46', '0_3_46', 'Effective Current of Phase 3', '', 'Analog values', 'float', '', '-1', 'r', 'A', '', '', '', '', '', '', '', '', '3_46_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_47', '0_3_47', 'Effective active Power of Phase 3', '', 'Analog values', 'float', '', '-1', 'r', 'kW', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_47_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_48', '0_3_48', 'Effective reactive Power of Phase 3', '', 'Analog values', 'float', '', '-1', 'r', 'kvar', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_48_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_49', '0_3_49', 'cos phi phase 3', '', 'Analog values', 'float', '', '-1', 'r', '', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_49_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_50', '0_3_50', 'Effective active Power of all phases', '', 'Analog values', 'float', '', '-1', 'r', 'kW', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_50_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_51', '0_3_51', 'Effective reactive power of all phases', '', 'Analog values', 'float', '', '-1', 'r', 'kvar', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_51_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_27', '0_3_27', 'Counter Energy Total Tariff 1 High', '', 'Analog values', 'float', '', '-1', 'r', 'kWh', '', '', '', '1', '0', '1000', '0', '100', '3_27_I32_W_-_-_-_-', ''),
(NOW(), 'data_0_3_29', '0_3_29', 'Counter Energy Partial Tariff 1', '', 'Analog values', 'float', '', '-1', 'r', 'kWh', '', '', '', '1', '0', '1000', '0', '100', '3_29_I32_W_-_-_-_-', ''),
(NOW(), 'data_0_3_0', '0_3_0', 'Firmware-Version', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_0_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_1', '0_3_1', 'Number of supported registers', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_1_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_2', '0_3_2', 'Number of supported flags', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_2_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_3', '0_3_3', 'Baudrate', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_3_I32_W_-_-_-_-', ''),
(NOW(), 'data_0_3_14', '0_3_14', 'HW vers. Modif.', '', 'Integral values', 'integer', '', '-1', 'r', '', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_14_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_15', '0_3_15', 'Serial number Low', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_15_I32_W_-_-_-_-', ''),
(NOW(), 'data_0_3_17', '0_3_17', 'Serial number High', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_17_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_21', '0_3_21', 'Status', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_21_I16_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"No problem"},"1":{"t":"Problem with last com req"}}}'),
(NOW(), 'data_0_3_22', '0_3_22', 'Response Timeout', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_22_I16_N_-_-_-_-', ''),
(NOW(), 'data_0_3_23', '0_3_23', 'Modbus Address', '', 'Integral values', 'integer', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_23_I16_N_-_-_-_-', '');

CREATE TABLE IF NOT EXISTS `iw_set_awd3_energy` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='4.0.0';

REPLACE INTO `iw_set_awd3_energy` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'data_0_3_25', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_0_3_24', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_0_3_35', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_36', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_37', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_38', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_39', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_40', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_41', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_42', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_43', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_44', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_45', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_46', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_47', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_48', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_49', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_50', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_51', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_27', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_29', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_0', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_0_3_1', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_0_3_2', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_0_3_3', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_14', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_0_3_15', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'data_0_3_17', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_0_3_21', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_0_3_22', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'data_0_3_23', '1', '0', 'slow', 'change', '', '', '', 0);