-- Dette er for varianten som IKKE bruker Wurt Canbus to Modbus konverter. 

REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `view_order`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'U01', 'Plugin 01', 'liebherr_modbus', 'LIEBHERR', '0_1', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U02', 'Plugin 02', 'liebherr_modbus', 'LIEBHERR', '0_2', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U03', 'Plugin 03', 'liebherr_modbus', 'LIEBHERR', '0_3', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U04', 'Plugin 04', 'liebherr_modbus', 'LIEBHERR', '0_4', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U05', 'Plugin 05', 'liebherr_modbus', 'LIEBHERR', '0_5', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U06', 'Plugin 06', 'liebherr_modbus', 'LIEBHERR', '0_6', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U07', 'Plugin 07', 'liebherr_modbus', 'LIEBHERR', '0_7', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U08', 'Plugin 08', 'liebherr_modbus', 'LIEBHERR', '0_8', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U09', 'Plugin 09', 'liebherr_modbus', 'LIEBHERR', '0_9', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U10', 'Plugin 10', 'liebherr_modbus', 'LIEBHERR', '0_10', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U11', 'Plugin 11', 'liebherr_modbus', 'LIEBHERR', '0_11', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U12', 'Plugin 12', 'liebherr_modbus', 'LIEBHERR', '0_12', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U13', 'Plugin 13', 'liebherr_modbus', 'LIEBHERR', '0_13', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U14', 'Plugin 14', 'liebherr_modbus', 'LIEBHERR', '0_14', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U15', 'Plugin 15', 'liebherr_modbus', 'LIEBHERR', '0_15', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U16', 'Plugin 16', 'liebherr_modbus', 'LIEBHERR', '0_16', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U17', 'Plugin 17', 'liebherr_modbus', 'LIEBHERR', '0_17', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U18', 'Plugin 18', 'liebherr_modbus', 'LIEBHERR', '0_18', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U19', 'Plugin 19', 'liebherr_modbus', 'LIEBHERR', '0_19', 'LIEBHERR', 'LIEBHERR', 0, ''),
(NOW(), '1', '0', 'U20', 'Plugin 20', 'liebherr_modbus', 'LIEBHERR', '0_20', 'LIEBHERR', 'LIEBHERR', 0, '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES
(NOW(), 'mb_mode', 'LIEBHERR', '0', '', '0=RTU|1=ASCII|2=TCP', ''),
(NOW(), 'comm_port', 'LIEBHERR', '5', '', '', ''),
(NOW(), 'mb_tcp_servers', 'LIEBHERR', '1;192.168.10.100;502;1000;2;1000\r\n', '', 'ID;IPadr;IPport;ConnTout;ConnRetries;RequestTout', ''),
(NOW(), 'comm_parity', 'LIEBHERR', '2', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'comm_data_bits', 'LIEBHERR', '8', '', '', ''),
(NOW(), 'comm_stop_bits', 'LIEBHERR', '1', '', '', ''),
(NOW(), 'comm_baudrate', 'LIEBHERR', '19200', '', '', ''),
(NOW(), 'mb_request_retries', 'LIEBHERR', '2', '', '', ''),
(NOW(), 'force_word_not_byte', 'LIEBHERR', '0', '', '0|1', ''),
(NOW(), 'handshake', 'LIEBHERR', '0', '', '0|1|2', ''),
(NOW(), 'check_rate', 'LIEBHERR', '1', 'ms', '', ''),
(NOW(), 'max_outstanding_packets', 'LIEBHERR', '-1', '', '', ''),
(NOW(), 'packet_timeout', 'LIEBHERR', '1', 'sec.', '', ''),
(NOW(), 'idle_event_rate', 'LIEBHERR', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'LIEBHERR', '2000', 'msec.', '', ''),
(NOW(), 'max_error_count', 'LIEBHERR', '2', '', '', ''),
(NOW(), 'mb_request_timeout', 'LIEBHERR', '1000', 'ms', '', ''),
(NOW(), 'com_error_alarm_delay', 'LIEBHERR', '10', 'min.', '', ''),
(NOW(), 'show_queue_info', 'LIEBHERR', '0', '', '', ''),
(NOW(), 'speed_index_block', 'LIEBHERR', '10', '', '', ''),
(NOW(), 'speed_index_offline', 'LIEBHERR', '10', '', '', ''),
(NOW(), 'speed_index_slow', 'LIEBHERR', '1', '', '', ''),
(NOW(), 'speed_index_norm', 'LIEBHERR', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'LIEBHERR', '2', 'hours', '', ''),
(NOW(), 'max_group_count', 'LIEBHERR', '1', '', '', ''),
(NOW(), 'value_quality_check_limit', 'LIEBHERR', '0', '', '0 = disabled', ''),
(NOW(), 'mux_settle_time', 'LIEBHERR', '1500', 'ms', 'Time for the muxed input to settle. The value shuld be a multiple off 100.', ''),
(NOW(), 'startup_delay', 'LIEBHERR', '15', 'Sec.', '', ''),
(NOW(), 'alarm_handler', 'LIEBHERR', '', '', '', ''),
(NOW(), 'mb_tcp_connect_retries_default', 'LIEBHERR', '2', '', '', ''),
(NOW(), 'mb_tcp_connect_timeout_default', 'LIEBHERR', '1000', 'ms', '', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES
(NOW(), '0', 'iw_mb.exe', 'LIEBHERR', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'LIEBHERR', 'liebherr_modbus_param', 'liebherr_modbus_groups');

CREATE TABLE IF NOT EXISTS `iw_par_liebherr_modbus_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='2.0.0';

REPLACE INTO `iw_par_liebherr_modbus_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'most', 'Most Used'),
(NOW(), 'group_alias', 2, 'info', 'Info'),
(NOW(), 'group_alias', 3, 'di', 'Digital'),
(NOW(), 'group', 0, 'most', 'most_0_1_200'),
(NOW(), 'group', 1, 'most', 'most_0_3_100'),
(NOW(), 'group', 2, 'most', 'most_0_3_101'),
(NOW(), 'group', 3, 'most', 'most_0_3_110'),
(NOW(), 'group', 4, 'most', 'most_0_3_111'),
(NOW(), 'group', 5, 'most', 'most_0_3_112'),
(NOW(), 'group', 6, 'most', 'most_0_3_113'),
(NOW(), 'group', 7, 'most', 'most_0_3_2050'),
(NOW(), 'group', 8, 'most', 'most_0_1_202'),
(NOW(), 'group', 9, 'most', 'most_0_1_203'),
(NOW(), 'group', 10, 'most', 'most_0_1_236'),
(NOW(), 'group', 11, 'most', 'most_0_1_237'),
(NOW(), 'group', 12, 'most', 'most_0_3_2500'),
(NOW(), 'group', 13, 'most', 'most_0_3_2501'),
(NOW(), 'group', 14, 'most', 'most_0_3_2502'),
(NOW(), 'group', 15, 'most', 'most_0_3_2503'),
(NOW(), 'group', 0, 'info', 'info_0_3_114'),
(NOW(), 'group', 1, 'info', 'info_0_3_0'),
(NOW(), 'group', 2, 'info', 'info_0_3_1'),
(NOW(), 'group', 3, 'info', 'info_0_3_2'),
(NOW(), 'group', 4, 'info', 'info_0_3_3'),
(NOW(), 'group', 5, 'info', 'info_0_3_2002'),
(NOW(), 'group', 6, 'info', 'info_0_3_2001.0#7'),
(NOW(), 'group', 7, 'info', 'info_0_3_2001.8#15'),
(NOW(), 'group', 8, 'info', 'info_0_3_2000.0#7'),
(NOW(), 'group', 9, 'info', 'info_0_3_2000.8#15'),
(NOW(), 'group', 0, 'di', 'di_0_1_201'),
(NOW(), 'group', 1, 'di', 'di_0_1_204'),
(NOW(), 'group', 2, 'di', 'di_0_1_205'),
(NOW(), 'group', 3, 'di', 'di_0_1_206'),
(NOW(), 'group', 4, 'di', 'di_0_1_232'),
(NOW(), 'group', 5, 'di', 'di_0_1_233'),
(NOW(), 'group', 6, 'di', 'di_0_1_234'),
(NOW(), 'group', 7, 'di', 'di_0_1_235'),
(NOW(), 'group', 8, 'di', 'di_0_1_238'),
(NOW(), 'group', 9, 'di', 'di_0_1_240'),
(NOW(), 'group', 10, 'di', 'di_0_1_243'),
(NOW(), 'group', 11, 'di', 'di_0_1_244'),
(NOW(), 'group', 12, 'di', 'di_0_1_245'),
(NOW(), 'group', 13, 'di', 'di_0_1_246'),
(NOW(), 'group', 14, 'di', 'di_0_1_247'),
(NOW(), 'group', 15, 'di', 'di_0_1_250'),
(NOW(), 'group', 16, 'di', 'di_0_1_1000'),
(NOW(), 'group', 17, 'di', 'di_0_1_1001'),
(NOW(), 'group', 18, 'di', 'di_0_1_1002'),
(NOW(), 'group', 19, 'di', 'di_0_3_2600'),
(NOW(), 'group', 20, 'di', 'di_0_3_2601');

CREATE TABLE IF NOT EXISTS `iw_par_liebherr_modbus_param` (
  `row_date` datetime NOT NULL DEFAULT '2002-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';

REPLACE INTO `iw_par_liebherr_modbus_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'info_0_3_0', '0_3_0', 'Family Code', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_0_U16_N_-_-_-_-', ''),
(NOW(), 'info_0_3_1', '0_3_1', 'Device Code Msw', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_1_U16_N_-_-_-_-', ''),
(NOW(), 'info_0_3_2', '0_3_2', 'Device Code Lsw', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_2_U16_N_-_-_-_-', ''),
(NOW(), 'info_0_3_3', '0_3_3', 'Firmwareversion', '', 'Analog values', 'float', '', '-1', 'r', '', '', '', '', '', '', '', '', '', '3_3_U16_N_-_-_-_-', ''),
(NOW(), 'most_0_3_100', '0_3_100', 'Setpoint', '', 'Analog values', 'float', '', '-1', 'rw', '&deg;C', '%.0f', '', '', '1', '0', '1000', '0', '100', '3_100_I16_N_6_100_I16_N', ''),
(NOW(), 'most_0_3_101', '0_3_101', 'Actual Control Value', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_101_I16_N_-_-_-_-', ''),
(NOW(), 'most_0_3_110', '0_3_110', 'Actual Value Probe 1', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_110_I16_N_-_-_-_-', ''),
(NOW(), 'most_0_3_111', '0_3_111', 'Actual Value Probe 2', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_111_I16_N_-_-_-_-', ''),
(NOW(), 'most_0_3_112', '0_3_112', 'Actual Value Probe 3', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_112_I16_N_-_-_-_-', ''),
(NOW(), 'most_0_3_113', '0_3_113', 'Actual Value Probe 4', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_113_I16_N_-_-_-_-', ''),
(NOW(), 'info_0_3_114', '0_3_114', 'Actual Value Mainboard', '', 'Analog values', 'float', '', '-1', 'r', '&deg;C', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_114_I16_N_-_-_-_-', ''),
(NOW(), 'most_0_1_200', '0_1_200', 'Device Operation', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_200_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"Running"}}}'),
(NOW(), 'di_0_1_201', '0_1_201', 'General Alarm ', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_201_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"Active"}}}'),
(NOW(), 'most_0_1_202', '0_1_202', 'Cooling', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_202_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"Active"}}}'),
(NOW(), 'most_0_1_203', '0_1_203', 'Defrost', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_203_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"Active"}}}'),
(NOW(), 'di_0_1_204', '0_1_204', 'Hotgas Valve', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_204_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"Active"}}}'),
(NOW(), 'di_0_1_205', '0_1_205', 'Lighting', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_205_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"Active"}}}'),
(NOW(), 'di_0_1_206', '0_1_206', 'Fan Engine 1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_206_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"Active"}}}'),
(NOW(), 'di_0_1_232', '0_1_232', 'Error Probe 1', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_232_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_233', '0_1_233', 'Error Probe 2', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_233_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_234', '0_1_234', 'Error Probe 3', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_234_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_235', '0_1_235', 'Error Probe 4', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_235_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'most_0_1_236', '0_1_236', 'Low Goods Temperature Alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_236_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'most_0_1_237', '0_1_237', 'High Goods Temperature Alarm', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_237_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_238', '0_1_238', 'Malfunction Hotgas Valve', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_238_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_240', '0_1_240', 'Memory Error', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_240_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_243', '0_1_243', 'Rtc Error', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_243_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_244', '0_1_244', 'Display Error', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_244_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_245', '0_1_245', 'High Temperature Engine Bay', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_245_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_246', '0_1_246', 'High Goods Temperature After Power-On', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_246_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_247', '0_1_247', 'Error Probe Mainboard', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_247_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_250', '0_1_250', 'Wrong Display Type', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_250_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Normal"},"1":{"t":"Alarm Active"}}}'),
(NOW(), 'di_0_1_1000', '0_1_1000', 'Device Operation', '', 'Digital IO', 'boolean', '', '-1', 'r', '', '', '0', '1', '', '', '', '', '', '1_1000_X_N_-_-_-_-', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"Active"}}}'),
(NOW(), 'di_0_1_1001', '0_1_1001', 'Lighting', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_1001_X_N_5_1001_X_N', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"Active"}}}'),
(NOW(), 'di_0_1_1002', '0_1_1002', 'Start Manual Defrost', '', 'Digital IO', 'boolean', '', '-1', 'rw', '', '', '0', '1', '', '', '', '', '', '1_1002_X_N_5_1002_X_N', '{"rev":"1","type":"num","v":{"0":{"t":"Off"},"1":{"t":"Active"}}}'),
(NOW(), 'info_0_3_2002', '0_3_2002', 'Year', '', 'Analog values', 'float', '', '-1', 'rw', 'yyyy', '%.0f', '', '', '', '', '', '', '', '3_2002_U16_N_6_2002_U16_N', ''),
(NOW(), 'most_0_3_2050', '0_3_2050', 'Actual Compressor Speed', '', 'Analog values', 'float', '', '-1', 'r', '&#037', '', '', '', '', '', '', '', '', '3_2050_U16_N_6_2050_U16_N', ''),
(NOW(), 'most_0_3_2500', '0_3_2500', 'High Temperature Difference', '', 'Analog values', 'float', '', '-1', 'rw', 'K', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_2500_U16_N_6_2500_U16_N', ''),
(NOW(), 'most_0_3_2501', '0_3_2501', 'Low Temperature Difference', '', 'Analog values', 'float', '', '-1', 'rw', 'K', '%.1f', '', '', '1', '0', '1000', '0', '100', '3_2501_U16_N_6_2501_U16_N', ''),
(NOW(), 'most_0_3_2502', '0_3_2502', 'Alarm Delay Temperature Standard', '', 'Analog values', 'float', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '3_2502_U16_N_6_2502_U16_N', ''),
(NOW(), 'most_0_3_2503', '0_3_2503', 'Alarm Delay Temperature After Defrost / Power On', '', 'Analog values', 'float', '', '-1', 'rw', 'min', '', '', '', '', '', '', '', '', '3_2503_U16_N_6_2503_U16_N', ''),
(NOW(), 'di_0_3_2600', '0_3_2600', 'Alarm Buzzer', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_2600_U16_N_6_2600_U16_N', ''),
(NOW(), 'di_0_3_2601', '0_3_2601', 'Acoustic Feedback', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_2601_U16_N_6_2601_U16_N', ''),
(NOW(), 'info_0_3_2000', '0_3_2000', 'Time', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_2000_U16_N_6_2000_U16_N', ''),
(NOW(), 'info_0_3_2001', '0_3_2001', 'Month/Day', '', 'Analog values', 'float', '', '-1', 'rw', '', '', '', '', '', '', '', '', '', '3_2001_U16_N_6_2001_U16_N', ''),
(NOW(), 'info_0_3_2001.0#7', '0_3_2001.0#7', 'Day', '', 'Analog values', 'float', '', '-1', 'vrw', 'day', '%.0f', '', '', '', '', '', '', '', '3_2001_U16_N_', ''),
(NOW(), 'info_0_3_2001.8#15', '0_3_2001.8#15', 'Month', '', 'Analog values', 'float', '', '-1', 'vrw', 'month', '%.0f', '', '', '', '', '', '', '', '3_2001_U16_N_', ''),
(NOW(), 'info_0_3_2000.0#7', '0_3_2000.0#7', 'Minutes', '', 'Analog values', 'float', '', '-1', 'vrw', 'hour', '%.0f', '', '', '', '', '', '', '', '3_2000_U16_N_', ''),
(NOW(), 'info_0_3_2000.8#15', '0_3_2000.8#15', 'Hour', '', 'Analog values', 'float', '', '-1', 'vrw', 'min', '%.0f', '', '', '', '', '', '', '', '3_2000_U16_N_', '');

CREATE TABLE IF NOT EXISTS `iw_set_liebherr_modbus` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_set_liebherr_modbus` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'info_0_3_0', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'info_0_3_1', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'info_0_3_2', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'info_0_3_3', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'most_0_3_100', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'most_0_3_101', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'most_0_3_110', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'most_0_3_111', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'most_0_3_112', '1', '1', 'norm', 'min', '1', '', '', 0),
(NOW(), 'most_0_3_113', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'info_0_3_114', '1', '0', 'norm', 'min', '1', '', '', 0),
(NOW(), 'most_0_1_200', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di_0_1_201', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'most_0_1_202', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'most_0_1_203', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di_0_1_204', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di_0_1_205', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di_0_1_206', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di_0_1_232', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'di_0_1_233', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'di_0_1_234', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'di_0_1_235', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'most_0_1_236', '1', '0', 'norm', 'min', '', 'A', '', 0),
(NOW(), 'most_0_1_237', '1', '0', 'norm', 'min', '', 'A', '', 0),
(NOW(), 'di_0_1_238', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'di_0_1_240', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'di_0_1_243', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'di_0_1_244', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'di_0_1_245', '1', '0', 'slow', 'change', '', 'A', '', 0),
(NOW(), 'di_0_1_246', '0', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di_0_1_247', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'di_0_1_250', '1', '0', 'slow', 'change', '', 'B', '', 0),
(NOW(), 'di_0_1_1000', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di_0_1_1001', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di_0_1_1002', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'info_0_3_2002', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'most_0_3_2050', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'most_0_3_2500', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'most_0_3_2501', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'most_0_3_2502', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'most_0_3_2503', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di_0_3_2600', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'di_0_3_2601', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'info_0_3_2000', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'info_0_3_2001', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'info_0_3_2001.0#7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'info_0_3_2001.8#15', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'info_0_3_2000.0#7', '1', '0', 'slow', 'change', '', '', '', 0),
(NOW(), 'info_0_3_2000.8#15', '1', '0', 'slow', 'change', '', '', '', 0);
