-- Husk å sette rett group,param og set tabell
-- Husk å sette poisjonsnavn på param listen
-- Husk å endre unit_id og element_id i virtuell tabellen
-- Husk å sette rett gruppe i groups


REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `driver_adr_extra`) VALUES
(NOW(), '1', '0', 'VIRT01', 'SM850 Alarmer', 'SM850_virt', 'SM850', '1_1', 'SM850', 'SM850', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES
(NOW(), 'SM850', 'SM850_virt_param', 'SM850_virt_groups');

CREATE TABLE IF NOT EXISTS `iw_par_SM850_virt_groups` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL DEFAULT '',
  `view_order` mediumint(6) NOT NULL DEFAULT '0',
  `ref` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(200) NOT NULL DEFAULT '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';



CREATE TABLE IF NOT EXISTS `iw_par_SM850_virt_param` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `driver_id` varchar(100) NOT NULL DEFAULT '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL DEFAULT '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(20) NOT NULL DEFAULT '',
  `format` varchar(20) NOT NULL DEFAULT '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL DEFAULT '',
  `raw_min` varchar(15) NOT NULL DEFAULT '',
  `raw_max` varchar(15) NOT NULL DEFAULT '',
  `eng_min` varchar(15) NOT NULL DEFAULT '',
  `eng_max` varchar(15) NOT NULL DEFAULT '',
  `driver_id_extra` varchar(255) NOT NULL DEFAULT '',
  `format_extra` text NOT NULL,
  UNIQUE KEY `element_id` (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.2.3';



CREATE TABLE IF NOT EXISTS `iw_set_SM850_virt` (
  `row_date` datetime NOT NULL DEFAULT '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL DEFAULT '',
  `active` enum('0','1') NOT NULL DEFAULT '0',
  `onl_ind` enum('0','1') NOT NULL DEFAULT '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL DEFAULT 'norm',
  `save_data` varchar(20) NOT NULL DEFAULT 'change',
  `save_freq` varchar(20) NOT NULL DEFAULT '',
  `plant_pri` char(1) NOT NULL DEFAULT '',
  `sys_pri` char(1) NOT NULL DEFAULT '',
  `alarm_type` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`element_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='3.0.0';

REPLACE INTO `iw_par_SM850_virt_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'group', 100, 'virt', 'hlimit_10'),
(NOW(), 'group', 110, 'virt', 'hlimit_11'),
(NOW(), 'group', 120, 'virt', 'hlimit_12'),
(NOW(), 'group', 130, 'virt', 'hlimit_13'),
(NOW(), 'group', 140, 'virt', 'hlimit_14'),
(NOW(), 'group', 150, 'virt', 'hlimit_15'),
(NOW(), 'group', 160, 'virt', 'hlimit_16'),
(NOW(), 'group', 170, 'virt', 'hlimit_17'),
(NOW(), 'group', 180, 'virt', 'hlimit_18'),
(NOW(), 'group', 190, 'virt', 'hlimit_19'),
(NOW(), 'group', 200, 'virt', 'hlimit_20'),
(NOW(), 'group', 210, 'virt', 'hlimit_21'),
(NOW(), 'group', 220, 'virt', 'hlimit_22'),
(NOW(), 'group', 230, 'virt', 'hlimit_23'),
(NOW(), 'group', 240, 'virt', 'hlimit_24'),
(NOW(), 'group', 250, 'virt', 'hlimit_25'),
(NOW(), 'group', 260, 'virt', 'hlimit_26'),
(NOW(), 'group', 270, 'virt', 'hlimit_27'),
(NOW(), 'group', 280, 'virt', 'hlimit_28'),
(NOW(), 'group', 290, 'virt', 'hlimit_29'),
(NOW(), 'group', 300, 'virt', 'hlimit_30'),
(NOW(), 'group', 310, 'virt', 'hlimit_31'),
(NOW(), 'group', 320, 'virt', 'hlimit_32'),
(NOW(), 'group', 330, 'virt', 'hlimit_33'),
(NOW(), 'group', 340, 'virt', 'hlimit_34'),
(NOW(), 'group', 350, 'virt', 'hlimit_35'),
(NOW(), 'group', 360, 'virt', 'hlimit_36'),
(NOW(), 'group', 370, 'virt', 'hlimit_37'),
(NOW(), 'group', 380, 'virt', 'hlimit_38'),
(NOW(), 'group', 390, 'virt', 'hlimit_39'),
(NOW(), 'group', 400, 'virt', 'hlimit_40'),
(NOW(), 'group', 410, 'virt', 'hlimit_41'),
(NOW(), 'group', 420, 'virt', 'hlimit_42'),
(NOW(), 'group', 430, 'virt', 'hlimit_43'),
(NOW(), 'group', 440, 'virt', 'hlimit_44'),
(NOW(), 'group', 102, 'virt', 'delay_10'),
(NOW(), 'group', 112, 'virt', 'delay_11'),
(NOW(), 'group', 122, 'virt', 'delay_12'),
(NOW(), 'group', 132, 'virt', 'delay_13'),
(NOW(), 'group', 142, 'virt', 'delay_14'),
(NOW(), 'group', 152, 'virt', 'delay_15'),
(NOW(), 'group', 162, 'virt', 'delay_16'),
(NOW(), 'group', 172, 'virt', 'delay_17'),
(NOW(), 'group', 182, 'virt', 'delay_18'),
(NOW(), 'group', 192, 'virt', 'delay_19'),
(NOW(), 'group', 202, 'virt', 'delay_20'),
(NOW(), 'group', 212, 'virt', 'delay_21'),
(NOW(), 'group', 222, 'virt', 'delay_22'),
(NOW(), 'group', 232, 'virt', 'delay_23'),
(NOW(), 'group', 242, 'virt', 'delay_24'),
(NOW(), 'group', 252, 'virt', 'delay_25'),
(NOW(), 'group', 262, 'virt', 'delay_26'),
(NOW(), 'group', 272, 'virt', 'delay_27'),
(NOW(), 'group', 282, 'virt', 'delay_28'),
(NOW(), 'group', 292, 'virt', 'delay_29'),
(NOW(), 'group', 302, 'virt', 'delay_30'),
(NOW(), 'group', 312, 'virt', 'delay_31'),
(NOW(), 'group', 322, 'virt', 'delay_32'),
(NOW(), 'group', 332, 'virt', 'delay_33'),
(NOW(), 'group', 342, 'virt', 'delay_34'),
(NOW(), 'group', 352, 'virt', 'delay_35'),
(NOW(), 'group', 362, 'virt', 'delay_36'),
(NOW(), 'group', 372, 'virt', 'delay_37'),
(NOW(), 'group', 382, 'virt', 'delay_38'),
(NOW(), 'group', 392, 'virt', 'delay_39'),
(NOW(), 'group', 402, 'virt', 'delay_40'),
(NOW(), 'group', 412, 'virt', 'delay_41'),
(NOW(), 'group', 422, 'virt', 'delay_42'),
(NOW(), 'group', 432, 'virt', 'delay_43'),
(NOW(), 'group', 442, 'virt', 'delay_44'),
(NOW(), 'group', 103, 'virt', 'halm_10'),
(NOW(), 'group', 113, 'virt', 'halm_11'),
(NOW(), 'group', 123, 'virt', 'halm_12'),
(NOW(), 'group', 133, 'virt', 'halm_13'),
(NOW(), 'group', 143, 'virt', 'halm_14'),
(NOW(), 'group', 153, 'virt', 'halm_15'),
(NOW(), 'group', 163, 'virt', 'halm_16'),
(NOW(), 'group', 173, 'virt', 'halm_17'),
(NOW(), 'group', 183, 'virt', 'halm_18'),
(NOW(), 'group', 193, 'virt', 'halm_19'),
(NOW(), 'group', 203, 'virt', 'halm_20'),
(NOW(), 'group', 213, 'virt', 'halm_21'),
(NOW(), 'group', 223, 'virt', 'halm_22'),
(NOW(), 'group', 233, 'virt', 'halm_23'),
(NOW(), 'group', 243, 'virt', 'halm_24'),
(NOW(), 'group', 253, 'virt', 'halm_25'),
(NOW(), 'group', 263, 'virt', 'halm_26'),
(NOW(), 'group', 273, 'virt', 'halm_27'),
(NOW(), 'group', 283, 'virt', 'halm_28'),
(NOW(), 'group', 293, 'virt', 'halm_29'),
(NOW(), 'group', 303, 'virt', 'halm_30'),
(NOW(), 'group', 313, 'virt', 'halm_31'),
(NOW(), 'group', 323, 'virt', 'halm_32'),
(NOW(), 'group', 333, 'virt', 'halm_33'),
(NOW(), 'group', 343, 'virt', 'halm_34'),
(NOW(), 'group', 353, 'virt', 'halm_35'),
(NOW(), 'group', 363, 'virt', 'halm_36'),
(NOW(), 'group', 373, 'virt', 'halm_37'),
(NOW(), 'group', 383, 'virt', 'halm_38'),
(NOW(), 'group', 393, 'virt', 'halm_39'),
(NOW(), 'group', 403, 'virt', 'halm_40'),
(NOW(), 'group', 413, 'virt', 'halm_41'),
(NOW(), 'group', 423, 'virt', 'halm_42'),
(NOW(), 'group', 433, 'virt', 'halm_43'),
(NOW(), 'group', 443, 'virt', 'halm_44');


REPLACE INTO `iw_par_SM850_virt_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'hlimit_10', 'HLIMIT_AI_10', 'Grense høy temp adr 10 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_11', 'HLIMIT_AI_11', 'Grense høy temp adr 11 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_12', 'HLIMIT_AI_12', 'Grense høy temp adr 12 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_13', 'HLIMIT_AI_13', 'Grense høy temp adr 13 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_14', 'HLIMIT_AI_14', 'Grense høy temp adr 14 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_15', 'HLIMIT_AI_15', 'Grense høy temp adr 15 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_16', 'HLIMIT_AI_16', 'Grense høy temp adr 16 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_17', 'HLIMIT_AI_17', 'Grense høy temp adr 17 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_18', 'HLIMIT_AI_18', 'Grense høy temp adr 18 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_19', 'HLIMIT_AI_19', 'Grense høy temp adr 19 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_20', 'HLIMIT_AI_20', 'Grense høy temp adr 1 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_21', 'HLIMIT_AI_21', 'Grense høy temp adr 21 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_22', 'HLIMIT_AI_22', 'Grense høy temp adr 22 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_23', 'HLIMIT_AI_23', 'Grense høy temp adr 23 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_24', 'HLIMIT_AI_24', 'Grense høy temp adr 24 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_25', 'HLIMIT_AI_25', 'Grense høy temp adr 26 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_26', 'HLIMIT_AI_26', 'Grense høy temp adr 27 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_27', 'HLIMIT_AI_27', 'Grense høy temp adr 28 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_28', 'HLIMIT_AI_28', 'Grense høy temp adr 29 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_29', 'HLIMIT_AI_29', 'Grense høy temp adr 2 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_30', 'HLIMIT_AI_30', 'Grense høy temp adr 30 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_31', 'HLIMIT_AI_31', 'Grense høy temp adr 31 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_32', 'HLIMIT_AI_32', 'Grense høy temp adr 32 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_33', 'HLIMIT_AI_33', 'Grense høy temp adr 33 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_34', 'HLIMIT_AI_34', 'Grense høy temp adr 34 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_35', 'HLIMIT_AI_35', 'Grense høy temp adr 35 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_36', 'HLIMIT_AI_36', 'Grense høy temp adr 36 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_37', 'HLIMIT_AI_37', 'Grense høy temp adr 37 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_38', 'HLIMIT_AI_38', 'Grense høy temp adr 3 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_39', 'HLIMIT_AI_39', 'Grense høy temp adr 4 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_40', 'HLIMIT_AI_40', 'Grense høy temp adr 5 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_41', 'HLIMIT_AI_41', 'Grense høy temp adr 6 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_42', 'HLIMIT_AI_42', 'Grense høy temp adr 7 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_43', 'HLIMIT_AI_43', 'Grense høy temp adr 8 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_44', 'HLIMIT_AI_44', 'Grense høy temp adr 9 u12 S3 Air Temp', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'delay_10', 'DELAY_AI_10', 'Forsinkelse alarm temp adr 10 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_11', 'DELAY_AI_11', 'Forsinkelse alarm temp adr 11 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_12', 'DELAY_AI_12', 'Forsinkelse alarm temp adr 12 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_13', 'DELAY_AI_13', 'Forsinkelse alarm temp adr 13 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_14', 'DELAY_AI_14', 'Forsinkelse alarm temp adr 14 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_15', 'DELAY_AI_15', 'Forsinkelse alarm temp adr 15 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_16', 'DELAY_AI_16', 'Forsinkelse alarm temp adr 16 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_17', 'DELAY_AI_17', 'Forsinkelse alarm temp adr 17 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_18', 'DELAY_AI_18', 'Forsinkelse alarm temp adr 18 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_19', 'DELAY_AI_19', 'Forsinkelse alarm temp adr 19 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_20', 'DELAY_AI_20', 'Forsinkelse alarm temp adr 1 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_21', 'DELAY_AI_21', 'Forsinkelse alarm temp adr 21 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_22', 'DELAY_AI_22', 'Forsinkelse alarm temp adr 22 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_23', 'DELAY_AI_23', 'Forsinkelse alarm temp adr 23 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_24', 'DELAY_AI_24', 'Forsinkelse alarm temp adr 24 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_25', 'DELAY_AI_25', 'Forsinkelse alarm temp adr 26 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_26', 'DELAY_AI_26', 'Forsinkelse alarm temp adr 27 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_27', 'DELAY_AI_27', 'Forsinkelse alarm temp adr 28 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_28', 'DELAY_AI_28', 'Forsinkelse alarm temp adr 29 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_29', 'DELAY_AI_29', 'Forsinkelse alarm temp adr 2 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_30', 'DELAY_AI_30', 'Forsinkelse alarm temp adr 30 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_31', 'DELAY_AI_31', 'Forsinkelse alarm temp adr 31 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_32', 'DELAY_AI_32', 'Forsinkelse alarm temp adr 32 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_33', 'DELAY_AI_33', 'Forsinkelse alarm temp adr 33 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_34', 'DELAY_AI_34', 'Forsinkelse alarm temp adr 34 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_35', 'DELAY_AI_35', 'Forsinkelse alarm temp adr 35 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_36', 'DELAY_AI_36', 'Forsinkelse alarm temp adr 36 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_37', 'DELAY_AI_37', 'Forsinkelse alarm temp adr 37 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_38', 'DELAY_AI_38', 'Forsinkelse alarm temp adr 3 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_39', 'DELAY_AI_39', 'Forsinkelse alarm temp adr 4 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_40', 'DELAY_AI_40', 'Forsinkelse alarm temp adr 5 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_41', 'DELAY_AI_41', 'Forsinkelse alarm temp adr 6 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_42', 'DELAY_AI_42', 'Forsinkelse alarm temp adr 7 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_43', 'DELAY_AI_43', 'Forsinkelse alarm temp adr 8 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_44', 'DELAY_AI_44', 'Forsinkelse alarm temp adr 9 u12 S3 Air Temp', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'halm_10', 'HALM_AI_10', 'Alarm høy temp adr 10 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_11', 'HALM_AI_11', 'Alarm høy temp adr 11 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_12', 'HALM_AI_12', 'Alarm høy temp adr 12 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_13', 'HALM_AI_13', 'Alarm høy temp adr 13 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_14', 'HALM_AI_14', 'Alarm høy temp adr 14 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_15', 'HALM_AI_15', 'Alarm høy temp adr 15 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_16', 'HALM_AI_16', 'Alarm høy temp adr 16 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_17', 'HALM_AI_17', 'Alarm høy temp adr 17 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_18', 'HALM_AI_18', 'Alarm høy temp adr 18 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_19', 'HALM_AI_19', 'Alarm høy temp adr 19 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_20', 'HALM_AI_20', 'Alarm høy temp adr 1 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_21', 'HALM_AI_21', 'Alarm høy temp adr 21 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_22', 'HALM_AI_22', 'Alarm høy temp adr 22 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_23', 'HALM_AI_23', 'Alarm høy temp adr 23 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_24', 'HALM_AI_24', 'Alarm høy temp adr 24 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_25', 'HALM_AI_25', 'Alarm høy temp adr 26 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_26', 'HALM_AI_26', 'Alarm høy temp adr 27 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_27', 'HALM_AI_27', 'Alarm høy temp adr 28 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_28', 'HALM_AI_28', 'Alarm høy temp adr 29 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_29', 'HALM_AI_29', 'Alarm høy temp adr 2 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_30', 'HALM_AI_30', 'Alarm høy temp adr 30 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_31', 'HALM_AI_31', 'Alarm høy temp adr 31 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_32', 'HALM_AI_32', 'Alarm høy temp adr 32 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_33', 'HALM_AI_33', 'Alarm høy temp adr 33 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_34', 'HALM_AI_34', 'Alarm høy temp adr 34 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_35', 'HALM_AI_35', 'Alarm høy temp adr 35 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_36', 'HALM_AI_36', 'Alarm høy temp adr 36 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_37', 'HALM_AI_37', 'Alarm høy temp adr 37 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_38', 'HALM_AI_38', 'Alarm høy temp adr 3 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_39', 'HALM_AI_39', 'Alarm høy temp adr 4 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_40', 'HALM_AI_40', 'Alarm høy temp adr 5 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_41', 'HALM_AI_41', 'Alarm høy temp adr 6 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_42', 'HALM_AI_42', 'Alarm høy temp adr 7 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_43', 'HALM_AI_43', 'Alarm høy temp adr 8 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_44', 'HALM_AI_44', 'Alarm høy temp adr 9 u12 S3 Air Temp', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', '');


REPLACE INTO `iw_set_SM850_virt` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'hlimit_10', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_11', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_12', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_13', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_14', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_15', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_16', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_17', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_18', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_19', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_20', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_21', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_22', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_23', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_24', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_25', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_26', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_27', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_28', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_29', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_30', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_31', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_32', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_33', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_34', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_35', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_36', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_37', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_38', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_39', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_40', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_41', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_42', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_43', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_44', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_10', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_11', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_12', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_13', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_14', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_15', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_16', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_17', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_18', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_19', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_20', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_21', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_22', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_23', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_24', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_25', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_26', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_27', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_28', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_29', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_30', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_31', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_32', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_33', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_34', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_35', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_36', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_37', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_38', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_39', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_40', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_41', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_42', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_43', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_44', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'halm_10', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_11', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_12', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_13', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_14', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_15', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_16', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_17', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_18', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_19', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_20', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_21', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_22', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_23', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_24', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_25', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_26', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_27', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_28', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_29', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_30', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_31', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_32', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_33', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_34', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_35', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_36', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_37', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_38', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_39', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_40', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_41', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_42', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_43', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_44', '1', '0', 'norm', 'change', '', 'A', '', 0);


REPLACE INTO `iw_sys_virtual_values` (`row_date`, `active`, `owner`, `id`, `thread_id`, `trigger`, `inputs`, `outputs`, `formula`) VALUES
(NOW(), '0', 'VIRTUAL', 10, 0, '1 min', '000:010;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_10;hlimit\r\nVIRT01;delay_10;delay', 'VIRT01;halm_10', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 11, 0, '1 min', '000:011;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_11;hlimit\r\nVIRT01;delay_11;delay', 'VIRT01;halm_11', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 12, 0, '1 min', '000:012;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_12;hlimit\r\nVIRT01;delay_12;delay', 'VIRT01;halm_12', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 13, 0, '1 min', '000:013;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_13;hlimit\r\nVIRT01;delay_13;delay', 'VIRT01;halm_13', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 14, 0, '1 min', '000:014;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_14;hlimit\r\nVIRT01;delay_14;delay', 'VIRT01;halm_14', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 15, 0, '1 min', '000:015;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_15;hlimit\r\nVIRT01;delay_15;delay', 'VIRT01;halm_15', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 16, 0, '1 min', '000:016;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_16;hlimit\r\nVIRT01;delay_16;delay', 'VIRT01;halm_16', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 17, 0, '1 min', '000:017;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_17;hlimit\r\nVIRT01;delay_17;delay', 'VIRT01;halm_17', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 18, 0, '1 min', '000:018;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_18;hlimit\r\nVIRT01;delay_18;delay', 'VIRT01;halm_18', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 19, 0, '1 min', '000:019;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_19;hlimit\r\nVIRT01;delay_19;delay', 'VIRT01;halm_19', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 20, 0, '1 min', '000:001;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_20;hlimit\r\nVIRT01;delay_20;delay', 'VIRT01;halm_20', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 21, 0, '1 min', '000:021;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_21;hlimit\r\nVIRT01;delay_21;delay', 'VIRT01;halm_21', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 22, 0, '1 min', '000:022;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_22;hlimit\r\nVIRT01;delay_22;delay', 'VIRT01;halm_22', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 23, 0, '1 min', '000:023;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_23;hlimit\r\nVIRT01;delay_23;delay', 'VIRT01;halm_23', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 24, 0, '1 min', '000:024;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_24;hlimit\r\nVIRT01;delay_24;delay', 'VIRT01;halm_24', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 25, 0, '1 min', '000:026;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_25;hlimit\r\nVIRT01;delay_25;delay', 'VIRT01;halm_25', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 26, 0, '1 min', '000:027;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_26;hlimit\r\nVIRT01;delay_26;delay', 'VIRT01;halm_26', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 27, 0, '1 min', '000:028;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_27;hlimit\r\nVIRT01;delay_27;delay', 'VIRT01;halm_27', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 28, 0, '1 min', '000:029;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_28;hlimit\r\nVIRT01;delay_28;delay', 'VIRT01;halm_28', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 29, 0, '1 min', '000:002;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_29;hlimit\r\nVIRT01;delay_29;delay', 'VIRT01;halm_29', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 30, 0, '1 min', '000:030;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_30;hlimit\r\nVIRT01;delay_30;delay', 'VIRT01;halm_30', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 31, 0, '1 min', '000:031;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_31;hlimit\r\nVIRT01;delay_31;delay', 'VIRT01;halm_31', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 32, 0, '1 min', '000:032;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_32;hlimit\r\nVIRT01;delay_32;delay', 'VIRT01;halm_32', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 33, 0, '1 min', '000:033;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_33;hlimit\r\nVIRT01;delay_33;delay', 'VIRT01;halm_33', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 34, 0, '1 min', '000:034;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_34;hlimit\r\nVIRT01;delay_34;delay', 'VIRT01;halm_34', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 35, 0, '1 min', '000:035;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_35;hlimit\r\nVIRT01;delay_35;delay', 'VIRT01;halm_35', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 36, 0, '1 min', '000:036;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_36;hlimit\r\nVIRT01;delay_36;delay', 'VIRT01;halm_36', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 37, 0, '1 min', '000:037;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_37;hlimit\r\nVIRT01;delay_37;delay', 'VIRT01;halm_37', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 38, 0, '1 min', '000:003;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_38;hlimit\r\nVIRT01;delay_38;delay', 'VIRT01;halm_38', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 39, 0, '1 min', '000:004;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_39;hlimit\r\nVIRT01;delay_39;delay', 'VIRT01;halm_39', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 40, 0, '1 min', '000:005;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_40;hlimit\r\nVIRT01;delay_40;delay', 'VIRT01;halm_40', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 41, 0, '1 min', '000:006;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_41;hlimit\r\nVIRT01;delay_41;delay', 'VIRT01;halm_41', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 42, 0, '1 min', '000:007;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_42;hlimit\r\nVIRT01;delay_42;delay', 'VIRT01;halm_42', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 43, 0, '1 min', '000:008;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_43;hlimit\r\nVIRT01;delay_43;delay', 'VIRT01;halm_43', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '0', 'VIRTUAL', 44, 0, '1 min', '000:009;0_2530_u12_s3_air_temp;#temp\r\nVIRT01;hlimit_44;hlimit\r\nVIRT01;delay_44;delay', 'VIRT01;halm_44', 'check_value_higher(temp, hlimit, delay)');



REPLACE INTO `iw_par_SM850_virt_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'default_link', 1, '', '')
(NOW(), 'group_alias', 1, 'virt', 'SM850 Alarmer');



REPLACE INTO `iw_dyn_unit_status` (`row_date`, `driver_type`, `unit_id`, `blocked`, `offline_when`, `is_offline`) VALUES
(NOW(), 'SM850', 'VIRT01', 0, 4294967295, 0);



-- Changelog
--
-- v1 Orginal
--
--
