-- Husk å sette rett group,param og set tabell
-- Husk å sette poisjonsnavn på param listen
-- Husk å endre unit_id og element_id i virtuell tabellen
-- Husk å sette rett gruppe i groups


REPLACE INTO `iw_par_saia1_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES
(NOW(), 'group', 100, 'torg', 'hlimit_10'),
(NOW(), 'group', 110, 'torg', 'hlimit_11'),
(NOW(), 'group', 120, 'torg', 'hlimit_12'),
(NOW(), 'group', 130, 'torg', 'hlimit_13'),
(NOW(), 'group', 140, 'torg', 'hlimit_14'),
(NOW(), 'group', 150, 'torg', 'hlimit_15'),
(NOW(), 'group', 160, 'torg', 'hlimit_16'),
(NOW(), 'group', 170, 'torg', 'hlimit_17'),
(NOW(), 'group', 180, 'torg', 'hlimit_18'),
(NOW(), 'group', 190, 'torg', 'hlimit_19'),
(NOW(), 'group', 200, 'torg', 'hlimit_20'),
(NOW(), 'group', 210, 'torg', 'hlimit_21'),
(NOW(), 'group', 220, 'torg', 'hlimit_22'),
(NOW(), 'group', 230, 'torg', 'hlimit_23'),
(NOW(), 'group', 240, 'torg', 'hlimit_24'),
(NOW(), 'group', 250, 'torg', 'hlimit_25'),
(NOW(), 'group', 260, 'torg', 'hlimit_26'),
(NOW(), 'group', 270, 'torg', 'hlimit_27'),
(NOW(), 'group', 280, 'torg', 'hlimit_28'),
(NOW(), 'group', 290, 'torg', 'hlimit_29'),
(NOW(), 'group', 101, 'torg', 'llimit_10'),
(NOW(), 'group', 111, 'torg', 'llimit_11'),
(NOW(), 'group', 121, 'torg', 'llimit_12'),
(NOW(), 'group', 131, 'torg', 'llimit_13'),
(NOW(), 'group', 141, 'torg', 'llimit_14'),
(NOW(), 'group', 151, 'torg', 'llimit_15'),
(NOW(), 'group', 161, 'torg', 'llimit_16'),
(NOW(), 'group', 171, 'torg', 'llimit_17'),
(NOW(), 'group', 181, 'torg', 'llimit_18'),
(NOW(), 'group', 191, 'torg', 'llimit_19'),
(NOW(), 'group', 201, 'torg', 'llimit_20'),
(NOW(), 'group', 211, 'torg', 'llimit_21'),
(NOW(), 'group', 221, 'torg', 'llimit_22'),
(NOW(), 'group', 231, 'torg', 'llimit_23'),
(NOW(), 'group', 241, 'torg', 'llimit_24'),
(NOW(), 'group', 251, 'torg', 'llimit_25'),
(NOW(), 'group', 261, 'torg', 'llimit_26'),
(NOW(), 'group', 271, 'torg', 'llimit_27'),
(NOW(), 'group', 281, 'torg', 'llimit_28'),
(NOW(), 'group', 291, 'torg', 'llimit_29'),
(NOW(), 'group', 102, 'torg', 'delay_10'),
(NOW(), 'group', 112, 'torg', 'delay_11'),
(NOW(), 'group', 122, 'torg', 'delay_12'),
(NOW(), 'group', 132, 'torg', 'delay_13'),
(NOW(), 'group', 142, 'torg', 'delay_14'),
(NOW(), 'group', 152, 'torg', 'delay_15'),
(NOW(), 'group', 162, 'torg', 'delay_16'),
(NOW(), 'group', 172, 'torg', 'delay_17'),
(NOW(), 'group', 182, 'torg', 'delay_18'),
(NOW(), 'group', 192, 'torg', 'delay_19'),
(NOW(), 'group', 202, 'torg', 'delay_20'),
(NOW(), 'group', 212, 'torg', 'delay_21'),
(NOW(), 'group', 222, 'torg', 'delay_22'),
(NOW(), 'group', 232, 'torg', 'delay_23'),
(NOW(), 'group', 242, 'torg', 'delay_24'),
(NOW(), 'group', 252, 'torg', 'delay_25'),
(NOW(), 'group', 262, 'torg', 'delay_26'),
(NOW(), 'group', 272, 'torg', 'delay_27'),
(NOW(), 'group', 282, 'torg', 'delay_28'),
(NOW(), 'group', 292, 'torg', 'delay_29'),
(NOW(), 'group', 103, 'torg', 'halm_10'),
(NOW(), 'group', 113, 'torg', 'halm_11'),
(NOW(), 'group', 123, 'torg', 'halm_12'),
(NOW(), 'group', 133, 'torg', 'halm_13'),
(NOW(), 'group', 143, 'torg', 'halm_14'),
(NOW(), 'group', 153, 'torg', 'halm_15'),
(NOW(), 'group', 163, 'torg', 'halm_16'),
(NOW(), 'group', 173, 'torg', 'halm_17'),
(NOW(), 'group', 183, 'torg', 'halm_18'),
(NOW(), 'group', 193, 'torg', 'halm_19'),
(NOW(), 'group', 203, 'torg', 'halm_20'),
(NOW(), 'group', 213, 'torg', 'halm_21'),
(NOW(), 'group', 223, 'torg', 'halm_22'),
(NOW(), 'group', 233, 'torg', 'halm_23'),
(NOW(), 'group', 243, 'torg', 'halm_24'),
(NOW(), 'group', 253, 'torg', 'halm_25'),
(NOW(), 'group', 263, 'torg', 'halm_26'),
(NOW(), 'group', 273, 'torg', 'halm_27'),
(NOW(), 'group', 283, 'torg', 'halm_28'),
(NOW(), 'group', 293, 'torg', 'halm_29'),
(NOW(), 'group', 104, 'torg', 'lalm_10'),
(NOW(), 'group', 114, 'torg', 'lalm_11'),
(NOW(), 'group', 124, 'torg', 'lalm_12'),
(NOW(), 'group', 134, 'torg', 'lalm_13'),
(NOW(), 'group', 144, 'torg', 'lalm_14'),
(NOW(), 'group', 154, 'torg', 'lalm_15'),
(NOW(), 'group', 164, 'torg', 'lalm_16'),
(NOW(), 'group', 174, 'torg', 'lalm_17'),
(NOW(), 'group', 184, 'torg', 'lalm_18'),
(NOW(), 'group', 194, 'torg', 'lalm_19'),
(NOW(), 'group', 204, 'torg', 'lalm_20'),
(NOW(), 'group', 214, 'torg', 'lalm_21'),
(NOW(), 'group', 224, 'torg', 'lalm_22'),
(NOW(), 'group', 234, 'torg', 'lalm_23'),
(NOW(), 'group', 244, 'torg', 'lalm_24'),
(NOW(), 'group', 254, 'torg', 'lalm_25'),
(NOW(), 'group', 264, 'torg', 'lalm_26'),
(NOW(), 'group', 274, 'torg', 'lalm_27'),
(NOW(), 'group', 284, 'torg', 'lalm_28'),
(NOW(), 'group', 294, 'torg', 'lalm_29');


REPLACE INTO `iw_par_saia1_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`, `format_extra`) VALUES
(NOW(), 'hlimit_10', 'HLIMIT_AI_10', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_11', 'HLIMIT_AI_11', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_12', 'HLIMIT_AI_12', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_13', 'HLIMIT_AI_13', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_14', 'HLIMIT_AI_14', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_15', 'HLIMIT_AI_15', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_16', 'HLIMIT_AI_16', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_17', 'HLIMIT_AI_17', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_18', 'HLIMIT_AI_18', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_19', 'HLIMIT_AI_19', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_20', 'HLIMIT_AI_20', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_21', 'HLIMIT_AI_21', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_22', 'HLIMIT_AI_22', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_23', 'HLIMIT_AI_23', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_24', 'HLIMIT_AI_24', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_25', 'HLIMIT_AI_25', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_26', 'HLIMIT_AI_26', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_27', 'HLIMIT_AI_27', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_28', 'HLIMIT_AI_28', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'hlimit_29', 'HLIMIT_AI_29', 'Grense høy temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_10', 'LLIMIT_AI_10', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_11', 'LLIMIT_AI_11', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_12', 'LLIMIT_AI_12', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_13', 'LLIMIT_AI_13', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_14', 'LLIMIT_AI_14', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_15', 'LLIMIT_AI_15', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_16', 'LLIMIT_AI_16', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_17', 'LLIMIT_AI_17', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_18', 'LLIMIT_AI_18', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_19', 'LLIMIT_AI_19', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_20', 'LLIMIT_AI_20', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_21', 'LLIMIT_AI_21', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_22', 'LLIMIT_AI_22', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_23', 'LLIMIT_AI_23', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_24', 'LLIMIT_AI_24', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_25', 'LLIMIT_AI_25', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_26', 'LLIMIT_AI_26', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_27', 'LLIMIT_AI_27', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_28', 'LLIMIT_AI_28', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'llimit_29', 'LLIMIT_AI_29', 'Grense lav temperatur xxx', '', 'Analog values', 'float', '', '-1', 'vrw', '&deg;C', '%.1f', '-50', '150', '', '', '', '', '', '', ''),
(NOW(), 'delay_10', 'DELAY_AI_10', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_11', 'DELAY_AI_11', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_12', 'DELAY_AI_12', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_13', 'DELAY_AI_13', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_14', 'DELAY_AI_14', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_15', 'DELAY_AI_15', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_16', 'DELAY_AI_16', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_17', 'DELAY_AI_17', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_18', 'DELAY_AI_18', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_19', 'DELAY_AI_19', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_20', 'DELAY_AI_20', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_21', 'DELAY_AI_21', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_22', 'DELAY_AI_22', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_23', 'DELAY_AI_23', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_24', 'DELAY_AI_24', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_25', 'DELAY_AI_25', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_26', 'DELAY_AI_26', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_27', 'DELAY_AI_27', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_28', 'DELAY_AI_28', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'delay_29', 'DELAY_AI_29', 'Forsinkelse alarm temperatur xxx', '', 'Integral values', 'integer', '', '-1', 'vrw', 'min.', '%.0f', '0', '240', '', '', '', '', '', '', ''),
(NOW(), 'halm_10', 'HALM_AI_10', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_11', 'HALM_AI_11', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_12', 'HALM_AI_12', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_13', 'HALM_AI_13', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_14', 'HALM_AI_14', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_15', 'HALM_AI_15', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_16', 'HALM_AI_16', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_17', 'HALM_AI_17', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_18', 'HALM_AI_18', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_19', 'HALM_AI_19', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_20', 'HALM_AI_20', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_21', 'HALM_AI_21', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_22', 'HALM_AI_22', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_23', 'HALM_AI_23', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_24', 'HALM_AI_24', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_25', 'HALM_AI_25', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_26', 'HALM_AI_26', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_27', 'HALM_AI_27', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_28', 'HALM_AI_28', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'halm_29', 'HALM_AI_29', 'Alarm høy temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_10', 'LALM_AI_10', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_11', 'LALM_AI_11', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_12', 'LALM_AI_12', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_13', 'LALM_AI_13', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_14', 'LALM_AI_14', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_15', 'LALM_AI_15', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_16', 'LALM_AI_16', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_17', 'LALM_AI_17', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_18', 'LALM_AI_18', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_19', 'LALM_AI_19', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_20', 'LALM_AI_20', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_21', 'LALM_AI_21', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_22', 'LALM_AI_22', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_23', 'LALM_AI_23', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_24', 'LALM_AI_24', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_25', 'LALM_AI_25', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_26', 'LALM_AI_26', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_27', 'LALM_AI_27', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_28', 'LALM_AI_28', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', ''),
(NOW(), 'lalm_29', 'LALM_AI_29', 'Alarm lav temperatur xxx', '', 'Digital IO', 'boolean', '', '-1', 'vr', '', '', '0', '1', '', '', '', '', '', '', '');



REPLACE INTO `iw_set_saia1` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES
(NOW(), 'hlimit_10', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_11', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_12', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_13', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_14', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_15', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_16', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_17', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_18', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_19', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_20', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_21', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_22', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_23', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_24', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_25', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_26', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_27', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_28', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'hlimit_29', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_10', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_11', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_12', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_13', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_14', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_15', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_16', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_17', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_18', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_19', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_20', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_21', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_22', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_23', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_24', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_25', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_26', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_27', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_28', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'llimit_29', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_10', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_11', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_12', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_13', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_14', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_15', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_16', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_17', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_18', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_19', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_20', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_21', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_22', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_23', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_24', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_25', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_26', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_27', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_28', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'delay_29', '1', '0', 'norm', 'change', '', '', '', 0),
(NOW(), 'halm_10', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_11', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_12', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_13', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_14', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_15', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_16', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_17', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_18', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_19', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_20', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_21', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_22', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_23', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_24', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_25', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_26', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_27', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_28', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'halm_29', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_10', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_11', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_12', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_13', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_14', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_15', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_16', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_17', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_18', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_19', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_20', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_21', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_22', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_23', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_24', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_25', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_26', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_27', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_28', '1', '0', 'norm', 'change', '', 'A', '', 0),
(NOW(), 'lalm_29', '1', '0', 'norm', 'change', '', 'A', '', 0);



REPLACE INTO `iw_sys_virtual_values` (`row_date`, `active`, `owner`, `id`, `thread_id`, `trigger`, `inputs`, `outputs`, `formula`) VALUES
(NOW(), '1', 'VIRTUAL', 10, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_10;hlimit\r\nV01;delay_10;delay', 'V01;halm_10', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 11, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_11;hlimit\r\nV01;delay_11;delay', 'V01;halm_11', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 12, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_12;hlimit\r\nV01;delay_12;delay', 'V01;halm_12', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 13, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_13;hlimit\r\nV01;delay_13;delay', 'V01;halm_13', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 14, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_14;hlimit\r\nV01;delay_14;delay', 'V01;halm_14', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 15, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_15;hlimit\r\nV01;delay_15;delay', 'V01;halm_15', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 16, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_16;hlimit\r\nV01;delay_16;delay', 'V01;halm_16', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 17, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_17;hlimit\r\nV01;delay_17;delay', 'V01;halm_17', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 18, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_18;hlimit\r\nV01;delay_18;delay', 'V01;halm_18', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 19, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_19;hlimit\r\nV01;delay_19;delay', 'V01;halm_19', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 20, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_20;hlimit\r\nV01;delay_20;delay', 'V01;halm_20', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 21, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_21;hlimit\r\nV01;delay_21;delay', 'V01;halm_21', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 22, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_22;hlimit\r\nV01;delay_22;delay', 'V01;halm_22', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 23, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_23;hlimit\r\nV01;delay_23;delay', 'V01;halm_23', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 24, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_24;hlimit\r\nV01;delay_24;delay', 'V01;halm_24', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 25, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_25;hlimit\r\nV01;delay_25;delay', 'V01;halm_25', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 26, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_26;hlimit\r\nV01;delay_26;delay', 'V01;halm_26', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 27, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_27;hlimit\r\nV01;delay_27;delay', 'V01;halm_27', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 28, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_28;hlimit\r\nV01;delay_28;delay', 'V01;halm_28', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 29, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;hlimit_29;hlimit\r\nV01;delay_29;delay', 'V01;halm_29', 'check_value_higher(temp, hlimit, delay)'),
(NOW(), '1', 'VIRTUAL', 30, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_10;llimit\r\nV01;delay_10;delay', 'V01;lalm_10', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 31, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_11;llimit\r\nV01;delay_11;delay', 'V01;lalm_11', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 32, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_12;llimit\r\nV01;delay_12;delay', 'V01;lalm_12', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 33, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_13;llimit\r\nV01;delay_13;delay', 'V01;lalm_13', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 34, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_14;llimit\r\nV01;delay_14;delay', 'V01;lalm_14', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 35, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_15;llimit\r\nV01;delay_15;delay', 'V01;lalm_15', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 36, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_16;llimit\r\nV01;delay_16;delay', 'V01;lalm_16', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 37, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_17;llimit\r\nV01;delay_17;delay', 'V01;lalm_17', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 38, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_18;llimit\r\nV01;delay_18;delay', 'V01;lalm_18', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 39, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_19;llimit\r\nV01;delay_19;delay', 'V01;lalm_19', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 40, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_20;llimit\r\nV01;delay_20;delay', 'V01;lalm_20', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 41, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_21;llimit\r\nV01;delay_21;delay', 'V01;lalm_21', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 42, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_22;llimit\r\nV01;delay_22;delay', 'V01;lalm_22', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 43, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_23;llimit\r\nV01;delay_23;delay', 'V01;lalm_23', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 44, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_24;llimit\r\nV01;delay_24;delay', 'V01;lalm_24', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 45, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_25;llimit\r\nV01;delay_25;delay', 'V01;lalm_25', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 46, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_26;llimit\r\nV01;delay_26;delay', 'V01;lalm_26', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 47, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_27;llimit\r\nV01;delay_27;delay', 'V01;lalm_27', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 48, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_28;llimit\r\nV01;delay_28;delay', 'V01;lalm_28', 'check_value_lower(temp, llimit, delay)'),
(NOW(), '1', 'VIRTUAL', 49, 0, '1 min', 'V01;XXXXX;#temp\r\nV01;llimit_29;llimit\r\nV01;delay_29;delay', 'V01;lalm_29', 'check_value_lower(temp, llimit, delay)');







-- Changelog
--
-- v1 Orginal
--
--
