REPLACE INTO `iw_sys_plant_units` (`row_date`, `active`, `blockout`, `unit_id`, `unit_name`, `grp_name`, `driver_type`, `driver_addr`, `regulator_type`, `order_no`, `driver_adr_extra`) VALUES 
(NOW(), '1', '0', 'E-KF', 'Energi Kj�l og Frys', 'cge_wm14', 'WM14', '0_1', 'WM14', 'WM14', '');

REPLACE INTO `iw_sys_plant_settings` (`row_date`, `setting`, `owner`, `value`, `eng_unit`, `help_text`, `help_link`) VALUES 
(NOW(), 'comm_port', 'WM14', '3', '', '', ''),
(NOW(), 'force_word_not_byte', 'WM14', '0', '', '0|1', ''),
(NOW(), 'handshake', 'WM14', '0', '', '0|1|2', ''),
(NOW(), 'check_rate', 'WM14', '1', 'ms', '', ''),
(NOW(), 'comm_parity', 'WM14', '0', '', '0=N|1=O|2=E|3=M|4=S', ''),
(NOW(), 'comm_data_bits', 'WM14', '8', '', '', ''),
(NOW(), 'comm_stop_bits', 'WM14', '1', '', '', ''),
(NOW(), 'comm_baudrate', 'WM14', '9600', '', '', ''),
(NOW(), 'max_outstanding_packets', 'WM14', '-1', '', '', ''),
(NOW(), 'packet_timeout', 'WM14', '1', 'sec.', '', ''),
(NOW(), 'idle_event_rate', 'WM14', '250', 'msec.', '', ''),
(NOW(), 'sql_queue_poll_time', 'WM14', '2000', 'msec.', '', ''),
(NOW(), 'max_error_count', 'WM14', '2', '', '', ''),
(NOW(), 'mb_mode', 'WM14', '0', '', '0=RTU|1=ASCII|3=TCP', ''),
(NOW(), 'mb_request_timeout', 'WM14', '1000', 'ms', '', ''),
(NOW(), 'mb_request_retries', 'WM14', '2', '', '', ''),
(NOW(), 'com_error_alarm_delay', 'WM14', '10', 'min.', '', ''),
(NOW(), 'show_queue_info', 'WM14', '0', '', '', ''),
(NOW(), 'speed_index_block', 'WM14', '10', '', '', ''),
(NOW(), 'speed_index_offline', 'WM14', '10', '', '', ''),
(NOW(), 'speed_index_slow', 'WM14', '1', '', '', ''),
(NOW(), 'speed_index_norm', 'WM14', '1', '', '', ''),
(NOW(), 'max_param_block_time', 'WM14', '2', 'hours', '', ''),
(NOW(), 'max_group_count', 'WM14', '1', '', '', ''),
(NOW(), 'value_quality_check_limit', 'WM14', '0', '', '0 = disabled', '');

REPLACE INTO `iw_sys_processes` (`row_date`, `man_start`, `path`, `process_name`, `process_id`, `process_status`) VALUES 
(NOW(), '0', 'iw_mb.exe', 'WM14', '', '');

REPLACE INTO `iw_sys_order_no` (`row_date`, `order_no`, `db_link`, `group_link`) VALUES 
(NOW(), 'WM14', 'cge_wm14_param', 'cge_wm14_groups');

DROP TABLE IF EXISTS `iw_par_cge_wm14_groups`;
CREATE TABLE `iw_par_cge_wm14_groups` (
  `row_date` datetime NOT NULL default '2004-01-10 00:00:00',
  `type` varchar(50) NOT NULL default '',
  `view_order` mediumint(6) NOT NULL default '0',
  `ref` varchar(100) NOT NULL default '',
  `value` varchar(200) NOT NULL default '',
  UNIQUE KEY `type` (`type`,`view_order`,`ref`,`value`)
) TYPE=MyISAM COMMENT='2.0.0';

REPLACE INTO `iw_par_cge_wm14_groups` (`row_date`, `type`, `view_order`, `ref`, `value`) VALUES 
(NOW(), 'default_link', 1, '', ''),
(NOW(), 'group_alias', 1, 'status', 'M�linger'),
(NOW(), 'group_alias', 2, 'counters', 'kWh og kvarh'),
(NOW(), 'group_alias', 3, 'settings', 'Innstillinger'),
(NOW(), 'group', 6, 'status', 'V_L1_N'),
(NOW(), 'group', 7, 'status', 'V_L2_N'),
(NOW(), 'group', 8, 'status', 'V_L3_N'),
(NOW(), 'group', 9, 'status', 'V_L1_L2'),
(NOW(), 'group', 10, 'status', 'V_L2_L3'),
(NOW(), 'group', 11, 'status', 'V_L3_L1'),
(NOW(), 'group', 12, 'status', 'A_L1'),
(NOW(), 'group', 13, 'status', 'A_L2'),
(NOW(), 'group', 14, 'status', 'A_L3'),
(NOW(), 'group', 15, 'status', 'A_N'),
(NOW(), 'group', 16, 'status', 'W_L1'),
(NOW(), 'group', 17, 'status', 'W_L2'),
(NOW(), 'group', 18, 'status', 'W_L3'),
(NOW(), 'group', 19, 'status', 'va_L1'),
(NOW(), 'group', 20, 'status', 'va_L2'),
(NOW(), 'group', 21, 'status', 'va_L3'),
(NOW(), 'group', 22, 'status', 'var_L1'),
(NOW(), 'group', 23, 'status', 'var_L2'),
(NOW(), 'group', 24, 'status', 'var_L3'),
(NOW(), 'group', 25, 'status', 'PF_seq'),
(NOW(), 'group', 26, 'status', 'PF_L1'),
(NOW(), 'group', 27, 'status', 'PF_L2'),
(NOW(), 'group', 28, 'status', 'PF_L3'),
(NOW(), 'group', 29, 'status', 'V_L_N_SYS'),
(NOW(), 'group', 30, 'status', 'V_L_L_SYS'),
(NOW(), 'group', 1, 'status', 'W_SYS'),
(NOW(), 'group', 2, 'status', 'VA_SYS'),
(NOW(), 'group', 3, 'status', 'VAR_SYS'),
(NOW(), 'group', 4, 'status', 'pf_sys'),
(NOW(), 'group', 5, 'status', 'HZ'),
(NOW(), 'group', 31, 'status', 'asym_l_n'),
(NOW(), 'group', 32, 'status', 'asym_l_l'),
(NOW(), 'group', 33, 'status', 'a_l1_dmd'),
(NOW(), 'group', 34, 'status', 'a_l2_dmd'),
(NOW(), 'group', 35, 'status', 'a_l3_dmd'),
(NOW(), 'group', 36, 'status', 'w_l1_dmd'),
(NOW(), 'group', 37, 'status', 'w_l2_dmd'),
(NOW(), 'group', 38, 'status', 'w_l3_dmd'),
(NOW(), 'group', 39, 'status', 'va_l1_dmd'),
(NOW(), 'group', 40, 'status', 'va_l2_dmd'),
(NOW(), 'group', 41, 'status', 'va_l3_dmd'),
(NOW(), 'group', 42, 'status', 'w_dmd'),
(NOW(), 'group', 43, 'status', 'va_dmd'),
(NOW(), 'group', 1, 'counters', 'kwh_tot'),
(NOW(), 'group', 2, 'counters', 'kvarh_tot'),
(NOW(), 'group', 3, 'counters', 'kwh_par'),
(NOW(), 'group', 4, 'counters', 'kvarh_par'),
(NOW(), 'group', 5, 'counters', 'hour_counter'),
(NOW(), 'group', 44, 'status', 'a_max'),
(NOW(), 'group', 45, 'status', 'a_max_dmd'),
(NOW(), 'group', 46, 'status', 'a_l1_max'),
(NOW(), 'group', 47, 'status', 'a_l2_max'),
(NOW(), 'group', 48, 'status', 'a_l3_max'),
(NOW(), 'group', 49, 'status', 'w_l1_max'),
(NOW(), 'group', 50, 'status', 'w_l2_max'),
(NOW(), 'group', 51, 'status', 'w_l3_max'),
(NOW(), 'group', 52, 'status', 'w_max_dmd'),
(NOW(), 'group', 53, 'status', 'va_max_dmd'),
(NOW(), 'group', 54, 'status', 'pf_l1_min'),
(NOW(), 'group', 55, 'status', 'pf_l2_min'),
(NOW(), 'group', 56, 'status', 'pf_l3_min'),
(NOW(), 'group', 57, 'status', 'a_l1_min'),
(NOW(), 'group', 58, 'status', 'a_l2_min'),
(NOW(), 'group', 59, 'status', 'a_l3_min'),
(NOW(), 'group', 60, 'status', 'v_l1_min'),
(NOW(), 'group', 61, 'status', 'v_l2_min'),
(NOW(), 'group', 62, 'status', 'v_l3_min'),
(NOW(), 'group', 63, 'status', 'v_l1_max'),
(NOW(), 'group', 64, 'status', 'v_l2_max'),
(NOW(), 'group', 65, 'status', 'v_l3_max'),
(NOW(), 'group', 66, 'status', 'tdh_v1'),
(NOW(), 'group', 67, 'status', 'tdh_v2'),
(NOW(), 'group', 68, 'status', 'tdh_v3'),
(NOW(), 'group', 69, 'status', 'tdh_i1'),
(NOW(), 'group', 70, 'status', 'tdh_i2'),
(NOW(), 'group', 71, 'status', 'tdh_i3'),
(NOW(), 'group', 1, 'settings', 'instrument_code'),
(NOW(), 'group', 2, 'settings', 'firmware_revision'),
(NOW(), 'group', 3, 'settings', 'Module_type'),
(NOW(), 'group', 4, 'settings', 'latch_alarm'),
(NOW(), 'group', 5, 'settings', 'output_state'),
(NOW(), 'group', 6, 'settings', 'locked'),
(NOW(), 'group', 7, 'settings', 'out1'),
(NOW(), 'group', 8, 'settings', 'out2'),
(NOW(), 'group', 9, 'settings', 'remote'),
(NOW(), 'group', 10, 'settings', 'ct_ratio'),
(NOW(), 'group', 11, 'settings', 'vt_ratio'),
(NOW(), 'group', 12, 'settings', 'filter_scl'),
(NOW(), 'group', 13, 'settings', 'filter_coe'),
(NOW(), 'group', 14, 'settings', 'p_int'),
(NOW(), 'group', 15, 'settings', 'a_int'),
(NOW(), 'group', 16, 'settings', 'system'),
(NOW(), 'group', 17, 'settings', 'thd_mode');


DROP TABLE IF EXISTS `iw_par_cge_wm14_param`;
CREATE TABLE `iw_par_cge_wm14_param` (
  `row_date` datetime NOT NULL default '2004-01-01 00:00:00',
  `element_id` varchar(100) NOT NULL default '',
  `driver_id` varchar(100) NOT NULL default '',
  `alias_text` text NOT NULL,
  `menu` varchar(10) NOT NULL default '',
  `application` text NOT NULL,
  `parameter_type` text NOT NULL,
  `factory_setting` text NOT NULL,
  `grp` text NOT NULL,
  `att` text NOT NULL,
  `eng_unit` varchar(50) NOT NULL default '',
  `format` varchar(20) NOT NULL default '',
  `range_min` text NOT NULL,
  `range_max` text NOT NULL,
  `scale` varchar(15) NOT NULL default '',
  `raw_min` varchar(15) NOT NULL default '',
  `raw_max` varchar(15) NOT NULL default '',
  `eng_min` varchar(15) NOT NULL default '',
  `eng_max` varchar(15) NOT NULL default '',
  `driver_id_extra` varchar(255) NOT NULL default '',
  UNIQUE KEY `element_id` (`element_id`)
) TYPE=MyISAM COMMENT='2.0.0';

REPLACE INTO `iw_par_cge_wm14_param` (`row_date`, `element_id`, `driver_id`, `alias_text`, `menu`, `application`, `parameter_type`, `factory_setting`, `grp`, `att`, `eng_unit`, `format`, `range_min`, `range_max`, `scale`, `raw_min`, `raw_max`, `eng_min`, `eng_max`, `driver_id_extra`) VALUES 
(NOW(), 'V_L1_N', '0_F_0', 'V L1-N', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_0_F_N_-_-_-_-'),
(NOW(), 'V_L2_N', '0_F_2', 'V L2-N', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_2_F_N_-_-_-_-'),
(NOW(), 'V_L3_N', '0_F_4', 'V L3-N', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_4_F_N_-_-_-_-'),
(NOW(), 'V_L1_L2', '0_F_6', 'V L1-L2', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_6_F_N_-_-_-_-'),
(NOW(), 'V_L2_L3', '0_F_8', 'V L2-L3', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_8_F_N_-_-_-_-'),
(NOW(), 'V_L3_L1', '0_F_A', 'V L3-L1', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_10_F_N_-_-_-_-'),
(NOW(), 'A_L1', '0_F_C', 'A L1', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_12_F_N_-_-_-_-'),
(NOW(), 'A_L2', '0_F_E', 'A L2', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_14_F_N_-_-_-_-'),
(NOW(), 'A_L3', '0_F_10', 'A L3', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_16_F_N_-_-_-_-'),
(NOW(), 'A_N', '0_F_12', 'A N', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_18_F_N_-_-_-_-'),
(NOW(), 'W_L1', '0_F_14', 'W L1', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_20_F_N_-_-_-_-'),
(NOW(), 'W_L2', '0_F_16', 'W L2', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_22_F_N_-_-_-_-'),
(NOW(), 'W_L3', '0_F_18', 'W L3', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_24_F_N_-_-_-_-'),
(NOW(), 'va_L1', '0_F_1A', 'VA L1', '', 'Analoge values', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '2', '', '', '', '', '3_26_F_N_-_-_-_-'),
(NOW(), 'va_L2', '0_F_1C', 'VA L2', '', 'Analoge values', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '2', '', '', '', '', '3_28_F_N_-_-_-_-'),
(NOW(), 'va_L3', '0_F_1E', 'VA L3', '', 'Analoge values', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '2', '', '', '', '', '3_30_F_N_-_-_-_-'),
(NOW(), 'var_L1', '0_F_20', 'VAR L1', '', 'Analoge values', 'float', '', '1', 'r', 'VAR', '%.0f', '', '', '2', '', '', '', '', '3_32_F_N_-_-_-_-'),
(NOW(), 'var_L2', '0_F_22', 'VAR L2', '', 'Analoge values', 'float', '', '1', 'r', 'VAR', '%.0f', '', '', '2', '', '', '', '', '3_34_F_N_-_-_-_-'),
(NOW(), 'var_L3', '0_F_24', 'VAR L3', '', 'Analoge values', 'float', '', '1', 'r', 'VAR', '%.0f', '', '', '2', '', '', '', '', '3_36_F_N_-_-_-_-'),
(NOW(), 'PF_seq', '0_F_26', 'Phase sequence', '', 'Analoge values', 'float', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_38_F_N_-_-_-_-'),
(NOW(), 'PF_L1', '0_F_28', 'PF L1', '', 'Analoge values', 'float', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_40_F_N_-_-_-_-'),
(NOW(), 'PF_L2', '0_F_2A', 'PF L2', '', 'Analoge values', 'float', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_42_F_N_-_-_-_-'),
(NOW(), 'PF_L3', '0_F_2C', 'PF L3', '', 'Analoge values', 'float', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_44_F_N_-_-_-_-'),
(NOW(), 'V_L_N_SYS', '0_F_2E', 'V L-N sys', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_46_F_N_-_-_-_-'),
(NOW(), 'V_L_L_SYS', '0_F_30', 'V L-L sys', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_48_F_N_-_-_-_-'),
(NOW(), 'W_SYS', '0_F_32', 'kW sys', '', 'Analoge values', 'float', '', '1', 'r', 'kW', '%.1f', '', '', '1', '0', '10000', '0', '10', '3_50_F_N_-_-_-_-'),
(NOW(), 'VA_SYS', '0_F_34', 'kVA sys', '', 'Analoge values', 'float', '', '1', 'r', 'kVA', '%.1f', '', '', '1', '0', '10000', '0', '10', '3_52_F_N_-_-_-_-'),
(NOW(), 'VAR_SYS', '0_F_36', 'kVAR sys', '', 'Analoge values', 'float', '', '1', 'r', 'kVAR', '%.1f', '', '', '1', '0', '10000', '0', '10', '3_54_F_N_-_-_-_-'),
(NOW(), 'pf_sys', '0_F_38', 'PF sys', '', 'Analoge values', 'float', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_56_F_N_-_-_-_-'),
(NOW(), 'HZ', '0_F_3A', 'Hz', '', 'Analoge values', 'float', '', '1', 'r', 'Hz', '%.1f', '', '', '2', '', '', '', '', '3_58_F_N_-_-_-_-'),
(NOW(), 'asym_l_n', '0_F_3C', 'Asymmetry L-N %', '', 'Analoge values', 'float', '', '1', 'r', '&#037', '%.1f', '', '', '2', '', '', '', '', '3_60_F_N_-_-_-_-'),
(NOW(), 'asym_l_l', '0_F_3E', 'Asymmetry L-L %', '', 'Analoge values', 'float', '', '1', 'r', '&#037', '%.1f', '', '', '2', '', '', '', '', '3_62_F_N_-_-_-_-'),
(NOW(), 'a_l1_dmd', '0_F_40', 'A L1 dmd', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_64_F_N_-_-_-_-'),
(NOW(), 'a_l2_dmd', '0_F_42', 'A L2 dmd', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_66_F_N_-_-_-_-'),
(NOW(), 'a_l3_dmd', '0_F_44', 'A L3 dmd', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_68_F_N_-_-_-_-'),
(NOW(), 'w_l1_dmd', '0_F_46', 'W L1 dmd', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_70_F_N_-_-_-_-'),
(NOW(), 'w_l2_dmd', '0_F_48', 'W L2 dmd', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_72_F_N_-_-_-_-'),
(NOW(), 'w_l3_dmd', '0_F_4A', 'W L3 dmd', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_74_F_N_-_-_-_-'),
(NOW(), 'va_l1_dmd', '0_F_4C', 'VA L1 dmd', '', 'Analoge values', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '2', '', '', '', '', '3_76_F_N_-_-_-_-'),
(NOW(), 'va_l2_dmd', '0_F_4E', 'VA L2 dmd', '', 'Analoge values', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '2', '', '', '', '', '3_78_F_N_-_-_-_-'),
(NOW(), 'va_l3_dmd', '0_F_50', 'VA L3 dmd', '', 'Analoge values', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '2', '', '', '', '', '3_80_F_N_-_-_-_-'),
(NOW(), 'w_dmd', '0_F_52', 'W dmd', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_82_F_N_-_-_-_-'),
(NOW(), 'va_dmd', '0_F_54', 'VA dmd', '', 'Analoge values', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '2', '', '', '', '', '3_84_F_N_-_-_-_-'),
(NOW(), 'kwh_tot', '0_UI_56', 'kWh tot.', '', 'Integral values', 'integer', '', '1', 'r', 'kWh', '%.0f', '', '', '1', '0', '1000', '0', '100', '3_86_UI32_N_-_-_-_-'),
(NOW(), 'kvarh_tot', '0_UI_58', 'kVARh tot.', '', 'Integral values', 'integer', '', '1', 'r', 'kVARh', '%.0f', '', '', '1', '0', '1000', '0', '100', '3_88_UI32_N_-_-_-_-'),
(NOW(), 'kwh_par', '0_UI_5A', 'kWh par.', '', 'Integral values', 'integer', '', '1', 'r', 'kWh', '%.0f', '', '', '1', '0', '1000', '0', '100', '3_90_UI32_N_-_-_-_-'),
(NOW(), 'kvarh_par', '0_UI_5C', 'kVARh par.', '', 'Integral values', 'integer', '', '1', 'r', 'kVARh', '%.0f', '', '', '1', '0', '1000', '0', '100', '3_92_UI32_N_-_-_-_-'),
(NOW(), 'hour_counter', '0_UI_5E', 'Hour Counter', '', 'Integral values', 'integer', '', '1', 'r', 'Hour', '%.0f', '', '', '1', '0', '1000', '0', '10', '3_94_UI32_N_-_-_-_-'),
(NOW(), 'a_max', '0_F_60', 'A MAX', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_96_F_N_-_-_-_-'),
(NOW(), 'a_max_dmd', '0_F_62', 'A MAX dmd', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_98_F_N_-_-_-_-'),
(NOW(), 'a_l1_max', '0_F_64', 'A L1 MAX', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_100_F_N_-_-_-_-'),
(NOW(), 'a_l2_max', '0_F_66', 'A L2 MAX', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_102_F_N_-_-_-_-'),
(NOW(), 'a_l3_max', '0_F_68', 'A L3 MAX', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_104_F_N_-_-_-_-'),
(NOW(), 'w_l1_max', '0_F_6A', 'W L1 MAX', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_106_F_N_-_-_-_-'),
(NOW(), 'w_l2_max', '0_F_6C', 'W L2 MAX', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_108_F_N_-_-_-_-'),
(NOW(), 'w_l3_max', '0_F_6E', 'W L3 MAX', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_110_F_N_-_-_-_-'),
(NOW(), 'w_max_dmd', '0_F_70', 'W MAX dmd', '', 'Analoge values', 'float', '', '1', 'r', 'W', '%.1f', '', '', '2', '', '', '', '', '3_112_F_N_-_-_-_-'),
(NOW(), 'va_max_dmd', '0_F_72', 'VA MAX dmd', '', 'Analoge values', 'float', '', '1', 'r', 'VA', '%.0f', '', '', '2', '', '', '', '', '3_114_F_N_-_-_-_-'),
(NOW(), 'pf_l1_min', '0_F_74', 'PF L1 min', '', 'Analoge values', 'float', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_116_F_N_-_-_-_-'),
(NOW(), 'pf_l2_min', '0_F_76', 'PF L2 min', '', 'Analoge values', 'float', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_118_F_N_-_-_-_-'),
(NOW(), 'pf_l3_min', '0_F_78', 'PF L3 min', '', 'Analoge values', 'float', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_120_F_N_-_-_-_-'),
(NOW(), 'a_l1_min', '0_F_7A', 'A L1 min', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_122_F_N_-_-_-_-'),
(NOW(), 'a_l2_min', '0_F_7C', 'A L2 min', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_124_F_N_-_-_-_-'),
(NOW(), 'a_l3_min', '0_F_7E', 'A L3 min', '', 'Analoge values', 'float', '', '1', 'r', 'A', '%.1f', '', '', '2', '', '', '', '', '3_126_F_N_-_-_-_-'),
(NOW(), 'v_l1_min', '0_F_80', 'V L1 min', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_128_F_N_-_-_-_-'),
(NOW(), 'v_l2_min', '0_F_82', 'V L2 min', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_130_F_N_-_-_-_-'),
(NOW(), 'v_l3_min', '0_F_84', 'V L3 min', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_132_F_N_-_-_-_-'),
(NOW(), 'v_l1_max', '0_F_86', 'V L1 MAX', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_134_F_N_-_-_-_-'),
(NOW(), 'v_l2_max', '0_F_88', 'V L2 MAX', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_136_F_N_-_-_-_-'),
(NOW(), 'v_l3_max', '0_F_8A', 'V L3 MAX', '', 'Analoge values', 'float', '', '1', 'r', 'V', '%.0f', '', '', '2', '', '', '', '', '3_138_F_N_-_-_-_-'),
(NOW(), 'tdh_v1', '0_F_8C', 'THD V1', '', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '2', '', '', '', '', '3_140_F_N_-_-_-_-'),
(NOW(), 'tdh_v2', '0_F_8E', 'THD V2', '', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '2', '', '', '', '', '3_142_F_N_-_-_-_-'),
(NOW(), 'tdh_v3', '0_F_90', 'THD V3', '', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '2', '', '', '', '', '3_144_F_N_-_-_-_-'),
(NOW(), 'tdh_i1', '0_F_92', 'THD I1', '', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '2', '', '', '', '', '3_146_F_N_-_-_-_-'),
(NOW(), 'tdh_i2', '0_F_94', 'THD I2', '', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '2', '', '', '', '', '3_148_F_N_-_-_-_-'),
(NOW(), 'tdh_i3', '0_F_96', 'THD I3', '', 'Analoge values', 'float', '', '1', 'r', '', '%.1f', '', '', '2', '', '', '', '', '3_150_F_N_-_-_-_-'),
(NOW(), 'instrument_code', '0_UI_D3', 'Instrument Code', '', 'Integral values', 'integer', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_211_UI16_N_-_-_-_-'),
(NOW(), 'firmware_revision', '0_UI_DE', 'Firmware Revision', '', 'Integral values', 'integer', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_222_UI16_N_-_-_-_-'),
(NOW(), 'Module_type', '0_UI_DF', 'Module Type', '', 'Integral values', 'integer', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_223_UI16_N_-_-_-_-'),
(NOW(), 'latch_alarm', '0_UI_F4', 'Latch Alarm', '', 'Integral values', 'integer', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_244_UI16_N_-_-_-_-'),
(NOW(), 'output_state', '0_UI_F5', 'Output State', '', 'Integral values', 'integer', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_245_UI16_N_-_-_-_-'),
(NOW(), 'locked', '0_UI_F7', 'Locked', '', 'Integral values', 'integer', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_247_UI16_N_-_-_-_-'),
(NOW(), 'out1', '0_UI_103', 'Out1', '', 'Integral values', 'integer', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_259_UI16_N_-_-_-_-'),
(NOW(), 'out2', '0_UI_104', 'Out2', '', 'Integral values', 'integer', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_260_UI16_N_-_-_-_-'),
(NOW(), 'remote', '0_UI_105', 'Remote', '', 'Integral values', 'integer', '', '1', 'r', '', '%.0f', '', '', '2', '', '', '', '', '3_261_UI16_N_-_-_-_-'),
(NOW(), 'ct_ratio', '0_UI_19A', 'CT-ratio', '', 'Integral values', 'integer', '', '1', 'rw', '', '', '', '', '', '', '', '', '', '3_410_UI16_N_6_410_UI16_N'),
(NOW(), 'vt_ratio', '0_UI_19B', 'VT-ratio', '', 'Integral values', 'integer', '', '1', 'rw', '', '', '', '', '', '', '', '', '', '3_411_UI16_N_6_411_UI16_N'),
(NOW(), 'filter_scl', '0_UI_19C', 'Filter range', '', 'Integral values', 'integer', '', '1', 'rw', '', '', '', '', '', '', '', '', '', '3_412_UI16_N_6_412_UI16_N'),
(NOW(), 'filter_coe', '0_UI_19D', 'Filter coefficient', '', 'Integral values', 'integer', '', '1', 'rw', '', '', '', '', '', '', '', '', '', '3_413_UI16_N_6_413_UI16_N'),
(NOW(), 'p_int', '0_UI_19E', 'Power Integration time (for W dmd)', '', 'Integral values', 'integer', '', '1', 'rw', '', '', '', '', '', '', '', '', '', '3_414_UI16_N_6_414_UI16_N'),
(NOW(), 'a_int', '0_UI_19F', 'Current Integration time (for A dmd)', '', 'Integral values', 'integer', '', '1', 'rw', '', '', '', '', '', '', '', '', '', '3_415_UI16_N_6_415_UI16_N'),
(NOW(), 'system', '0_UI_1A0', 'System type', '', 'Integral values', 'integer', '', '1', 'rw', '', '', '', '', '', '', '', '', '', '3_416_UI16_N_6_416_UI16_N'),
(NOW(), 'thd_mode', '0_UI_1A8', 'Total harmonics distorsion activation', '', 'Integral values', 'integer', '', '1', 'rw', '', '', '', '', '', '', '', '', '', '3_424_UI16_N_6_424_UI16_N');

DROP TABLE IF EXISTS `iw_set_cge_wm14`;
CREATE TABLE `iw_set_cge_wm14` (
  `row_date` datetime NOT NULL default '2004-01-10 00:00:00',
  `element_id` varchar(100) NOT NULL default '',
  `active` enum('0','1') NOT NULL default '0',
  `onl_ind` enum('0','1') NOT NULL default '1',
  `update_freq` set('','fast','norm','slow','once','never') NOT NULL default 'norm',
  `save_data` enum('0','1','2') NOT NULL default '0',
  `save_freq` set('','fast','norm','slow') NOT NULL default 'norm',
  `plant_pri` char(1) NOT NULL default '',
  `sys_pri` char(1) NOT NULL default '',
  `alarm_type` tinyint(3) NOT NULL default '0',
  PRIMARY KEY  (`element_id`)
) TYPE=MyISAM COMMENT='2.0.4';

REPLACE INTO `iw_set_cge_wm14` (`row_date`, `element_id`, `active`, `onl_ind`, `update_freq`, `save_data`, `save_freq`, `plant_pri`, `sys_pri`, `alarm_type`) VALUES 
(NOW(), 'V_L1_N', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'V_L2_N', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'V_L3_N', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'V_L1_L2', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'V_L2_L3', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'V_L3_L1', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'A_L1', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'A_L2', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'A_L3', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'A_N', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'W_L1', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'W_L2', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'W_L3', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'va_L1', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'va_L2', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'va_L3', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'var_L1', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'var_L2', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'var_L3', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'PF_seq', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'PF_L1', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'PF_L2', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'PF_L3', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'V_L_N_SYS', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'V_L_L_SYS', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'W_SYS', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'VA_SYS', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'VAR_SYS', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'pf_sys', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'HZ', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'asym_l_n', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'asym_l_l', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'a_l1_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'a_l2_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'a_l3_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'w_l1_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'w_l2_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'w_l3_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'va_l1_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'va_l2_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'va_l3_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'w_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'va_dmd', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'kwh_tot', '1', '1', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kvarh_tot', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kwh_par', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'kvarh_par', '1', '0', 'norm', '1', 'norm', '', '', 0),
(NOW(), 'hour_counter', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'a_max', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'a_max_dmd', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'a_l1_max', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'a_l2_max', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'a_l3_max', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'w_l1_max', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'w_l2_max', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'w_l3_max', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'w_max_dmd', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'va_max_dmd', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pf_l1_min', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pf_l2_min', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'pf_l3_min', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'a_l1_min', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'a_l2_min', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'a_l3_min', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'v_l1_min', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'v_l2_min', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'v_l3_min', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'v_l1_max', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'v_l2_max', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'v_l3_max', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'tdh_v1', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'tdh_v2', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'tdh_v3', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'tdh_i1', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'tdh_i2', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'tdh_i3', '1', '0', 'slow', '1', 'norm', '', '', 0),
(NOW(), 'instrument_code', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'firmware_revision', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'Module_type', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'latch_alarm', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'output_state', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'locked', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'out1', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'out2', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'remote', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'ct_ratio', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'vt_ratio', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'filter_scl', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'filter_coe', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'p_int', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'a_int', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'system', '1', '0', 'slow', '2', 'norm', '', '', 0),
(NOW(), 'thd_mode', '1', '0', 'slow', '2', 'norm', '', '', 0);


-- Changelog
--
-- v1 Orginal
--
--